### ISSUE TITLE
Crash caused by race condition during concurrent flyway.migrate on empty database

### ISSUE THREAD

**Issue by roband** [flyway/flyway#1014]
Using Flyway 3.2.1, Java 8, Wildfly 8.2, PostgreSQL 9.4

If multiple apps at the exact same moment in time do a flyway.migrate() against an empty database (one without the schema_version table), then I get crashes.

According to the FAQ "Can multiple nodes migrate in parallel?" I believe this is supposed to work.

Looks as if there is a small window in this logic, so if multiple apps race, sometimes the window is hit and it crashes, other times it works.

Caused by: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Script failed
-------------
SQL State  : 23505
Error Code : 0
Message    : ERROR: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
  Detail: Key (typname, typnamespace)=(schema_version, 2200) already exists.
Line       : 17
Statement  : CREATE TABLE "public"."schema_version" (
    "version_rank" INT NOT NULL,
    "installed_rank" INT NOT NULL,
    "version" VARCHAR(50) NOT NULL,
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INTEGER,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TIMESTAMP NOT NULL DEFAULT now(),
    "execution_time" INTEGER NOT NULL,
    "success" BOOLEAN NOT NULL
) WITH (
  OIDS=FALSE
)

        at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:117)
        at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.createIfNotExists(MetaDataTableImpl.java:93)
        at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:100)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:158)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
        at no.ssb.valg.database.FlywayLoader.initialize(FlywayLoader.java:42)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_40]
        at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_40]
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
        ... 51 more
Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
  Detail: Key (typname, typnamespace)=(schema_version, 2200) already exists.
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:406)
        at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:398)
        at org.jboss.jca.adapters.jdbc.WrappedStatement.execute(WrappedStatement.java:157)
        at org.flywaydb.core.internal.dbsupport.JdbcTemplate.executeStatement(JdbcTemplate.java:238)
        at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:114)
        ... 69 more

**Comment by axelfontaine** [comment]
Thanks for the report. This is unfortunately something we cannot easily fix. Coordination between multiple nodes happens via a database lock on the metadata table. In this case there is nothing there yet to lock. You can use baseline to create it first as a workaround. A real fix unfortunately doesn't appear to be possible in this case.

Cheers
Axel

**Comment by h1ppo** [comment]
I'm not sure about other dbs but MySQL supports `IF NOT EXISTS` for most schema creation operations which would alleviate this problem if added to the initial schema creation script: https://github.com/flyway/flyway/blob/f643945ad513ea0889a6f7b8c69422a3b972e55a/flyway-core/src/main/resources/org/flywaydb/core/internal/dbsupport/mysql/createMetaDataTable.sql

The alter and index creation would actually need to all be written into one statement like so:
```sql
CREATE TABLE `${schema}`.`${table}` (
    `version_rank` INT NOT NULL,
    `installed_rank` INT NOT NULL,
    `version` VARCHAR(50) NOT NULL,
    `description` VARCHAR(200) NOT NULL,
    `type` VARCHAR(20) NOT NULL,
    `script` VARCHAR(1000) NOT NULL,
    `checksum` INT,
    `installed_by` VARCHAR(100) NOT NULL,
    `installed_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `execution_time` INT NOT NULL,
    `success` BOOL NOT NULL,
    PRIMARY KEY(`version`),
    KEY `${table}_vr_idx` (`version_rank`),
    KEY `${table}_ir_idx` (`installed_rank`),
    KEY `${table}_s_idx` (`success`)
) ENGINE=InnoDB;
```

Maybe there are similar refactors that could be done for the table creation on other DBs to avoid the race condition here?
