### ISSUE TITLE
Problem with placeholder replacement

### ISSUE THREAD

**Issue by hkz-dev** [flyway/flyway#1018]
* If placeholder replacement to OFF, Flyway throws exception.
	* Example
	```java
	Flyway flyway = new Flyway();
	flyway.setSchemas("test");
	flyway.setDataSource(new DataSource());
	flyway.setLocations("classpath:/");
	
	// set to false
	flyway.setPlaceholderReplacement(false);
	
	flyway.clean();
	flyway.migrate();
	```
	* classpath:/V1__CREATE_TABLE.sql
	```sql
	CREATE TABLE IF NOT EXISTS "test"."table1" (
	  "id" BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID',
	  "code" VARCHAR(64) NOT NULL COMMENT 'code',
	  PRIMARY KEY ("id"))
	ENGINE = InnoDB;
	```
	* Result
	```java
	org.flywaydb.core.api.FlywayException: No value provided for placeholder expressions: ...... Check your configuration!
		at org.flywaydb.core.internal.util.PlaceholderReplacer.checkForUnmatchedPlaceholderExpression(PlaceholderReplacer.java:101)
		at org.flywaydb.core.internal.util.PlaceholderReplacer.replacePlaceholders(PlaceholderReplacer.java:78)
		at org.flywaydb.core.internal.dbsupport.SqlScript.<init>(SqlScript.java:79)
		......
	```

* I think PlaceholderReplacer has bug?
	* Current ( [PlaceholderReplacer.java#L34](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/util/PlaceholderReplacer.java#L34) / [PlaceholderReplacer.java#L78](https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/util/PlaceholderReplacer.java#L78) )
	```java
	public String replacePlaceholders(String input) {
		String noPlaceholders = input;
		
		for (String placeholder : placeholders.keySet()) {
			......
		}
		
		// TODO: not good work when placeholderPrefix="" and placeholderSuffix="" ?
		checkForUnmatchedPlaceholderExpression(noPlaceholders);
		
		return noPlaceholders;
	}
	```
	* Fixed
	```java
	public String replacePlaceholders(String input) {
		
		// FIX: if placeholders is empty, no replacing
		if (placeholders == null || placeholders.isEmpty()) {
			return input;
		}
		
		String noPlaceholders = input;
		......
	}
	```

**Comment by axelfontaine** [comment]
Somehow I can't reproduce this (see commit). Can you attach a small test case that reproduces this exactly?

**Comment by axelfontaine** [comment]
Please reopen with an exact test case if this can be reproduced.

**Comment by hkz-dev** [comment]
I tried with Flyway 4.0, and this error did not appeared.
Thank you!
