### ISSUE TITLE
use c3p0 as DataSource

### ISSUE THREAD

**Issue by simlegate** [flyway/flyway#1028]
define bean for Flyway
```Java
<bean id="flyway" class="org.flywaydb.core.Flyway" init-method="migrate">
        <property name="baselineOnMigrate" value="true"/>
        <property name="dataSource" ref="dataSource" />
</bean>
```
define bean for DataSource
```Java
 <bean id="dataSource"
          class="com.mchange.v2.c3p0.ComboPooledDataSource" destroy-method="close">
</bean>
```
when I start my Application, some errors are throwed
```Java
Caused by: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56) ~[flyway-core-3.2.1.jar:?]
	at org.flywaydb.core.Flyway.execute(Flyway.java:1385) ~[flyway-core-3.2.1.jar:?]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1006) ~[flyway-core-3.2.1.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_25]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_25]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1702) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1641) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
	... 19 more
```
but When I use the `dataSource` connect to dababase , All is Ok
```Java
<bean id="entityManagerFactory"
          class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean">
</bean>
```
So, What's wrong ?

**Comment by axelfontaine** [comment]
Check your datasource and your Spring config. Your entityManagerFactory is probably using a different datasource. Check the cause of the FlywayException (not included in your report) and it should tell you what went wrong.

**Comment by simlegate** [comment]
@axelfontaine My entityManagerFactory use same datasource with flyway.
```XML
 <bean id="entityManagerFactory"
          class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean" depends-on="flyway">
        <property name="dataSource" ref="dataSource"/>
 .....
</bean>
```

**Comment by axelfontaine** [comment]
That was hard to guess from your initial report :-)

What is the original exception being returned by C3P0?
