### ISSUE TITLE
Error when executing a very long running migration

### ISSUE THREAD

**Issue by avesse** [flyway/flyway#1029]
We have a Clustrix db (MySQL compatible) with millions of records. An update that adds a column takes a long time to execute (10 and 30 minutes, in the two cases below). While the column is correctly added, the schema_version table does not get updated, and flyway exits with the following stacktrace:

#### First example:

Database: jdbc:mysql://x.x.x.x:3306/ (MySQL 5.0)
Validated 2 migrations (execution time 00:01.119s)
Current version of schema `XXX`: 1
Migrating schema `XXX` to version 1.1 - XXX
ERROR: Unable to commit transaction
java.sql.SQLNonTransientConnectionException: Could not read resultset: unexpected end of stream, read 0bytes from 4
        at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:136)
        at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106)
        at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:264)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:288)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:338)
        at org.mariadb.jdbc.MySQLConnection.commit(MySQLConnection.java:230)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:88)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:118)
        at org.flywaydb.commandline.Main.main(Main.java:87)
Caused by: org.mariadb.jdbc.internal.common.QueryException: Could not read resultset: unexpected end of stream, read 0by
tes from 4
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:926)
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:991)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:281)
        ... 10 more
Caused by: java.io.EOFException: unexpected end of stream, read 0bytes from 4
        at org.mariadb.jdbc.internal.common.packet.buffer.ReadUtil.readFully(ReadUtil.java:84)
        at org.mariadb.jdbc.internal.common.packet.buffer.ReadUtil.readFully(ReadUtil.java:92)
        at org.mariadb.jdbc.internal.common.packet.RawPacket.nextPacket(RawPacket.java:77)
        at org.mariadb.jdbc.internal.common.packet.SyncPacketFetcher.getRawPacket(SyncPacketFetcher.java:67)
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:894)
        ... 12 more
ERROR: Unable to restore autocommit to original value for connection
java.sql.SQLNonTransientConnectionException: Could not read resultset: unexpected end of stream, read 0bytes from 4
        at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:136)
        at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106)
        at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:264)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:288)
        at org.mariadb.jdbc.MySQLStatement.executeUpdate(MySQLStatement.java:317)
        at org.mariadb.jdbc.MySQLStatement.executeUpdate(MySQLStatement.java:349)
        at org.mariadb.jdbc.MySQLConnection.setAutoCommit(MySQLConnection.java:206)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:96)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:118)
        at org.flywaydb.commandline.Main.main(Main.java:87)
Caused by: org.mariadb.jdbc.internal.common.QueryException: Could not read resultset: unexpected end of stream, read 0by
tes from 4
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:926)
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:991)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:281)
        ... 11 more
Caused by: java.io.EOFException: unexpected end of stream, read 0bytes from 4
        at org.mariadb.jdbc.internal.common.packet.buffer.ReadUtil.readFully(ReadUtil.java:84)
        at org.mariadb.jdbc.internal.common.packet.buffer.ReadUtil.readFully(ReadUtil.java:92)
        at org.mariadb.jdbc.internal.common.packet.RawPacket.nextPacket(RawPacket.java:77)
        at org.mariadb.jdbc.internal.common.packet.SyncPacketFetcher.getRawPacket(SyncPacketFetcher.java:67)
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.getResult(MySQLProtocol.java:894)
        ... 13 more
ERROR: Unable to check whether table `XXX`.`schema_version` exists

#### Second example:

Database: jdbc:mysql://x.x.x.x:3306/ (MySQL 5.0)
Validated 3 migrations (execution time 00:00.020s)
Current version of schema `XXX`: 1.1
Migrating schema `XXX` to version 1.2 - XXX
ERROR: Unable to commit transaction
java.sql.SQLNonTransientConnectionException: Could not send query: Software caused connection abort: socket write error
        at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:136)
        at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106)
        at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:264)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:288)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:338)
        at org.mariadb.jdbc.MySQLConnection.commit(MySQLConnection.java:230)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:88)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:118)
        at org.flywaydb.commandline.Main.main(Main.java:87)
Caused by: org.mariadb.jdbc.internal.common.QueryException: Could not send query: Software caused connection abort: sock
et write error
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:984)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:281)
        ... 10 more
Caused by: java.net.SocketException: Software caused connection abort: socket write error
        at java.net.SocketOutputStream.socketWrite0(Native Method)
        at java.net.SocketOutputStream.socketWrite(Unknown Source)
        at java.net.SocketOutputStream.write(Unknown Source)
        at org.mariadb.jdbc.internal.common.packet.PacketOutputStream.internalFlush(PacketOutputStream.java:122)
        at org.mariadb.jdbc.internal.common.packet.PacketOutputStream.finishPacket(PacketOutputStream.java:73)
        at org.mariadb.jdbc.internal.common.packet.commands.StreamedQueryPacket.send(StreamedQueryPacket.java:79)
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:982)
        ... 11 more
ERROR: Unable to restore autocommit to original value for connection
java.sql.SQLNonTransientConnectionException: Could not send query: Last packet not finished
        at org.mariadb.jdbc.internal.SQLExceptionMapper.get(SQLExceptionMapper.java:136)
        at org.mariadb.jdbc.internal.SQLExceptionMapper.throwException(SQLExceptionMapper.java:106)
        at org.mariadb.jdbc.MySQLStatement.executeQueryEpilog(MySQLStatement.java:264)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:288)
        at org.mariadb.jdbc.MySQLStatement.executeUpdate(MySQLStatement.java:317)
        at org.mariadb.jdbc.MySQLStatement.executeUpdate(MySQLStatement.java:349)
        at org.mariadb.jdbc.MySQLConnection.setAutoCommit(MySQLConnection.java:206)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:96)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:118)
        at org.flywaydb.commandline.Main.main(Main.java:87)
Caused by: org.mariadb.jdbc.internal.common.QueryException: Could not send query: Last packet not finished
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:984)
        at org.mariadb.jdbc.MySQLStatement.execute(MySQLStatement.java:281)
        ... 11 more
Caused by: java.io.IOException: Last packet not finished
        at org.mariadb.jdbc.internal.common.packet.PacketOutputStream.startPacket(PacketOutputStream.java:38)
        at org.mariadb.jdbc.internal.common.packet.commands.StreamedQueryPacket.send(StreamedQueryPacket.java:76)
        at org.mariadb.jdbc.internal.mysql.MySQLProtocol.executeQuery(MySQLProtocol.java:982)
        ... 12 more
ERROR: Unable to check whether table `XXX`.`schema_version` exists

#### Additional info

- Running a baseline after the successful (but failed) migration is the current workaround. 
- There is no transaction timeout on the database server.

**Comment by axelfontaine** [comment]
I am not sure what we could do on our side to fix this. It seems to be either a driver or a db server issue. Do you have any idea where the problem may lie?

**Comment by avesse** [comment]
I was hoping you could help with that :) Nope, no idea. I checked the relevant settings on the db server side, and I don't know jdbc that well. I thought there might be a jdbc setting somewhere that could make it friendlier to this kind of operation.

**Comment by axelfontaine** [comment]
This is most likely due to a DB server or firewall issue. Nothing we can do on our end.

**Comment by dlazerka** [comment]
How about `connection.setNetworkTimeout()`? We could allow users to set it.
