### ISSUE TITLE
Add support for the official Redshift JDBC driver

### ISSUE THREAD

**Issue by slmnhq** [flyway/flyway#1058]
It seems like Flyway is generating an SQL statement that Redshift considers to be invalid.

This happens when Flyway tries to insert a row in the ``schema_version`` table.

The error from the Redshift client JAR states ``Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: Specified types or functions (one per INFO message) not supported on Redshift tables.;``

I have narrowed down the problem to ``org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.addAppliedMigration(MetaDataTableImpl.java:115)``

See command and traceback for more info:

```
mvn compile -Dflyway.schemas=test_dropme -Dflyway.locations=filesystem:src/main/resources/db/analytic -Dflyway.url=jdbc:redshift://somesubdomain.redshift.amazonaws.com:5439/somedb -Dflyway.user=someuser -Dflyway.password=somepassword -Dflyway.driver=com.amazon.redshift.jdbc41.Driver flyway:baseline -Dflyway:baselineVersion=1.0.0.0 -X
```

```
[DEBUG] DDL Transactions Supported: true
[DEBUG] Schema: test_dropme
[DEBUG] Scanning for filesystem resources at 'src/main/resources/db/analytic' (Prefix: '', Suffix: '.sql')
[DEBUG] Scanning for resources in path: src/main/resources/db/analytic (src/main/resources/db/analytic)
[DEBUG] Found filesystem resource: src/main/resources/db/analytic/V1.0.0.0__Init.sql
[DEBUG] Schema "test_dropme" already exists. Skipping schema creation.
[DEBUG] Rolling back transaction...
[DEBUG] Transaction rolled back
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 7.303 s
[INFO] Finished at: 2015-07-16T10:08:46-05:00
[INFO] Final Memory: 22M/227M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:baseline (default-cli) on project data: org.flywaydb.core.api.FlywayException: Unable to insert row for version '0' in metadata table "test_dropme"."schema_version": [Amazon](500310) Invalid operation: Specified types or functions (one per INFO message) not supported on Redshift tables.; -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:baseline (default-cli) on project data: org.flywaydb.core.api.FlywayException: Unable to insert row for version '0' in metadata table "test_dropme"."schema_version"
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: org.flywaydb.core.api.FlywayException: Unable to insert row for version '0' in metadata table "test_dropme"."schema_version"
	at org.flywaydb.maven.AbstractFlywayMojo.execute(AbstractFlywayMojo.java:526)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: Specified types or functions (one per INFO message) not supported on Redshift tables.;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getReadyForQuery(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getReadyForQuery(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGClient.prepareStatement(Unknown Source)
	at com.amazon.redshift.dataengine.PGIQueryExecutor.<init>(Unknown Source)
	at com.amazon.redshift.dataengine.PGJDBCIDataEngine.prepare(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.<init>(Unknown Source)
	at com.amazon.jdbc.jdbc41.S41PreparedStatement.<init>(Unknown Source)
	at com.amazon.redshift.core.jdbc41.PGJDBC41PreparedStatement.<init>(Unknown Source)
	at com.amazon.redshift.core.jdbc41.PGJDBC41ObjectFactory.createPreparedStatement(Unknown Source)
	at com.amazon.jdbc.common.SConnection.prepareStatement(Unknown Source)
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.prepareStatement(JdbcTemplate.java:286)
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.update(JdbcTemplate.java:270)
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.addAppliedMigration(MetaDataTableImpl.java:115)
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.addBaselineMarker(MetaDataTableImpl.java:255)
	at org.flywaydb.core.internal.command.DbBaseline$2.doInTransaction(DbBaseline.java:116)
	at org.flywaydb.core.internal.command.DbBaseline$2.doInTransaction(DbBaseline.java:95)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbBaseline.baseline(DbBaseline.java:95)
	at org.flywaydb.core.Flyway$5.execute(Flyway.java:1186)
	at org.flywaydb.core.Flyway$5.execute(Flyway.java:1182)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
	at org.flywaydb.core.Flyway.baseline(Flyway.java:1182)
	at org.flywaydb.maven.BaselineMojo.doExecute(BaselineMojo.java:29)
	at org.flywaydb.maven.AbstractFlywayMojo.execute(AbstractFlywayMojo.java:524)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
```

**Comment by slmnhq** [comment]
I finally got this to work by specifying ``jdbc:postgresql`` instead of ``jdbc:redshift`` as the value for ``flyway.url``.

Also, ``flyway.driver`` does not need to be specified (it should just use the default Postgres driver).

I'm going to leave this issue open because the documentation should be updated to capture these caveats.

The 'correct' version of the command:

``mvn compile -Dflyway.schemas=test_dropme -Dflyway.locations=filesystem:src/main/resources/db/analytic -Dflyway.url=jdbc:postgresql://somesubdomain.redshift.amazonaws.com:5439/somedb -flyway:baseline -Dflyway:baselineVersion=1.0.0.0 -X``

**Comment by tleach** [comment]
Hitting this too.

**Comment by axelfontaine** [comment]
@nathanvick Can you take a look at this?

**Comment by nathanvick** [comment]
The Amazon Redshift jdbc driver was released Feb 26, 2015. Flyway currently supports only the old jdbc:postgresql URL format. We should add support for the new driver:

https://aws.amazon.com/about-aws/whats-new/2015/02/26/amazon-redshift-announces-custom-odbc-jdbc-drivers-and-query-visualization-in-the-console/

**Comment by axelfontaine** [comment]
Totally agree. Would you be willing to provide a PR?

**Comment by nathanvick** [comment]
Yes, will do.

**Comment by nathanvick** [comment]
@axelfontaine,

Redshift has two different driver classes, one for JDBC 4.1 and one for JDBC 4 (see http://docs.aws.amazon.com/redshift/latest/mgmt/configure-jdbc-connection.html). They are distributed in separate jar files, but we cannot detect the class name directly from the JDBC URL. Here are three ways of implementing support for this in `DriverDataSource.detectDriverForUrl`. What are your thoughts?

OPTION 1:
```java
if (AutoCloseable.class.isAssignableFrom(java.sql.Connection.class)) {
    // Connection implements AutoCloseable in JDBC 4.1:
    return "com.amazon.redshift.jdbc41.Driver";
} else {
    return "com.amazon.redshift.jdbc4.Driver";
}        
```

OPTION 2:
```java
try {
    // Return the newest Redshift driver on the classpath, without initializing it yet:
    Class.forName("com.amazon.redshift.jdbc41.Driver", false, this.getClass().getClassLoader());
    return "com.amazon.redshift.jdbc41.Driver";
} catch (ClassNotFoundException e) {
    return "com.amazon.redshift.jdbc4.Driver";            
}
```

OPTION 3:
Refactor `detectDriverForUrl` to return an array/list of possible driver class names, in order of preference.

**Comment by axelfontaine** [comment]
Add another if to https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/util/jdbc/DriverDataSource.java#L171

**Comment by axelfontaine** [comment]
Fixed with Nathan's PR. Thanks!
