### ISSUE TITLE
Flyway doesn't respect set search_path at method beforeMigrate

### ISSUE THREAD

**Issue by maroonyw** [flyway/flyway#1073]
There is a problem using method `beforeMigrate` for setting the `search_path` to a specific schema. My database setup is the following:

I use a PostgreSQL 9.1 database with 2 schemas `foo` and `bar` and the search path is set to `foo, bar`. Both schemas were migrated using flyway. Now I remove schema `bar` for example with

    drop schema bar cascade;

and create a **new flyway sql script** for schema `foo`. This migration fails at `flyway.migrate()`:

    Caused by: org.flywaydb.core.api.FlywayException: Error setting current schema to "foo"
            at org.flywaydb.core.internal.dbsupport.DbSupport.setCurrentSchema(DbSupport.java:103)
            at org.flywaydb.core.Flyway$1.execute(Flyway.java:1052)
            at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
            at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
            at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
            ... 18 more
    Caused by: org.postgresql.util.PSQLException: ERROR: invalid value for parameter "search_path": "foo, bar"
      Detail: schema "bar" does not exist
            at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
            at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
            at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
            at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
            at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
            at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:412)
            at org.flywaydb.core.internal.dbsupport.JdbcTemplate.execute(JdbcTemplate.java:219)
            at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.doSetCurrentSchema(PostgreSQLDbSupport.java:67)
            at org.flywaydb.core.internal.dbsupport.DbSupport.setCurrentSchema(DbSupport.java:101)
            ... 23 more

I don't understand this behavior. I want to migrate schema `foo` so the "missing schema `bar`" is something irrelevant at this moment. That's exactly the reason I'm using method `beforeMigrate`. But this method seems to be called later? 

Using Flyway 3.2.1

**Comment by maroonyw** [comment]
I have a workaround for this issue: Set the search path in method {{beforeValidate}}. 
But I really do not understand why method {{beforeMigrate}} is called to late?

**Comment by axelfontaine** [comment]
Setting the flyway.schemas property to foo should do what you want.

**Comment by maroonyw** [comment]
That's what I do before migrating schema ``foo`` with database user ``X`` (with configured search path ``foo, bar``): 

    flyway.setSchemas("foo");

Although I use this method, I get the error. That's why I'm using the workaround:

      @Override
      public void beforeValidate(Connection connection) {
        // This would be better at method beforeInfo, unfortunately it has no effect there.
        // Maybe flyway creates a separate database session in method info?
        try (Statement s = connection.createStatement()) {
          s.execute("SELECT set_config('search_path', '', false)");
        } catch (SQLException e) {
          throw new RuntimeException("Could not set search path", e);
        }
      }

**Comment by axelfontaine** [comment]
Can you try the code from master and see if it works for you now? (Simply build flyway-core with -DskipTests)

**Comment by maroonyw** [comment]
Tried code from master. Problem is still alive.

**Comment by axelfontaine** [comment]
OK, then

````
flyway.setDataSource(url, user, pwd, "SELECT set_config('search_path', '', false)");
```

is probably what you need.

**Comment by maroonyw** [comment]
That also works! And the position of the code is way better than in method ``beforeValidate``, but I think this is still a workaround?!

**Comment by axelfontaine** [comment]
No. It is designed for setting up the connection to the initial state you require.

Happy this is resolved :-) Closing.

**Comment by maroonyw** [comment]
Ok, thanks for your support!:-)

**Comment by bladeoflight16** [comment]
This is a major problem if you need to alter the `search_path` in beforeMigrate.
