### ISSUE TITLE
Connection gets reset when executing a very long running migration

### ISSUE THREAD

**Issue by nistopia** [flyway/flyway#1103]
Seems like flyway creates 2 connections per migration; where one connection just locks and updates the metadata and other connection runs the migration script. Problem is that for long running migration the connection for metadata table gets reset because of inactivity. As a result migration fails because it can't update the metadata table. Do we really need to use 2 connections? And if we need is there a way to keep that connection alive?

Exception in thread "main" org.flywaydb.core.api.FlywayException: Unable to check whether table "FLYWAY_USER"."schema_version" exists at org.flywaydb.core.internal.dbsupport.Table.exists(Table.java:53) at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.createIfNotExists(MetaDataTableImpl.java:78) at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.addAppliedMigration(MetaDataTableImpl.java:106) at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:327) at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:46) at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:207) at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156) at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72) at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156) at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059) at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006) at org.flywaydb.core.Flyway.execute(Flyway.java:1418) at org.flywaydb.core.Flyway.migrate(Flyway.java:1006) at 
.........
Caused by: java.sql.SQLRecoverableException: IO Error: Connection reset at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:899) at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175) at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296) at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3613) at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3657) at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1495) at oracle.jdbc.OracleDatabaseMetaData.getTables(OracleDatabaseMetaData.java:3078) at com.mchange.v2.c3p0.impl.NewProxyDatabaseMetaData.getTables(NewProxyDatabaseMetaData.java:2828) at org.flywaydb.core.internal.dbsupport.Table.exists(Table.java:84) at org.flywaydb.core.internal.dbsupport.oracle.OracleTable.doExists(OracleTable.java:48) at org.flywaydb.core.internal.dbsupport.Table.exists(Table.java:51) ... 14 more Caused by: java.net.SocketException: Connection reset at java.net.SocketInputStream.read(SocketInputStream.java:209) at java.net.SocketInputStream.read(SocketInputStream.java:141) at oracle.net.ns.Packet.receive(Packet.java:308) at oracle.net.ns.DataPacket.receive(DataPacket.java:106) at oracle.net.ns.NetInputStream.getNextPacket(NetInputStream.java:324) at oracle.net.ns.NetInputStream.read(NetInputStream.java:268) at oracle.net.ns.NetInputStream.read(NetInputStream.java:190) at oracle.net.ns.NetInputStream.read(NetInputStream.java:107) at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:124) at oracle.jdbc.driver.T4CSocketInputStreamWrapper.read(T4CSocketInputStreamWrapper.java:80) at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1137) at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:350) at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227) at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531) at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:208) at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:886)

**Comment by axelfontaine** [comment]
Yes we need two connections for managing concurrent nodes. See http://flywaydb.org/documentation/faq.html#parallel

You can increase the timeout on your DB or divide up the migration to fix this.

**Comment by nistopia** [comment]
Can we make this a configurable settings? I get it we need this to manage concurrent nodes, but i don't think we need it to manage a single node. The migration i am trying is to partition a big table. DB is behind a firewall and idle connection is getting killed by firewall after around 10 mins.

**Comment by dlazerka** [comment]
+1

**Comment by gavdjones** [comment]
+1

However, since we are using Oracle, I'm trying out the following, since i believe the locking mechanism that Flyway uses (for [Oracle](https://docs.oracle.com/cd/B28359_01/server.111/b28286/statements_9015.htm)) will still work using the same Connection as the one done for migrations.  Even if it doesn't, it allows us to use long running migrations that can't be predictably broken down.  I used Spring's "SingleConnectionDataSource", though its almost as easy to write a delegate/wrapper that only ever returns one connection.  

DataSource singleConnectionDataSource = new SingleConnectionDataSource(this.dbUrl, this.dbUser, this.dbPwd, true);
newFlyway.setDataSource(singleConnectionDataSource);

**Comment by scoobyshi** [comment]
+1; This should be considered a bug.  If your target migration is failing simply because the connection on the metadata table is not kept alive, you are preventing a migration by not managing that initial connection on the metadata table.  This behaviour is unexpected, because you can no longer rely on it to consistently apply all migrations, instead, you must circumvent this limitation.  If your migration failed because the actual migration itself was taking too long, then that would be another matter.

**Comment by cosmin** [comment]
@axelfontaine can you please re-consider this issue? Not everyone has control over the connection timeout or keep alive settings on the database. It would be great to have some control over this from within flyway itself to allow flyway to be used in more environments. If it's a question of resources I might be able to contribute a pull request as long as I know it's something you will consider.

**Comment by axelfontaine** [comment]
@cosmin It is not an issue of resources or code. I simply don't see a solution. As long as Oracle issues implicit commits before and after DDL statements causing `LOCK TABLE` to release its lock, I just don't see how a single connection could work without giving up the ability for multiple nodes to safely attempt to migrate concurrently. So yes, if you have a conceptual solution to this that you can contribute, I am all ears.

**Comment by dlazerka** [comment]
@axelfontaine This issue happens with MySQL as well.

**Comment by axelfontaine** [comment]
@dlazerka That must be a different issue as MySQL support uses a single connection with named locks that don't suffer from the same issues as Oracle's `LOCK TABLE`. Please test again with 4.2.0 and file a new issue if you still see the problem.

**Comment by axelfontaine** [comment]
@cosmin We have now enabled Oracle's support for keepAlive by default in the 5.0 branch. There is honestly not much else I can think of we could do on our end.

**Comment by cosmin** [comment]
@axelfontaine I wasn’t suggesting using a single connection, I understand the reason behind having two connections. I just wanted a way to either keep alive the connection or deal with it if it goes stale.

Using Oracle’s keep alive should work. We’ll give that a shot. Thanks!
