### ISSUE TITLE
Upgrading H2 DB from Flyway 2.0.3 to 4.0 failed - couldn't upgrade metadata table

### ISSUE THREAD

**Issue by kubo44** [flyway/flyway#1243]
###### What version of Flyway are you using?

4.0

###### What database are you using (type & version)?

h2 version 1.3.170

###### What operating system are you using?

Windows 7 64bit

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I was using Flyway 2.0.3 and changed my code to use Flyway 4.0. On calling Flyway#migrate, Flyway tried to upgrade and failed (details below).
Migration script would like to DROP CONSTRAINT which is not in 2.0.3 (it was added later):
org\flywaydb\core\internal\dbsupport\h2\upgradeMetaDataTable.sql
It seems it's not only H2 DB problem.

###### What did you expect to see?

Expected to see successful Flyway init.

###### What did you see instead?

```
Exception in thread "main" org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Script failed
-------------
SQL State  : 90057
Error Code : 90057
Message    : Constraint "ABC_SCHEMA_VERSION_pk" not found; SQL statement:
ALTER TABLE "PUBLIC"."ABC_SCHEMA_VERSION" DROP CONSTRAINT "ABC_SCHEMA_VERSION_pk" [90057-170]
Line       : 20
Statement  : ALTER TABLE "PUBLIC"."ABC_SCHEMA_VERSION" DROP CONSTRAINT "ABC_SCHEMA_VERSION_pk"

	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:117)
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.upgradeIfNecessary(MetaDataTableImpl.java:79)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1356)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
	...
Caused by: org.h2.jdbc.JdbcSQLException: Constraint "ABC_SCHEMA_VERSION_pk" not found; SQL statement:
ALTER TABLE "PUBLIC"."ABC_SCHEMA_VERSION" DROP CONSTRAINT "ABC_SCHEMA_VERSION_pk" [90057-170]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:329)
	at org.h2.message.DbException.get(DbException.java:169)
	at org.h2.message.DbException.get(DbException.java:146)
	at org.h2.command.ddl.AlterTableDropConstraint.update(AlterTableDropConstraint.java:40)
	at org.h2.command.CommandContainer.update(CommandContainer.java:75)
	at org.h2.command.Command.executeUpdate(Command.java:230)
	at org.h2.server.TcpServerThread.process(TcpServerThread.java:333)
	at org.h2.server.TcpServerThread.run(TcpServerThread.java:149)
	at java.lang.Thread.run(Thread.java:745)

	at org.h2.engine.SessionRemote.done(SessionRemote.java:568)
	at org.h2.command.CommandRemote.executeUpdate(CommandRemote.java:181)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:177)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:152)
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.executeStatement(JdbcTemplate.java:238)
	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:114)
	... 8 more
```

**Comment by axelfontaine** [comment]
To upgrade from Flyway 2.x you have to upgrade at least 2.1 first and then everything should work as expected.

**Comment by kubo44** [comment]
What if you use syntax 
`ALTER TABLE tableName DROP CONSTRAINT IF EXISTS constraintName`
I have many customers and they use different versions of my application. I cannot make them to first use version with 2.1 and then with 4.0.

**Comment by axelfontaine** [comment]
Well the alternative is then for you to manually migrate the metadata table using jdbc statements or to drop and recreate it with Flyway 4.0 by using baseline().

**Comment by kubo44** [comment]
ok, thank you Axel

**Comment by joachimvda** [comment]
We are currently using 2.3.1 and also get this exception when trying to migrate to 3.0.
