### ISSUE TITLE
Executing OracleSchema.doExists() fails

### ISSUE THREAD

**Issue by MaxWeinhart** [flyway/flyway#1284]
Flyway Version: 3.2.1
Database: Oracle 12c
Operating-System: Linux

I am using flyway with spring-boot.

Flyway executes following sql command: 

    package org.flywaydb.core.internal.dbsupport.oracle;
    ...
    public class OracleSchema extends Schema<OracleDbSupport> {
	@Override
	protected boolean doExists() throws SQLException {
	    return jdbcTemplate.queryForInt("SELECT COUNT(*) FROM all_users WHERE username=?", name) > 0;
	}
    ...
    }

this causes following exception:

    Caused by: java.sql.SQLSyntaxErrorException: ORA-00942: Tabelle oder View nicht vorhanden

	    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)
	    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)
	    at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)
	    at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)
	    at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)
	    at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)
	    at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)
	    at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)
	    at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:774)
	    at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:925)
	    at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1111)
	    at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)
	    at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:4845)
	    at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1501)
	    at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	    at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	    at org.flywaydb.core.internal.dbsupport.JdbcTemplate.queryForInt(JdbcTemplate.java:156)
	    at org.flywaydb.core.internal.dbsupport.oracle.OracleSchema.doExists(OracleSchema.java:48)
	    at org.flywaydb.core.internal.dbsupport.Schema.exists(Schema.java:72)
	    ... 205 more

This happens because I am not allowed to read table all_users.

The schema name is dertermined with following command:

    @Override
    protected String doGetCurrentSchema() throws SQLException {
        return jdbcTemplate.queryForString("SELECT USER FROM dual");
    }

Is it resonable to merge the queries 

    SELECT COUNT(*) FROM all_users WHERE username=?

and 

    SELECT USER FROM dual
to check schema existence?

**Comment by axelfontaine** [comment]
No, because also the existence of non-default schemas (differing from the user name) must be checked.

**Comment by liweinan0423** [comment]
We are facing the same problem that our production oracle db user doesn't have permission to read   `all_users` view.  I think we should give user the liberty of deciding whether to create schema on migration(this options would default to true for backward capability).

````
if (createSchema) {
     new DbSchemas(connectionMetaDataTable, schemas, metaDataTable).create();
}
````

The createSchema options should be able to be turned off by the following property

````
flyway.createSchema=false
````
