### ISSUE TITLE
NullPointerException migrating to "current" on empty DB

### ISSUE THREAD

**Issue by gimmi** [flyway/flyway#1302]
###### What version of Flyway are you using?

```
      <dependency>
         <groupId>org.flywaydb</groupId>
         <artifactId>flyway-core</artifactId>
         <version>4.0</version>
      </dependency>
```

###### What database are you using (type & version)?

MySQL

###### What operating system are you using?

Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

On a freshly created, empty DB (even without `schema_version`) run the following:

```
Flyway flyway = new Flyway();
flyway.setDataSource(/* ... */);
flyway.setTargetAsString("current");
flyway.migrate();
```

###### What did you expect to see?

The database should be migrated to the latest version available in migrations scripts

###### What did you see instead?

```
java.lang.NullPointerException
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:110)
	at org.flywaydb.core.internal.command.DbValidate$2.doInTransaction(DbValidate.java:156)
	at org.flywaydb.core.internal.command.DbValidate$2.doInTransaction(DbValidate.java:150)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:150)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:994)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:72)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:921)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1361)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
	...
```

**Comment by axelfontaine** [comment]
Good catch! Fixed.

**Comment by gimmi** [comment]
Thanks a lot!
