### ISSUE TITLE
SQLite clean fails with foreign key constraints

### ISSUE THREAD

**Issue by jonbarksdale** [flyway/flyway#1311]
###### What version of Flyway are you using?

4.0
###### What database are you using (type & version)?

SQLite 3, jdbc driver: 'org.xerial:sqlite-jdbc:3.8.11.2'
###### What operating system are you using?

Mac OX 10.11, not that it is relevant
###### What did you do?

Writing integration tests for a DAO, attempted to use flyway clean between tests (cleanup method).
I am using an in memory version of SQLite for testing, with foreign keys enabled:

``` groovy
    def config = new SQLiteConfig()
    config.enforceForeignKeys(true)
    Connection conn = new DriverManagerDataSource(getUrl(), config.toProperties()).getConnection()
    def dataSource = new SingleConnectionDataSource(conn, true)
```
###### What did you expect to see?

No error, all objects dropped
###### What did you see instead?

``` stacktrace
org.flywaydb.core.api.FlywayException: Unable to drop "main"."PROCESS_FLOW"

    at org.flywaydb.core.internal.dbsupport.SchemaObject.drop(SchemaObject.java:82)
    at org.flywaydb.core.internal.dbsupport.sqlite.SQLiteSchema.doClean(SQLiteSchema.java:78)
    at org.flywaydb.core.internal.dbsupport.Schema.clean(Schema.java:148)
    at org.flywaydb.core.internal.command.DbClean$4.doInTransaction(DbClean.java:182)
    at org.flywaydb.core.internal.command.DbClean$4.doInTransaction(DbClean.java:180)
    at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
    at org.flywaydb.core.internal.command.DbClean.cleanSchema(DbClean.java:180)
    at org.flywaydb.core.internal.command.DbClean.clean(DbClean.java:130)
    at org.flywaydb.core.Flyway$3.execute(Flyway.java:1017)
    at org.flywaydb.core.Flyway$3.execute(Flyway.java:1013)
    at org.flywaydb.core.Flyway.execute(Flyway.java:1361)
    at org.flywaydb.core.Flyway.clean(Flyway.java:1013)
    at com.the41.datapull.model.SparkProcessFlowDaoDbSpec.cleanup(SparkProcessFlowDaoDbSpec.groovy:57)
Caused by: java.sql.SQLException: [SQLITE_CONSTRAINT]  Abort due to constraint violation (FOREIGN KEY constraint failed)
    at org.sqlite.core.DB.newSQLException(DB.java:890)
    at org.sqlite.core.DB.newSQLException(DB.java:901)
    at org.sqlite.core.DB.execute(DB.java:810)
    at org.sqlite.jdbc3.JDBC3PreparedStatement.execute(JDBC3PreparedStatement.java:50)
    at org.flywaydb.core.internal.dbsupport.JdbcTemplate.execute(JdbcTemplate.java:219)
    at org.flywaydb.core.internal.dbsupport.sqlite.SQLiteTable.doDrop(SQLiteTable.java:47)
    at org.flywaydb.core.internal.dbsupport.SchemaObject.drop(SchemaObject.java:80)
    ... 12 more
```

**Comment by axelfontaine** [comment]
Please provide a small example sql migration Flyway fails to clean so we can reproduce this.

**Comment by jonbarksdale** [comment]
Sure, it might be later today though, a little slammed at work right now.  Also, are you guys aware that flyway uses two connections simultaneously? So if I don't wrap the datasource in the single connection data source, it deadlocks on migrate (with sqlite)?  If not, I can write that up as well.

**Comment by jonbarksdale** [comment]
Attaching a simple gradle project that reproduces the issue.

[flyway-sqlite-bug.zip](https://github.com/flyway/flyway/files/268828/flyway-sqlite-bug.zip)

**Comment by axelfontaine** [comment]
Unable to reproduce. See my commit.
