### ISSUE TITLE
Postgresql CopyManager class not found when using SBT 

### ISSUE THREAD

**Issue by mlvn23** [flyway/flyway#1325]
I'm using Flyway 4.0.1 using SBT plugin and Postgresql 9.3.1102-jdbc41 driver with Postgresql 9.3 database. I'm on Windows 7, Java 8, SBT 0.13.9.

When I try to flywayMigrate an SQL with a COPY ... FROM stdin, it would fail with class not found exception (see stack trace below).

I tried with flyway command line using the same migration script and configuration and it worked.

```
java.lang.NoClassDefFoundError: org/postgresql/copy/CopyManager
        at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.executePgCopy(PostgreSQLDbSupport.java:138)
        at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:112)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:71)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrate(DbMigrate.java:352)
        at org.flywaydb.core.internal.command.DbMigrate.access$1100(DbMigrate.java:47)
        at org.flywaydb.core.internal.command.DbMigrate$4.doInTransaction(DbMigrate.java:308)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:305)
        at org.flywaydb.core.internal.command.DbMigrate.access$1000(DbMigrate.java:47)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:230)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:173)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:173)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:959)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1365)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$37$$anonfun$apply$1.apply$mcI$sp(FlywayPlugin.scala:184)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$37$$anonfun$apply$1.apply(FlywayPlugin.scala:184)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$37$$anonfun$apply$1.apply(FlywayPlugin.scala:184)
        at org.flywaydb.sbt.FlywayPlugin$.withContextClassLoader(FlywayPlugin.scala:227)
        at org.flywaydb.sbt.FlywayPlugin$.org$flywaydb$sbt$FlywayPlugin$$withPrepared(FlywayPlugin.scala:210)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$37.apply(FlywayPlugin.scala:184)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$37.apply(FlywayPlugin.scala:184)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.postgresql.copy.CopyManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.executePgCopy(PostgreSQLDbSupport.java:138)
        at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:112)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:71)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrate(DbMigrate.java:352)
        at org.flywaydb.core.internal.command.DbMigrate.access$1100(DbMigrate.java:47)
        at org.flywaydb.core.internal.command.DbMigrate$4.doInTransaction(DbMigrate.java:308)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:305)
        at org.flywaydb.core.internal.command.DbMigrate.access$1000(DbMigrate.java:47)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:230)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:173)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:173)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:959)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1365)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$37$$anonfun$apply$1.apply$mcI$sp(FlywayPlugin.scala:184)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$37$$anonfun$apply$1.apply(FlywayPlugin.scala:184)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$37$$anonfun$apply$1.apply(FlywayPlugin.scala:184)
        at org.flywaydb.sbt.FlywayPlugin$.withContextClassLoader(FlywayPlugin.scala:227)
        at org.flywaydb.sbt.FlywayPlugin$.org$flywaydb$sbt$FlywayPlugin$$withPrepared(FlywayPlugin.scala:210)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$37.apply(FlywayPlugin.scala:184)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$37.apply(FlywayPlugin.scala:184)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (service/*:flywayMigrate) java.lang.NoClassDefFoundError: org/postgresql/copy/CopyManager
```

**Comment by axelfontaine** [comment]
Are you facing the same issue with the latest version of the driver?

**Comment by axelfontaine** [comment]
Closing due to lack of response.

**Comment by mlvn23** [comment]
@axelfontaine, sorry for the late reply. I tried it with SBT plugin version 4.1.2 and I still see the same issue:

```
java.lang.NoClassDefFoundError: org/postgresql/copy/CopyManager
        at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.executePgCopy(PostgreSQLDbSupport.java:152)
        at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:140)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:76)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrate(DbMigrate.java:324)
        at org.flywaydb.core.internal.command.DbMigrate.access$900(DbMigrate.java:49)
        at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:280)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:277)
        at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:49)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:201)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:142)
        at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:68)
        at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.lock(PostgreSQLDbSupport.java:162)
        at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:174)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:142)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:969)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:930)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1413)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:930)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$40$$anonfun$apply$1.apply$mcI$sp(FlywayPlugin.scala:190)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$40$$anonfun$apply$1.apply(FlywayPlugin.scala:190)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$40$$anonfun$apply$1.apply(FlywayPlugin.scala:190)
        at org.flywaydb.sbt.FlywayPlugin$.withContextClassLoader(FlywayPlugin.scala:233)
        at org.flywaydb.sbt.FlywayPlugin$.org$flywaydb$sbt$FlywayPlugin$$withPrepared(FlywayPlugin.scala:216)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$40.apply(FlywayPlugin.scala:190)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$40.apply(FlywayPlugin.scala:190)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.postgresql.copy.CopyManager
        at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.executePgCopy(PostgreSQLDbSupport.java:152)
        at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:140)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:76)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrate(DbMigrate.java:324)
        at org.flywaydb.core.internal.command.DbMigrate.access$900(DbMigrate.java:49)
        at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:280)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:277)
        at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:49)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:201)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:142)
        at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:68)
        at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.lock(PostgreSQLDbSupport.java:162)
        at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:174)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:142)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:969)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:930)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1413)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:930)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$40$$anonfun$apply$1.apply$mcI$sp(FlywayPlugin.scala:190)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$40$$anonfun$apply$1.apply(FlywayPlugin.scala:190)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$40$$anonfun$apply$1.apply(FlywayPlugin.scala:190)
        at org.flywaydb.sbt.FlywayPlugin$.withContextClassLoader(FlywayPlugin.scala:233)
        at org.flywaydb.sbt.FlywayPlugin$.org$flywaydb$sbt$FlywayPlugin$$withPrepared(FlywayPlugin.scala:216)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$40.apply(FlywayPlugin.scala:190)
        at org.flywaydb.sbt.FlywayPlugin$$anonfun$flywayBaseSettings$40.apply(FlywayPlugin.scala:190)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:35)
        at scala.Function3$$anonfun$tupled$1.apply(Function3.scala:34)
        at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
        at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
        at sbt.std.Transform$$anon$4.work(System.scala:63)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
        at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
        at sbt.Execute.work(Execute.scala:235)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
        at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
        at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
[error] (chronos/*:flywayMigrate) java.lang.NoClassDefFoundError: org/postgresql/copy/CopyManager
```

**Comment by bigmoby** [comment]
@mlvn23 @axelfontaine 
Hi guys,
I solved the issue adding `libraryDependencies += "org.postgresql" % "postgresql" % "42.0.0"` in plugins.sbt. In other words this could resolve your issue:
`
libraryDependencies += "org.postgresql" % "postgresql" % "42.0.0"

resolvers += "Flyway" at "https://flywaydb.org/repo"

addSbtPlugin("org.flywaydb" % "flyway-sbt" % "4.1.2")
`
I hope this help you!
Fabio Mauro

**Comment by mlvn23** [comment]
@bigmoby @axelfontaine it works for me as well. Thanks!
