### ISSUE TITLE
OracleDB failed to migrate while schema name contains character "-"

### ISSUE THREAD

**Issue by eugenpp** [flyway/flyway#1333]
###### What version of Flyway are you using?

4.0.1
###### What database are you using (type & version)?

Oracle 11.2
###### What operating system are you using?

Windows, Linux
###### What did you do?
- run command line "flyway migrate" or "flyway repair" or whatever
- run migration within java application
###### What did you expect to see?

Migrated database.
###### What did you see instead?

Database unchanged.

```
Database: jdbc:oracle:thin:@**** (Oracle 11.2)
....
ERROR: Error restoring current schema to its original setting
```

with -X switch enabled....

```
C:\tmp\flyway-4.0.1>flyway -X repair
Flyway 4.0.1 by Boxfuse

DEBUG: Java 1.6.0_45 (Sun Microsystems Inc.)
DEBUG: Windows 8 6.2 amd64

...
DEBUG: flyway.jarDirs -> C:\tmp\flyway-4.0.1\jars
DEBUG: flyway.password -> *********
DEBUG: flyway.url -> jdbc:oracle:*****************
DEBUG: flyway.user -> MY-SCHEMA
DEBUG: flyway.locations -> classpath:db.migration
...
Database: jdbc:oracle:thin:********************* (Oracle 11.2)
DEBUG: DDL Transactions Supported: false
DEBUG: Schema: "MY-SCHEMA"
DEBUG: Spring Jdbc available: false
DEBUG: Scanning for SQL callbacks ...
DEBUG: Scanning for classpath resources at 'classpath:db/migration' (Prefix: '', Suffix: '.sql')
DEBUG: Determining location urls for classpath:db/migration using ClassLoader sun.misc.Launcher$AppClassLoader@40affc70 ...
...
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Error restoring current schema to its original setting
        at org.flywaydb.core.internal.dbsupport.DbSupport.restoreCurrentSchema(DbSupport.java:132)
        at org.flywaydb.core.internal.command.DbRepair.repair(DbRepair.java:144)
        at org.flywaydb.core.Flyway$6.execute(Flyway.java:1100)
        at org.flywaydb.core.Flyway$6.execute(Flyway.java:1098)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1365)
        at org.flywaydb.core.Flyway.repair(Flyway.java:1098)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:145)
        at org.flywaydb.commandline.Main.main(Main.java:102)
Caused by: java.sql.SQLSyntaxErrorException: ORA-00922: chřbaj˙ca alebo neplatnß vożba

        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:440)
        at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:396)
        at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:837)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:445)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:191)
        at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:523)
        at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:207)
        at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:1010)
        at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1315)
        at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3576)
        at oracle.jdbc.driver.OraclePreparedStatement.execute(OraclePreparedStatement.java:3677)
        at oracle.jdbc.driver.OraclePreparedStatementWrapper.execute(OraclePreparedStatementWrapper.java:1374)
        at org.flywaydb.core.internal.dbsupport.JdbcTemplate.execute(JdbcTemplate.java:219)
        at org.flywaydb.core.internal.dbsupport.oracle.OracleDbSupport.doChangeCurrentSchemaTo(OracleDbSupport.java:55)
        at org.flywaydb.core.internal.dbsupport.DbSupport.restoreCurrentSchema(DbSupport.java:130)
        ... 7 more
```

**Comment by eugenpp** [comment]
Error is caused by SQL command 
```
public class OracleDbSupport extends DbSupport {
...  
    @Override
    protected void doChangeCurrentSchemaTo(String schema) throws SQLException {
        jdbcTemplate.execute("ALTER SESSION SET CURRENT_SCHEMA=" + schema);
    }

```

For schema names with special characters (like "-" in our schema name MY-SCHEMA) schema name should be quoted.

**Comment by axelfontaine** [comment]
Schema name is already quoted. Reverting previous erroneous fix. That is not the issue.

Please reopen with _exact_ steps to reproduce if it occurs again.

**Comment by eugenpp** [comment]
Schema is not quoted. I build version 4.0.1 from sources to add logging info to the source code.

```java
/**
 * Oracle-specific support.
 */
public class OracleDbSupport extends DbSupport {
    @Override
    protected void doChangeCurrentSchemaTo(String schema) throws SQLException {
    	String command = "ALTER SESSION SET CURRENT_SCHEMA=" + schema;
        // ADDED LOG MESSAGE
    	System.out.println("****"+command+"****");
        jdbcTemplate.execute(command);
    }
}
```

flyway migrate....

```
Database: jdbc:oracle:thin:@localhost:1525/MYORA (Oracle 11.2)
Repair of failed migration in metadata table "MY-SCHEMA"."schema_version" not necessary. No failed migration detected.
Successfully repaired metadata table "MY-SCHEMA"."schema_version" (execution time 00:00.055s).
Manual cleanup of the remaining effects the failed migration may still be required.
****ALTER SESSION SET CURRENT_SCHEMA=RSD-CRK****
ERROR: Error restoring current schema to its original setting
```

If you got quoted schema in ALTER SESSION command then I have no idea what is the reason. Maybe some database or environment settings????

**Comment by axelfontaine** [comment]
Thanks for investigating. Then the problem lies in one of the calling methods.

**Comment by eugenpp** [comment]
`SELECT USER FROM dual` returns unqoted string regardless if schema name is created as case sensitive or not. 

case insensitive
```
create user TEST identified by passwd;
SELECT USER FROM dual # returns TEST without quotes
ALTER SESSION SET CURRENT_SCHEMA=TEST # succeed
ALTER SESSION SET CURRENT_SCHEMA="TEST" # succeed!!!
```

case sensitive
```
create user MY-TEST identified by passwd; # FAILED
# to create user name with hyphen in it you should use quoted name. 
create user "MY-TEST" identified by passwd;
SELECT USER FROM dual # returns MY-TEST without quotes!!!
ALTER SESSION SET CURRENT_SCHEMA=MY-TEST # FAILED
ALTER SESSION SET CURRENT_SCHEMA="MY-TEST" # succeed
```
