### ISSUE TITLE
Flyway-repo s3 failure

### ISSUE THREAD

**Issue by deeboh** [flyway/flyway#1335]
###### What version of Flyway are you using?
org.flywaydb:flyway-maven-plugin:3.2.1

###### What database are you using (type & version)?
Oracle 11.3r2 RAC

###### What operating system are you using?
bcs-ipit-jenkins:~> lsb_release -a
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:cxx-3.0-amd64:cxx-3.0-noarch:cxx-3.1-amd64:cxx-3.1-noarch:cxx-3.2-amd64:cxx-3.2-noarch:cxx-4.0-amd64:cxx-4.0-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-3.1-amd64:desktop-3.1-noarch:desktop-3.2-amd64:desktop-3.2-noarch:desktop-4.0-amd64:desktop-4.0-noarch:desktop-4.1-amd64:desktop-4.1-noarch:graphics-2.0-amd64:graphics-2.0-noarch:graphics-3.0-amd64:graphics-3.0-noarch:graphics-3.1-amd64:graphics-3.1-noarch:graphics-3.2-amd64:graphics-3.2-noarch:graphics-4.0-amd64:graphics-4.0-noarch:graphics-4.1-amd64:graphics-4.1-noarch:languages-3.2-amd64:languages-3.2-noarch:languages-4.0-amd64:languages-4.0-noarch:languages-4.1-amd64:languages-4.1-noarch:multimedia-3.2-amd64:multimedia-3.2-noarch:multimedia-4.0-amd64:multimedia-4.0-noarch:multimedia-4.1-amd64:multimedia-4.1-noarch:printing-3.2-amd64:printing-3.2-noarch:printing-4.0-amd64:printing-4.0-noarch:printing-4.1-amd64:printing-4.1-noarch:qt4-3.1-amd64:qt4-3.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
Tried to build my project from within Jenkins using MVN

###### What did you expect to see?
a normal build deployment.

###### What did you see instead?
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:clean (rebuild-database) on project ocp-app: Execution rebuild-database of goal org.flywaydb:flyway-maven-plugin:3.2.1:clean failed: Plugin org.flywaydb:flyway-maven-plugin:3.2.1 or one of its dependencies could not be resolved: Could not transfer artifact com.oracle:ojdbc6:jar:11.1.0.7.0 from/to flyway-repo (s3://flyway-repo/release): Cannot access s3://flyway-repo/release with type default using the available connector factories: BasicRepositoryConnectorFactory: Cannot access s3://flyway-repo/release using the registered transporter factories: WagonTransporterFactory: java.util.NoSuchElementException
[ERROR] role: org.apache.maven.wagon.Wagon
[ERROR] roleHint: s3
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.flywaydb:flyway-maven-plugin:3.2.1:clean (rebuild-database) on project ocp-app: Execution rebuild-database of goal org.flywaydb:flyway-maven-plugin:3.2.1:clean failed: Plugin org.flywaydb:flyway-maven-plugin:3.2.1 or one of its dependencies could not be resolved: Could not transfer artifact com.oracle:ojdbc6:jar:11.1.0.7.0 from/to flyway-repo (s3://flyway-repo/release): Cannot access s3://flyway-repo/release with type default using the available connector factories: BasicRepositoryConnectorFactory
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.jvnet.hudson.maven3.launcher.Maven32Launcher.main(Maven32Launcher.java:132)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
	at jenkins.maven3.agent.Maven32Main.launch(Maven32Main.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:136)
	at hudson.maven.Maven3Builder.call(Maven3Builder.java:71)
	at hudson.remoting.UserRequest.perform(UserRequest.java:152)
	at hudson.remoting.UserRequest.perform(UserRequest.java:50)
	at hudson.remoting.Request$2.run(Request.java:332)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution rebuild-database of goal org.flywaydb:flyway-maven-plugin:3.2.1:clean failed: Plugin org.flywaydb:flyway-maven-plugin:3.2.1 or one of its dependencies could not be resolved: Could not transfer artifact com.oracle:ojdbc6:jar:11.1.0.7.0 from/to flyway-repo (s3://flyway-repo/release): Cannot access s3://flyway-repo/release with type default using the available connector factories: BasicRepositoryConnectorFactory
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	... 31 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.flywaydb:flyway-maven-plugin:3.2.1 or one of its dependencies could not be resolved: Could not transfer artifact com.oracle:ojdbc6:jar:11.1.0.7.0 from/to flyway-repo (s3://flyway-repo/release): Cannot access s3://flyway-repo/release with type default using the available connector factories: BasicRepositoryConnectorFactory
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:218)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:149)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:400)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:372)
	at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:231)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:102)
	... 32 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact com.oracle:ojdbc6:jar:11.1.0.7.0 from/to flyway-repo (s3://flyway-repo/release): Cannot access s3://flyway-repo/release with type default using the available connector factories: BasicRepositoryConnectorFactory
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:367)
	at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolveInternal(DefaultPluginDependenciesResolver.java:210)
	... 37 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact com.oracle:ojdbc6:jar:11.1.0.7.0 from/to flyway-repo (s3://flyway-repo/release): Cannot access s3://flyway-repo/release with type default using the available connector factories: BasicRepositoryConnectorFactory
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:531)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 40 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access s3://flyway-repo/release with type default using the available connector factories: BasicRepositoryConnectorFactory
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:174)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
	... 41 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access s3://flyway-repo/release using the registered transporter factories: WagonTransporterFactory
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:119)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
	at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
	... 42 more
Caused by: org.eclipse.aether.transfer.NoTransporterException: Cannot access s3://flyway-repo/release using the registered transporter factories: WagonTransporterFactory
	at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:151)
	at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:115)
	... 44 more
Caused by: org.eclipse.aether.transfer.NoTransporterException: java.util.NoSuchElementException
      role: org.apache.maven.wagon.Wagon
  roleHint: s3
	at org.eclipse.aether.transport.wagon.WagonTransporter.<init>(WagonTransporter.java:120)
	at org.eclipse.aether.transport.wagon.WagonTransporterFactory.newInstance(WagonTransporterFactory.java:127)
	at org.eclipse.aether.internal.impl.DefaultTransporterProvider.newTransporter(DefaultTransporterProvider.java:110)
	... 45 more
Caused by: org.codehaus.plexus.component.repository.exception.ComponentLookupException: java.util.NoSuchElementException
      role: org.apache.maven.wagon.Wagon
  roleHint: s3
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:267)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:255)
	at org.eclipse.aether.internal.transport.wagon.PlexusWagonProvider.lookup(PlexusWagonProvider.java:58)
	at org.eclipse.aether.transport.wagon.WagonTransporter.lookupWagon(WagonTransporter.java:271)
[JENKINS] Archiving /var/lib/jenkins/workspace/ocp-app-dev-deploy/pom.xml to com.qualcomm.ipit/ocp-app/1.2.1/ocp-app-1.2.1.pom
	at org.eclipse.aether.transport.wagon.WagonTransporter.<init>(WagonTransporter.java:115)
	... 47 more
Caused by: java.util.NoSuchElementException
	at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:118)
	at org.eclipse.sisu.plexus.RealmFilteredBeans$FilteredItr.next(RealmFilteredBeans.java:1)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:76)
	at org.eclipse.sisu.plexus.DefaultPlexusBeans$Itr.next(DefaultPlexusBeans.java:1)
	at org.codehaus.plexus.DefaultPlexusContainer.lookup(DefaultPlexusContainer.java:263)
	... 51 more

**Comment by axelfontaine** [comment]
The issue here: You are missing the Oracle JDBC jar on your classpath.
What is happening: Maven is trying all repos including our private one to find it and fails.

**Comment by deeboh** [comment]
I get that my friend. what I don’t get is why the s3 location can’t be access… do you have any suggestions to that possibility?
