### ISSUE TITLE
Flyway uses non exists version_rank column.

### ISSUE THREAD

**Issue by t0kieu** [flyway/flyway#1343]
Hello, I have problem with migrations. Probably it's bug in flyway. Migration process to try use `version_rank` column from table `schema_version`, which doesn't exist.
Please could me someone help?
###### What version of Flyway are you using?
4.0.2

###### What database are you using (type & version)?
MySQL 5.5.49

###### What operating system are you using?
OS X El Capitan

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I ran flyway migration before tests.

###### What did you expect to see?
I expect successful migration.

###### What did you see instead?

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Error while retrieving the list of applied migrations from metadata table `xxx`.`schema_version`
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:118)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:766)
	at org.springframework.boot.SpringApplication.createAndRefreshContext(SpringApplication.java:361)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.test.SpringApplicationContextLoader.loadContext(SpringApplicationContextLoader.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
	... 45 more
Caused by: org.flywaydb.core.api.FlywayException: Error while retrieving the list of applied migrations from metadata table `xxx`.`schema_version`
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.findAppliedMigrations(MetaDataTableImpl.java:248)
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.allAppliedMigrations(MetaDataTableImpl.java:182)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:97)
	at org.flywaydb.core.internal.command.DbValidate$2.doInTransaction(DbValidate.java:136)
	at org.flywaydb.core.internal.command.DbValidate$2.doInTransaction(DbValidate.java:131)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:131)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:1102)
	at org.flywaydb.core.Flyway.access$300(Flyway.java:62)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1012)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1637)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
	... 61 more
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'version_rank' in 'field list'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:404)
	at com.mysql.jdbc.Util.getInstance(Util.java:387)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:939)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3878)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3814)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2478)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2625)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2547)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2505)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1370)
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.query(JdbcTemplate.java:317)
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.findAppliedMigrations(MetaDataTableImpl.java:225)
	... 76 more
```

**Comment by axelfontaine** [comment]
Could you please include the full log of the Flyway run?

**Comment by t0kieu** [comment]
I found problem. Problem was in one submodule, that one submodule used the wrong version of flyway. Thank you for your willingness.

**Comment by pedroafonsoms** [comment]
t0kieu what is solution that you found ? Could you post in here, pls ?

**Comment by t0kieu** [comment]
@pedroafonsoms I did reconfiguration of project structure -> use one version for all submodules.

**Comment by Rawiank** [comment]
I have the same problem. Ide Eclipse ..

**Comment by starrychloe** [comment]
LOL! Now it gives an error that "Field 'version_rank' doesn't have a default value".

Maybe FlyWay should use Rails to manage its own schema?

Had to manually add a default value to the field by write it into the migration that already ran, comment the other lines, migrate, uncomment the lines, validate, copy the checksum into the schema_version table manually. Hopefully it will work in staging & production.

I know DB versioning is a hard problem and FlyWay is supposed to make it easier, but sometimes it feels like it's more work than going back to custom SQL scripts or manual deployment checklists.
