### ISSUE TITLE
How to configure timeouts for postgres

### ISSUE THREAD

**Issue by jcristovao** [flyway/flyway#1371]
###### What version of Flyway are you using?

3.2.1

###### What database are you using (type & version)?

Postgres 9.5

###### What operating system are you using?

Arch linux / Ubuntu (problem manifests itself on both)

###### What did you do?

Run a long migration sequence, that in total takes around 40 seconds.

###### What did you expect to see?

Migration succeeds

###### What did you see instead?

Migration fails with:

```
ERROR: Unable to rollback transaction
org.postgresql.util.PSQLException: This connection has been closed.
        at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:843)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.rollback(AbstractJdbc2Connection.java:860)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:81)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:282)
        at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:46)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:207)
        at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1059)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:122)
        at org.flywaydb.commandline.Main.main(Main.java:91)
org.postgresql.util.PSQLException: This connection has been closed.
```

I've tried to increase all the timeout values:

```
Database: jdbc:postgresql://localhost:5432/testdb?connectTimeout=0&cancelSignalTimeout=0&socketTimeout=0&tcpKeepAlive=true
```

(Zero means unlimited timeout) to no effect.

If I run flyway again, it finishes properly, so it's not a problem on the SQL.

Also, since this is being run as localhost, it is not likely that it is a firewall problem, I think

**Comment by axelfontaine** [comment]
Flyway does not influence timeouts. This is an issue with either your driver, db server or network infrastructure in between.

**Comment by jcristovao** [comment]
But how can I know if the timeout parameters are being passed / handled by the JDBC driver (used by flyway)?

**Comment by axelfontaine** [comment]
Flyway passes the connection string as is to the driver.
