### ISSUE TITLE
intermittent failure with Maven

### ISSUE THREAD

**Issue by subodhchhabra** [flyway/flyway#1436]
I am seeing an intermittent failure while invoking flyway with maven ( in have tried 2 different Dist. and seeing same failure across, tried with both JDK 7,8.   

###### What version of Flyway are you using?
4.0.3, 4.0.2, 3.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Maven Plugin

###### What database are you using (type & version)?
Oracle 11g R2

###### What operating system are you using?
Linux (red hat 6, ubuntu) 

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
MVN flyway:repair

###### What did you expect to see?
Build pass

###### What did you see instead?

[INFO] ------------------------------------------------------------------------
[DEBUG] Trace
org.apache.maven.lifecycle.LifecycleExecutionException: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:oracle:thin:<user>/<pwd>@//<host>:1521/<DB>) for user '<user>': IO Error: Connection reset
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:719)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeStandaloneGoal(DefaultLifecycleExecutor.java:569)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoal(DefaultLifecycleExecutor.java:539)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoalAndHandleFailures(DefaultLifecycleExecutor.java:387)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeTaskSegments(DefaultLifecycleExecutor.java:348)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.execute(DefaultLifecycleExecutor.java:180)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:328)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:138)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:362)
    at org.apache.maven.cli.compat.CompatibleMain.main(CompatibleMain.java:60)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.codehaus.classworlds.Launcher.launchEnhanced(Launcher.java:315)
    at org.codehaus.classworlds.Launcher.launch(Launcher.java:255)
    at org.codehaus.classworlds.Launcher.mainWithExitCode(Launcher.java:430)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:375)
Caused by: org.apache.maven.plugin.MojoExecutionException: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:oracle:thin:<user>/<pwd>@//<host>:1521/<DB>) for user '<user>': IO Error: Connection reset
    at org.flywaydb.maven.AbstractFlywayMojo.execute(AbstractFlywayMojo.java:541)
    at org.apache.maven.plugin.DefaultPluginManager.executeMojo(DefaultPluginManager.java:490)
    at org.apache.maven.lifecycle.DefaultLifecycleExecutor.executeGoals(DefaultLifecycleExecutor.java:694)
    ... 17 more
Caused by: java.net.SocketException: Connection reset
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
    at oracle.net.ns.DataPacket.send(DataPacket.java:210)
    at oracle.net.ns.NetOutputStream.flush(NetOutputStream.java:230)
    at oracle.net.ns.NetInputStream.getNextPacket(NetInputStream.java:312)
    at oracle.net.ns.NetInputStream.read(NetInputStream.java:260)
    at oracle.net.ns.NetInputStream.read(NetInputStream.java:185)
    at oracle.net.ns.NetInputStream.read(NetInputStream.java:102)
    at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:124)
    at oracle.jdbc.driver.T4CSocketInputStreamWrapper.read(T4CSocketInputStreamWrapper.java:80)
    at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1137)
    at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:290)
    at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
    at oracle.jdbc.driver.T4CTTIoauthenticate.doOSESSKEY(T4CTTIoauthenticate.java:404)
    at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:385)
    at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:546)
    at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:236)
    at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
    at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:521)
    at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:409)
    at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:370)
    at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
    at org.flywaydb.core.Flyway.execute(Flyway.java:1326)
    at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
    at org.flywaydb.maven.MigrateMojo.doExecute(MigrateMojo.java:30)
    at org.flywaydb.maven.AbstractFlywayMojo.execute(AbstractFlywayMojo.java:539)
    ... 19 more
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1 minute 3 seconds
[INFO] Finished at: Tue Sep 20 14:54:56 PDT 2016
[INFO] Final Memory: 14M/109M
[INFO] ------------------------------------------------------------------------
Build step 'Execute shell' marked build as failure
Finished: FAILURE

**Comment by axelfontaine** [comment]
This is either an issue in your JDBC driver or the network of your datacenter. Not much we can do on our end.

**Comment by subodhchhabra** [comment]
it was neither JDBC or Datacenter,  we had to override java security settings using  maven options
"-Djava.security.egd=file:///dev/urandom", much like  1077 (https://github.com/flyway/flyway/issues/1077), I am no java developer so couldn't sent you a PR.

**Comment by axelfontaine** [comment]
Thank you for investigating. This is unfortunately something we have no control over when running as a Maven plugin.
