### ISSUE TITLE
Flyway swallows the error and dies with unhelpful stack trace when trying to create a partitioned table on Oracle XE

### ISSUE THREAD

**Issue by frankschmitt** [flyway/flyway#1485]
###### What version of Flyway are you using?
4.0.3 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Command-line

###### What database are you using (type & version)?
Oracle Database 11g Express Edition Release 11.2.0.2.0 - 64bit Production

###### What operating system are you using?
Mac OS X 10.11.5 (client)
Ubuntu 14.04.4 LTS (Oracle server, inside Docker container)

###### What did you do?
Ran 

  flyway migrate

with this config:

flyway.driver=oracle.jdbc.OracleDriver
flyway.url=jdbc:oracle:thin:SYSTEM/oracle@//localhost:42161/XE
flyway.user=SYSTEM
flyway.password=oracle
flyway.schemas=FLYWAY_DEMO
flyway.table=SCHEMA_HISTORY

and this migration:

create table partition_demo (pk number) partition by list(pk) (partition p1 values (1), partition p2 values (2));

###### What did you expect to see?
ERROR at line 1:
ORA-00439: feature not enabled: Partitioning

That's the error message I get when running the script from the SQL/Plus command line.

###### What did you see instead?
$ ./flyway migrate
Flyway 4.0.3 by Boxfuse

Database: jdbc:oracle:thin:SYSTEM/oracle@//localhost:42161/XE (Oracle 11.2)
Successfully validated 1 migration (execution time 00:00.007s)
Creating Metadata table: "FLYWAY_DEMO"."SCHEMA_HISTORY"
Current version of schema "FLYWAY_DEMO": << Empty Schema >>
Migrating schema "FLYWAY_DEMO" to version 1 - Create table
ERROR: Unable to rollback transaction
java.sql.SQLRecoverableException: Getrennte Verbindung
	at oracle.jdbc.driver.PhysicalConnection.rollback(PhysicalConnection.java:3933)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:81)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:305)
	at org.flywaydb.core.internal.command.DbMigrate.access$1000(DbMigrate.java:47)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:230)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:173)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:173)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:959)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:139)
	at org.flywaydb.commandline.Main.main(Main.java:102)
ERROR: Unable to restore autocommit to original value for connection
java.sql.SQLRecoverableException: Getrennte Verbindung
	at oracle.jdbc.driver.PhysicalConnection.setAutoCommit(PhysicalConnection.java:3775)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:96)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:305)
	at org.flywaydb.core.internal.command.DbMigrate.access$1000(DbMigrate.java:47)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:230)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:173)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:173)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:959)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:139)
	at org.flywaydb.commandline.Main.main(Main.java:102)
ERROR: Migration of schema "FLYWAY_DEMO" to version 1 - Create table failed! Please restore backups and roll back database and code!
ERROR: Error restoring current schema to its original setting

**Comment by axelfontaine** [comment]
No idea why the connection to your DB got severed, this is however something you should check in your networking setup. When this is working properly Flyway does clearly return and display any error that is returned by the database.
