### ISSUE TITLE
> gradle flywayMigrate -i gives Java heap space error

### ISSUE THREAD

**Issue by mva1991** [flyway/flyway#1518]
###### What version of Flyway are you using?

3.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

gradle

###### What database are you using (type & version)?

5.7.15 Homebrew

###### What operating system are you using?
Mac OS X El Captain/Centos

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

gradle flywayMigrate -i

###### What did you expect to see?

BUILD SUCCESSFUL

###### What did you see instead?
`* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':flywayMigrate'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:61)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:45)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.OutOfMemoryError: Java heap space
        at org.flywaydb.core.internal.util.FileCopyUtils.copy(FileCopyUtils.java:117)
        at org.flywaydb.core.internal.util.FileCopyUtils.copyToByteArray(FileCopyUtils.java:68)
        at org.flywaydb.core.internal.util.scanner.classpath.ClassPathResource.loadAsBytes(ClassPathResource.java:100)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.extractMigrationInfo(SqlMigrationResolver.java:140)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:112)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:41)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:126)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:108)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:94)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:42)
        at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:96)
        at org.flywaydb.core.internal.command.DbValidate$2.doInTransaction(DbValidate.java:136)
        at org.flywaydb.core.internal.command.DbValidate$2.doInTransaction(DbValidate.java:131)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
        at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:131)
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:1014)
        at org.flywaydb.core.Flyway.access$300(Flyway.java:52)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:925)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:919)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1320)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:919)
        at org.flywaydb.core.Flyway$migrate$0.call(Unknown Source)
        at org.flywaydb.gradle.task.FlywayMigrateTask.run(FlywayMigrateTask.groovy:30)
        at org.flywaydb.gradle.task.FlywayMigrateTask$run.callCurrent(Unknown Source)
        at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.groovy:75)`

**Comment by axelfontaine** [comment]
3.1 is ancient. Can you test with the latest version to see if it also occurs?

**Comment by mva1991** [comment]
Hi, 
The issue also occurs with the latest version of flyway.
I am planning to implement migrations over mysql database and my sample gradle.build looks like this:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'mysql:mysql-connector-java:5.1.34'
    }
}


plugins {
    id "org.flywaydb.flyway" version "4.0.3"
}

flyway {
    url = 'jdbc:mysql://localhost:3306/flywayTest'
    user = 'root'
    password = 'Test!23'
    schemas = ['flywayTest']
    baselineVersion = 1
    baselineDescription = "Let's go!"
}
```

`flywayMigrations vinayabhishek$ gradle flywayMigrate
Parallel execution is an incubating feature.
:flywayMigrate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayMigrate'.
> Java heap space

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.6 secs`

**Comment by axelfontaine** [comment]
It seems to occur while loading your migration files from the classpath. How large are they?

**Comment by axelfontaine** [comment]
Any news?

**Comment by mva1991** [comment]
```
buildscript {
    dependencies {
        classpath 'mysql:mysql-connector-java:5.1.34'
    }
}


plugins {
    id "org.flywaydb.flyway" version "4.0.3"
}

flyway {
    url = 'jdbc:mysql://10.1.10.240:3306/testbase'
    user = 'user'
    password = 'root!23'
    schemas = ['testbase']
    baselineVersion = 1
    baselineDescription = "Baselining DB Schema"
}
```

The problem was with the user not being privileged  to access the database. 
Thanks for the follow up and sorry for the delayed response.
