### ISSUE TITLE
Schema version table not being found though it exists.

### ISSUE THREAD

**Issue by bearrito** [flyway/flyway#1524]
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java with Dropwizard Plugin

###### What database are you using (type & version)?
Postgres 9.5

###### What operating system are you using?
Ubuntu 14.04

###### What did you do?

I'm seeing the following error

```
ERROR [2017-02-10 23:59:06,411] io.dropwizard.flyway.cli.AbstractFlywayCommand: Error while running database command
! org.flywaydb.core.api.FlywayException: Found non-empty schema "bnr" without metadata table! Use baseline() or set baselineOnMigrate to true to initialize the metadata table.
! at org.flywaydb.core.Flyway$1.execute(Flyway.java:943) ~[label-service-2.0.1.jar:na]
! at org.flywaydb.core.Flyway$1.execute(Flyway.java:917) ~[label-service-2.0.1.jar:na]
! at org.flywaydb.core.Flyway.execute(Flyway.java:1373) ~[label-service-2.0.1.jar:na]
! at org.flywaydb.core.Flyway.migrate(Flyway.java:917) ~[label-service-2.0.1.jar:na]
! at io.dropwizard.flyway.cli.DbMigrateCommand.run(DbMigrateCommand.java:76) ~[label-service-2.0.1.jar:na]
! at io.dropwizard.flyway.cli.DbCommand.run(DbCommand.java:48) ~[label-service-2.0.1.jar:na]
! at io.dropwizard.flyway.cli.AbstractFlywayCommand.run(AbstractFlywayCommand.java:45) ~[label-service-2.0.1.jar:na]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77) [label-service-2.0.1.jar:na]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [label-service-2.0.1.jar:na]
! at io.dropwizard.Application.run(Application.java:80) [label-service-2.0.1.jar:na]
! at com.bossanova.core.labelservice.LabelApplication.main(LabelApplication.java:93) [label-service-2.0.1.jar:na]
Exception in thread "main" org.flywaydb.core.api.FlywayException: Found non-empty schema "bnr" without metadata table! Use baseline() or set baselineOnMigrate to true to initialize the metadata table.
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:943)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
	at io.dropwizard.flyway.cli.DbMigrateCommand.run(DbMigrateCommand.java:76)
	at io.dropwizard.flyway.cli.DbCommand.run(DbCommand.java:48)
	at io.dropwizard.flyway.cli.AbstractFlywayCommand.run(AbstractFlywayCommand.java:45)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:80)
	at com.bossanova.core.labelservice.LabelApplication.main(LabelApplication.java:93)
```

However my schema version table does exist

```
labelservice_db=# \dt 
            List of relations
 Schema |      Name      | Type  | Owner  
--------+----------------+-------+--------
 public | schema_version | table | Ops
(1 row)

```

Since I'm using the dropwizard plugin for this. Here is my configuration from that project

```
flyway:
  schemas:
    - bnr
  metaDataTableName: schema_version
```

**Comment by axelfontaine** [comment]
This definitely works in the core so it is either a configuration error on your side or a DropWizard plugin bug. Please check with the DropWizard plugin maintainers.
