### ISSUE TITLE
Inflater has been closed

### ISSUE THREAD

**Issue by cowwoc** [flyway/flyway#1602]
###### What version of Flyway are you using?
4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
Postgresql 42.0.0.jre7

###### What operating system are you using?
Windows 10 64-bit

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I ran `Flyway.migrate()`

###### What did you expect to see?
No exception

###### What did you see instead?
```
java.lang.NullPointerException: Inflater has been closed
	at java.util.zip.Inflater.ensureOpen(Inflater.java:389)
	at java.util.zip.Inflater.inflate(Inflater.java:257)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:152)
	at java.io.FilterInputStream.read(FilterInputStream.java:133)
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	at java.io.Reader.read(Reader.java:140)
	at org.flywaydb.core.internal.util.FileCopyUtils.copy(FileCopyUtils.java:84)
	at org.flywaydb.core.internal.util.FileCopyUtils.copyToString(FileCopyUtils.java:47)
	at org.flywaydb.core.internal.util.scanner.classpath.ClassPathResource.loadAsString(ClassPathResource.java:88)
	at org.flywaydb.core.internal.dbsupport.SqlScript.<init>(SqlScript.java:78)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:70)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrate(DbMigrate.java:352)
	at org.flywaydb.core.internal.command.DbMigrate.access$1100(DbMigrate.java:47)
	at org.flywaydb.core.internal.command.DbMigrate$4.doInTransaction(DbMigrate.java:308)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:305)
	at org.flywaydb.core.internal.command.DbMigrate.access$1000(DbMigrate.java:47)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:230)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:173)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:173)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:959)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
```

Googling this some more, https://bugs.openjdk.java.net/browse/JDK-8080363 seems to indicate that this exception is caused by user error (Flyway's code).

**Comment by axelfontaine** [comment]
Please include the exact steps to reproduce. The issue linked does not appear to be related. See https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/org/flywaydb/core/internal/util/FileCopyUtils.java#L84

**Comment by axelfontaine** [comment]
Any news?

**Comment by cowwoc** [comment]
I haven't run into this exception since the original report so let's close
it for now.
