### ISSUE TITLE
connection timeout error for Aurora

### ISSUE THREAD

**Issue by rdsuser** [flyway/flyway#1610]
###### What version of Flyway are you using?

4.0.3

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java SDK, JDBC driver is "org.mariadb.jdbc:mariadb-java-client:1.4.5"

###### What database are you using (type & version)?

Aurora DB 1.12

###### What operating system are you using?

AWS RDS

###### What did you do?
Running a sql from flyway ALTER TABLE `table_name` MODIFY COLUMN `column_name` CHAR(36) NOT NULL

###### What did you expect to see?
expected to see the changes to the column, 

###### What did you see instead?
The changes are done from db side but flyway is giving the error like below. When I run this same query from mysql workbench, it took 3+ minutes to complete this query and ran without any timeout. we set the parameter from db side, net_read_timout and net_write_timeout and max_allowed_packet and interactive_timeout.

SQL State  : 25S03
Error Code : -1
Message    : (conn:81751) Communications link failure with primary host host_name:3306. Could not read packet: Read timed out
Query is : ALTER TABLE `table_name` MODIFY COLUMN `column_name` CHAR(36) NOT NULL
on HostAddress{host='host_name', port=3306},master=true.  Driver has reconnect connection
Location   : /location/-FlywayTest.sql)
Line       : 1
Statement  : ALTER TABLE `table_name` MODIFY COLUMN `column_name` CHAR(36) NOT NULL

	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:117)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:71)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrate(DbMigrate.java:352)
	at org.flywaydb.core.internal.command.DbMigrate.access$1100(DbMigrate.java:47)
	at org.flywaydb.core.internal.command.DbMigrate$4.doInTransaction(DbMigrate.java:308)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:305)
	at org.flywaydb.core.internal.command.DbMigrate.access$1000(DbMigrate.java:47)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:230)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:173)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:173)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:959)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:917)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1373)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:917)
	at org.flywaydb.core.Flyway$migrate$2.call(Unknown Source)
	at com.tr.legal.infrastructure.dbchange.actions.MigrateAction.executeDbChangeTarget(MigrateAction.groovy:339)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:190)
	at com.tr.legal.infrastructure.dbchange.actions.MigrateAction.runInTenant(MigrateAction.groovy:298)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.tr.legal.infrastructure.dbchange.actions.MigrateAction.applyMigrateToTenant(MigrateAction.groovy:280)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:182)
	at com.tr.legal.infrastructure.dbchange.actions.MigrateAction.applyMigrateToTenants(MigrateAction.groovy:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)

**Comment by rdsuser** [comment]
And also, it's timing out after 30 seconds.

**Comment by axelfontaine** [comment]
This is an issue with either your network or your JDBC driver config. Not a Flyway issue.

**Comment by rdsuser** [comment]
Could you please let us know how to track JDBC driver config or network related issues? Any help is much appreciated.
