### ISSUE TITLE
Upgrading from Flyway 3.2 to 4.2 fails on multiple nodes

### ISSUE THREAD

**Issue by IncredibleLou** [flyway/flyway#1637]
###### What version of Flyway are you using?

4.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

Oracle 11.2

###### What operating system are you using?

Ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

We upgraded our Flyway dependency from 3.2 to 4.2. On the initial deployment, the server nodes tried to simultaneous upgrade the meta table to the new format. 
  
###### What did you expect to see?

A upgrade to the new format without fail. 

###### What did you see instead?

Node 1: 
```
2017-05-16 09:16:32,370 DEBUG org.flywaydb.core.internal.dbsupport.Table - Locking table "..."."schema_version"...
2017-05-16 09:16:32,372 DEBUG org.flywaydb.core.internal.dbsupport.Table - Lock acquired for table "..."."schema_version" 
2017-05-16 09:16:32,372 INFO  org.flywaydb.core.internal.metadatatable.MetaDataTableImpl - Upgrading metadata table "..."."schema_version" to the Flyway 4.0 format ...
2017-05-16 09:16:32,373 DEBUG org.flywaydb.core.internal.dbsupport.SqlScript - Found statement at line 17: DROP INDEX "..."."schema_version_vr_idx" 
2017-05-16 09:16:32,374 DEBUG org.flywaydb.core.internal.dbsupport.SqlScript - Found statement at line 18: DROP INDEX "..."."schema_version_ir_idx" 
2017-05-16 09:16:32,374 DEBUG org.flywaydb.core.internal.dbsupport.SqlScript - Found statement at line 19: ALTER TABLE "..."."schema_version" DROP COLUMN "version_rank" 
2017-05-16 09:16:32,374 DEBUG org.flywaydb.core.internal.dbsupport.SqlScript - Found statement at line 20: ALTER TABLE "..."."schema_version" DROP PRIMARY KEY DROP INDEX
2017-05-16 09:16:32,374 DEBUG org.flywaydb.core.internal.dbsupport.SqlScript - Found statement at line 21: ALTER TABLE "..."."schema_version" MODIFY "version" NULL
2017-05-16 09:16:32,374 DEBUG org.flywaydb.core.internal.dbsupport.SqlScript - Found statement at line 22: ALTER TABLE "..."."schema_version" ADD CONSTRAINT "schema_version_pk" PRIMARY KEY ("installed_rank")
2017-05-16 09:16:32,374 DEBUG org.flywaydb.core.internal.dbsupport.SqlScript - Found statement at line 23: UPDATE "..."."schema_version" SET "type"='BASELINE' WHERE "type"='INIT'
2017-05-16 09:16:32,375 DEBUG org.flywaydb.core.internal.dbsupport.SqlScript - Executing SQL: DROP INDEX "..."."schema_version_vr_idx" 
2017-05-16 09:16:32,490 DEBUG org.flywaydb.core.internal.dbsupport.JdbcTemplate - Update Count: 0
2017-05-16 09:16:32,490 DEBUG org.flywaydb.core.internal.dbsupport.SqlScript - Executing SQL: DROP INDEX "..."."schema_version_ir_idx" 

```
Node 2: 
```
2017-05-16 09:16:32,498
org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Script failed
-------------
SQL State  : 72000
Error Code : 1418
Message    : ORA-01418: specified index does not exist
Line       : 17
Statement  : DROP INDEX "..."."schema_version_vr_idx" 

    at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:145) ~[flyway-core-4.2.0.jar:na]
    at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl$1$1.call(MetaDataTableImpl.java:112) ~[flyway-core-4.2.0.jar:na]
    at org.flywaydb.core.internal.dbsupport.DbSupport$1.call(DbSupport.java:223) ~[flyway-core-4.2.0.jar:na]
    at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75) ~[flyway-core-4.2.0.jar:na]
    at org.flywaydb.core.internal.dbsupport.DbSupport.lock(DbSupport.java:219) ~[flyway-core-4.2.0.jar:na]
    at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:174) ~[flyway-core-4.2.0.jar:na]
    at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl$1.call(MetaDataTableImpl.java:99) ~[flyway-core-4.2.0.jar:na]
    at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl$1.call(MetaDataTableImpl.java:96) ~[flyway-core-4.2.0.jar:na]
    at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75) ~[flyway-core-4.2.0.jar:na]
    at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.upgradeIfNecessary(MetaDataTableImpl.java:96) ~[flyway-core-4.2.0.jar:na]
    at org.flywaydb.core.Flyway.execute(Flyway.java:1459) ~[flyway-core-4.2.0.jar:na]
    at org.flywaydb.core.Flyway.migrate(Flyway.java:971) ~[flyway-core-4.2.0.jar:na]
```

**Comment by axelfontaine** [comment]
Thanks. This is definitely an issue for database that don't support DDL transactions as the explicit commits release our locks.

Workaround for now: do the Flyway major upgrade on one node first.

**Comment by IncredibleLou** [comment]
This is what we thought, too.

**Comment by bitsal** [comment]
@axelfontaine any update here? I still have an error `ERROR: index "schema_version_vr_idx" does not exist` with PostgreSql and Flyway version `4.2.0`

**Comment by axelfontaine** [comment]
We will not be making further fixes in this direction. Stick to the workaround and you should be fine.
