### ISSUE TITLE
Flyway over SSH Tunnel does not work on macOS 10.12

### ISSUE THREAD

**Issue by apeschel** [flyway/flyway#1667]
###### What version of Flyway are you using?

Flyway 4.2.0 by Boxfuse

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?

MariaDB

mysql  Ver 15.1 Distrib 10.1.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

###### What operating system are you using?

macOS Sierra 10.12.5

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

Set up an SSH Tunnel to a remote database:

```
ssh -L 3306:sqldb1:3306 jumpbox
```

Settings in a config file:
```
flyway.url=jdbc:mariadb://localhost:3306/XXXXX?serverTimezone=UTC
flyway.user=XXXXX
flyway.password=XXXXX
flyway.locations=com.xxx.db.migration,filesystem:workbench/src/main/resources/db/migration
flyway.jarDirs=workbench/target/scala-2.11/
```

Trying to test the connection to the DB:
```
flyway -X info -configFile=local_XXX_flyway.conf
```

Failure:

```
Flyway 4.2.0 by Boxfuse

DEBUG: Java 1.8.0_131 (Oracle Corporation)
DEBUG: Mac OS X 10.12.5 x86_64

DEBUG: Loading config file: /usr/local/Cellar/flyway/4.2.0/libexec/conf/flyway.conf
DEBUG: Unable to load config file: /Users/apeschel/flyway.conf
DEBUG: Unable to load config file: /Users/apeschel/projects/XXX-workbench/backend/flyway.conf
DEBUG: Loading config file: /Users/apeschel/projects/XXX-workbench/backend/local_XXX_flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.configFile -> local_XXX_flyway.conf
DEBUG: flyway.jarDirs -> workbench/target/scala-2.11/
DEBUG: flyway.password -> ********************
DEBUG: flyway.url -> jdbc:mariadb://localhost:3306/XXX?serverTimezone=UTC&useSSL=false
DEBUG: flyway.user -> XXX
DEBUG: flyway.locations -> com.XXXanalytics.db.migration,filesystem:workbench/src/main/resources/db/migration
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/4.2.0/libexec/drivers/derby-10.12.1.1.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/4.2.0/libexec/drivers/derbyclient-10.12.1.1.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/4.2.0/libexec/drivers/greenplumdriver-5.1.1.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/4.2.0/libexec/drivers/h2-1.4.193.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/4.2.0/libexec/drivers/hsqldb-2.3.4.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/4.2.0/libexec/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/4.2.0/libexec/drivers/mariadb-java-client-1.4.5.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/4.2.0/libexec/drivers/postgresql-9.4.1208.jre6.jar
DEBUG: Adding location to classpath: /usr/local/Cellar/flyway/4.2.0/libexec/drivers/sqlite-jdbc-3.7.15-M1.jar
DEBUG: Adding location to classpath: workbench/target/scala-2.11/workbench-backend-assembly-v2.0.0.0-SNAPSHOT.jar
ERROR: Unexpected error
org.flywaydb.core.internal.dbsupport.FlywaySqlException:
Unable to obtain Jdbc connection from DataSource (jdbc:mariadb://localhost:3306/XXX?serverTimezone=UTC&useSSL=false) for user 'XXX': Could not connect to localhost:3306: unexpected end of stream, read 0 bytes from 4
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08
Error Code : -1
Message    : Could not connect to localhost:3306: unexpected end of stream, read 0 bytes from 4

        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:419)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:381)
        at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.info(Flyway.java:1097)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:152)
        at org.flywaydb.commandline.Main.main(Main.java:103)
Caused by: java.sql.SQLNonTransientConnectionException: Could not connect to localhost:3306: unexpected end of stream, read 0 bytes from 4
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:123)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
        at org.mariadb.jdbc.Driver.connect(Driver.java:110)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:416)
        ... 6 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect to localhost:3306: unexpected end of stream, read 0 bytes from 4
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:460)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
        at org.mariadb.jdbc.Driver.connect(Driver.java:105)
        ... 7 more
Caused by: java.io.EOFException: unexpected end of stream, read 0 bytes from 4
        at org.mariadb.jdbc.internal.packet.read.ReadPacketFetcher.getPacket(ReadPacketFetcher.java:100)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:477)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
        ... 11 more
```
Verified flyway was able to connect to a locally running database via a unix socket.

Verified flyway was able to connect to a locally running database via its external interface.

Verified with the mysql command-line tool that the connection to the database was fine and the credentials correct.

Coworker duplicated my environment on a macOS 10.11 machine and flyway there was able to connect to the database.

Coworker duplicated my environment on another macOS 10.12 machine, and flyway there had the same issue.

Bound the SSH tunnel to the external interface on the macOS 10.12 machine. Machines running macOS 10.11 were able to connect with flyway through the interface. flyway on the macOS 10.12 machine was not able to connect to the database.

Bound the SSH tunnel to the external interface on a macOS 10.11 machine. Machine running macOS 10.11 was able to connect with flyway through the interface. flyway on the macOS 10.12 machine was not able to connect to the database.

The problem appears when a connection over an SSH tunnel is used on macOS 10.12, and results in Flyway being unable to connect to a remote host.

###### What did you expect to see?

flyway should be able to establish a connection over an SSH tunnel to a database on macOS 10.12.

###### What did you see instead?

flyway is unable to establish a connection over an SSH tunnel to any host on macOS 10.12.

**Comment by apeschel** [comment]
I suspected the bug actually lies in the jdbc connector library, so I did some more research by stressing the MariaDB JDBC connector directly and found the following:

mariadb-java-client

* 1.1.8 : works
* 1.4.5: fails on macOS 10.12
* 1.5.9: works

flyway is pinned to mariadb-java-client 1.4.5 which has this bug. Upgrading the library within flyway should fix this problem.

Please upgrade the mariadb-java-client library to 1.5.9 ASAP.

**Comment by pikeas** [comment]
Seeing the same issue. Flyway 5.07, OS X 10.12.6, tried both the MySQL and MariaDB drivers. This is an AWS Aurora database mapped to a local port via ssh forwarding.

Flyway is unable to interact with the server beyond validating login (eg, a login error is thrown when username/password are incorrect). Server is responsive to other means of access.

**Comment by axelfontaine** [comment]
@pikeas Please open a new issue with steps how to reproduce if you are 100% sure this is a Flyway issue and not a driver issue.
