### ISSUE TITLE
Flyway Command-line not able to connect to Phoenix database

### ISSUE THREAD

**Issue by Aquileolus** [flyway/flyway#1697]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Command-line

###### What database are you using (type & version)?
Phoenix 4.10.0 HBase

###### What operating system are you using?

OSX

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

The command I ran is as followed:
sudo sh flyway -n -configFile="conf/flyway_test.conf" info

The conf file is as followed:
```
fyway.driver=org.apache.phoenix.jdbc.PhoenixDriver
flyway.url=jdbc:phoenix:22.200.111.111:8765;serialization=PROTOBUF
flyway.jarDirs=/Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin
flyway.locations=filesystem:/Users/alex/Documents/flyway-4.2.0/sql
```

I don't use username or password in the database, so -n is used.

###### What did you expect to see?

Got connected to the database and show the info

###### What did you see instead?

```
2030007662:flyway-4.2.0 alex$ sudo sh flyway -n -configFile="conf/flyway_test.conf" info
Password:
10:29:53.927 [main] INFO org.flywaydb.core.internal.util.VersionPrinter - Flyway 4.2.0 by Boxfuse
10:29:53.929 [main] INFO org.flywaydb.commandline.Main - 
10:29:53.930 [main] DEBUG org.flywaydb.commandline.Main - Java 1.8.0_74 (Oracle Corporation)
10:29:53.930 [main] DEBUG org.flywaydb.commandline.Main - Mac OS X 10.12.4 x86_64

10:29:53.931 [main] DEBUG org.flywaydb.commandline.Main - Loading config file: /Users/alex/Documents/flyway-4.2.0/conf/flyway.conf
10:29:53.935 [main] DEBUG org.flywaydb.commandline.Main - Unable to load config file: /var/root/flyway.conf
10:29:53.935 [main] DEBUG org.flywaydb.commandline.Main - Unable to load config file: /Users/alex/Documents/flyway-4.2.0/flyway.conf
10:29:53.935 [main] DEBUG org.flywaydb.commandline.Main - Loading config file: /Users/alex/Documents/flyway-4.2.0/conf/flyway_test.conf
10:29:53.936 [main] DEBUG org.flywaydb.commandline.Main - Using configuration:
10:29:53.936 [main] DEBUG org.flywaydb.commandline.Main - flyway.configFile -> conf/flyway_test.conf
10:29:53.936 [main] DEBUG org.flywaydb.commandline.Main - flyway.jarDirs -> /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin
10:29:53.936 [main] DEBUG org.flywaydb.commandline.Main - flyway.url -> jdbc:phoenix:22.200.111.111:8765;serialization=PROTOBUF
10:29:53.936 [main] DEBUG org.flywaydb.commandline.Main - flyway.driver -> org.apache.phoenix.jdbc.PhoenixDriver
10:29:53.936 [main] DEBUG org.flywaydb.commandline.Main - flyway.locations -> filesystem:/Users/alex/Documents/flyway-4.2.0/sql
10:29:53.936 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/drivers/derby-10.12.1.1.jar
10:29:53.937 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/drivers/derbyclient-10.12.1.1.jar
10:29:53.937 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/drivers/greenplumdriver-5.1.1.jar
10:29:53.937 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/drivers/h2-1.4.193.jar
10:29:53.937 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/drivers/hsqldb-2.3.4.jar
10:29:53.937 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/drivers/jtds-1.3.1.jar
10:29:53.938 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/drivers/mariadb-java-client-1.4.5.jar
10:29:53.938 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/drivers/phoenix-core-4.10.0-HBase-1.1.jar
10:29:53.938 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/drivers/postgresql-9.4.1208.jre6.jar
10:29:53.938 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/drivers/sqlite-jdbc-3.7.15-M1.jar
10:29:53.940 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-4.10.0-HBase-1.1-client.jar
10:29:53.941 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-4.10.0-HBase-1.1-hive.jar
10:29:53.941 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-4.10.0-HBase-1.1-pig.jar
10:29:53.941 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-4.10.0-HBase-1.1-queryserver.jar
10:29:53.941 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-4.10.0-HBase-1.1-server.jar
10:29:53.941 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-4.10.0-HBase-1.1-thin-client.jar
10:29:53.944 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-core-4.10.0-HBase-1.1-sources.jar
10:29:53.944 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-core-4.10.0-HBase-1.1-tests.jar
10:29:53.944 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-core-4.10.0-HBase-1.1.jar
10:29:53.944 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-flume-4.10.0-HBase-1.1-sources.jar
10:29:53.944 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-flume-4.10.0-HBase-1.1-tests.jar
10:29:53.944 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-flume-4.10.0-HBase-1.1.jar
10:29:53.944 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-hive-4.10.0-HBase-1.1-sources.jar
10:29:53.945 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-hive-4.10.0-HBase-1.1-tests.jar
10:29:53.945 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-hive-4.10.0-HBase-1.1.jar
10:29:53.945 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-kafka-4.10.0-HBase-1.1-minimal.jar
10:29:53.945 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-kafka-4.10.0-HBase-1.1-sources.jar
10:29:53.945 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-kafka-4.10.0-HBase-1.1-tests.jar
10:29:53.945 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-kafka-4.10.0-HBase-1.1.jar
10:29:53.945 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-pherf-4.10.0-HBase-1.1-minimal.jar
10:29:53.946 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-pherf-4.10.0-HBase-1.1-sources.jar
10:29:53.946 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-pherf-4.10.0-HBase-1.1-tests.jar
10:29:53.946 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-pherf-4.10.0-HBase-1.1.jar
10:29:53.946 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-pig-4.10.0-HBase-1.1-sources.jar
10:29:53.946 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-pig-4.10.0-HBase-1.1-tests.jar
10:29:53.946 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-pig-4.10.0-HBase-1.1.jar
10:29:53.946 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-queryserver-4.10.0-HBase-1.1-sources.jar
10:29:53.946 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-queryserver-4.10.0-HBase-1.1-tests.jar
10:29:53.946 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-queryserver-4.10.0-HBase-1.1.jar
10:29:53.946 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-queryserver-client-4.10.0-HBase-1.1-sources.jar
10:29:53.947 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-queryserver-client-4.10.0-HBase-1.1-tests.jar
10:29:53.947 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-queryserver-client-4.10.0-HBase-1.1.jar
10:29:53.947 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-spark-4.10.0-HBase-1.1-sources.jar
10:29:53.947 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-spark-4.10.0-HBase-1.1-tests.jar
10:29:53.947 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-spark-4.10.0-HBase-1.1.jar
10:29:53.947 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-tracing-webapp-4.10.0-HBase-1.1-runnable.jar
10:29:53.947 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-tracing-webapp-4.10.0-HBase-1.1-sources.jar
10:29:53.947 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-tracing-webapp-4.10.0-HBase-1.1-tests.jar
10:29:53.947 [main] DEBUG org.flywaydb.core.internal.util.ClassUtils - Adding location to classpath: /Users/alex/Documents/flyway-4.2.0/jars/apache-phoenix-4.10.0-HBase-1.1-bin/phoenix-tracing-webapp-4.10.0-HBase-1.1.jar
10:29:54.560 [main] DEBUG org.apache.hadoop.security.authentication.util.KerberosName - Kerberos krb5 configuration not found, setting default realm to empty
10:29:54.564 [main] DEBUG org.apache.hadoop.util.PerformanceAdvisory - Falling back to shell based
10:29:54.698 [main] DEBUG org.apache.phoenix.jdbc.PhoenixEmbeddedDriver$ConnectionInfo - Principal and keytab not provided, not attempting Kerberos login
10:29:54.834 [main] INFO org.apache.phoenix.query.ConnectionQueryServicesImpl - An instance of ConnectionQueryServices was created: java.lang.Exception
	at org.apache.phoenix.query.ConnectionQueryServicesImpl$12.call(ConnectionQueryServicesImpl.java:2405)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl$12.call(ConnectionQueryServicesImpl.java:2382)
	at org.apache.phoenix.util.PhoenixContextExecutor.call(PhoenixContextExecutor.java:76)
	at org.apache.phoenix.query.ConnectionQueryServicesImpl.init(ConnectionQueryServicesImpl.java:2382)
	at org.apache.phoenix.jdbc.PhoenixDriver.getConnectionQueryServices(PhoenixDriver.java:255)
	at org.apache.phoenix.jdbc.PhoenixEmbeddedDriver.createConnection(PhoenixEmbeddedDriver.java:149)
	at org.apache.phoenix.jdbc.PhoenixDriver.connect(PhoenixDriver.java:221)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:416)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:381)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
	at org.flywaydb.core.Flyway.info(Flyway.java:1097)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:152)
	at org.flywaydb.commandline.Main.main(Main.java:103)

10:29:57.357 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:zookeeper.version=3.4.6-1569965, built on 02/20/2014 09:09 GMT
10:29:57.357 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:host.name=120.255.117.110
10:29:57.357 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:java.version=1.8.0_74
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:java.vendor=Oracle Corporation
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:java.home=/Users/alex/Documents/flyway-4.2.0/jre
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:java.class.path=./lib/flyway-commandline-4.2.0.jar:./lib/flyway-core-4.2.0.jar:./lib/logback-classic-1.2.3.jar:./lib/logback-core-1.2.3.jar:./lib/slf4j-api-1.7.25.jar:./drivers/derby-10.12.1.1.jar:./drivers/derbyclient-10.12.1.1.jar:./drivers/greenplumdriver-5.1.1.jar:./drivers/h2-1.4.193.jar:./drivers/hsqldb-2.3.4.jar:./drivers/jtds-1.3.1.jar:./drivers/mariadb-java-client-1.4.5.jar:./drivers/phoenix-core-4.10.0-HBase-1.1.jar:./drivers/postgresql-9.4.1208.jre6.jar:./drivers/sqlite-jdbc-3.7.15-M1.jar
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:java.library.path=/Users/alex/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:java.io.tmpdir=/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:java.compiler=<NA>
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:os.name=Mac OS X
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:os.arch=x86_64
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:os.version=10.12.4
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:user.name=root
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:user.home=/var/root
10:29:57.360 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Client environment:user.dir=/Users/alex/Documents/flyway-4.2.0
10:29:57.361 [main] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ZooKeeper - Initiating client connection, connectString=22.200.111.111:8765 sessionTimeout=90000 watcher=hconnection-0x34f7cfd90x0, quorum=22.200.111.111:8765, baseZNode=/hbase
10:29:57.365 [main] DEBUG org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - zookeeper.disableAutoWatchReset is false
10:29:57.391 [main-SendThread(22.200.111.111:8765)] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Opening socket connection to server 22.200.111.111/22.200.111.111:8765. Will not attempt to authenticate using SASL (unknown error)
10:29:57.445 [main-SendThread(22.200.111.111:8765)] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Socket connection established to 22.200.111.111/22.200.111.111:8765, initiating session
10:29:57.446 [main-SendThread(22.200.111.111:8765)] DEBUG org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Session establishment request sent on 22.200.111.111/22.200.111.111:8765
10:29:57.481 [main-SendThread(22.200.111.111:8765)] WARN org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Session 0x0 for server 22.200.111.111/22.200.111.111:8765, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Packet len1213486160 is out of range!
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxnSocket.readLength(ClientCnxnSocket.java:112)
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:79)
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
10:29:58.617 [main-SendThread(22.200.111.111:8765)] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Opening socket connection to server 22.200.111.111/22.200.111.111:8765. Will not attempt to authenticate using SASL (unknown error)
10:29:58.645 [main-SendThread(22.200.111.111:8765)] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Socket connection established to 22.200.111.111/22.200.111.111:8765, initiating session
10:29:58.645 [main-SendThread(22.200.111.111:8765)] DEBUG org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Session establishment request sent on 22.200.111.111/22.200.111.111:8765
10:29:58.675 [main-SendThread(22.200.111.111:8765)] WARN org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Session 0x0 for server 22.200.111.111/22.200.111.111:8765, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Packet len1213486160 is out of range!
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxnSocket.readLength(ClientCnxnSocket.java:112)
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:79)
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
10:30:00.505 [main-SendThread(22.200.111.111:8765)] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Opening socket connection to server 22.200.111.111/22.200.111.111:8765. Will not attempt to authenticate using SASL (unknown error)
10:30:00.533 [main-SendThread(22.200.111.111:8765)] INFO org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Socket connection established to 22.200.111.111/22.200.111.111:8765, initiating session
10:30:00.533 [main-SendThread(22.200.111.111:8765)] DEBUG org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Session establishment request sent on 22.200.111.111/22.200.111.111:8765
10:30:00.562 [main-SendThread(22.200.111.111:8765)] WARN org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn - Session 0x0 for server 22.200.111.111/22.200.111.111:8765, unexpected error, closing socket connection and attempting reconnect
java.io.IOException: Packet len1213486160 is out of range!
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxnSocket.readLength(ClientCnxnSocket.java:112)
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxnSocketNIO.doIO(ClientCnxnSocketNIO.java:79)
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:366)
	at org.apache.phoenix.shaded.org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1081)
^C
```

And it kept retry and kept getting 'Packet len1213486160 is out of range!' until use control+c to force stop

**Comment by axelfontaine** [comment]
This looks like an issue in either your JDBC driver, your DB installation or your network. Not a Flyway issue.
