### ISSUE TITLE
Unable to clean schema due to dependent assemblies

### ISSUE THREAD

**Issue by rogatec** [flyway/flyway#1715]
###### What version of Flyway are you using?

```
$ ./flyway.cmd -v
Flyway 4.2.0 by Boxfuse
```

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

> flyway-commandline-4.2.0-windows-x64

###### What database are you using (type & version)?

> Microsoft SQL Server Developer Edition (64-bit)
> 13.0.4202 SP1
> Short: SQL 2016 Developer Edition

###### What operating system are you using?

> Windows 10 Pro 64bit OS Build: 15063.483

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

> step by step from https://flywaydb.org/documentation/existing
- Created complete DDL from database via SSMS 2017
- file placed into `sql` folder as `V1__Base_V214.sql`
- executed flyway

**OUTPUT**
```
$ ./flyway.cmd clean -X
Flyway 4.2.0 by Boxfuse

DEBUG: Java 1.8.0_74 (Oracle Corporation)
DEBUG: Windows 10 10.0 amd64

DEBUG: Loading config file: C:\flyway\flyway-4.2.0\conf\flyway.conf
DEBUG: Unable to load config file: C:\Users\***\flyway.conf
DEBUG: Unable to load config file: C:\flyway\flyway-4.2.0\flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> C:\flyway\flyway-4.2.0\jars
DEBUG: flyway.url -> jdbc:sqlserver://\\SQLTEC;databaseName=testdb;integratedSecurity=true;
DEBUG: flyway.locations -> filesystem:C:\flyway\flyway-4.2.0\sql
DEBUG: Adding location to classpath: C:\flyway\flyway-4.2.0\drivers\derby-10.12.1.1.jar
DEBUG: Adding location to classpath: C:\flyway\flyway-4.2.0\drivers\derbyclient-10.12.1.1.jar
DEBUG: Adding location to classpath: C:\flyway\flyway-4.2.0\drivers\greenplumdriver-5.1.1.jar
DEBUG: Adding location to classpath: C:\flyway\flyway-4.2.0\drivers\h2-1.4.193.jar
DEBUG: Adding location to classpath: C:\flyway\flyway-4.2.0\drivers\hsqldb-2.3.4.jar
DEBUG: Adding location to classpath: C:\flyway\flyway-4.2.0\drivers\jtds-1.3.1.jar
DEBUG: Adding location to classpath: C:\flyway\flyway-4.2.0\drivers\mariadb-java-client-1.4.5.jar
DEBUG: Adding location to classpath: C:\flyway\flyway-4.2.0\drivers\mssql-jdbc-6.2.1.jre8.jar
DEBUG: Adding location to classpath: C:\flyway\flyway-4.2.0\drivers\postgresql-9.4.1208.jre6.jar
DEBUG: Adding location to classpath: C:\flyway\flyway-4.2.0\drivers\sqlite-jdbc-3.7.15-M1.jar
Database: jdbc:sqlserver://null\sqltec:53751;jaasConfigurationName=SQLJDBCDriver;serverPreparedStatementDiscardThreshold=10;enablePrepareOnFirstPreparedStatementCall=false;fips=false;socketTimeout=0;authentication=NotSpecified;authenticationScheme=nativeAuthentication;xopenStates=false;sendTimeAsDatetime=true;trustStoreType=JKS;trustServerCertificate=false;TransparentNetworkIPResolution=true;serverNameAsACE=false;sendStringParametersAsUnicode=true;selectMethod=direct;responseBuffering=adaptive;queryTimeout=-1;packetSize=8000;multiSubnetFailover=false;loginTimeout=15;lockTimeout=-1;lastUpdateCount=true;encrypt=false;disableStatementPooling=true;databaseName=testdb;columnEncryptionSetting=Disabled;applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 13.0)
DEBUG: DDL Transactions Supported: true
DEBUG: Schema: dbo
DEBUG: Spring Jdbc available: false
DEBUG: Scanning for SQL callbacks ...
DEBUG: Scanning for filesystem resources at 'C:/flyway/flyway-4.2.0/sql' (Prefix: '', Suffix: '.sql')
DEBUG: Scanning for resources in path: C:\flyway\flyway-4.2.0\sql (C:/flyway/flyway-4.2.0/sql)
DEBUG: Found filesystem resource: C:\flyway\flyway-4.2.0\sql\V1__Base_V214.sql
DEBUG: Cleaning schema [dbo] ...
DEBUG: Rolling back transaction...
DEBUG: Transaction rolled back
SQLServer does not support setting the schema for the current session. Default schema NOT changed to dbo
ERROR: Unexpected error
org.flywaydb.core.internal.dbsupport.FlywaySqlException:
Unable to clean schema [dbo]
----------------------------
SQL State  : S0001
Error Code : 6589
Message    : Fehler bei DROP ASSEMBLY, weil die SoAssBlycolin.XmlSerializers-Assembly auf die angegebenen Assemblys verweist.

        at org.flywaydb.core.internal.dbsupport.Schema.clean(Schema.java:150)
        at org.flywaydb.core.internal.command.DbClean$4.call(DbClean.java:184)
        at org.flywaydb.core.internal.command.DbClean$4.call(DbClean.java:181)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
        at org.flywaydb.core.internal.command.DbClean.cleanSchema(DbClean.java:181)
        at org.flywaydb.core.internal.command.DbClean.clean(DbClean.java:130)
        at org.flywaydb.core.Flyway$3.execute(Flyway.java:1082)
        at org.flywaydb.core.Flyway$3.execute(Flyway.java:1078)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1464)
        at org.flywaydb.core.Flyway.clean(Flyway.java:1078)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:144)
        at org.flywaydb.commandline.Main.main(Main.java:103)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Fehler bei DROP ASSEMBLY, weil die SoAssBlycolin.XmlSerializers-Assembly auf die angegebenen Assemblys verweist.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:258)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1535)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:467)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:409)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7151)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2478)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:219)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:199)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:393)
        at org.flywaydb.core.internal.dbsupport.JdbcTemplate.execute(JdbcTemplate.java:248)
        at org.flywaydb.core.internal.dbsupport.sqlserver.SQLServerSchema.doClean(SQLServerSchema.java:212)
        at org.flywaydb.core.internal.dbsupport.Schema.clean(Schema.java:148)
        ... 11 more
```
###### What did you expect to see?

The database should be empty.

###### What did you see instead?

The problem is the dependency of the assemblies, as the exception is already telling me.
Therefore flyway can't remove the database.

I think that the implementation is quite extensive, but I've found a [blog post](http://www.andrewburrow.net/drop-sql-clr-assembly-dependencies/) how it's done via SQL.

**Comment by axelfontaine** [comment]
Thanks for the report. Could you supply the smallest possible SQL file that reproduces this?

**Comment by axelfontaine** [comment]
Any news?

**Comment by rogatec** [comment]
Sorry for the late reply, unfortunately I can't give you a sql file. The evaluation was in July and I needed to move forward and so there are no files anymore.

**Comment by DoodleBobBuffPants** [comment]
This may be fixed now, closing until further activity
