### ISSUE TITLE
Could not find a valid Docker environment

### ISSUE THREAD

**Issue by dhoer** [flyway/flyway#1747]
Travis build is failing because docker service is enabled making the build run docker in docker.  Removing docker service will fix this.

Exception:
```
Tests run: 13, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 6.168 sec <<< FAILURE! - in org.flywaydb.core.internal.util.scanner.classpath.ClassPathScannerSmallTest
scanForClassesSubPackage(org.flywaydb.core.internal.util.scanner.classpath.ClassPathScannerSmallTest)  Time elapsed: 6.122 sec  <<< ERROR!
java.lang.ExceptionInInitializerError
	at org.flywaydb.core.internal.util.scanner.classpath.ClassPathScannerSmallTest.scanForClassesSubPackage(ClassPathScannerSmallTest.java:149)
Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.flywaydb.core.internal.util.scanner.classpath.ClassPathScannerSmallTest.scanForClassesSubPackage(ClassPathScannerSmallTest.java:149)


Results :

Tests in error: 
  ClassPathScannerSmallTest.scanForClassesSubPackage:149 Â» ExceptionInInitializer
```

**Comment by dhoer** [comment]
Note that PR #1746 fixes this issue.

**Comment by axelfontaine** [comment]
Related to #1579
