### ISSUE TITLE
Syntax error on multi line delimiter command MySQL (PROCEDURE, EVENT)

### ISSUE THREAD

**Issue by iamareebjamal** [flyway/flyway#1768]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Spring Boot Plugin

###### What database are you using (type & version)?
MySQL 5.7.19

###### What operating system are you using?
Ubuntu 17.04

###### What did you do?
I wanted to create a procedure and event, so tested them on MySQL console and they worked. When I created migration SQL files for those, I started getting Syntax Error exceptions, and then tries to keep those two in different files but still no luck.

Procedure SQL
```
DELIMITER $
DROP PROCEDURE IF EXISTS delete_config;
create PROCEDURE delete_config(extra INT)
  begin
    SET @page_from = extra;
    PREPARE stmt FROM "DELETE FROM configuration ORDER BY id ASC limit ?;";
    EXECUTE stmt USING @page_from;
    DEALLOCATE PREPARE stmt;
  end $
DELIMITER ;
```

Event SQL
```
DELIMITER $
DROP EVENT IF EXISTS CleanConfig;
CREATE EVENT CleanConfig
  ON SCHEDULE EVERY 1 DAY
  STARTS CURRENT_TIMESTAMP
DO
  BEGIN
    SELECT COUNT(*) INTO @cnt FROM configuration;
    SET @max_config = 50;
    SET @extra = @cnt - @max_config;
    IF @extra > 0 THEN
      CALL delete_config(@extra);
    END IF;
  END $
DELIMITER ;
```

###### What did you expect to see?
Migrations should have been successfully applied

###### What did you see instead?
Procedure Error
```
2017-09-12 20:06:08.923  WARN 17842 --- [  restartedMain] o.f.c.internal.dbsupport.JdbcTemplate    : DB: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create PROCEDURE delete_config(extra INT)
  begin
    SET @page_from = extra;
  ' at line 2 (SQL State: 42000 - Error Code: 1064)
2017-09-12 20:06:08.925 ERROR 17842 --- [  restartedMain] o.f.core.internal.command.DbMigrate      : Migration of schema `zhcet` to version 1.2.4 - create config cleanup procedure failed! Please restore backups and roll back database and code!
2017-09-12 20:06:09.382  WARN 17842 --- [  restartedMain] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
Migration V1.2.4__create_config_cleanup_procedure.sql failed
------------------------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create PROCEDURE delete_config(extra INT)
  begin
    SET @page_from = extra;
  ' at line 2
Location   : db/migration/V1.2.4__create_config_cleanup_procedure.sql (/home/iamareebjamal/IdeaProjects/zhcet-web/build/resources/main/db/migration/V1.2.4__create_config_cleanup_procedure.sql)
Line       : 2
Statement  : DROP PROCEDURE IF EXISTS delete_config;
create PROCEDURE delete_config(extra INT)
  begin
    SET @page_from = extra;
    PREPARE stmt FROM "DELETE FROM configuration ORDER BY id ASC limit ?;";
    EXECUTE stmt USING @page_from;
    DEALLOCATE PREPARE stmt;
  end 

2017-09-12 20:06:09.386  INFO 17842 --- [  restartedMain] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2017-09-12 20:06:09.410  INFO 17842 --- [  restartedMain] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-09-12 20:06:09.419 ERROR 17842 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
Migration V1.2.4__create_config_cleanup_procedure.sql failed
------------------------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create PROCEDURE delete_config(extra INT)
  begin
    SET @page_from = extra;
  ' at line 2
Location   : db/migration/V1.2.4__create_config_cleanup_procedure.sql (/home/iamareebjamal/IdeaProjects/zhcet-web/build/resources/main/db/migration/V1.2.4__create_config_cleanup_procedure.sql)
Line       : 2
Statement  : DROP PROCEDURE IF EXISTS delete_config;
create PROCEDURE delete_config(extra INT)
  begin
    SET @page_from = extra;
    PREPARE stmt FROM "DELETE FROM configuration ORDER BY id ASC limit ?;";
    EXECUTE stmt USING @page_from;
    DEALLOCATE PREPARE stmt;
  end 

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1078) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at in.ac.amu.zhcet.CoreApplication.main(CoreApplication.java:28) [main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.4.RELEASE.jar:1.5.4.RELEASE]
Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
Migration V1.2.4__create_config_cleanup_procedure.sql failed
------------------------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create PROCEDURE delete_config(extra INT)
  begin
    SET @page_from = extra;
  ' at line 2
Location   : db/migration/V1.2.4__create_config_cleanup_procedure.sql (/home/iamareebjamal/IdeaProjects/zhcet-web/build/resources/main/db/migration/V1.2.4__create_config_cleanup_procedure.sql)
Line       : 2
Statement  : DROP PROCEDURE IF EXISTS delete_config;
create PROCEDURE delete_config(extra INT)
  begin
    SET @page_from = extra;
    PREPARE stmt FROM "DELETE FROM configuration ORDER BY id ASC limit ?;";
    EXECUTE stmt USING @page_from;
    DEALLOCATE PREPARE stmt;
  end 

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:345) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$900(DbMigrate.java:53) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:276) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:53) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:210) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:146) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.dbsupport.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.dbsupport.mysql.MySQLDbSupport.lock(MySQLDbSupport.java:129) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:174) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:146) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1010) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:971) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:1464) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:971) ~[flyway-core-4.2.0.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 23 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'create PROCEDURE delete_config(extra INT)
  begin
    SET @page_from = extra;
  ' at line 2
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_144]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc-8.5.15.jar:na]
	at com.sun.proxy.$Proxy87.execute(Unknown Source) ~[na:na]
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.executeStatement(JdbcTemplate.java:267) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:142) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:76) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:343) ~[flyway-core-4.2.0.jar:na]
	... 41 common frames omitted
```

Event Error
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
Migration V1.2.4__create_config_cleanup_procedure.sql failed
------------------------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE EVENT CleanConfig
  ON SCHEDULE EVERY 1 DAY
  STARTS CURRENT_TIMESTAMP
DO' at line 2
Location   : db/migration/V1.2.4__create_config_cleanup_procedure.sql (/home/iamareebjamal/IdeaProjects/zhcet-web/build/resources/main/db/migration/V1.2.4__create_config_cleanup_procedure.sql)
Line       : 2
Statement  : DROP EVENT IF EXISTS CleanConfig;
CREATE EVENT CleanConfig
  ON SCHEDULE EVERY 1 DAY
  STARTS CURRENT_TIMESTAMP
DO
  BEGIN
    SELECT COUNT(*) INTO @cnt FROM configuration;
    SET @max_config = 50;
    SET @extra = @cnt - @max_config;
    IF @extra > 0 THEN
      CALL delete_config(@extra);
    END IF;
  END 

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1078) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at in.ac.amu.zhcet.CoreApplication.main(CoreApplication.java:28) [main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.4.RELEASE.jar:1.5.4.RELEASE]
Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
Migration V1.2.4__create_config_cleanup_procedure.sql failed
------------------------------------------------------------
SQL State  : 42000
Error Code : 1064
Message    : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE EVENT CleanConfig
  ON SCHEDULE EVERY 1 DAY
  STARTS CURRENT_TIMESTAMP
DO' at line 2
Location   : db/migration/V1.2.4__create_config_cleanup_procedure.sql (/home/iamareebjamal/IdeaProjects/zhcet-web/build/resources/main/db/migration/V1.2.4__create_config_cleanup_procedure.sql)
Line       : 2
Statement  : DROP EVENT IF EXISTS CleanConfig;
CREATE EVENT CleanConfig
  ON SCHEDULE EVERY 1 DAY
  STARTS CURRENT_TIMESTAMP
DO
  BEGIN
    SELECT COUNT(*) INTO @cnt FROM configuration;
    SET @max_config = 50;
    SET @extra = @cnt - @max_config;
    IF @extra > 0 THEN
      CALL delete_config(@extra);
    END IF;
  END 

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:345) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$900(DbMigrate.java:53) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:276) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:53) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:210) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:146) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.dbsupport.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.dbsupport.mysql.MySQLDbSupport.lock(MySQLDbSupport.java:129) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:174) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:146) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1010) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:971) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:1464) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:971) ~[flyway-core-4.2.0.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-1.5.4.RELEASE.jar:1.5.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.9.RELEASE.jar:4.3.9.RELEASE]
	... 23 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'CREATE EVENT CleanConfig
  ON SCHEDULE EVERY 1 DAY
  STARTS CURRENT_TIMESTAMP
DO' at line 2
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_144]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.Util.getInstance(Util.java:408) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2486) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2444) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.StatementImpl.executeInternal(StatementImpl.java:845) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at com.mysql.jdbc.StatementImpl.execute(StatementImpl.java:745) ~[mysql-connector-java-5.1.42.jar:5.1.42]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114) ~[tomcat-jdbc-8.5.15.jar:na]
	at com.sun.proxy.$Proxy87.execute(Unknown Source) ~[na:na]
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.executeStatement(JdbcTemplate.java:267) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:142) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:76) ~[flyway-core-4.2.0.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:343) ~[flyway-core-4.2.0.jar:na]
	... 41 common frames omitted

```

**Comment by axelfontaine** [comment]
Your SQL scripts have a syntax error as they should use the new delimiter for the drop statements.
