### ISSUE TITLE
Issue with to_timestamp, containing miliseconds

### ISSUE THREAD

**Issue by lizardeye** [flyway/flyway#1787]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
SpringBoot (using flyway-core library)

###### What database are you using (type & version)?
Oracle 11G

###### What operating system are you using?
Linux, bug is not reproduced under Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

I'm running my app, using SpringBoot. 
Migration of one of the scripts fails, if the app is run on Linux env.

Script:

Insert into MY_TABLE (ID,DATE_CREATE,FUNCTION_ID,ROLE_ID) values ('8046',to_timestamp('16.08.17 18:08:18,983000000','DD.MM.RR HH24:MI:SSXFF'),'2535','3005')

Line with trimmed milliseconds is inserted ok both in Linux&Windows.

Insert into MY_TABLE(ID,DATE_CREATE,FUNCTION_ID,ROLE_ID) values ('8046',to_timestamp('16.08.17 18:08:18','DD.MM.RR HH24:MI:SS'),'2535','3005')

###### What did you see instead?

t org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:345) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$900(DbMigrate.java:53) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:276) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:53) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:210) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:146) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.dbsupport.DbSupport$1.call(DbSupport.java:223) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.dbsupport.DbSupport.lock(DbSupport.java:219) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:174) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:146) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1010) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:971) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:1464) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:971) ~[flyway-core-4.2.0.jar!/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_101]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_101]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1758) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1695) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.9.RELEASE.jar!/:4.3.9.RELEASE]
	... 136 common frames omitted
Caused by: java.sql.SQLException: ORA-01830: date format picture ends before converting entire input string

	at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:112) ~[ojdbc-14.jar!/:Oracle JDBC Driver version - "10.2.0.1.0"]
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:331) ~[ojdbc-14.jar!/:Oracle JDBC Driver version - "10.2.0.1.0"]
	at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:288) ~[ojdbc-14.jar!/:Oracle JDBC Driver version - "10.2.0.1.0"]
	at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:743) ~[ojdbc-14.jar!/:Oracle JDBC Driver version - "10.2.0.1.0"]
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:207) ~[ojdbc-14.jar!/:Oracle JDBC Driver version - "10.2.0.1.0"]
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:946) ~[ojdbc-14.jar!/:Oracle JDBC Driver version - "10.2.0.1.0"]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1160) ~[ojdbc-14.jar!/:Oracle JDBC Driver version - "10.2.0.1.0"]
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1679) ~[ojdbc-14.jar!/:Oracle JDBC Driver version - "10.2.0.1.0"]
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1645) ~[ojdbc-14.jar!/:Oracle JDBC Driver version - "10.2.0.1.0"]
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.executeStatement(JdbcTemplate.java:267) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:142) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:76) ~[flyway-core-4.2.0.jar!/:na]
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:343) ~[flyway-core-4.2.0.jar!/:na]
	... 159 common frames omitted

**Comment by rodrigoords** [comment]
i have the same issue, any work around ?

**Comment by axelfontaine** [comment]
Since Flyway's parser is absolutely identical across platforms, this is either an issue with your JDBC driver or your database.
