### ISSUE TITLE
Gradle plugin with SpringJdbcMigration: loader constraint violation

### ISSUE THREAD

**Issue by dorongold** [flyway/flyway#1788]
###### What version of Flyway are you using?
4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Gradle plugin

###### What database are you using (type & version)?
PostgreSQL 9.6.2

###### What operating system are you using?
Linux - Ubuntu

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)
I have a Java migration file that implements `SpringJdbcMigration`.
When running `gradle flywayMigrate` I get the following error:
```
Caused by: java.lang.LinkageError: loader constraint violation in interface itable initialization: when resolving method "db.migration.V1002__populate.migrate(Lorg/springframework/jdbc/core/JdbcTemplate;)V" the class loader (instance of java/net/URLClassLoader) of the current class, db/migration/V1002__populate, and the class loader (instance of org/gradle/internal/classloader/VisitableURLClassLoader) for interface org/flywaydb/core/api/migration/spring/SpringJdbcMigration have different Class objects for the type org/springframework/jdbc/core/JdbcTemplate used in the signature
        at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:59)
        at org.flywaydb.core.internal.util.scanner.classpath.ClassPathScanner.scanForClasses(ClassPathScanner.java:119)
        at org.flywaydb.core.internal.util.scanner.Scanner.scanForClasses(Scanner.java:75)
        at org.flywaydb.core.internal.resolver.spring.SpringJdbcMigrationResolver.resolveMigrationsForSingleLocation(SpringJdbcMigrationResolver.java:87)
        at org.flywaydb.core.internal.resolver.spring.SpringJdbcMigrationResolver.resolveMigrations(SpringJdbcMigrationResolver.java:78)
        at org.flywaydb.core.internal.resolver.spring.SpringJdbcMigrationResolver.resolveMigrations(SpringJdbcMigrationResolver.java:41)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:123)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:105)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:91)
        at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:44)
        at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:112)
        at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:171)
        at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:164)
        at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
        at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:164)
        at org.flywaydb.core.Flyway.doValidate(Flyway.java:1058)
        at org.flywaydb.core.Flyway.access$100(Flyway.java:72)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:975)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:971)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1464)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:971)
        at org.flywaydb.gradle.task.FlywayMigrateTask.run(FlywayMigrateTask.java:28)
        at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:319)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:142)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:135)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:122)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:762)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:729)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 28 more


```

I have found a workaround. It's described in a repo that was created solely for this purpose (not by me): https://github.com/andyrbell/flyway-spring-migration.
As mentioned in that repo, to solve this problem a dependency on `org.springframework:spring-jdbc:${springVersion}` has to be added to Gradle's`buildScript` block.

I suggest that Flyway Gradle plugin try to detect the presence of `spring-jdbc` in the project's compile classpath and automatically use it.

In any case, currently the requirement for explicit dependency on `spring-jdbc` should at least be documented.

**Comment by axelfontaine** [comment]
This change was made as part of #1539 . I guess we just can't win in all cases. Declaring the dependency as part of the buildscript is kinda logical though, as this is a dependency for a plugin and not for your artifact.

Note added to documentation in the Flyway 5.0 branch.
