### ISSUE TITLE
Cockroachdb: Unable to insert row for version '1' in metadata table "core"."schema_version"

### ISSUE THREAD

**Issue by rendaw** [flyway/flyway#1798]
###### What version of Flyway are you using?
0-SNAPSHOT (2017-10-17 ~12:52 UTC) commit `ac266f42a5d365c1ffb4df0030b3281bb76508b8`

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)
Java API

###### What database are you using (type & version)?
CockroachDB Docker image `cockroachdb/cockroach:v1.0.6`

###### What operating system are you using?
Linux

###### What did you do?
Running initial migration, `V1__auto.sql` - it looks like the migration passes but storing migration metadata fails.  I'm assuming this is an issue with Cockroach supported SQL limitations, but I apologize if this is user error.

###### What did you see instead?
```
21:47:33.792 [main] DEBUG o.f.core.internal.command.DbMigrate - Successfully completed migration of schema "core" to version 1 - auto
21:47:33.812 [main] DEBUG o.f.core.internal.dbsupport.Table - Locking table "core"."schema_version"...
21:47:33.813 [main] DEBUG o.f.c.i.d.c.CockroachDBTable - Unable to lock "core"."schema_version" as CockroachDB does not support locking. No concurrent migration supported.
21:47:33.813 [main] DEBUG o.f.core.internal.dbsupport.Table - Lock acquired for table "core"."schema_version"
21:47:33.837 [main] DEBUG o.f.c.i.u.jdbc.TransactionTemplate - Rolling back transaction...
21:47:34.083 [main] DEBUG o.f.c.i.u.jdbc.TransactionTemplate - Transaction rolled back
Exception in thread "main" org.flywaydb.core.internal.dbsupport.FlywaySqlException: 
Unable to insert row for version '1' in metadata table "core"."schema_version"
------------------------------------------------------------------------------
SQL State  : XX000
Error Code : 0
Message    : ERROR: syntax error at or near "show"
INSERT INTO "core"."schema_version" ("installed_rank","version","description","type","script","checksum","installed_by","execution_time","success") VALUES ($1, $2, $3, $4, $5, $6, (SELECT * FROM [SHOW SESSION_USER]), $7, $8)
                                                                                                                                                                                                    ^

	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.addAppliedMigration(MetaDataTableImpl.java:247)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:360)
	at org.flywaydb.core.internal.command.DbMigrate.access$900(DbMigrate.java:53)
	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:276)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:273)
	at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:53)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:210)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:146)
	at org.flywaydb.core.internal.dbsupport.DbSupport$1.call(DbSupport.java:212)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
	at org.flywaydb.core.internal.dbsupport.DbSupport.lock(DbSupport.java:208)
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.lock(MetaDataTableImpl.java:174)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:146)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1049)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1010)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1510)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1010)
...
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "show"
INSERT INTO "core"."schema_version" ("installed_rank","version","description","type","script","checksum","installed_by","execution_time","success") VALUES ($1, $2, $3, $4, $5, $6, (SELECT * FROM [SHOW SESSION_USER]), $7, $8)
                                                                                                                                                                                                    ^

	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.update(JdbcTemplate.java:315)
	at org.flywaydb.core.internal.metadatatable.MetaDataTableImpl.addAppliedMigration(MetaDataTableImpl.java:222)
	... 19 more
```

**Comment by rendaw** [comment]
And as always, thanks for the awesome library!  I unfortunately only know SQL basics myself, but I can dig in if this isn't quickly apparent.

**Comment by axelfontaine** [comment]
Only CockroachDB 1.1 and up are supported in the upcoming Flyway 5.0 release.
