### ISSUE TITLE
Support H2 MySQL compatibility mode

### ISSUE THREAD

**Issue by lukas-krecan-lt** [flyway/flyway#1810]
###### What version of Flyway are you using?

4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Java API

###### What database are you using (type & version)?

H2

###### What operating system are you using?

Mac OS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, and the command you ran)

See this failing test https://github.com/flyway/flyway/pull/1811/files

###### What did you expect to see?

Not failing

###### What did you see instead?

```java
 org.flywaydb.core.internal.dbsupport.FlywaySqlException: 
Unable to drop "PUBLIC"."big_name"
----------------------------------
SQL State  : 42S02
Error Code : 42102
Message    : Table "big_name" not found; SQL statement:
DROP TABLE "PUBLIC"."big_name" CASCADE [42102-193]


	at org.flywaydb.core.internal.dbsupport.SchemaObject.drop(SchemaObject.java:82)
	at org.flywaydb.core.internal.dbsupport.h2.H2Schema.doClean(H2Schema.java:69)
	at org.flywaydb.core.internal.dbsupport.Schema.clean(Schema.java:148)
	at org.flywaydb.core.internal.command.DbClean$4.call(DbClean.java:184)
	at org.flywaydb.core.internal.command.DbClean$4.call(DbClean.java:181)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
	at org.flywaydb.core.internal.command.DbClean.cleanSchema(DbClean.java:181)
	at org.flywaydb.core.internal.command.DbClean.clean(DbClean.java:130)
	at org.flywaydb.core.Flyway$3.execute(Flyway.java:1121)
	at org.flywaydb.core.Flyway$3.execute(Flyway.java:1117)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1510)
	at org.flywaydb.core.Flyway.clean(Flyway.java:1117)
	at org.flywaydb.core.internal.dbsupport.h2.H2MigrationMediumTest.mysqlModeWithUppercase(H2MigrationMediumTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.h2.jdbc.JdbcSQLException: Table "big_name" not found; SQL statement:
DROP TABLE "PUBLIC"."big_name" CASCADE [42102-193]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.command.ddl.DropTable.prepareDrop(DropTable.java:69)
	at org.h2.command.ddl.DropTable.update(DropTable.java:113)
	at org.h2.command.CommandContainer.update(CommandContainer.java:98)
	at org.h2.command.Command.executeUpdate(Command.java:258)
	at org.h2.jdbc.JdbcPreparedStatement.execute(JdbcPreparedStatement.java:201)
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.execute(JdbcTemplate.java:259)
	at org.flywaydb.core.internal.dbsupport.h2.H2Table.doDrop(H2Table.java:43)
	at org.flywaydb.core.internal.dbsupport.SchemaObject.drop(SchemaObject.java:80)
	... 26 more
```

**Comment by axelfontaine** [comment]
This is an H2 bug. Querying the H2 information schema (as Flyway does) should return tables in the correct case.

**Comment by lukas-krecan-lt** [comment]
The bug happens even with lower-case table names. I would have updated the test, but it's gone now.

**Comment by lukas-krecan-lt** [comment]
This test fails as well https://github.com/flyway/flyway/pull/1829

**Comment by axelfontaine** [comment]
Hmm upon second thought this is due to Flyway not explicitly supporting H2 modes and H2's MySQL mode using a different quotation style (backticks instead of double quotes).

I strongly recommend you to use the real MySQL instead as H2's compatibility mode most likely has a number of subtle differences which will no doubt bite you later.

**Comment by axelfontaine** [comment]
@lukas-krecan-lt Do you know if there is a way to query to current compatibility mode H2 is in? This would be an important prerequisite for fixing this.

**Comment by lukas-krecan-lt** [comment]
Sorry, I do not know

**Comment by juliahayward** [comment]
@axelfontaine Yes, there is (but it appears to be a property of the connection, not of the database itself): https://stackoverflow.com/questions/56584473/how-can-i-find-which-compatibility-mode-an-h2-database-is-in

**Comment by axelfontaine** [comment]
@juliahayward Good to know! Thanks!

**Comment by juliahayward** [comment]
Have tested with `com.h2database.h2` versions 1.4.193 through 199, and can confirm the test in #1811 passes at v1.4.199 but not older versions. Closing this as an H2 problem - Flyway 6.0.0 ships with the v1.4.199 H2 and should therefore be OK. If there are problems with v6.0, please open a new issue.
