### ISSUE TITLE
Field version_rank doesn't have a default value on Spring Boot 2.0 RC1

### ISSUE THREAD

**Issue by mfolivas** [flyway/flyway#1925]
###### What version of Flyway are you using?
2.0.0.RC1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin, SBT plugin, ANT tasks)

Gradle

###### What database are you using (type & version)?
MySQL

###### What operating system are you using?
Linux

###### What did you do?
Bump version to Spring boot 2.0 and added a new DML:
`ALTER TABLE vulcan.vpln_transactions modify acquirer bigint(20);`

with the name `V12__Increase_Acquirer_Column.sql`

Migrated my Spring Boot from version 1.5 to 2.0 using the following script:
```buildscript {
	ext {
		springBootVersion = '2.0.0.RC1'
	}
	repositories {
		mavenCentral()
		maven { url "https://repo.spring.io/snapshot" }
		maven { url "https://repo.spring.io/milestone" }
		jcenter()
	}
	dependencies {
		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}",
				  "se.transmode.gradle:gradle-docker:1.2")
	}
}

group = "sfw365"

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: "docker"


version = '1.4.1'

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
	mavenCentral()
	maven { url "https://repo.spring.io/snapshot" }
	maven { url "https://repo.spring.io/milestone" }
	jcenter()
}


ext {
	springCloudVersion = 'Finchley.M6'
}

dependencies {
	compile('org.springframework.boot:spring-boot-starter-actuator',
			'org.springframework.boot:spring-boot-starter-data-jpa',
			'org.flywaydb:flyway-core',
			'org.springframework.boot:spring-boot-starter-web',
			'mysql:mysql-connector-java',
			'javax.inject:javax.inject:1',
			'io.springfox:springfox-swagger2:2.6.1',
			'io.springfox:springfox-swagger-ui:2.6.1',
			'org.springframework.cloud:spring-cloud-starter-netflix-hystrix',
	        'commons-io:commons-io:2.6',
	        'org.springframework.retry:spring-retry')
	runtime('com.h2database:h2')
	testCompile('org.springframework.boot:spring-boot-starter-test',
				'org.springframework.cloud:spring-cloud-contract-wiremock')
}

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
	}
}

task buildDocker(type: Docker, dependsOn: build) {
	push = true
	applicationName = jar.baseName
	tagVersion = jar.version
	dockerfile = file('Dockerfile')
	doFirst {
		copy {
			from jar
			into stageDir
		}
	}
}
```

###### What did you expect to see?
Expected to see the migrated script on the schema version.

###### What did you see instead?
```SQL State  : HY000
Error Code : 1364
Message    : Field 'version_rank' doesn't have a default value

	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.doAddAppliedMigration(JdbcTableSchemaHistory.java:171) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.addAppliedMigration(SchemaHistory.java:146) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:378) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$400(DbMigrate.java:52) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$5.call(DbMigrate.java:297) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:294) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:259) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.access$300(DbMigrate.java:52) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:179) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:176) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:78) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:148) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:176) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:145) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1206) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1168) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:1650) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1168) ~[flyway-core-5.0.6.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.0.0.RC1.jar:2.0.0.RC1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769) ~[spring-beans-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706) ~[spring-beans-5.0.3.RELEASE.jar:5.0.3.RELEASE]
	... 18 common frames omitted
Caused by: java.sql.SQLException: Field 'version_rank' doesn't have a default value
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998) ~[mysql-connector-java-5.1.45.jar:5.1.45]
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-2.7.6.jar:na]
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-2.7.6.jar:na]
	at org.flywaydb.core.internal.util.jdbc.JdbcTemplate.update(JdbcTemplate.java:334) ~[flyway-core-5.0.6.jar:na]
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.doAddAppliedMigration(JdbcTableSchemaHistory.java:165) ~[flyway-core-5.0.6.jar:na]
	... 40 common frames omitted```

**Comment by axelfontaine** [comment]
Not a Flyway issue. See my comment on https://github.com/spring-projects/spring-boot/issues/12033 for why this is happening and how to resolve this.
