### ISSUE TITLE
flyway migration for test does not look application.properties.

### ISSUE THREAD

**Issue by SpaceNet** [flyway/flyway#1958]
###### Which version and edition of Flyway are you using?
5.0.6

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

    buildscript {
    	ext {
    		springBootVersion = '2.0.0.RELEASE'
    	}
    	repositories {
    		mavenCentral()
    		maven { url "https://repo.spring.io/snapshot" }
    		maven { url "https://repo.spring.io/milestone" }
    		maven { url 'http://jcenter.bintray.com' }
    		maven { url 'https://mvnrepository.com/artifact/com.opencsv/opencsv' }
    	}
    	dependencies {
    	    classpath("io.spring.gradle:dependency-management-plugin:1.0.4.RELEASE")
    		classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
    		classpath("mysql:mysql-connector-java:5.1.45")
    	}
    }
    
    plugins {
        id "org.flywaydb.flyway" version "5.0.6"
    }
    
    flyway {
    	url = "jdbc:mysql://localhost:3306/dev_db"
    	user = "sa"
    	password = ""
    }
    
    apply plugin: 'java'
    apply plugin: 'eclipse'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'org.springframework.boot'
    
    group = 'test'
    version = '0.0.1-SNAPSHOT'
    sourceCompatibility = 1.8
    
    repositories {
    	maven { url "https://repo.spring.io/snapshot" }
        maven { url "https://repo.spring.io/plugins-release" }
        maven { url "https://repo.spring.io/milestone" }
        maven { url "https://repository.jboss.org/nexus/content/repositories/releases" }
    	mavenCentral()
    }
    
    
    dependencies {
    	compile('org.springframework.boot:spring-boot-starter-aop')
    	compile('org.springframework.boot:spring-boot-starter-hateoas')
    	compile('org.springframework.boot:spring-boot-starter-thymeleaf')
    	compile('org.springframework.boot:spring-boot-starter-web')
    	compile('org.springframework.boot:spring-boot-starter-webflux')
    	compile('org.springframework.boot:spring-boot-starter-jdbc')
    	compile('org.springframework.data:spring-data-commons')
    	compile('org.springframework.boot:spring-boot-starter-data-jpa')
    
    	compile('org.flywaydb:flyway-core:5.0.7')
        compile('org.flywaydb.flyway-test-extensions:flyway-spring5-test:5.0.0')
        compile('com.h2database:h2')
    	compile('mysql:mysql-connector-java:5.1.45')
    
    	compile('org.mybatis.spring.boot:mybatis-spring-boot-starter:1.3.1')
        compile('org.slf4j:slf4j-api:1.7.+')
        compile('org.slf4j:log4j-over-slf4j:1.7.+')
        compile('org.slf4j:jcl-over-slf4j:1.7.+')
    
    	compile('net.sf.dozer:dozer:5.5.1')
    
    	compile('ch.qos.logback:logback-classic:1.2.3')
    
    	compile('com.opencsv:opencsv:4.1')
    
    	compileOnly("org.projectlombok:lombok:1.16.20")
    
    	runtime('org.springframework.boot:spring-boot-devtools')
    	runtime('com.h2database:h2')
        runtime('mysql:mysql-connector-java:5.1.45')
    
        compile ('com.fasterxml.jackson.core:jackson-databind')
        
    	testCompile('org.springframework.boot:spring-boot-starter-test')
    	testCompile('io.projectreactor:reactor-test')
        testCompile("org.junit.jupiter:junit-jupiter-api")
        testRuntime("org.junit.jupiter:junit-jupiter-engine")
    	testRuntime('mysql:mysql-connector-java:5.1.45')
    	testRuntime('com.h2database:h2')
        testCompile('org.hamcrest:hamcrest-all:1.3')
        testCompile('org.dbunit:dbunit:2.5.+')
    	testCompile('mysql:mysql-connector-java:5.1.45')
    	testCompile('com.h2database:h2')
    }
    

###### Which database are you using (type & version)?
    	testCompile('mysql:mysql-connector-java:5.1.45')
    	testCompile('com.h2database:h2')

###### Which operating system are you using?
    	MacOS 10.13.3

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I'm using flyway with mysql with spring boot 2.0.0

The flyway migration works for running the spring boot App, but does not work for junit5 test.

    18:05:48.686 [main] ERROR o.f.core.internal.command.DbMigrate - Migration of schema "PUBLIC" to version 1.3.3 - ALTERItem failed! Please restore backups and roll back database and code!
    18:05:48.689 [main] WARN  o.s.w.c.s.GenericWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
    Migration V1_3_3__ALTERItem.sql failed
    --------------------------------------
    SQL State  : 42000
    Error Code : 42000
    Message    : SQLステートメントに文法エラーがあります "ALTER TABLE ITEM MODIFY UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP "
    Syntax error in SQL statement "ALTER TABLE ITEM MODIFY UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP "; SQL statement:
    ALTER TABLE item MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP [42000-196]
    Location   : db/migration/V1_3_3__ALTERItem.sql (/Users/user/dev/test-app/bin/main/db/migration/V1_3_3__ALTERItem.sql)
    Line       : 3
    Statement  : ALTER TABLE item MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    
    18:05:48.689 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
    18:05:48.692 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
    18:05:48.696 [main] ERROR o.s.test.context.TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.web.ServletTestExecutionListener@3bf9ce3e] to prepare test instance [test.someTest@5f95f1e1]
    java.lang.IllegalStateException: Failed to load ApplicationContext
    	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
    	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:107)
    	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
    	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
    	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:242)
    	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:97)
    	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeTestInstancePostProcessors$3(ClassTestDescriptor.java:215)
    	at org.junit.jupiter.engine.descriptor.JupiterTestDescriptor.executeAndMaskThrowable(JupiterTestDescriptor.java:141)
    	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$invokeTestInstancePostProcessors$4(ClassTestDescriptor.java:215)
    	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
    	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
    	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
    	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
    	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
    	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeTestInstancePostProcessors(ClassTestDescriptor.java:214)
    	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.instantiateAndPostProcessTestInstance(ClassTestDescriptor.java:196)
    	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstanceProvider$0(ClassTestDescriptor.java:185)
    	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstanceProvider$1(ClassTestDescriptor.java:189)
    	at java.util.Optional.orElseGet(Optional.java:267)
    	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$testInstanceProvider$2(ClassTestDescriptor.java:188)
    	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:156)
    	at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.before(ClassTestDescriptor.java:65)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:110)
    	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$2(HierarchicalTestExecutor.java:120)
    	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
    	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
    	at java.util.Iterator.forEachRemaining(Iterator.java:116)
    	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
    	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
    	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
    	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
    	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
    	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.lambda$executeRecursively$3(HierarchicalTestExecutor.java:120)
    	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.executeRecursively(HierarchicalTestExecutor.java:108)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor$NodeExecutor.execute(HierarchicalTestExecutor.java:79)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:55)
    	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
    	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
    	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
    	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
    	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:86)
    	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
    	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
    Migration V1_3_3__ALTERItem.sql failed
    --------------------------------------
    SQL State  : 42000
    Error Code : 42000
    Message    : SQLステートメントに文法エラーがあります "ALTER TABLE ITEM MODIFY UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP "
    Syntax error in SQL statement "ALTER TABLE ITEM MODIFY UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP "; SQL statement:
    ALTER TABLE item MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP [42000-196]
    Location   : db/migration/V1_3_3__ALTERItem.sql (/Users/user/dev/test-app/bin/main/db/migration/V1_3_3__ALTERItem.sql)
    Line       : 3
    Statement  : ALTER TABLE item MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1710)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:583)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312)
    	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:304)
    	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
    	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1085)
    	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:858)
    	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
    	at org.springframework.test.context.web.AbstractGenericWebContextLoader.loadContext(AbstractGenericWebContextLoader.java:129)
    	at org.springframework.test.context.web.AbstractGenericWebContextLoader.loadContext(AbstractGenericWebContextLoader.java:61)
    	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.delegateLoading(AbstractDelegatingSmartContextLoader.java:107)
    	at org.springframework.test.context.support.AbstractDelegatingSmartContextLoader.loadContext(AbstractDelegatingSmartContextLoader.java:243)
    	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
    	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:117)
    	... 54 common frames omitted
    Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateSqlException: 
    Migration V1_3_3__ALTERItem.sql failed
    --------------------------------------
    SQL State  : 42000
    Error Code : 42000
    Message    : SQLステートメントに文法エラーがあります "ALTER TABLE ITEM MODIFY UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP "
    Syntax error in SQL statement "ALTER TABLE ITEM MODIFY UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP "; SQL statement:
    ALTER TABLE item MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP [42000-196]
    Location   : db/migration/V1_3_3__ALTERItem.sql (/Users/user/dev/test-app/bin/main/db/migration/V1_3_3__ALTERItem.sql)
    Line       : 3
    Statement  : ALTER TABLE item MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
    
    	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:365)
    	at org.flywaydb.core.internal.command.DbMigrate.access$400(DbMigrate.java:52)
    	at org.flywaydb.core.internal.command.DbMigrate$5.call(DbMigrate.java:297)
    	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
    	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:294)
    	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:259)
    	at org.flywaydb.core.internal.command.DbMigrate.access$300(DbMigrate.java:52)
    	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:179)
    	at org.flywaydb.core.internal.command.DbMigrate$4.call(DbMigrate.java:176)
    	at org.flywaydb.core.internal.database.Connection$1.call(Connection.java:155)
    	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:75)
    	at org.flywaydb.core.internal.database.Connection.lock(Connection.java:151)
    	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:148)
    	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:176)
    	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:145)
    	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1206)
    	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1168)
    	at org.flywaydb.core.Flyway.execute(Flyway.java:1655)
    	at org.flywaydb.core.Flyway.migrate(Flyway.java:1168)
    	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1769)
    	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1706)
    	... 71 common frames omitted
    Caused by: org.h2.jdbc.JdbcSQLException: SQLステートメントに文法エラーがあります "ALTER TABLE ITEM MODIFY UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP "
    Syntax error in SQL statement "ALTER TABLE ITEM MODIFY UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON[*] UPDATE CURRENT_TIMESTAMP "; SQL statement:
    ALTER TABLE item MODIFY updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP [42000-196]
    	at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)
    	at org.h2.message.DbException.get(DbException.java:179)
    	at org.h2.message.DbException.get(DbException.java:155)
    	at org.h2.message.DbException.getSyntaxError(DbException.java:191)
    	at org.h2.command.Parser.getSyntaxError(Parser.java:534)
    	at org.h2.command.Parser.prepareCommand(Parser.java:261)
    	at org.h2.engine.Session.prepareLocal(Session.java:578)
    	at org.h2.engine.Session.prepareCommand(Session.java:519)
    	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1204)
    	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:176)
    	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:164)
    	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:95)
    	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
    	at org.flywaydb.core.internal.util.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:265)
    	at org.flywaydb.core.internal.database.StandardSqlStatement.execute(StandardSqlStatement.java:41)
    	at org.flywaydb.core.internal.database.ExecutableSqlScript.execute(ExecutableSqlScript.java:128)
    	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:75)
    	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:363)
    	... 92 common frames omitted

this migration is work on mysql but not on h2.
I want to use mysql for junit test, how can I use mysql by flyway migration for junit tests?

my configuration class for test is

    package test;
    
    import org.springframework.beans.BeansException;
    import org.springframework.context.ApplicationContext;
    import org.springframework.context.ApplicationContextAware;
    import org.springframework.context.annotation.ComponentScan;
    import org.springframework.context.annotation.Configuration;
    import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
    
    @Configuration
    @ComponentScan(basePackages = {"test"})
    public class TestWebConfig implements WebMvcConfigurer, ApplicationContextAware {
    
        private ApplicationContext applicationContext;
    
        @Override
        public void setApplicationContext(ApplicationContext applicationContext) throws BeansException {
            this.applicationContext = applicationContext;
        }
    
    }

my test class is simple like below

    import org.junit.jupiter.api.Test;
    import org.junit.jupiter.api.TestInstance;
    import org.junit.jupiter.api.TestInstance.Lifecycle;
    import org.junit.jupiter.api.extension.ExtendWith;
    import org.springframework.test.context.web.WebAppConfiguration;
    import org.springframework.test.context.ContextConfiguration;
    import org.springframework.test.context.junit.jupiter.SpringExtension;
    
    @ExtendWith(SpringExtension.class)
    @WebAppConfiguration()
    @ContextConfiguration(classes = TestWebConfig.class)
    @TestInstance(Lifecycle.PER_CLASS)
    public class someTest{
    
    	@Test
        public void testCase() throws Exception {
        }
    }

my application.properties is 

    server.port=9090
    
    spring.datasource.driver-class-name=com.mysql.jdbc.Driver
    spring.datasource.url=jdbc:mysql://localhost:3306/dev_db
    spring.datasource.username=sa
    spring.datasource.password=
    
    spring.flyway.url=jdbc:mysql://localhost:3306/dev_db
    spring.flyway.user=sa
    spring.flyway.password=
    
    spring.flyway.baselineVersion=1
    spring.flyway.baseline-on-migrate=false
    
    spring.messages.basename=messages
    spring.messages.cache-duration=-1
    spring.messages.encoding=UTF-8

###### What did you expect to see?

flyway migration with mysql for the test.

###### What did you see instead?

flyway migration with h2 for the test.

**Comment by axelfontaine** [comment]
That file is a Spring Boot-specific config file which the Flyway Gradle plugin doesn't know about. You must either configure the Gradle plugin in the build script or via any of the other configuration possibilities: https://flywaydb.org/documentation/gradle/#configuration
