### ISSUE TITLE
migrate fails after baseline succeeds: org.flywaydb.core.internal.exception.FlywaySqlException:  Unable to insert row for version '2' in Schema History table "myschema"."flyway_schema_history"

### ISSUE THREAD

**Issue by eepstein** [flyway/flyway#2002]
###### Which version and edition of Flyway are you using?
5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

          <artifactId>flyway-maven-plugin</artifactId>
          <version>5.0.7</version>

###### Which database are you using (type & version)?

PostgreSQL v 9.6

JDBC:     <postgresql.version>42.2.2</postgresql.version>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>

###### Which operating system are you using?

MacOS, Zsh

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I want to use a schema, so configured flyway's maven plugin accordingly:

      <plugin>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-maven-plugin</artifactId>
        <configuration>
          <schemas>
            <schema>myschema</schema>
          </schemas>

We keep the URL for the db in an env-specific conf file.

First made the baseline:

    mvn -Dflyway.configFiles=./flyway-dev.conf flyway:baseline

That worked perfectly.  The "flyway_schema_history" table was created in the expected schema with a single row (for the baseline).

Then, changing nothing, ran the :migrate command with two migration files in the default location (src/main/resources/db/migration).

    mvn -Dflyway.configFiles=./flyway-dev.conf flyway:migrate

###### What did you expect to see?

A successful migration with the tables created and the entries added to the "myschema"."flyway_schema_history" table.

###### What did you see instead?

```
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:5.0.7:migrate (default-cli) on project coincore: org.flywaydb.core.internal.exception.FlywaySqlException: 
[ERROR] Unable to insert row for version '2' in Schema History table "myschema"."flyway_schema_history"
[ERROR] -------------------------------------------------------------------------------------------------
[ERROR] SQL State  : 42P01
[ERROR] Error Code : 0
[ERROR] Message    : ERROR: relation "myschema.flyway_schema_history" does not exist
[ERROR]   Position: 35
```
I noticed the quoting in the Error messages is different: first time uses quotes around the schema name and the table name, second time just quotes the whole string (that's slightly confusing).

I re-ran with the -e flag but learned nothing, but perhaps the stack trace is useful to the devs:

```  
Position: 35

	at org.flywaydb.maven.AbstractFlywayMojo.execute(AbstractFlywayMojo.java:603)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: org.postgresql.util.PSQLException: ERROR: relation "coinbridge.flyway_schema_history" does not exist
  Position: 35
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2433)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2178)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:306)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:155)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:118)
	at org.flywaydb.core.internal.util.jdbc.JdbcTemplate.queryForInt(JdbcTemplate.java:164)
```

As mentioned, when I check the DB the table is there.

**Comment by eepstein** [comment]
whoops.  bug in the migration script from pre-flyway days where the schema was being dropped and recreated.  fixed.
