### ISSUE TITLE
Can't connect with "(using password: NO)" error even though password is specified.

### ISSUE THREAD

**Issue by cha4osoOwll** [flyway/flyway#2049]
###### Which version and edition of Flyway are you using?
4.2.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
That is the version my team is using.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line.

###### Which database are you using (type & version)?
MySQL 8.0

###### Which operating system are you using?
Windows 10 x64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Conf file lines:
flyway.url=jdbc:mysql://localhost:3306/?useSSL=false
flyway.user=root
flyway.password={redacted but definitely present}

Command line:
bash sql/flyway -X -password={redacted but definitely present} -schemas=consumer_attribution_shadow -locations=filesystem:sql/sql_consumer_attribution_shadow migrate

###### What did you expect to see?
Not necessarily a successful connection but I expected Flyway to at least use the password it was given.

###### What did you see instead?
DEBUG: Java 1.8.0_171 (Oracle Corporation)
DEBUG: Windows 10 10.0 amd64

DEBUG: Loading config file: C:\Users\r624121\Documents\cmb-vbps-attribution\sql\conf\flyway.conf
DEBUG: Unable to load config file: C:\Users\r624121\flyway.conf
DEBUG: Unable to load config file: C:\Users\r624121\Documents\cmb-vbps-attribution\flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.locations -> filesystem:sql/sql_consumer_attribution_shadow
DEBUG: flyway.outOfOrder -> true
DEBUG: flyway.cleanDisabled -> true
DEBUG: flyway.password -> *******************
DEBUG: flyway.placeholders.consmr_attribution_contract_cud_arn -> arn:aws:lambda:@@awsRegion:@@awsAccount:function:chp-vbps-consmr-attribution-contract-cud-@@awsEnv
DEBUG: flyway.schemas -> consumer_attribution_shadow
DEBUG: flyway.placeholders.consmr_attribution_attribution_cud_arn -> arn:aws:lambda:@@awsRegion:@@awsAccount:function:chp-vbps-consmr-attribution-attribution-cud-@@awsEnv
DEBUG: flyway.url -> jdbc:mysql://localhost:3306/?useSSL=false
DEBUG: flyway.user -> root
DEBUG: flyway.jarDirs -> C:\Users\r624121\Documents\cmb-vbps-attribution\sql\jars
DEBUG: Adding location to classpath: C:\Users\r624121\Documents\cmb-vbps-attribution\sql\drivers\mariadb-java-client-1.4.5.jar
ERROR: Unexpected error
org.flywaydb.core.internal.dbsupport.FlywaySqlException:
Unable to obtain Jdbc connection from DataSource (jdbc:mysql://localhost:3306/?useSSL=false) for user 'root': Could not connect: Access denied for user 'root'@'localhost' (using password: NO)
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 28000
Error Code : 1045
Message    : Could not connect: Access denied for user 'root'@'localhost' (using password: NO)

        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:419)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:381)
        at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:971)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:148)
        at org.flywaydb.commandline.Main.main(Main.java:103)
Caused by: java.sql.SQLInvalidAuthorizationSpecException: Could not connect: Access denied for user 'root'@'localhost' (using password: NO)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:121)
        at org.mariadb.jdbc.internal.util.ExceptionMapper.throwException(ExceptionMapper.java:69)
        at org.mariadb.jdbc.Driver.connect(Driver.java:110)
        at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:416)
        ... 6 more
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Could not connect: Access denied for user 'root'@'localhost' (using password: NO)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.authentication(AbstractConnectProtocol.java:500)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.handleConnectionPhases(AbstractConnectProtocol.java:448)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connect(AbstractConnectProtocol.java:359)
        at org.mariadb.jdbc.internal.protocol.AbstractConnectProtocol.connectWithoutProxy(AbstractConnectProtocol.java:701)
        at org.mariadb.jdbc.internal.util.Utils.retrieveProxy(Utils.java:471)
        at org.mariadb.jdbc.Driver.connect(Driver.java:105)
        ... 7 more

**Comment by axelfontaine** [comment]
Use the latest Flyway and MySQL driver versions and things will work as expected.
