### ISSUE TITLE
Java based migration fails with class not found after upgrade from 4.2.0 to 5.0.7

### ISSUE THREAD

**Issue by stherkildsen** [flyway/flyway#2107]
###### Which version and edition of Flyway are you using?
5.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
Yes. 5.1.4 has same behaviour. But it works with 4.2.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command line

###### Which database are you using (type & version)?
10.0.27-MariaDB-1~trusty

###### Which operating system are you using?
Ubuntu 14.04

###### What did you do?
Running a combination of SQL and java based migrations.

My java based migration has dependencies on hibernate. Those dependencies (jar files) are present in the same directory as the jar file containing the java based migration, and the jarDirs property points to this directory.

###### What did you expect to see?
With 4.2.0 it seems to work correctly. My java base migration completes successfully.

[2018-08-15 18:16:37,559] [INFO ] com.mycompany.MyHibernateSchemaUpgrade: [beforeMigration] Upgrading database schema [mySchema] with upgrade mode [update] [2018-08-15 18:16:37,611] [INFO ] org.hibernate.jpa.internal.util.LogHelper: HHH000204: Processing PersistenceUnitInfo [
        name: MyHibernateSchemaUpgrade
        ...]
[2018-08-15 18:16:37,764] [INFO ] org.hibernate.Version: HHH000412: Hibernate Core {5.2.16.Final}
[2018-08-15 18:16:37,766] [INFO ] org.hibernate.cfg.Environment: HHH000206: hibernate.properties not found
[2018-08-15 18:16:37,814] [INFO ] org.hibernate.annotations.common.Version: HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
[2018-08-15 18:16:38,469] [INFO ] org.hibernate.dialect.Dialect: HHH000400: Using dialect: org.hibernate.dialect.MySQL55Dialect
[2018-08-15 18:16:46,867] [INFO ] com.mycompany.MyHibernateSchemaUpgrade: [beforeMigration] Upgrading database schema finished successfully

###### What did you see instead?
I get this when i run "info" or "migrate" for that matter:

Exception in thread "main" java.lang.NoClassDefFoundError: javax/persistence/spi/PersistenceUnitInfo
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:59)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.setCallbacksAsClassNames(ClassicConfiguration.java:1241)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1528)
        at org.flywaydb.core.Flyway.configure(Flyway.java:1193)
        at org.flywaydb.core.Flyway.configure(Flyway.java:1181)
        at org.flywaydb.commandline.Main.main(Main.java:105)
Caused by: java.lang.ClassNotFoundException: javax.persistence.spi.PersistenceUnitInfo
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 8 more

Running with debugging info lists all dependencies in the jarDirs folder as:

DEBUG: Adding location to classpath: /pack/migr/libs/hibernate-core-5.2.16.Final.jar
DEBUG: Adding location to classpath: /pack/migr/libs/hibernate-commons-annotations-5.0.1.Final.jar
DEBUG: Adding location to classpath: /pack/migr/libs/hibernate-jpa-2.1-api-1.0.0.Final.jar

**Comment by stherkildsen** [comment]
Hi @axelfontaine 

I don't understand your reply.

When you say the jar is not my "installation" do you mean, that I should put my hibernate dependencies into the flyway $INSTALLDIR/lib/ ?

The javax.persistence.spi.PersistenceUnitInfo is in the jar files listed by flyway:

DEBUG: Adding location to classpath: /pack/migr/libs/hibernate-core-5.2.16.Final.jar
DEBUG: Adding location to classpath: /pack/migr/libs/hibernate-commons-annotations-5.0.1.Final.jar
DEBUG: Adding location to classpath: /pack/migr/libs/hibernate-jpa-2.1-api-1.0.0.Final.jar

And it works with version 4.2.0.

Can you elaborate on your answer?

**Comment by stherkildsen** [comment]
My workaround is to change the bash script running flyway, so i can add the jars to the flyway classpath:

I replace:

`CP="$INSTALLDIR/lib/*:$INSTALLDIR/drivers/*"`

with

`if` [ -z "$IFDB_MIGRATION_CLASSPATH" ]; then
CP="$INSTALLDIR/lib/*:$INSTALLDIR/drivers/*";
else
CP="$INSTALLDIR/lib/*:$INSTALLDIR/drivers/*:$IFDB_MIGRATION_CLASSPATH";
fi`

**Comment by axelfontaine** [comment]
Hmmm I can't see where we could be doing something wrong with our class loading. I would be happy to reopen if you can point me to the place where we fail to load a class correctly.

**Comment by stherkildsen** [comment]
Cool. I will look into it.
