### ISSUE TITLE
Eclipse Gemini OSGi container support

### ISSUE THREAD

**Issue by aegyed** [flyway/flyway#2114]
Flyway version 5.1.4

The change you made for #1922 made flyway unusable in OSGi environment, as the TTCL cannot find your own JavaUtilLogCreator as seen below:

[2018-08-23 09:51:46.278] ERROR iniBlueprintExtenderThread-1 o.e.g.b.e.i.d.startup.DependencyWaiterApplicationContextExecutor | 199 - org.eclipse.gemini.blueprint.extender - 2.1.0.RELEASE | Unable to create application context for [whatever], unsatisfied dependencies: none java.lang.ExceptionInInitializerError: null
	at org.flywaydb.core.internal.util.FeatureDetector.isSlf4jAvailable(FeatureDetector.java:96)
	at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:75)
	at org.flywaydb.core.internal.util.FeatureDetector.<clinit>(FeatureDetector.java:25)
	at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:72)
	at org.flywaydb.core.Flyway.<clinit>(Flyway.java:79)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.eclipse.gemini.blueprint.extensions.annotation.ServiceReferenceDependencyBeanFactoryPostProcessor.getServiceDependencies(ServiceReferenceDependencyBeanFactoryPostProcessor.java:68)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyServiceManager.doFindDependencies(DependencyServiceManager.java:355)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyServiceManager.findServiceDependencies(DependencyServiceManager.java:294)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.stageOne(DependencyWaiterApplicationContextExecutor.java:251)
	at org.eclipse.gemini.blueprint.extender.internal.dependencies.startup.DependencyWaiterApplicationContextExecutor.refresh(DependencyWaiterApplicationContextExecutor.java:177)
	at org.eclipse.gemini.blueprint.context.support.AbstractDelegatedExecutionApplicationContext.refresh(AbstractDelegatedExecutionApplicationContext.java:154)
	at org.eclipse.gemini.blueprint.extender.internal.activator.LifecycleManager$1.run(LifecycleManager.java:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.flywaydb.core.api.FlywayException: Unable to instantiate class org.flywaydb.core.internal.util.logging.javautil.JavaUtilLogCreator : org.flywaydb.core.internal.util.logging.javautil.JavaUtilLogCreator
	at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:61)
	at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:80)
	at org.flywaydb.core.internal.util.ClassUtils.<clinit>(ClassUtils.java:37)
	... 17 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.flywaydb.core.internal.util.logging.javautil.JavaUtilLogCreator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:59)
	... 19 common frames omitted

Also, setting fallbackLogCreator does not work in OSGi environment as it depends on which classloader loaded the class.

After I hacked it back to how it was before, it worked fine.

As I see it, LogCreator implementations should be instantiated normally with new, but the TCCL could be added into them so they can use that to instantiate the respective logging systems classes. So instead of instantiating the log creators with TCCL, use TCCL only for the third party classes inside the log creators.

**Comment by axelfontaine** [comment]
Thanks for reporting this. We test with Equinox and Flyway works fine within that OSGi container. We would however be happy to accept a pull request if you can fix this for Eclipse Gemini without breaking the existing functionality.
