### ISSUE TITLE
Attempts to connect result in localhost

### ISSUE THREAD

**Issue by boha11oran** [flyway/flyway#2131]
###### Which version and edition of Flyway are you using?
5.1.4 Professional

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using (type & version)?
psql (9.6.10, server 9.6.2)

###### Which operating system are you using?
Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Attempts to migrate are failing
```
[ors@ip-10-9-2-42 ~]$ flyway -url=jdbc:postgresql::/devorsdb.cbzap9vzxhuy.us-east-1.rds.amazonaws.com:5432/ors -user=flyway -password=***** migrate

ERROR: 
Unable to obtain connection from database (jdbc:postgresql::/devorsdb.xxx.us-east-1.rds.amazonaws.com:5432/ors) for user 'flyway': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

and yet we can connect to this database
```
[ors@ip-10-9-2-42 ~]$ psql -d ors -h devorsdb.xxx.us-east-1.rds.amazonaws.com -p 5432 -U flyway
Password for user flyway: 
psql (9.6.10, server 9.6.2)
SSL connection (protocol: TLSv1.2, cipher: ECDHE-RSA-AES256-GCM-SHA384, bits: 256, compression: off)
Type "help" for help.
```

here is contents of conf
```
[ors@ip-10-9-2-42 ~]$ cat flyway.conf 
flyway.url=jdbc:postgresql:://devorsdb.xxx.us-east-1.rds.amazonaws.com:5432/ors
flyway.user=flyway
flyway.password=***********
flyway.locations=flywaymigrations
```

###### What did you expect to see?
Successful migration to devorsdb.xxx.us-east-1.rds.amazonaws.com:5432

###### What did you see instead?
Connection to localhost:5432 refused

**Comment by boha11oran** [comment]
Here is more with DEBUG

```[ors@ip-10-9-2-42 ~]$ flyway -X -url=jdbc:postgresql::/devorsdb.xxx.us-east-1.rds.amazonaws.com:5432/ors -user=flyway -password=flyway12345 migrate
Flyway Pro Edition 5.1.4 by Boxfuse

DEBUG: Java 1.8.0_172 (Oracle Corporation)
DEBUG: Linux 4.14.62-70.117.amzn2.x86_64 amd64

DEBUG: Loading config file: /home/ors/flyway-5.1.4/flyway-commandline/flyway-5.1.4/conf/flyway.conf
DEBUG: Loading config file: /home/ors/flyway.conf
DEBUG: Loading config file: /home/ors/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /home/ors/flyway-5.1.4/flyway-commandline/flyway-5.1.4/jars
DEBUG: flyway.password -> ***********
DEBUG: flyway.url -> jdbc:postgresql::/devorsdb.xxx.us-east-1.rds.amazonaws.com:5432/ors
DEBUG: flyway.user -> flyway
DEBUG: flyway.locations -> flywaymigrations
DEBUG: Adding location to classpath: /home/ors/flyway-5.1.4/flyway-commandline/flyway-5.1.4/drivers/derby-10.14.2.0.jar
DEBUG: Adding location to classpath: /home/ors/flyway-5.1.4/flyway-commandline/flyway-5.1.4/drivers/derbyclient-10.14.2.0.jar
DEBUG: Adding location to classpath: /home/ors/flyway-5.1.4/flyway-commandline/flyway-5.1.4/drivers/h2-1.4.197.jar
DEBUG: Adding location to classpath: /home/ors/flyway-5.1.4/flyway-commandline/flyway-5.1.4/drivers/hsqldb-2.4.0.jar
DEBUG: Adding location to classpath: /home/ors/flyway-5.1.4/flyway-commandline/flyway-5.1.4/drivers/mssql-jdbc-6.4.0.jre7.jar
DEBUG: Adding location to classpath: /home/ors/flyway-5.1.4/flyway-commandline/flyway-5.1.4/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /home/ors/flyway-5.1.4/flyway-commandline/flyway-5.1.4/drivers/mariadb-java-client-2.2.4.jar
DEBUG: Adding location to classpath: /home/ors/flyway-5.1.4/flyway-commandline/flyway-5.1.4/drivers/postgresql-42.2.2.jre6.jar
DEBUG: Adding location to classpath: /home/ors/flyway-5.1.4/flyway-commandline/flyway-5.1.4/drivers/sqlite-jdbc-3.20.1.jar
Sep 04, 2018 5:35:30 PM org.postgresql.core.v3.ConnectionFactoryImpl log
WARNING: ConnectException occurred while connecting to localhost:5432
java.net.ConnectException: Connection refused (Connection refused)
```

**Comment by axelfontaine** [comment]
What is your full url? Did you add `&ssl=true` to connect using TLS? See https://jdbc.postgresql.org/documentation/head/connect.html

**Comment by boha11oran** [comment]
We are seeing similar result with ssl setting.  Is it possible that we also need a postgres instance running locally?

```
[ors@ip-10-9-2-42 ~]$ flyway -X migrate
Flyway Community Edition 5.1.4 by Boxfuse

DEBUG: Java 1.8.0_172 (Oracle Corporation)
DEBUG: Linux 4.14.62-70.117.amzn2.x86_64 amd64

DEBUG: Loading config file: /usr/local/lib/flyway-5.1.4/conf/flyway.conf
DEBUG: Loading config file: /home/ors/flyway.conf
DEBUG: Loading config file: /home/ors/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /usr/local/lib/flyway-5.1.4/jars
DEBUG: flyway.password -> ***********
DEBUG: flyway.url -> jdbc:postgresql:://devorsdb.xxx.us-east-1.rds.amazonaws.com:5432/ors&ssl=true
DEBUG: flyway.user -> flyway
DEBUG: flyway.locations -> flywaymigrations
DEBUG: Adding location to classpath: /usr/local/lib/flyway-5.1.4/drivers/derby-10.14.2.0.jar
DEBUG: Adding location to classpath: /usr/local/lib/flyway-5.1.4/drivers/derbyclient-10.14.2.0.jar
DEBUG: Adding location to classpath: /usr/local/lib/flyway-5.1.4/drivers/h2-1.4.197.jar
DEBUG: Adding location to classpath: /usr/local/lib/flyway-5.1.4/drivers/hsqldb-2.4.0.jar
DEBUG: Adding location to classpath: /usr/local/lib/flyway-5.1.4/drivers/mssql-jdbc-6.4.0.jre7.jar
DEBUG: Adding location to classpath: /usr/local/lib/flyway-5.1.4/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /usr/local/lib/flyway-5.1.4/drivers/mariadb-java-client-2.2.4.jar
DEBUG: Adding location to classpath: /usr/local/lib/flyway-5.1.4/drivers/postgresql-42.2.2.jre6.jar
DEBUG: Adding location to classpath: /usr/local/lib/flyway-5.1.4/drivers/sqlite-jdbc-3.20.1.jar
Sep 05, 2018 12:54:34 PM org.postgresql.core.v3.ConnectionFactoryImpl log
WARNING: ConnectException occurred while connecting to localhost:5432
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:69)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:421)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:384)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:70)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1227)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:910)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
	at org.flywaydb.commandline.Main.main(Main.java:108)

Sep 05, 2018 12:54:34 PM org.postgresql.Driver connect
SEVERE: Connection error: 
org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:245)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:452)
	at org.postgresql.Driver.connect(Driver.java:254)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:421)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:384)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:51)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:70)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1227)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:910)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.postgresql.core.PGStream.<init>(PGStream.java:69)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:156)
	... 12 more

ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:postgresql:://devorsdb.xxx.us-east-1.rds.amazonaws.com:5432/ors&ssl=true) for user 'flyway': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```

**Comment by axelfontaine** [comment]
@boha11oran If it's the only URL parameter, it should be `?ssl=true` (not `&ssl=true`). What is the result with that?

**Comment by boha11oran** [comment]
Similar results with ```?ssl=true```

```
Unable to obtain connection from database (jdbc:postgresql:://devorsdb.cbzap9vzxhuy.us-east-1.rds.amazonaws.com:5432/ors?ssl=true) for user 'flyway': Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
```
We are seeing what appears to be a named socket error when running with ```strace -f -e trace=network flyway migrate 2>&1```

```
[pid 27690] connect(3, {sa_family=AF_UNIX, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
```

**Comment by pzygielo** [comment]
I can't see in any [URL form](https://jdbc.postgresql.org/documentation/94/connect.html) the case for two colons before the hostname (eg. `devorsdb` here). They say:

> The host name of the server. Defaults to localhost.

**Comment by boha11oran** [comment]
Thanks @pzygielo that solved my problem!
