### ISSUE TITLE
PostgreSQL current schema function throws NPE instead of permission denied exception

### ISSUE THREAD

**Issue by guylabs** [flyway/flyway#2134]
###### Which version and edition of Flyway are you using?
`master` on commit a9572e60b88b25bf199809a7ea6f3baa9f947ce0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
PostgreSQL 10.5
JDBC Driver: `42.2.2.jre6`

###### Which operating system are you using?
Mac OSX 10.13.6

###### What did you do?
Executed a migration with the PostgreSQL connection query parameter `currentSchema` set and without setting the `schemas` property on the Flyway `Configuration`. With this setup you will receive the below mentioned NPE as Flyway tries to retrieve the current schema via the `SELECT current_schema`. In older versions of Flyway the `SHOW search_path` query was used which returned the current schema of the connection.

You can check the https://github.com/guylabs/flyway/blob/ec52cd866895af6d6626b8821fd0753d472783bd/flyway-core/src/test/java/org/flywaydb/core/schema/CurrentSchemaTest.java test on my fork which shows the problem in a sample test. It also includes a test where the `schemas` property of the Flyway `Configuration` is set and this test is passing.

It looks like the issue is that the `SHOW search_path` query did not need any specific permissions on the schema and it returned the proper schema name. The `SELECT current_schema` query does need permissions on the schema to return the schema name. With the permissions set on the schema the test passes.

But still the NPE is misleading and we should get a permissions denied exception or Flyway should fallback to the `SHOW search_path` query if the `SELECT current_schema` query returns `null`.

###### What did you expect to see?
That Flyway is able to retrieve the current schema without setting it explicitly on the Flyway `Configuration`.

###### What did you see instead?
A NPE while retrieving the current schema:
```
java.lang.NullPointerException
	at org.flywaydb.core.internal.util.StringUtils.replaceAll(StringUtils.java:182)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLDatabase.pgQuote(PostgreSQLDatabase.java:126)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLDatabase.doQuote(PostgreSQLDatabase.java:122)
	at org.flywaydb.core.internal.database.base.Database.quote(Database.java:295)
	at org.flywaydb.core.internal.database.base.Schema.toString(Schema.java:262)
	at java.base/java.lang.String.valueOf(String.java:2801)
	at java.base/java.lang.StringBuilder.append(StringBuilder.java:135)
	at org.flywaydb.core.internal.command.DbSchemas$1.call(DbSchemas.java:80)
	at org.flywaydb.core.internal.command.DbSchemas$1.call(DbSchemas.java:69)
	at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
	at org.flywaydb.core.internal.command.DbSchemas.create(DbSchemas.java:69)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1232)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1221)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1577)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1221)
        ...
```

**Comment by axelfontaine** [comment]
Thanks for reporting and investigating. Since an empty_search path is definitely a valid state, we added an exception message for this situation that directs the user to possible solutions.

**Comment by guylabs** [comment]
Cool thanks for the quick fix @axelfontaine!
