### ISSUE TITLE
ArrayIndexOutOfBoundsException in parseSimpleHostAddress

### ISSUE THREAD

**Issue by htto** [flyway/flyway#2207]
###### Which version and edition of Flyway are you using?
5.2.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using (type & version)?
mysql  Ver 15.1 Distrib 10.1.37-MariaDB, for Linux (x86_64) using readline 5.1

###### Which operating system are you using?
Arch Linux

###### What did you do?
Just ran `
flyway -X -url=jdbc:mariadb://localhost: -user=root -password= baseline -schemas=new,existing
`
with a port missing.

###### What did you expect to see?
Some proper message/error handling, not index out of bounds

###### What did you see instead?
```
flyway -X -url=jdbc:mariadb://localhost: -user=root -password= baseline -schemas=new,existing
DEBUG: Loading config file: /opt/flyway/flyway-5.2.1/conf/flyway.conf
DEBUG: Unable to load config file: /home/user/flyway.conf
DEBUG: Unable to load config file: /tmp/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /opt/flyway/flyway-5.2.1/jars
DEBUG: flyway.password -> 
DEBUG: flyway.url -> jdbc:mariadb://localhost:
DEBUG: flyway.schemas -> new,existing
DEBUG: flyway.user -> root
DEBUG: flyway.locations -> filesystem:/opt/flyway/flyway-5.2.1/sql
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/derby-10.14.2.0.jar
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/mysql-connector-java-8.0.12.jar
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/jna-platform-4.5.2.jar
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/h2-1.4.197.jar
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/derbyclient-10.14.2.0.jar
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/jna-4.5.2.jar
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/hsqldb-2.4.1.jar
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/sqlite-jdbc-3.23.1.jar
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/postgresql-42.2.5.jre6.jar
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/mariadb-java-client-2.3.0.jar
DEBUG: Adding location to classpath: /opt/flyway/flyway-5.2.1/drivers/mssql-jdbc-7.0.0.jre8.jar
Flyway Community Edition 5.2.1 by Boxfuse
DEBUG: Memory usage: 4 of 119M
ERROR: Unexpected error
java.lang.ArrayIndexOutOfBoundsException: 1
	at org.mariadb.jdbc.HostAddress.parseSimpleHostAddress(HostAddress.java:167)
	at org.mariadb.jdbc.HostAddress.parse(HostAddress.java:138)
	at org.mariadb.jdbc.UrlParser.defineUrlParserParameters(UrlParser.java:268)
	at org.mariadb.jdbc.UrlParser.parseInternal(UrlParser.java:205)
	at org.mariadb.jdbc.UrlParser.parse(UrlParser.java:160)
	at org.mariadb.jdbc.Driver.connect(Driver.java:88)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:433)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:399)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1655)
	at org.flywaydb.core.Flyway.baseline(Flyway.java:1526)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:159)
	at org.flywaydb.commandline.Main.main(Main.java:108)
```

**Comment by htto** [comment]
After scrounging through your code I noticed that you do not parse the url at all, except for the prefix, so not your fault.
