### ISSUE TITLE
MySQL: Migrate fails when the user does not have permission to SELECT on user_variables_by_thread table

### ISSUE THREAD

**Issue by jhinch** [flyway/flyway#2215]
###### Which version and edition of Flyway are you using?

5.2.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This is the latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using (type & version)?

MySQL 5.7.22, specifically the mysql:5.7.22 docker image

###### Which operating system are you using?

Mac OS

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

Run a migrate() with a simple table creation

###### What did you expect to see?

The migration to succeed

###### What did you see instead?

```
org.flywaydb.core.internal.exception.FlywaySqlException:

Unable to restore connection to its original state
--------------------------------------------------
SQL State  : 42000
Error Code : 1142
Message    : SELECT command denied to user 'test'@'172.17.0.1' for table 'user_variables_by_thread'

Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: SELECT command denied to user 'test'@'172.17.0.1' for table 'user_variables_by_thread'
```

This appears to be due to the fix applied for #2197. It makes the assumption that the user creating the schema has permission to query this table. Reverting back to Flyway 5.2.1 fixes the problem.

**Comment by axelfontaine** [comment]
@jhinch Thanks for reporting. This is indeed a case we didn't consider as we just assumed the Flyway user would have access. We have now fixed this by adding an additional check. Please build from source and confirm it is now working for you.

**Comment by jhinch** [comment]
Just tested it out and it is working. Thankyou!

**Comment by bHacklv** [comment]
This bug was introduced in flyway 5.2.2.

**Comment by lin362234867** [comment]
is that working now in 5.2.4?  I just get this issue in flyway 5.2.4 and springboot 2.1.3.RELEASE

**Comment by keijack** [comment]
5.2.4 still have this problem.

**Comment by jaywongs** [comment]
5.2.4 still has this problem too, is there any way to fix that?

**Comment by jaywongs** [comment]
> 5.2.4 still has this problem.

Did you solved that?

**Comment by ltylty** [comment]
spring boot 2.2, flyway 6.0.8 still has this problem。
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to determine value for 'foreign_key_checks' variable
-----------------------------------------------------------
SQL State  : null
Error Code : 0
Message    : connection disabled

	at org.flywaydb.core.internal.database.mysql.MySQLConnection.getIntVariableValue(MySQLConnection.java:64)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.<init>(MySQLConnection.java:56)
	at org.flywaydb.core.internal.database.mysql.MySQLDatabase.doGetConnection(MySQLDatabase.java:162)
	at org.flywaydb.core.internal.database.mysql.MySQLDatabase.doGetConnection(MySQLDatabase.java:40)
	at org.flywaydb.core.internal.database.base.Database.getConnection(Database.java:122)
	at org.flywaydb.core.internal.database.base.Database.getMainConnection(Database.java:315)
	at org.flywaydb.core.Flyway.prepareSchemas(Flyway.java:550)
	at org.flywaydb.core.Flyway.execute(Flyway.java:487)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:149)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	... 18 common frames omitted
Caused by: java.sql.SQLException: connection disabled
	at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1169)
	at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1154)
	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:337)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:332)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForInt(JdbcTemplate.java:147)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.getIntVariableValue(MySQLConnection.java:62)
	... 29 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: SELECT command denied to user '' for table 'user_variables_by_thread'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForStringList(JdbcTemplate.java:119)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.hasUserVariableResetCapability(MySQLConnection.java:84)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.<init>(MySQLConnection.java:54)
	... 28 common frames omitted
Disconnected from the target VM, address: '127.0.0.1:0', transport: 'socket'

Process finished with exit code 1

**Comment by csonuryilmaz** [comment]
Bump to `5.2.4` from `5.2.3` solved below problem,
> SELECT command denied to user 'flyway'@'10.10.11.117' for table 'user_variables_by_thread'

Thanks! :pray:

**Comment by cnlinjie** [comment]
6.0.8 still has this problem.

**Comment by odravison** [comment]
I'm facing the same problem, in 6.4.4

**Comment by mh494078416** [comment]
6.5.3 still has the problem

**Comment by HeliusLee** [comment]
6.5.6 still has  the problem

**Comment by DoodleBobBuffPants** [comment]
Could you provide a minimal reproduction project?

**Comment by HiJackXD** [comment]
> Could you provide a minimal reproduction project?

grant a user with object(specific database) privilleges  only , because flyway need  the 'select ' server privillege (5.2.1 needn't )

**Comment by DoodleBobBuffPants** [comment]
I am unable to reproduce this. The original fix is working as intended for me. Providing a minimal project that reproduces this would help identify and fix the issue.

**Comment by HiJackXD** [comment]
> I am unable to reproduce this. The original fix is working as intended for me. Providing a minimal project that reproduces this would help identify and fix the issue.

```sql
CREATE USER `testUser`@`%` IDENTIFIED BY 'testUser';
GRANT ALL PRIVILEGES  ON `testdb`.* TO `testUser`@`%`;
```

mysql8.0.20 
flyway 6.5.7 
springboo 2.3.0.RELEASE

**Comment by DoodleBobBuffPants** [comment]
Can you share some debug output? (Run the flyway command with `-X`)

**Comment by HiJackXD** [comment]
```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: SELECT command denied to user 'testUser'@'172.17.0.1' for table 'user_variables_by_thread'
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:944)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3978)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3914)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2530)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2683)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2495)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1903)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2011)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3240)
	at com.alibaba.druid.wall.WallFilter.preparedStatement_executeQuery(WallFilter.java:647)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3237)
	at com.alibaba.druid.filter.FilterEventAdapter.preparedStatement_executeQuery(FilterEventAdapter.java:465)
	at com.alibaba.druid.filter.FilterChainImpl.preparedStatement_executeQuery(FilterChainImpl.java:3237)
	at com.alibaba.druid.proxy.jdbc.PreparedStatementProxyImpl.executeQuery(PreparedStatementProxyImpl.java:181)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForStringList(JdbcTemplate.java:119)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.hasUserVariableResetCapability(MySQLConnection.java:84)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.<init>(MySQLConnection.java:54)
	at org.flywaydb.core.internal.database.mysql.MySQLDatabase.doGetConnection(MySQLDatabase.java:197)
	at org.flywaydb.core.internal.database.mysql.MySQLDatabase.doGetConnection(MySQLDatabase.java:40)
	at org.flywaydb.core.internal.database.base.Database.getConnection(Database.java:126)
	at org.flywaydb.core.internal.database.base.Database.getMainConnection(Database.java:319)
	at org.flywaydb.core.Flyway.prepareSchemas(Flyway.java:580)
	at org.flywaydb.core.Flyway.execute(Flyway.java:503)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.addCandidateEntry(DefaultListableBeanFactory.java:1524)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1488)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveMultipleBeans(DefaultListableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1264)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory$DependencyObjectProvider.getIfAvailable(DefaultListableBeanFactory.java:1941)
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration.<init>(MybatisPlusAutoConfiguration.java:128)
	at com.baomidou.mybatisplus.autoconfigure.MybatisPlusAutoConfiguration$$EnhancerBySpringCGLIB$$f5d9197.<init>(<generated>)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:295)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1358)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:409)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1306)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1226)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1511)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1406)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:876)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
```

**Comment by HiJackXD** [comment]
#2341 
Cause by this issue fix

**Comment by DoodleBobBuffPants** [comment]
Unless you can provide a project reproducing this with only Flyway we won't be able to proceed.

**Comment by DoodleBobBuffPants** [comment]
Closing as this isn't an issue in Flyway

**Comment by HiJackXD** [comment]
It's not about project, just create a db user without server prillege in Mysql could repruduce it .
```
CREATE USER `testUser`@`%` IDENTIFIED BY 'testUser';
GRANT ALL PRIVILEGES  ON `testdb`.* TO `testUser`@`%`;
```

**Comment by xyohn** [comment]
This problem is caused by druid
When an error occurred in the previous SQL execution(_SELECT variable_name FROM performance_schema.user_variables_by_thread WHERE variable_value IS NOT NULL_
), druid did a certain amount of processing, which caused this problem in subsequent connections.
To solve this problem,you can replace the connection pool , or grant SELECT permission for user on performance_schema.user_variables_by_thread

**Comment by Phukety** [comment]
I change the druid to HikariDataSource and it works !

**Comment by rommy2015** [comment]
- sql/init_db.sql
-
`CREATE DATABASE IF NOT EXISTS 'db_test;
CREATE USER `test`@`%` IDENTIFIED BY 'test';
GRANT ALL PRIVILEGES ON `db_test`.* TO `test`@`%`;`

-  in Spring boot
`
....
String pathToInitScripts = "sql";

        MY_SQL_CONTAINER = new MySQLContainer<>(postgres)
                .withDatabaseName("db_test")
                .withUsername("test")
                .withPassword("test")
                .withInitScript(pathToInitScripts + "/init_db.sql")
                .withReuse(true);

        MY_SQL_CONTAINER.start();
@DynamicPropertySource
    public static void registerPgProperties(DynamicPropertyRegistry propertyRegistry) {

        String jdbcUrl = MY_SQL_CONTAINER.getJdbcUrl();
        System.out.println(jdbcUrl);

        propertyRegistry.add("spring.datasource.url", getMySqlContainer()::getJdbcUrl);
        propertyRegistry.add("ttdb_test", getMySqlContainer()::getDatabaseName);
        propertyRegistry.add("spring.datasource.username", getMySqlContainer()::getUsername);
        propertyRegistry.add("spring.datasource.password", getMySqlContainer()::getPassword);
    }

`

I have gotten errors:

`Caused by: org.testcontainers.ext.ScriptUtils$ScriptStatementFailedException: Script execution failed (sql/init_db.sql:2): CREATE USER `test`@`%` IDENTIFIED BY 'test'
	at org.testcontainers.jdbc.JdbcDatabaseDelegate.execute(JdbcDatabaseDelegate.java:49)
	at org.testcontainers.delegate.AbstractDatabaseDelegate.execute(AbstractDatabaseDelegate.java:34)
	at org.testcontainers.ext.ScriptUtils.executeDatabaseScript(ScriptUtils.java:362)
	... 71 more
Caused by: java.sql.SQLSyntaxErrorException: Access denied; you need (at least one of) the CREATE USER privilege(s) for this operation
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)`

How can this be fixed. ? I can't create tables in testcontainer, I can't use create and alter commands and others because of an access error.

**Comment by davidricardo1026** [comment]
I use flywaydb 6.4.4 and I change the druid to HikariDataSource and it works !
so far away from druid ,and save your life

**Comment by FanQijun** [comment]
druid sucks

**Comment by ZERONE-GO** [comment]
I found another solution to solve this issue when you use druid and flyway after 5.2.1 version. 
You can configure the flyway.url, and then flyway will not use the datasource which provide by druid, however, it will create mysql connection, and then the problems will be solved.

`
spring:
  flyway:
    enabled: true
    # 自己定义url不会使用druid自带的连接池，可以防止flyway 5.2.1以后需要performance_schema的问题
    url: jdbc:mysql://localhost:3306/BigData?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    user: testUser
    password: testUser@2023
`

**Comment by linghengqian** [comment]
- I have opened #6143 .
- By setting `closeConnOnFatalError` to `false`, Druid's behavior will align with HikariCP, that is, the connection will no longer be closed when a fatal error defined by Druid occurs. This solves a series of controversies surrounding Spring Boot, Hibernate, Flyway, and ShardingSphere. This is a huge regret introduced from https://github.com/alibaba/druid/commit/882470b1ce7a51a94f3525beceec91384ccd425f 7 years ago.

**Comment by zq99299** [comment]
> spring boot 2.2, flyway 6.0.8 still has this problem. This caused by [druid](https://github.com/alibaba/druid). The database connection pools cannot execute sql if Connection hold exception.
> 
> ```
> Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: 
> Unable to determine value for 'foreign_key_checks' variable
> -----------------------------------------------------------
> SQL State  : null
> Error Code : 0
> Message    : connection disabled
> 
> 	at org.flywaydb.core.internal.database.mysql.MySQLConnection.getIntVariableValue(MySQLConnection.java:64)
> 	at org.flywaydb.core.internal.database.mysql.MySQLConnection.<init>(MySQLConnection.java:56)
> 	at org.flywaydb.core.internal.database.mysql.MySQLDatabase.doGetConnection(MySQLDatabase.java:162)
> 	at org.flywaydb.core.internal.database.mysql.MySQLDatabase.doGetConnection(MySQLDatabase.java:40)
> 	at org.flywaydb.core.internal.database.base.Database.getConnection(Database.java:122)
> 	at org.flywaydb.core.internal.database.base.Database.getMainConnection(Database.java:315)
> 	at org.flywaydb.core.Flyway.prepareSchemas(Flyway.java:550)
> 	at org.flywaydb.core.Flyway.execute(Flyway.java:487)
> 	at org.flywaydb.core.Flyway.migrate(Flyway.java:149)
> 	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:65)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
> 	... 18 common frames omitted
> Caused by: java.sql.SQLException: connection disabled
> 	at com.alibaba.druid.pool.DruidPooledConnection.checkStateInternal(DruidPooledConnection.java:1169)
> 	at com.alibaba.druid.pool.DruidPooledConnection.checkState(DruidPooledConnection.java:1154)
> 	at com.alibaba.druid.pool.DruidPooledConnection.prepareStatement(DruidPooledConnection.java:337)
> 	at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:332)
> 	at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForInt(JdbcTemplate.java:147)
> 	at org.flywaydb.core.internal.database.mysql.MySQLConnection.getIntVariableValue(MySQLConnection.java:62)
> 	... 29 common frames omitted
> Caused by: java.sql.SQLSyntaxErrorException: SELECT command denied to user '' for table 'user_variables_by_thread'
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
> 	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
> 	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
> 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
> 	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1003)
> 	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:227)
> 	at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForStringList(JdbcTemplate.java:119)
> 	at org.flywaydb.core.internal.database.mysql.MySQLConnection.hasUserVariableResetCapability(MySQLConnection.java:84)
> 	at org.flywaydb.core.internal.database.mysql.MySQLConnection.<init>(MySQLConnection.java:54)
> 	... 28 common frames omitted
> Disconnected from the target VM, address: '127.0.0.1:0', transport: 'socket'
> 
> Process finished with exit code 1
> ```

spring boot 3.2.x, flyway 7.1.1 still has this problem.
