### ISSUE TITLE
LogFactory not initialized with the right classloader if first log is from the Flyway class

### ISSUE THREAD

**Issue by sofoklis** [flyway/flyway#2270]
5.2.4 Which version and edition of Flyway are you using?

Latest Version

Java API

Postgres 10.5

Ubuntu

Upgraded from 5.0.7 to 5.2.4 What did you do?
If i have an exception in the SQL the logger would fail with the regular message now i get the exception bellow, I believe that the Flyway o:
java.lang.ExceptionInInitializerError
        at org.flywaydb.core.internal.util.FeatureDetector.isSlf4jAvailable(FeatureDetector.java:96)
        at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:39)
        at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
        at org.flywaydb.core.internal.util.FeatureDetector.<clinit>(FeatureDetector.java:25)
        at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:35)
        at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
        at org.flywaydb.core.Flyway.<clinit>(Flyway.java:86)
        ...
Caused by: java.lang.ClassCastException: org.flywaydb.core.internal.logging.slf4j.Slf4jLogCreator cannot be cast to org.flywaydb.core.api.logging.LogCreator
        at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:40)
        at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
        at org.flywaydb.core.internal.util.ClassUtils.<clinit>(ClassUtils.java:39)
        ... 17 more

Normal log messages

What did you see instead? The exception above.

It seems to me that after the change to fluid configuration the default log creator is no longer initialized with the same class loader we use for the Configuration object. I think the default log creator should be using the same class loader as the parameter in the configuration object. If you are using multiple threads then depending on which thread you happen to be you randomly get this error.

As a workaround i make sure the first log is in the main method of my migration script.

**Comment by sofoklis** [comment]
I got this sometimes as well
java.lang.ExceptionInInitializerError
        at org.flywaydb.core.internal.util.FeatureDetector.isSlf4jAvailable(FeatureDetector.java:96)
        at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:39)
        at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
        at org.flywaydb.core.internal.util.FeatureDetector.<clinit>(FeatureDetector.java:25)
        at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:35)
        at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
        at org.flywaydb.core.Flyway.<clinit>(Flyway.java:86)
        at com.papasofokli.DbMigration$.migrateDb(DbMigration.scala:59)
        at com.papasofokli.DbCreate$.$anonfun$createDatabaseAndRestore$10(DbCreate.scala:73)
        at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:307)
        at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:41)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
        at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
        at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
        at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
        at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
        at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.ClassCastException: org.flywaydb.core.internal.logging.slf4j.Slf4jLogCreator cannot be cast to org.flywaydb.core.api.logging.LogCreator
        at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:40)
        at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78)
        at org.flywaydb.core.internal.util.ClassUtils.<clinit>(ClassUtils.java:39)
        ... 17 more

**Comment by axelfontaine** [comment]
Please share the necessary code to reproduce this.

**Comment by sofoklis** [comment]
I think there should be a connection between the log factory and the config object. Now the log factory is a singleton but when and where it is created can cause issues.

```
public class LogFactory{ ...
     public static Log getLog(Class<?> clazz) {
        if (logCreator == null) {
            // Here the class loader is not necessarily the same as the one you specified in the
            // configuration object, and if it is not the you get the exception above.
            ClassLoader classLoader = Thread.currentThread().getContextClassLoader();
            logCreator = LogCreatorFactory.getLogCreator(classLoader, fallbackLogCreator);
        }

        return logCreator.createLogger(clazz);
    }
}

```


To reproduce all you have to do is create the config object this migration in a different thread than the main thread, i believe this should be enough:
```
main(){
    val config = Flyway.configure(this.getClass.getClassLoader)
          .dataSource(url, ownerUser, password);

    new Thread(() -> {
         // Create the Flyway instance and point it to the database
          Flyway flyway = Flyway.configure().dataSource("jdbc:h2:file:./target/foobar", "sa", null).load();

          // Start the migration
        flyway.migrate();
    }).start();
}
```

**Comment by nigredo-tori** [comment]
Hit this as well using SBT.

I'm using Flyway to set up the test database. When running tests manually, on the first test run everything is OK, but on the second one I get the exception above. I explicitly initialize `Flyway` with a classloader from my project, and the tests are ran without forking - meaning they are run from two different classloaders.

**Comment by nigredo-tori** [comment]
In the first place, does `LogFactory` even need [the thread classloader](https://github.com/flyway/flyway/blob/216c9df931e31f5f20bffe1f0a87426d3991a19a/flyway-core/src/main/java/org/flywaydb/core/api/logging/LogFactory.java#L77-L78)? It's only used in `LogCreatorFactory` to instantiate one of the known `LogCreator`s, which are in the same artifact as `LogFactory`. `LogFactory.getClass().getClassLoader()` should be enough here, IMO.

**Comment by axelfontaine** [comment]
@nigredo-tori @sofoklis  Can you confirm the problem goes away if you switch to `LogFactory.getClass().getClassLoader()` instead?

**Comment by nigredo-tori** [comment]
@axelfontaine, it seems to solve the issue for my case (though it's `LogFactory.class.getClassLoader()`). But there's probably a use case somewhere for which this breaks things instead... Honestly, I'd much rather  Flyway didn't reinvent logging bridges at all.

**Comment by m4dc4p** [comment]
Seeing this problem from SBT myself. First run is fine, second run fails. Restarting SBT is the only thing that fixes.

I'm using `log4s` w/ logback for logging.

**Comment by axelfontaine** [comment]
This has now been changed to use `LogFactory.class.getClassLoader()`
