### ISSUE TITLE
Getting String index out of range : 0 at org.flywaydb.core.internal.parser.PlaceholderReplacingReader.read(PlaceholderReplacingReader.java:110)

### ISSUE THREAD

**Issue by sambekar** [flyway/flyway#2320]
I am getting issue on 6.0.0-beta
The same script was working fine in 5.2.4

I am using API where the configuration is set as follows
configuration.setLocationsAsStrings(list of locations);
        configuration.setPlaceholders( a predefined placeholders map);
        configuration.setDataSource(url, user, password);
        configuration.setValidateOnMigrate(false);
        configuration.setOutOfOrder(true);
        configuration.setPlaceholderPrefix("/** ");
        configuration.setPlaceholderSuffix(" **/");
        configuration.setSqlMigrationPrefix("v");
        configuration.setTable("SCHEMA_VERSION");
        configuration.setSchemas(list of schemas);

I am using h2:1.4.196 as the database

I executed the junit test for deployment on windows

I ran my migration jnuit tests (which were running fine with version 5.2.4) after migrating to 6.0.0-beta
I got the exception in my first script which was picked up for migration.
The script is something like, I am just adding the relevant snippet of the script because as per the error the problem occurred at "org.flywaydb.core.api.FlywayException: Unable to parse statement in db/migration/common/4.3/v4.3.0.02__baseline.sql at line 8 col 1: String index out of range: 0"

1 CREATE TABLE XYZ
2 (
3  DBVERSION    VARCHAR2(10 CHAR),
4  DESCRIPTION  VARCHAR2(100 CHAR),
5 "COMMENT"    VARCHAR2(4000 CHAR)
6  );
7
8 CREATE TABLE ABC
9 ("

I expected the test case to run fine without any errors.

The test case failed with following exception
org.flywaydb.core.api.FlywayException: Unable to parse statement in db/migration/common/4.3/v4.3.0.02__baseline.sql at line 8 col 1: String index out of range: 0
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:271)
	at org.flywaydb.core.internal.parser.Parser.access$000(Parser.java:41)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:608)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:573)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.<init>(ParserSqlScript.java:73)
	at org.flywaydb.core.internal.database.h2.H2Database.createSqlScript(H2Database.java:126)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.addMigrations(SqlMigrationResolver.java:140)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:100)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:47)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:130)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:112)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:98)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:44)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:133)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:187)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:164)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:161)
	at org.flywaydb.core.internal.database.base.Connection$1.call(Connection.java:147)
	at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:143)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:155)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:161)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:139)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:175)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:136)
	at org.flywaydb.core.Flyway.execute(Flyway.java:453)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:136)
	at xx.xx.xx.xx.xx.testH2(MigrationTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at org.flywaydb.core.internal.parser.PlaceholderReplacingReader.read(PlaceholderReplacingReader.java:110)
	at java.io.FilterReader.read(FilterReader.java:65)
	at org.flywaydb.core.internal.parser.RecordingReader.read(RecordingReader.java:33)
	at java.io.FilterReader.read(FilterReader.java:65)
	at org.flywaydb.core.internal.parser.PeekingReader.refillPeekBuffer(PeekingReader.java:68)
	at org.flywaydb.core.internal.parser.PeekingReader.peek(PeekingReader.java:57)
	at org.flywaydb.core.internal.parser.PeekingReader.peekWhitespace(PeekingReader.java:121)
	at org.flywaydb.core.internal.parser.PeekingReader.readWhitespace(PeekingReader.java:425)
	at org.flywaydb.core.internal.parser.Parser.readToken(Parser.java:447)
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:149)
	... 51 more

**Comment by sambekar** [comment]
Realized that this is a Duplicate of #2308
