### ISSUE TITLE
Flyway expects value for placeholder '&' even when 'SET DEFINE OFF' is added to the script

### ISSUE THREAD

**Issue by sambekar** [flyway/flyway#2321]
###### Which version and edition of Flyway are you using?
Flyway Enterprise Edition  6.0.0-beta

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Oracle 12.1

###### Which operating system are you using?
Windows

###### What did you do?
I have a script where I insert data into a table, one of the value that is to be inserted is "JOHN & TOM Ltd"
In java API usage of flyway, I am setting configuration.setOracleSqlplus(true);
Also other parameters are as given below
`configuration.setLocationsAsStrings(<list of locations>);
configuration.setPlaceholders(map of placeholders);
configuration.setDataSource(url, user, password);
configuration.setValidateOnMigrate(false);
configuration.setOutOfOrder(true);
configuration.setPlaceholderPrefix("/** ");
configuration.setPlaceholderSuffix(" **/");
configuration.setSqlMigrationPrefix("v");
configuration.setTable("SCHEMA_VERSION");
configuration.setSchemas(<list of schemas>);
configuration.setOracleSqlplus(true);`

The script is as follows
`SET DEFINE OFF;
INSERT
INTO ABC
  (
    ID,
    CREATEDBY,
    CREATEDON,
    MODIFIEDBY,
    MODIFIEDON,
    DELETEDFLAG,
    CNTR,
    ACCESSRIGHTNAME,
    DESCRIPTION
  )
  VALUES
  (
    SEQ.nextval,
    'XYZ',
    sysdate,
    'XYZ',
    sysdate,
    0,
	0,
    'dostuff',
    'JOHN & TOM Ltd'
  );
commit;`

###### What did you expect to see?
Since i have set configuration.setOracleSqlplus(true); and the script has SET DEFINE OFF;, I would expect the parser to ignore the '&'.

###### What did you see instead?
I see an exception while flyway tries to parse the script.
`org.flywaydb.core.api.FlywayException: Unable to parse statement in xx.sql at line 1 col 1: No value provided for placeholder: &.  Check your configuration!
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:271)
	at org.flywaydb.core.internal.parser.Parser.access$000(Parser.java:41)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.<init>(Parser.java:586)
	at org.flywaydb.core.internal.parser.Parser.parse(Parser.java:103)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.<init>(ParserSqlScript.java:70)
	at org.flywaydb.core.internal.database.oracle.OracleDatabase.createSqlScript(OracleDatabase.java:138)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.addMigrations(SqlMigrationResolver.java:140)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:100)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:47)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:130)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:112)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:98)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:44)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:133)
	at org.flywaydb.core.internal.command.DbRepair$1.call(DbRepair.java:104)
	at org.flywaydb.core.internal.command.DbRepair$1.call(DbRepair.java:101)
	at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
	at org.flywaydb.core.internal.command.DbRepair.repair(DbRepair.java:101)
	at org.flywaydb.core.Flyway$7.execute(Flyway.java:353)
	at org.flywaydb.core.Flyway$7.execute(Flyway.java:346)
	at org.flywaydb.core.Flyway.execute(Flyway.java:453)
	at org.flywaydb.core.Flyway.repair(Flyway.java:346)
	at xx.xx.xx.xx.MigrationTest.testOracle(MigrationTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: org.flywaydb.core.api.FlywayException: No value provided for placeholder: &.  Check your configuration!
	at org.flywaydb.core.internal.database.oracle.pro.SQLPlusPlaceholderReplacingReader.read(SQLPlusPlaceholderReplacingReader.java:91)
	at java.io.FilterReader.read(FilterReader.java:65)
	at org.flywaydb.core.internal.parser.RecordingReader.read(RecordingReader.java:33)
	at java.io.FilterReader.read(FilterReader.java:65)
	at org.flywaydb.core.internal.parser.PeekingReader.refillPeekBuffer(PeekingReader.java:68)
	at org.flywaydb.core.internal.parser.PeekingReader.peek(PeekingReader.java:57)
	at org.flywaydb.core.internal.parser.PeekingReader.peekWhitespace(PeekingReader.java:121)
	at org.flywaydb.core.internal.parser.PeekingReader.readWhitespace(PeekingReader.java:425)
	at org.flywaydb.core.internal.parser.Parser.readToken(Parser.java:447)
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:149)
	... 45 more

`

**Comment by axelfontaine** [comment]
Thanks for reporting. Upon further analysis this behavior is actually consistent with SQL\*Plus. If you execute the statement the same way, SQL\*Plus will also prompt you for a placeholder:

```
SQL> SET DEFINE OFF; INSERT INTO ABC ( ID, CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, DELETEDFLAG, CNTR, ACCESSRIGHTNAME, DESCRIPTION ) VALUES ( SEQ.nextval, 'XYZ', sysdate, 'XYZ', sysdate, 0, 0, 'dostuff', 'JOHN & TOM Ltd' ); commit;
Enter value for tom:
```

Placing `SET DEFINE OFF` on its own line gives you the desired behavior both with SQL\*Plus and Flyway.

**Comment by sambekar** [comment]
Even when I removed the ; it would still error out for the same issue. Can you please tell us as to how to get this script executed using flyway?

**Comment by axelfontaine** [comment]
Maybe there is something I am missing, but I just can't get it to fail. As soon as `SET DEFINE OFF;` (with or without `;`) is on its own line it works.

Are you sure this simplified script represents your case *exactly*?

**Comment by sambekar** [comment]
so I tried this  with **configuration.setOracleSqlplus(true);**, 
SET DEFINE OFF INSERT INTO ABC ( ID, CREATEDBY, CREATEDON, MODIFIEDBY, MODIFIEDON, DELETEDFLAG, CNTR, ACCESSRIGHTNAME, DESCRIPTION ) VALUES ( SEQ.nextval, 'XYZ', sysdate, 'XYZ', sysdate, 0, 0, 'dostuff', 'JOHN & TOM Ltd' ); commit;

and it failed for 
org.flywaydb.core.api.FlywayException: Unable to parse statement in xxx.sql at line 1 col 1: No value provided for placeholder: &.  Check your configuration!

**Comment by sambekar** [comment]
without the **configuration.setOracleSqlplus(true)** it works fine too.
But I want to use the oracleSqlPlus features of flyway and hence setting it to true.

**Comment by axelfontaine** [comment]
Please share the exact script with the *exact* formatting as there obviously must be some kind of small detail getting lost here.

Note that `SET DEFINE OFF` doesn't work at all without Oracle SQL\*Plus support being active.

**Comment by sambekar** [comment]
the sql attached, not that I am using API and the configuration is set as 
ClassicConfiguration configuration = new ClassicConfiguration();
configuration.setLocationsAsStrings(<list of locations>); 
configuration.setPlaceholders(map of placeholders); 
configuration.setDataSource(url, user, password); 
configuration.setValidateOnMigrate(false); 
configuration.setOutOfOrder(true); 
configuration.setPlaceholderPrefix("/** "); 
configuration.setPlaceholderSuffix(" **/"); 
configuration.setSqlMigrationPrefix("v"); 
configuration.setTable("SCHEMA_VERSION"); 
configuration.setSchemas(<list of schemas>); 
configuration.setOracleSqlplus(true);
configuration.setBaselineVersionAsString(BASELINE_VERSION);
configuration.setBaselineOnMigrate(true);
Flyway f = new FlywayWrapper(configuration);
f.migrate();
[v5.0.0.02__106724_access_right_encode_and_print_all_button.sql.zip](https://github.com/flyway/flyway/files/2967251/v5.0.0.02__106724_access_right_encode_and_print_all_button.sql.zip)

**Comment by axelfontaine** [comment]
Hmm even with all your settings, I just cannot get this to fail. Please share a small GitHub repository with a tiny Java project (Maven or Gradle) with a single class with a main method depending on the flyway-core library and the required SQL files that demonstrates this.

**Comment by sambekar** [comment]
I have added a project at https://github.com/sambekar/flyway-issue-2321
Please not that I have externalized the few parameters like license key, and database credentials which you would have to update manually before running the project.
