### ISSUE TITLE
SQL server database clean fails

### ISSUE THREAD

**Issue by hkorpi** [flyway/flyway#2342]
###### Which version and edition of Flyway are you using?
5.2.4

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API, but should not matter

###### Which database are you using (type & version)?
Microsoft SQL Server 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64) 
Nov 30 2018 12:57:58 
Copyright (C) 2017 Microsoft Corporation
Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS)

###### Which operating system are you using?
Ubuntu 16.04.5 LTS

###### What did you do?
Try to clean database: org.flywaydb.core.Flyway.clean(Flyway.java:1499)

The problem seems to be that cleaning of compiled columns does not work properly. The cleaning is implemented using 2-pass approach and the problem is that if the computed column clean fails in the first pass then SQL server performs an implicit rollback i.e. every database object dropped before the failure is rolled back.

Unfortunately I cannot provide our real schema but you should be able to produce a similar failure using the following test schema:

```
create table test.a(
  x integer primary key,
  y as 1 
)

create index i_a on test.a(y);

create table test.b(
  x as 1 primary key
)
```

###### What did you expect to see?
It should clean the database.

###### What did you see instead?
Database clean fails on error:

```
org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to clean schema [dbo]
----------------------------
SQL State  : S0001
Error Code : 5074
Message    : The index 'i_table_xxx' is dependent on column 'xxx'.

        at org.flywaydb.core.internal.database.base.Schema.clean(Schema.java:151)
        at org.flywaydb.core.internal.command.DbClean$3.call(DbClean.java:172)
        at org.flywaydb.core.internal.command.DbClean$3.call(DbClean.java:169)
        at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
        at org.flywaydb.core.internal.command.DbClean.cleanSchema(DbClean.java:169)
        at org.flywaydb.core.internal.command.DbClean.clean(DbClean.java:113)
        at org.flywaydb.core.Flyway.doClean(Flyway.java:1488)
        at org.flywaydb.core.Flyway.access$300(Flyway.java:85)
        at org.flywaydb.core.Flyway$3.execute(Flyway.java:1506)
        at org.flywaydb.core.Flyway$3.execute(Flyway.java:1499)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
        at org.flywaydb.core.Flyway.clean(Flyway.java:1499)
        ...
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The index 'i_table_xxx' is dependent on column 'xxx'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:254)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1608)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:578)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:508)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7240)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2869)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:243)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:218)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:493)
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:215)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerSchema.doClean(SQLServerSchema.java:247)
        at org.flywaydb.core.internal.database.base.Schema.clean(Schema.java:149)
        ... 33 common frames omitted
```

**Comment by axelfontaine** [comment]
Hmmm I can't seem to get this to fail. Can you please share the smallest possible SQL file that causes 6.0.0-beta to trip over this?

**Comment by axelfontaine** [comment]
Closing due to lack of response.
