### ISSUE TITLE
linux - can't connect to database through command line : fresh install

### ISSUE THREAD

**Issue by crissacandler** [flyway/flyway#2367]
###### Which version and edition of Flyway are you using?

5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This is latest.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using (type & version)?

mysql 5.7 and 8.0

###### Which operating system are you using?

linux-debian 9-stretch

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

flyway repair 

###### What did you expect to see?

flyway connects to database

###### What did you see instead?
```
> flyway -X repair && flyway -X migrate

DEBUG: Loading config file: /usr/src/flyway-5.2.4/conf/flyway.conf
DEBUG: Unable to load config file: /root/flyway.conf
DEBUG: Unable to load config file: /app/flyway.conf
DEBUG: Loading config file: /app/src/db/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /usr/src/flyway-5.2.4/jars
DEBUG: flyway.password -> ********
DEBUG: flyway.url -> jdbc:mysql://localhost:3306/relay_test?serverTimezone=EST
DEBUG: flyway.configFiles -> src/db/flyway.conf
DEBUG: flyway.user -> root
DEBUG: flyway.locations -> filesystem:src/db/migrations
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/derbyclient-10.14.2.0.jar
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/derby-10.14.2.0.jar
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/postgresql-42.2.5.jre6.jar
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/hsqldb-2.4.1.jar
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/mariadb-java-client-2.3.0.jar
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/jna-4.5.2.jar
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/h2-1.4.197.jar
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/mysql-connector-java-8.0.12.jar
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/sqlite-jdbc-3.23.1.jar
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/mssql-jdbc-7.0.0.jre8.jar
DEBUG: Adding location to classpath: /usr/src/flyway-5.2.4/drivers/jna-platform-4.5.2.jar
Flyway Community Edition 5.2.4 by Boxfuse
DEBUG: Memory usage: 7 of 39M
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to obtain connection from database (jdbc:mysql://localhost:3306/relay_test?serverTimezone=EST) for user 'root': Access denied for user 'root'@'localhost'
----------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 28000
Error Code : 1698
Message    : Access denied for user 'root'@'localhost'

	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1670)
	at org.flywaydb.core.Flyway.repair(Flyway.java:1566)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:174)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:129)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:832)
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:456)
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:240)
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:207)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:433)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:399)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
	... 5 more
```

**Comment by axelfontaine** [comment]
This is either a config or a server configuration issue. Flyway passes your credentials as-is to the database.

**Comment by crissacandler** [comment]
Thank you  @axelfontaine  for replying! 

Would you possibly know what a good config would be for using it with mysql?
We are following the installation and setup exactly for both mysql and flyway. 
 I have combed through documentation  a couple of times as well as using the suggestions left by others in another similar post.

 Any way you could point me to what that would be like specifically for mysql. My team has been working on this for a couple of days now. Any direction would be appreciated.
 
I would love to know what conditions you all are testing flyway with. 
We are able to put in our credentials as is when doing it straight from the command line.

**Comment by crissacandler** [comment]
The name of the other similar post === > Valid MySQL accounts cannot login via Flyway #2000
