### ISSUE TITLE
SQLPlusDefineSqlStatement should not depend on SLF4J

### ISSUE THREAD

**Issue by Me1gireesh** [flyway/flyway#2368]
###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

**Comment by Me1gireesh** [comment]
I am seeing the below exceptions while adding a callback script on the file path.

Flyway Enterprise Edition (trial) 5.2.4 by Boxfuse licensed to Dell until 2019-04-04
ERROR: Your 30 day limited Flyway trial license has expired and is no longer valid. You must upgrade to a full Flyway Enterprise Edition license immediately to keep on using this software.
Database: jdbc:oracle:thin:@My database URL (Oracle 12.1)
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.flywaydb.core.internal.database.oracle.pro.SQLPlusDefineSqlStatement.<clinit>(SQLPlusDefineSqlStatement.java:34)
	at org.flywaydb.core.internal.database.oracle.OracleSqlStatementBuilder.getSqlStatement(OracleSqlStatementBuilder.java:191)
	at org.flywaydb.core.internal.sqlscript.SqlScript.addStatement(SqlScript.java:152)
	at org.flywaydb.core.internal.sqlscript.SqlScript.extractStatements(SqlScript.java:138)
	at org.flywaydb.core.internal.sqlscript.SqlScript.<init>(SqlScript.java:86)
	at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory.<init>(SqlScriptCallbackFactory.java:87)
	at org.flywaydb.core.Flyway.prepareCallbacks(Flyway.java:1808)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1705)
	at org.flywaydb.core.Flyway.repair(Flyway.java:1566)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:174)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
Flyway Enterprise Edition (trial) 5.2.4 by Boxfuse licensed to Dell until 2019-04-04
ERROR: Your 30 day limited Flyway trial license has expired and is no longer valid. You must upgrade to a full Flyway Enterprise Edition license immediately to keep on using this software.
Database: jdbc:oracle:thin:@My datbase URL (Oracle 12.1)
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.flywaydb.core.internal.database.oracle.pro.SQLPlusDefineSqlStatement.<clinit>(SQLPlusDefineSqlStatement.java:34)
	at org.flywaydb.core.internal.database.oracle.OracleSqlStatementBuilder.getSqlStatement(OracleSqlStatementBuilder.java:191)
	at org.flywaydb.core.internal.sqlscript.SqlScript.addStatement(SqlScript.java:152)
	at org.flywaydb.core.internal.sqlscript.SqlScript.extractStatements(SqlScript.java:138)
	at org.flywaydb.core.internal.sqlscript.SqlScript.<init>(SqlScript.java:86)
	at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory.<init>(SqlScriptCallbackFactory.java:87)
	at org.flywaydb.core.Flyway.prepareCallbacks(Flyway.java:1808)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1705)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
Flyway Enterprise Edition (trial) 5.2.4 by Boxfuse licensed to Dell until 2019-04-04
ERROR: Your 30 day limited Flyway trial license has expired and is no longer valid. You must upgrade to a full Flyway Enterprise Edition license immediately to keep on using this software.
Database: jdbc:oracle:thin:@Mydatabase url (Oracle 12.1)
Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
	at org.flywaydb.core.internal.database.oracle.pro.SQLPlusDefineSqlStatement.<clinit>(SQLPlusDefineSqlStatement.java:34)
	at org.flywaydb.core.internal.database.oracle.OracleSqlStatementBuilder.getSqlStatement(OracleSqlStatementBuilder.java:191)
	at org.flywaydb.core.internal.sqlscript.SqlScript.addStatement(SqlScript.java:152)
	at org.flywaydb.core.internal.sqlscript.SqlScript.extractStatements(SqlScript.java:138)
	at org.flywaydb.core.internal.sqlscript.SqlScript.<init>(SqlScript.java:86)
	at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory.<init>(SqlScriptCallbackFactory.java:87)
	at org.flywaydb.core.Flyway.prepareCallbacks(Flyway.java:1808)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1705)
	at org.flywaydb.core.Flyway.info(Flyway.java:1521)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:167)
	at org.flywaydb.commandline.Main.main(Main.java:108)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more

**Comment by axelfontaine** [comment]
Thanks for reporting. Arrgh! It appears a SLF4J dependency inadvertently sneaked into the `SQLPlusDefineSqlStatement` class. Fixed.

**Comment by axelfontaine** [comment]
Possible workarounds:
- Do not use DEFINE statement (may not be possible)
- Add [SLF4J](https://search.maven.org/remotecontent?filepath=org/slf4j/slf4j-api/1.7.26/slf4j-api-1.7.26.jar) to the jars directory of your Flyway installation (probably the best choice)

**Comment by Me1gireesh** [comment]
I added the jar slf4j-api-1.7.26.jar, which in turn needed another dependency slf4j-simple-1.7.2.jar.
Now the callbacks are working fine.
