### ISSUE TITLE
Unable to install uuid-ossp extention function in Postgresql

### ISSUE THREAD

**Issue by bensullivan** [flyway/flyway#2373]
###### Which version and edition of Flyway are you using?
6.0.0-beta

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
Postgres 11.2

###### Which operating system are you using?
(Debian 11.2-1.pgdg90+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
Tried to run this migration:
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

create table PERSON (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
    name TEXT not null
);

###### What did you expect to see?
Successful table creation

###### What did you see instead?
```
[main] ERROR org.flywaydb.core.internal.command.DbMigrate - Migration of schema "coreillumination" to version 1 - Create person table failed! Changes successfully rolled back.
Exception in thread "main" org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V1__Create_person_table.sql failed
--------------------------------------------
SQL State  : 42883
Error Code : 0
Message    : ERROR: function uuid_generate_v1mc() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
Location   : db/migration/V1__Create_person_table.sql (/Users/bensullivan/work/spmi/out/production/resources/db/migration/V1__Create_person_table.sql)
Line       : 3
Statement  : create table PERSON (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
    name TEXT not null
)

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:370)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:284)
	at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:281)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:164)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:161)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:71)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:104)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:155)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:161)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:139)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:175)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:136)
	at org.flywaydb.core.Flyway.execute(Flyway.java:453)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:136)
	at com.coreillumination.spmi.main.Main.main(Main.java:61)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: 
Migration V1__Create_person_table.sql failed
--------------------------------------------
SQL State  : 42883
Error Code : 0
Message    : ERROR: function uuid_generate_v1mc() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
Location   : db/migration/V1__Create_person_table.sql (/Users/bensullivan/work/spmi/out/production/resources/db/migration/V1__Create_person_table.sql)
Line       : 3
Statement  : create table PERSON (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
    name TEXT not null
)

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:268)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:215)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:122)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:77)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:367)
	... 18 more
Caused by: org.postgresql.util.PSQLException: ERROR: function uuid_generate_v1mc() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2183)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:308)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:441)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:365)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:307)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:293)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:270)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:266)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:235)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:203)
	... 21 more

**Comment by bensullivan** [comment]
I can run the DDL through sql client and it's OK - for some reason the extension installation is not being picked up by the create table statement.  I'm assuming that both statements target the same DB - is that the case?

**Comment by axelfontaine** [comment]
This should work with any issues. Can you inspect the debug output or debug through to see if any kind of warning gets returned by the database?

**Comment by bensullivan** [comment]
Yeah - looks like the extension is installed for the DB:

```[main] WARN org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor - DB: extension "uuid-ossp" already exists, skipping (SQL State: 42710 - Error Code: 0)```

**Comment by bensullivan** [comment]
But then the call to the function I need in the extension fails...

```SQL State  : 42883
Error Code : 0
Message    : ERROR: function uuid_generate_v1mc() does not exist
  Hint: No function matches the given name and argument types. You might need to add explicit type casts.
Location   : db/migration/V1__Create_person_table.sql (/Users/bensullivan/work/spmi/out/production/resources/db/migration/V1__Create_person_table.sql)
Line       : 3
Statement  : create table PERSON (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v1mc(),
    name TEXT not null
```

**Comment by axelfontaine** [comment]
Then this could point at your user not having access to its objects or not having to the public schema on the search_path.

**Comment by bensullivan** [comment]
AAhh right - I closed off access to the public schema to lock my installation down....

**Comment by bensullivan** [comment]
Many thanks!
