### ISSUE TITLE
Flyway fails as SQLDroid misreports SQLite version as 0.0

### ISSUE THREAD

**Issue by beyondlov1** [flyway/flyway#2409]
###### Which version and edition of Flyway are you using?
5.2.4 or 6.0.0-beta2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Android, Gradle plugin

###### Which database are you using (type & version)?
sqlite 3.9.2

###### Which operating system are you using?
ubuntu 18.04

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I use flyway on Android, but it complaines the version of my sqlite. This is the code:
```
DroidDataSource dataSource = new DroidDataSource(getPackageName(), "test.db");
        ContextHolder.setContext(this);
        Flyway flyway = Flyway.configure()
                .dataSource(dataSource)
                .baselineOnMigrate(true)
                .load();
        flyway.migrate();
```

gradle:

```
    implementation 'org.flywaydb:flyway-core:6.0.0-beta2'
    implementation 'org.sqldroid:sqldroid:1.1.0-rc1'
```

###### What did you see instead?
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.beyond.note5, PID: 14720
    java.lang.RuntimeException: Unable to create application com.beyond.note5.MyApplication: org.flywaydb.core.internal.exception.FlywayDbUpgradeRequiredException: SQLite upgrade required: SQLite 0.0 is outdated and no longer supported by Flyway. Flyway currently supports SQLite 3.0 and newer.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5501)
        at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:360)
        at android.app.ActivityThread.handleBindApplication(<Xposed>)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1575)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6236)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:891)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:781)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
     Caused by: org.flywaydb.core.internal.exception.FlywayDbUpgradeRequiredException: SQLite upgrade required: SQLite 0.0 is outdated and no longer supported by Flyway. Flyway currently supports SQLite 3.0 and newer.
        at org.flywaydb.core.internal.database.base.Database.ensureDatabaseIsRecentEnough(Database.java:151)
        at org.flywaydb.core.internal.database.sqlite.SQLiteDatabase.ensureSupported(SQLiteDatabase.java:54)
        at org.flywaydb.core.Flyway.execute(Flyway.java:488)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:142)
```

**Comment by axelfontaine** [comment]
Thank you very much for reporting. Arrgghh these SQLite JDBC drivers are really hit and miss! We have removed the check. Could you file an issue with SQLDroid, so they actually fix this in the future?

**Comment by jeffque** [comment]
As this is not yet published (and I needed it, like, for yesterday), I have workedaround like this:

```java

  private void createDatasource(String dbName) {
    DroidDataSource dds = new DroidDataSource(PACKAGE_NAME, dbName);
    // DataSourceHasFilename extends DataSource + getDbFilename method
    this.sds = (DataSourceHasFilename) Proxy.newProxyInstance(this.getClass().getClassLoader(), new Class[] {DataSourceHasFilename.class }, (proxy, method, args) -> {
      switch (method.getName()) {
      case "getDbFilename": //ignore this, I need this method to open the same database in a Flutter app
        return "/data/data/" + dds.getPackageName() + "/" + dds.getDatabaseName() + ".db";
      case "getConnection": // wrapping the connection to wrap the databasemetadata object
        return connWrapper((Connection) method.invoke(dds, args));
      }
      return method.invoke(dds, args);
    });

    getTenantFlywayConf(sds).migrate();
  }

  public Connection connWrapper(Connection c) {
    return (Connection) Proxy.newProxyInstance(this.getClass().getClassLoader(), new Class[] { Connection.class }, (proxy, method, args) -> {
      switch (method.getName()) {
      case "getMetaData": // wrapping the databasemetadata
        return metadataWrapper((DatabaseMetaData) method.invoke(c, args));
      }
      return method.invoke(c, args);
    });
  }

  public DatabaseMetaData metadataWrapper(DatabaseMetaData dmd) {
    return (DatabaseMetaData) Proxy.newProxyInstance(this.getClass().getClassLoader(), new Class[] { DatabaseMetaData.class }, (proxy, method, args) -> {
      switch (method.getName()) {
      case "getDatabaseMajorVersion": // faking the results =D
        return 3;
      case "getDatabaseMinorVersion":
        return 7;
      }
      return method.invoke(dmd, args);
    });
  }

  public static Flyway getTenantFlywayConf(DataSource ds) {
    return Flyway.configure()
        .dataSource(ds)
        .target(MigrationVersion.LATEST)
        .baselineOnMigrate(true)
        .baselineVersion(MigrationVersion.fromVersion("0"))
        .load();
  }
```
