### ISSUE TITLE
Class Slf4jLogCreator not found

### ISSUE THREAD

**Issue by lusu007** [flyway/flyway#2463]
###### Which version and edition of Flyway are you using?
5.2.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
n/a

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
PostgreSQL 

###### Which operating system are you using?
Windows

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
```   
public DatabaseMigration(final Properties properties) {
        this.flyway = Flyway.configure()
                .locations(properties.getProperty("migration.folder"))
                .dataSource(String.format(url,
                        properties.getProperty("database.hostname"),
                        properties.getProperty("database.port"),
                        properties.getProperty("database.database-name")),
                        properties.getProperty("database.username"),
                        properties.getProperty("database.password"))
                .load();
}
```

###### What did you expect to see?
I expect to see no error in console and I want to execute 
`flyway.migrate();` afterwards.

###### What did you see instead?
```[15:12:58 ERROR]: Error occurred while enabling LegendDatabase v3c8854e-dev (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at org.flywaydb.core.internal.util.FeatureDetector.isSlf4jAvailable(FeatureDetector.java:96) ~[?:?]
        at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:39) ~[?:?]
        at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78) ~[?:?]
        at org.flywaydb.core.internal.util.FeatureDetector.<clinit>(FeatureDetector.java:25) ~[?:?]
        at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:35) ~[?:?]
        at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78) ~[?:?]
        at org.flywaydb.core.Flyway.<clinit>(Flyway.java:86) ~[?:?]
        at net.playlegend.legenddatabase.migration.DatabaseMigration.<init>(DatabaseMigration.java:28) ~[?:?]
        at net.playlegend.legenddatabase.LegendDatabasePlugin.onEnable(LegendDatabasePlugin.java:36) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-162]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-162]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-162]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-162]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-162]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.reload(CraftServer.java:859) ~[patched_1.14.4.jar:git-Paper-162]
        at org.bukkit.Bukkit.reload(Bukkit.java:610) ~[patched_1.14.4.jar:git-Paper-162]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[patched_1.14.4.jar:git-Paper-162]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159) ~[patched_1.14.4.jar:git-Paper-162]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:739) ~[patched_1.14.4.jar:git-Paper-162]
        at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchServerCommand(CraftServer.java:701) ~[patched_1.14.4.jar:git-Paper-162]
        at net.minecraft.server.v1_14_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:456) ~[patched_1.14.4.jar:git-Paper-162]
        at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.4.jar:git-Paper-162]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-162]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-162]
        at java.lang.Thread.run(Thread.java:835) [?:?]
Caused by: org.flywaydb.core.api.FlywayException: Unable to instantiate class org.flywaydb.core.internal.logging.slf4j.Slf4jLogCreator : org.flywaydb.core.internal.logging.slf4j.Slf4jLogCreator
        at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:63) ~[?:?]
        at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:40) ~[?:?]
        at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78) ~[?:?]
        at org.flywaydb.core.internal.util.ClassUtils.<clinit>(ClassUtils.java:39) ~[?:?]
        ... 25 more
Caused by: java.lang.ClassNotFoundException: org.flywaydb.core.internal.logging.slf4j.Slf4jLogCreator
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:?]
        at java.lang.Class.forName(Class.java:415) ~[?:?]
        at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:61) ~[?:?]
        at org.flywaydb.core.internal.logging.LogCreatorFactory.getLogCreator(LogCreatorFactory.java:40) ~[?:?]
        at org.flywaydb.core.api.logging.LogFactory.getLog(LogFactory.java:78) ~[?:?]
        at org.flywaydb.core.internal.util.ClassUtils.<clinit>(ClassUtils.java:39) ~[?:?]
        ... 25 more
```

Line 28 in Class DatabaseMigration is `this.flyway = Flyway.configure() ....`

**Comment by lusu007** [comment]
Fixed it by adding `LogFactory.setLogCreator(new JavaUtilLogCreator());`
