### ISSUE TITLE
H2 support removed by mistake?

### ISSUE THREAD

**Issue by terje2001** [flyway/flyway#2467]
###### Which version and edition of Flyway are you using?
6.0.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
n/a

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
H2

###### Which operating system are you using?
Linux

###### What did you do?
Upgrade Flyway to 6.0.0

###### What did you expect to see?
No issues

###### What did you see instead?
Exception:
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: H2
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:226) ~[flyway-core-6.0.0.jar:?]
	at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:107) ~[flyway-core-6.0.0.jar:?]
	at org.flywaydb.core.Flyway.execute(Flyway.java:472) ~[flyway-core-6.0.0.jar:?]
	at org.flywaydb.core.Flyway.clean(Flyway.java:285) ~[flyway-core-6.0.0.jar:?]

=> Think the commit f9bd09b70249acfa380e698b7491b41b9b1d57f7 removed H2 support in DatabaseFactory.java by mistake.

**Comment by juliahayward** [comment]
A code fix is being pushed asap, and will go in a 6.0.1 release very soon.

**Comment by loicknuchel** [comment]
Thanks for the reply, any ETA for 6.0.1 ?
Thanks!

**Comment by juliahayward** [comment]
We intend it to be Tuesday next week (Monday is a national holiday).
