### ISSUE TITLE
Oracle 19.3 driver problem on Linux

### ISSUE THREAD

**Issue by juliahayward** [flyway/flyway#2513]
According to https://medium.com/@kuassimensah/oracle-jdbc-drivers-on-maven-central-64fcf724d8b the Oracle JDBC driver and associated jars are now available on Maven Central. We will check that they are now redistributable, and if so include them by default.

**Comment by juliahayward** [comment]
I'm going to put this on hold for now as there's a problem with the 19.3 drivers we have yet to solve. Specifically against a 19.3 database, everything is fine on Windows but on our build server and on WSL with OpenJdk 11.0.3, we can't get a connection:

```
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to obtain connection from database (jdbc:oracle:thin:@//localhost:62064/ORCLPDB1) for user 'pdbadmin': IO Error: Invalid argument, Authentication lapse 0 ms.
--------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08006
Error Code : 17002
Message    : IO Error: Invalid argument, Authentication lapse 0 ms.

        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:80)
        at org.flywaydb.core.Flyway.execute(Flyway.java:431)
        at org.flywaydb.core.Flyway.info(Flyway.java:307)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:170)
        at org.flywaydb.commandline.Main.main(Main.java:111)
Caused by: java.sql.SQLRecoverableException: IO Error: Invalid argument, Authentication lapse 0 ms.
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:874)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:793)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:57)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:747)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:562)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:447)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:413)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
        ... 5 more
Caused by: java.io.IOException: Invalid argument, Authentication lapse 0 ms.
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:870)
        ... 12 more
Caused by: java.io.IOException: Invalid argument
        at java.base/sun.nio.ch.SocketChannelImpl.sendOutOfBandData(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.sendOutOfBandData(SocketChannelImpl.java:521)
        at java.base/sun.nio.ch.SocketAdaptor.sendUrgentData(SocketAdaptor.java:323)
        at oracle.net.nt.TcpNTAdapter.sendUrgentByte(TcpNTAdapter.java:433)
        at oracle.net.ns.NSProtocolNIO.negotiateConnection(NSProtocolNIO.java:159)
        at oracle.net.ns.NSProtocol.connect(NSProtocol.java:340)
        at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1596)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:588)
        ... 12 more
```

**Comment by juliahayward** [comment]
Not the best of answers, but ojdbc10.jar may be a solution for higher JDKs (clearly we need ojdbc8 for compatibility with older ones)

**Comment by juliahayward** [comment]
Had another answer on SO and this time it is good. Disabling out-of-band-break is harmless with the 18.3 driver, and Flyway works as expected with the 19.6 driver.  https://stackoverflow.com/questions/58319173/cant-connect-to-oracle-19-3-with-19-3-jdbc-driver/62078980#62078980
