### ISSUE TITLE
About errors that occur in [PostgreSQL11.5 + flyway6.0.4]

### ISSUE THREAD

**Issue by gaku3601** [flyway/flyway#2524]
###### Which version and edition of Flyway are you using?

org.flywaydb:flyway-core:6.0.4

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This is the current version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

I use maven plugin.
and I use org.springframework.boot:spring-boot-starter-web:1.5.20.RELEASE.

###### Which database are you using (type & version)?

I am using PostgreSQL11.5.

###### Which operating system are you using?

I use win10.

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

I am using spring-boot and I use maven to use flyway.
When using PostgreSQL11.5 in this situation, the following error occurs.

```
Caused by: java.lang.NoSuchMethodError: org.flywaydb.core.Flyway: method <init>()V not found
    at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$SpringBootFlyway.<init>(FlywayAutoConfiguration.java:190)
    at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$SpringBootFlyway.<init>(FlywayAutoConfiguration.java:190)
    at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.flyway(FlywayAutoConfiguration.java:134)
    at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration$$EnhancerBySpringCGLIB$$10d426d7.CGLIB$flyway$2(<generated>)
    at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration$$EnhancerBySpringCGLIB$$10d426d7$$FastClassBySpringCGLIB$$b2960e84.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
    at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration$$EnhancerBySpringCGLIB$$10d426d7.flyway(<generated>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
    ... 112 common frames omitted
```

###### What did you expect to see?

I am suffering from this error.
I saw an article that downgrading postgresql resolves this error.
But My PJ needs to use PostgreSQL11.5.

Please let me know if there is a way to solve it.

Thank you.

###### What did you see instead?
https://stackoverflow.com/questions/58119945/flyway-with-spring-boot-and-gradle-org-flywaydb-core-flyway-method-initv-n
https://github.com/flyway/flyway/issues/2193

**Comment by MikielAgutu** [comment]
It looks like only Spring Boot 2.2+ supports Flyway. [See this comment](https://github.com/spring-projects/spring-boot/issues/18483).

Can you wait for the Spring Boot 2.2 release (from that comment it looks like it's coming soon), and try that?

**Comment by gaku3601** [comment]
@MikielAgutu 

Thank you for your reply!
Our PJ cannot update Spring Boot from 1 to 2.
So, I wish you to 'flyway6.x' to be available on 'spring boot1.x'.

I understood the situation.
I will close this issue.
