### ISSUE TITLE
flyway failing while trying to connect to oracle via secure ldap

### ISSUE THREAD

**Issue by kausku** [flyway/flyway#2526]
Please refer to issue #2521 for a background.

Test 1:
gradle version - 4.10
Java version - 8.212
flyway (and flyway gradle plugin) version - 4.0.3
DB - oracle version 12.1
oracle driver used - ojdbc8:12.2.0.2.jar
url used - jdbc:oracle:thin:@ldaps://host:port/tns,CN=OracleContext,dc=name,dc=com
command used - ./gradlew -Doracle.net.ldap.ssl.supportedVersions=TLSv1.2  flywayInfo

Result: works fine and as expected 

Test 2:
gradle version - 5.6.2
Java version - 11.0.4
flyway (and flyway gradle plugin) version - 5.1.4
DB - (same as test 1)
oracle driver used - (same as test 1)
url used - (same as test 1)
command used - (same as test 1)

Result: throws an error
error:
SQL State : 08006
Error Code : 17002
Message : IO Error: JNDI Package failure javax.naming.CommunicationException: : [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]

    at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
    at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
    at org.flywaydb.core.Flyway.execute(Flyway.java:1670)
    at org.flywaydb.core.Flyway.info(Flyway.java:1521)
    at org.flywaydb.gradle.task.FlywayInfoTask.run(FlywayInfoTask.java:32)
    at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:489)
    .....
    Caused by: java.sql.SQLRecoverableException: IO Error: JNDI Package failure javax.naming.CommunicationException: <host>:<port> [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]
    at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:774)
    at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
    at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
    at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
    at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:433)
    at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:399)
    at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
    .....
    Caused by: oracle.net.ns.NetException: JNDI Package failure javax.naming.CommunicationException: <host>:<port> [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]
    at oracle.net.jndi.JndiAttrs.initializeLDAPContext(JndiAttrs.java:183)
    at oracle.net.jndi.JndiAttrs.<init>(JndiAttrs.java:162)
    at oracle.net.resolver.AddrResolution.<init>(AddrResolution.java:233)
    at oracle.net.ns.NSProtocol.connect(NSProtocol.java:233)
    at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1474)
    at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)
    .....
    Caused by: javax.naming.CommunicationException: <host>:<port> [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]
    at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:237)
    at java.naming/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
    at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1610)
    at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2752)
    at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:320)
    at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
    at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
    at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
    at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
    at oracle.net.jndi.JndiAttrs.initializeLDAPContext(JndiAttrs.java:175)
    ....
    Caused by: java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory
    at java.naming/com.sun.jndi.ldap.VersionHelper.loadClass(VersionHelper.java:76)
    at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:275)
    at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:216)

**Comment by kausku** [comment]
Additional Info: 
I tried the same tests using the command line tool and manually installing ojdbc8:12.2.0.2.jar as the driver.
Got an error saying - Could not load the driver.
Here again non SSL ldap url works just fine.

**Comment by kausku** [comment]
any chances of this being worked on anytime soon? considering the fact that we are not able to establish SSL connections with the database for flyway operations is a big security concern

**Comment by MikielAgutu** [comment]
These tests were run using a fairly old version of Flyway now. Could you try with V7?

There's some documentation on SSL support that might be helpful too: https://flywaydb.org/documentation/ssl

When using the flyway command line it's possible to append your own JVM properties when Flyway uses Java. You can use the JAVA_ARGS environment variable https://flywaydb.org/documentation/commandline/#java-arguments. This way perhaps you can try setting `oracle.net.ldap.ssl.supportedVersions` as you said in your previous comment: https://github.com/flyway/flyway/issues/2521#issuecomment-538049806

**Comment by MikielAgutu** [comment]
Closing for lack of response.
