### ISSUE TITLE
Schema#toString() causes NPE

### ISSUE THREAD

**Issue by vy** [flyway/flyway#2718]
Using Flyway 6.3.0 community edition against `postgres:9.6-alpine` Docker image, the following snippet:

```java
Flyway
        .configure()
        .locations("classpath:/flyway")
        .dataSource(dataSource)
        .baselineOnMigrate(true)
        .baselineVersion("000")
        .schemas("foo")
        .load()
        .migrate();
```

causes this NPE:

```
Caused by: java.lang.NullPointerException
	at org.flywaydb.core.internal.util.StringUtils.replaceAll(StringUtils.java:154)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLDatabase.pgQuote(PostgreSQLDatabase.java:131)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLDatabase.doQuote(PostgreSQLDatabase.java:127)
	at org.flywaydb.core.internal.database.base.Database.quote(Database.java:280)
	at org.flywaydb.core.internal.database.base.Schema.toString(Schema.java:267)
	at java.lang.String.valueOf(String.java:2994)
	at java.lang.StringBuilder.append(StringBuilder.java:131)
	at org.flywaydb.core.internal.command.DbSchemas$1.call(DbSchemas.java:85)
	at org.flywaydb.core.internal.command.DbSchemas$1.call(DbSchemas.java:79)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.command.DbSchemas.create(DbSchemas.java:79)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:187)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:153)
	at org.flywaydb.core.Flyway.execute(Flyway.java:523)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:153)
```

The host is a Xubuntu 18.04.4 LTS box running AdoptOpenJDK (build 1.8.0_242-b08).

**Comment by juliahayward** [comment]
I'm not able to reproduce this. Do you have a logging framework (eg. logback, log4j) available to do a full debug-level log which might throw more light on it?

**Comment by vy** [comment]
Thanks for taking time to check the issue @juliahayward. Due to Corona, I can barely spare some extra computer time next to my day job halved by babysitting sessions. Hence, I could not bisect in the code base to spot the state yielding the error. Though what I can comment on is, an `Object#toString()` method should not throw an NPE anyway. As far as I can trace back from the stacktrace, `Schema#toString()` reaches out to a set of methods where the passed parameter (in this case `schema`, I guess) is null. What about making `StringUtils.replaceAll` null-proof?

**Comment by juliahayward** [comment]
As far as I can determine, the only way that `Schema.toString()` can NPE is if the schema name is null, and that should be impossible (as you've set the schema name in `... .schemas("foo")`. If Flyway has managed to get into an invalid state then failing as soon as that comes to light has the fewest bad side effects - there's no sensible response `Schema.toString()` could give other than an exception of some sort.
