### ISSUE TITLE
Block depth below 0 error in version 6.3.2

### ISSUE THREAD

**Issue by mpittau-kiwipower** [flyway/flyway#2749]
###### Which version and edition of Flyway are you using?
6.3.2
```
2020-03-30 16:24:33.857 [ioapp-compute-0]                    I o.f.c.i.license.VersionPrinter      Flyway Community Edition 6.3.2 by Redgate
```

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
MySQL (ver. 5.7.27)
```
2020-03-30 16:24:33.911 [ioapp-compute-0]                    I o.f.c.i.database.DatabaseFactory    Database: jdbc:mysql://localhost/db (MySQL 5.7)
```

###### Which operating system are you using?
OSx

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
After upgrading from version 5.2.x, running a simple migration fails:
```
ALTER TABLE acceptance DROP COLUMN participant_id;
ALTER TABLE acceptance ADD end TIMESTAMP NOT NULL;
```

###### What did you expect to see?
The migration being applied successfully

###### What did you see instead?
```
org.flywaydb.core.api.FlywayException: Unable to parse statement in db/migration/V80__AcceptanceTable.sql at line 2 col 1: Flyway parsing bug: unable to decrease block depth below 0
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:287)
	at org.flywaydb.core.internal.parser.Parser.access$000(Parser.java:41)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:712)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:677)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:82)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:127)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.executeInTransaction(ParserSqlScript.java:196)
```

Similar to #2720?

**Comment by Lyeeedar** [comment]
This bug occurred because the column you have added is called 'end'. The current flyway sql parser assumes that anytime you have end, it is to close a block. We currently do not support objects named like this.

See https://github.com/flyway/flyway/issues/2703 for a similar issue.
