### ISSUE TITLE
unable to decrease block depth below 0

### ISSUE THREAD

**Issue by austek** [flyway/flyway#2768]
###### Which version and edition of Flyway are you using?
6.3.3, this problem doesn't occur on 6.3.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using (type & version)?
MySQL 5.7.27

###### Which operating system are you using?
Mac OSX

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
run migrate
```
#-------------- FIX SCHEMA CHARSET AND COLLATION ------------------------
DROP procedure if exists update_schema_char_set;
DELIMITER $$

CREATE PROCEDURE update_schema_char_set()
  BEGIN
      IF (@@character_set_database != 'utf8mb4' OR @@collation_database != 'utf8mb4_unicode_ci') THEN
        ALTER DATABASE ${SM_VISITS_DB_NAME} CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
      END IF;
  END$$

DELIMITER ;

CALL update_schema_char_set();
DROP procedure if exists update_schema_char_set;

 #-------------- FIX TABLE CHARSET AND COLLATION ------------------------
DROP procedure if exists update_table_char_set;

DELIMITER $$
CREATE PROCEDURE update_table_char_set()
  BEGIN
    DECLARE done INTEGER DEFAULT 0;
    DECLARE tableName VARCHAR(128);
    DECLARE table_cursor CURSOR FOR SELECT TABLE_NAME
                                    FROM `information_schema`.`TABLES`
                                    WHERE table_schema = '${SM_VISITS_DB_NAME}'
                                      AND TABLE_TYPE = 'BASE TABLE'
                                      AND TABLE_COLLATION != 'utf8mb4_unicode_ci';
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done = 1;
    OPEN table_cursor;
    SET FOREIGN_KEY_CHECKS = 0;
    read_loop: LOOP
      FETCH table_cursor
      INTO tableName;
      IF done
      THEN
        LEAVE read_loop;
      END IF;
      SET @t_sql = CONCAT('ALTER TABLE ', tableName, ' CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
      PREPARE stmt FROM @t_sql;
      EXECUTE stmt;
      DEALLOCATE PREPARE stmt;
    END LOOP read_loop;
    SET FOREIGN_KEY_CHECKS = 1;
    CLOSE table_cursor;
  END$$

DELIMITER ;

CALL update_table_char_set();
DROP procedure if exists update_table_char_set;
```

###### What did you expect to see?
Migration to be run succesfuly

###### What did you see instead?
```
[info] org.flywaydb.core.api.FlywayException: Unable to parse statement in db/migration/visits/beforeMigrate.sql at line 5 col 1: Flyway parsing bug: unable to decrease block depth below 0
[info]  at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:288)
[info]  at org.flywaydb.core.internal.parser.Parser.access$000(Parser.java:41)
[info]  at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:713)
[info]  at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:678)
[info]  at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:82)
[info]  at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:127)
[info]  at org.flywaydb.core.internal.sqlscript.ParserSqlScript.executeInTransaction(ParserSqlScript.java:196)
[info]  at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory$SqlScriptCallback.canHandleInTransaction(SqlScriptCallbackFactory.java:127)
[info]  at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.execute(DefaultCallbackExecutor.java:103)
[info]  at org.flywaydb.core.internal.callback.DefaultCallbackExecutor.onMigrateOrUndoEvent(DefaultCallbackExecutor.java:67)
[info] Caused by: org.flywaydb.core.api.FlywayException: Flyway parsing bug: unable to decrease block depth below 0
[info]  at org.flywaydb.core.internal.parser.ParserContext.decreaseBlockDepth(ParserContext.java:51)
[info]  at org.flywaydb.core.internal.database.mysql.MySQLParser.adjustBlockDepth(MySQLParser.java:128)
[info]  at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:203)
[info]  at org.flywaydb.core.internal.parser.Parser.access$000(Parser.java:41)
[info]  at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:713)
[info]  at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:678)
[info]  at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:82)
[info]  at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:127)
[info]  at org.flywaydb.core.internal.sqlscript.ParserSqlScript.executeInTransaction(ParserSqlScript.java:196)
[info]  at org.flywaydb.core.internal.callback.SqlScriptCallbackFactory$SqlScriptCallback.canHandleInTransaction(SqlScriptCallbackFactory.java:127)
[error] Nonzero exit code returned from runner: 1
[error] (api / Compile / runMain) Nonzero exit code returned from runner: 1
[error] Total time: 18 s, completed Apr 12, 2020 9:43:43 PM
```

**Comment by Lyeeedar** [comment]
This should be fixed in https://github.com/flyway/flyway/commit/d956445c4d96fd19db3c64f6bc2945388ff24c13, which will be released in flyway 6.4
