### ISSUE TITLE
Flyway parsing bug: unable to decrease block depth below 0

### ISSUE THREAD

**Issue by ln0v** [flyway/flyway#2773]
###### Which version and edition of Flyway are you using?
6.3.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
command line

###### Which database are you using (type & version)?
MySQL 5.7

###### Which operating system are you using?
Centos 7

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
flyway migration for the sql file below:

```
DELIMITER $$
DROP PROCEDURE IF EXISTS formBillCalculationDetails$$
CREATE PROCEDURE `formBillCalculationDetails`(IN p_company_id INT,IN startTime VARCHAR(126),IN endTime VARCHAR(126))
proc:
BEGIN
  DECLARE v_bill_plan_id,v_bill_plan_details_id INT;
  DECLARE v_billAmount,v_cost_perForm DOUBLE DEFAULT 0.0;
  DECLARE v_primary_Identifier_name,v_primary_Identifier_value,
  DROP TEMPORARY TABLE IF EXISTS Invoice_Temporary_Table;

  CREATE TEMPORARY TABLE IF NOT EXISTS Invoice_Temporary_Table
                (service VARCHAR(128), totalSubmission INT, submissionFeePerForm DOUBLE, totalAmount DOUBLE);

  SELECT billPlan.id billPlanId INTO v_bill_plan_id
    FROM    tbl_form_billing_plan billPlan  INNER JOIN tbl_company_form_bill_mapping companyBillPlan
      ON companyBillPlan.billing_plan_id = billPlan.id WHERE companyBillPlan.company_id = p_company_id;
 IF (NULL = v_bill_plan_id)
 THEN LEAVE proc;
  END IF;

REPEAT
  proc2: BEGIN
  DECLARE curs CURSOR FOR
  SELECT dtl.identifier_name primaryIdentifierName,
        dtl.identifier_value primaryIdentifierValue
         WHERE dtl.bill_plan_id =v_bill_plan_id;
    OPEN curs;
 
     UNTIL done = TRUE
  END REPEAT;
 CLOSE curs;
  END;
      SELECT * FROM Invoice_Temporary_Table;
END$$

DELIMITER ;


```

###### What did you expect to see?
migration to work 

###### What did you see instead?

```
org.flywaydb.core.api.FlywayException: Unable to parse statement in /home/btctomcat/flyway/flyway-633/sql-BTCShowcase/V9.2__EOLV193_DL_CC.sql at line 4 col 1: Flyway parsing bug: unable to decrease block depth below 0
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:288)
	at org.flywaydb.core.internal.parser.Parser.access$000(Parser.java:41)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:713)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:678)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:82)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:127)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.executeInTransaction(ParserSqlScript.java:196)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.canExecuteInTransaction(SqlMigrationExecutor.java:93)
	at org.flywaydb.core.internal.command.DbMigrate.isExecuteGroupInTransaction(DbMigrate.java:312)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:275)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:161)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:199)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:159)
	at org.flywaydb.core.Flyway.execute(Flyway.java:530)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:159)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:192)
	at org.flywaydb.commandline.Main.main(Main.java:128)
```

seems like the above problem is related to #2772, wanted to document so that you have more use cases to make sure you fix covers all cases.

**Comment by MikielAgutu** [comment]
> seems like the above problem is related to #2772, wanted to document so that you have more use cases to make sure you fix covers all cases

Thanks for the extra information. I've manually tested against our unreleased 6.4 build and it looks like this'll be fixed alongside the other bug reports.
