### ISSUE TITLE
Azure SQL Data Warehouse:  On Baseline, 'Stored procedure sp_getapplock does not exist or is not supported'

### ISSUE THREAD

**Issue by MikielAgutu** [flyway/flyway#2806]
Originally posted https://github.com/flyway/flyway/issues/2021#issuecomment-611122295

Baseline Flyway with my Azure SQL Data Warehouse database.

```
flyway baseline
Flyway Community Edition 6.3.3 by Redgate
applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 12.0)

ERROR: Unable to release SQL Server application lock
com.microsoft.sqlserver.jdbc.SQLServerException: Stored procedure sp_releaseapplock does not exist or is not supported.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:256)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:592)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2930)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:503)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:224)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerApplicationLockTemplate.execute(SQLServerApplicationLockTemplate.java:76)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerConnection.lock(SQLServerConnection.java:96)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.create(JdbcTableSchemaHistory.java:97)
        at org.flywaydb.core.internal.command.DbBaseline.baseline(DbBaseline.java:77)
        at org.flywaydb.core.Flyway.doBaseline(Flyway.java:206)
        at org.flywaydb.core.Flyway.access$200(Flyway.java:74)
        at org.flywaydb.core.Flyway$5.execute(Flyway.java:352)
        at org.flywaydb.core.Flyway$5.execute(Flyway.java:344)
        at org.flywaydb.core.Flyway.execute(Flyway.java:530)
        at org.flywaydb.core.Flyway.baseline(Flyway.java:344)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:190)
        at org.flywaydb.commandline.Main.main(Main.java:128)
ERROR:
Unable to acquire SQL Server application lock

---------------------------------------------
SQL State  : S0001
Error Code : 104386
Message    : Stored procedure sp_getapplock does not exist or is not supported.
```

**Comment by DoodleBobBuffPants** [comment]
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).

**Comment by we814** [comment]
> This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).

I get the same error in V7 beta, attempting baseline command.

Flyway Community Edition 7.0.0-beta1 by Redgate
applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 12.0)
ERROR: Unable to release SQL Server application lock
com.microsoft.sqlserver.jdbc.SQLServerException: Stored procedure sp_releaseapplock does not exist or is not supported.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:256)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:592)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2930)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:503)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:222)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerApplicationLockTemplate.execute(SQLServerApplicationLockTemplate.java:76)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerConnection.lock(SQLServerConnection.java:96)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.create(JdbcTableSchemaHistory.java:98)
        at org.flywaydb.core.internal.command.DbBaseline.baseline(DbBaseline.java:77)
        at org.flywaydb.core.Flyway.doBaseline(Flyway.java:214)
        at org.flywaydb.core.Flyway.access$200(Flyway.java:74)
        at org.flywaydb.core.Flyway$5.execute(Flyway.java:355)
        at org.flywaydb.core.Flyway$5.execute(Flyway.java:342)
        at org.flywaydb.core.Flyway.execute(Flyway.java:501)
        at org.flywaydb.core.Flyway.baseline(Flyway.java:342)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:220)
        at org.flywaydb.commandline.Main.main(Main.java:151)
ERROR:
Unable to acquire SQL Server application lock
---------------------------------------------
SQL State  : S0001
Error Code : 104386
Message    : Stored procedure sp_getapplock does not exist or is not supported.

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Stored procedure sp_getapplock does not exist or is not supported.
