### ISSUE TITLE
FlywayDB is unable to find postgresql driver

### ISSUE THREAD

**Issue by ctooley21** [flyway/flyway#2815]
###### Which version and edition of Flyway are you using?

flyway version 6.4.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

latest :)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle plugin

###### Which database are you using (type & version)?

PostgreSQL version 42.2.12

###### Which operating system are you using?

Centos 7 for running, Compiling on windows 10

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

```java
Flyway flyway = Flyway.configure().dataSource(getJdbcString(), DATABASE_USERNAME, DATABASE_PASSWORD).load();
flyway.migrate();
```
The first line triggers the following error:
```
[10:37:14 WARN]: org.flywaydb.core.api.FlywayException: Unable to instantiate JDBC driver: org.postgresql.Driver => Check whether the jar file is present
[10:37:14 WARN]:        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:180)
[10:37:14 WARN]:        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:144)
[10:37:14 WARN]:        at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1341)
[10:37:14 WARN]:        at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:803)
[10:37:14 WARN]:        at com.mclockup.core.database.SqlWrapper.<init>(SqlWrapper.java:42)
[10:37:14 WARN]:        at com.mclockup.core.database.SqlWrapper.initialize(SqlWrapper.java:78)
[10:37:14 WARN]:        at com.mclockup.core.LockupCore.onEnable(LockupCore.java:22)
[10:37:14 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[10:37:14 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337)
[10:37:14 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:435)
[10:37:14 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:470)
[10:37:14 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:384)
[10:37:14 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.reload(CraftServer.java:884)
[10:37:14 WARN]:        at org.bukkit.Bukkit.reload(Bukkit.java:654)
[10:37:14 WARN]:        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54)
[10:37:14 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
[10:37:14 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchCommand(CraftServer.java:752)
[10:37:14 WARN]:        at org.bukkit.craftbukkit.v1_15_R1.CraftServer.dispatchServerCommand(CraftServer.java:714)
[10:37:14 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:469)
[10:37:14 WARN]:        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:431)
[10:37:14 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1112)
[10:37:14 WARN]:        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:934)
[10:37:14 WARN]:        at java.lang.Thread.run(Thread.java:748)
[10:37:14 WARN]: Caused by: org.flywaydb.core.api.FlywayException: Unable to instantiate class org.postgresql.Driver : org.postgresql.Driver
[10:37:14 WARN]:        at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:59)
[10:37:14 WARN]:        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:176)
[10:37:14 WARN]:        ... 22 more
[10:37:14 WARN]: Caused by: java.lang.ClassNotFoundException: org.postgresql.Driver
[10:37:14 WARN]:        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
[10:37:14 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
[10:37:14 WARN]:        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
[10:37:14 WARN]:        at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
[10:37:14 WARN]:        at java.lang.Class.forName0(Native Method)
[10:37:14 WARN]:        at java.lang.Class.forName(Class.java:348)
[10:37:14 WARN]:        at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:57)
[10:37:14 WARN]:        ... 23 more
```
We are using the following to include Flyway & postgresql in our build (compiling via gradle jar)
```

    plugins {
        id 'java'
        id 'maven-publish'
        id 'signing'
    }

    group = 'com.mclockup'
    version = '1.0.0-SNAPSHOT'
    description = 'Core functionality used everywhere in Lockup'

    archivesBaseName = 'core'
    sourceCompatibility = '1.8'

    repositories {
        mavenLocal()
        mavenCentral()
    }

    dependencies {
        // Spigot
        implementation group: 'org.spigotmc', name: 'spigot-api', version: '1.15.2-R0.1-SNAPSHOT'

        // Postgres
        compile group: 'org.postgresql', name: 'postgresql', version: '42.2.12'

        // Flyway
        compile group: 'org.flywaydb', name: 'flyway-core', version: '6.4.1'

        // MyBatis
        compile group: 'org.mybatis', name: 'mybatis', version: '3.5.4'

        // Log4J
        compile group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.13.2'
        compile group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.13.2'
    }

    jar {
        from {
            configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
        }
    }

    javadoc {
        options.links += "https://hub.spigotmc.org/javadocs/spigot/"
    }

    task sourcesJar(type: Jar) {
        from sourceSets.main.allJava
        archiveClassifier.set("sources")
    }

    task javadocJar(type: Jar, dependsOn: javadoc) {
        classifier 'javadoc'
        from javadoc.destinationDir
    }
```
Error is extra confusing since the postgresql driver is very obviously in our jar file at the location its looking for:
![image](https://user-images.githubusercontent.com/24502339/82014199-20c8d380-964a-11ea-9045-aa6ff5027273.png)
I can also confirm that there are no issues with our database setup / jdbc string as I was able to successfully connect to our setup via DriverManager

###### What did you expect to see?

Recognition of our postgresql JDBC driver

###### What did you see instead?

Error posted above

**Comment by Michael-Ziluck** [comment]
I know I'm not OP, but I'm working with him. We fixed this in case someone is looking at it before he closes the issue.

**Comment by ctooley21** [comment]
yep! we thankfully figured it out.

turns out the spigot server software we use uses a different class loader than the main java thread, so it was causing issues when loading the jdbc driver. We fixed this by passing in the correct class loader.
`
Flyway flyway = Flyway.configure(LockupCore.getInstance().getPublicClassLoader())
`
