### ISSUE TITLE
Table 'flyway_schema_history' doesn't exist

### ISSUE THREAD

**Issue by JoeSeff** [flyway/flyway#2877]
###### Which version and edition of Flyway are you using?
**6.5.0**

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)
**latest**

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
**Gradle 5.6.4**

###### Which database are you using (type & version)?
**MySQL 8.0**

###### Which operating system are you using?
Windows 7x64

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)
plugins {
    id 'org.flywaydb.flyway' version '6.5.0'
}
flyway {
    url = 'jdbc:mysql://192.168.92.128:3306/reservationdb' 
    user = 'test'
    password = 'test123*'
    driver = 'com.mysql.cj.jdbc.Driver'
    // table='schema_version'
    table = 'flyway_schema_history'
}

###### What did you expect to see?
**Migration**

###### What did you see instead?
```
Unable to insert row for version '1' in Schema History table `reservationdb`.`flyway_schema_history`
----------------------------------------------------------------------------------------------------
SQL State  : 42S02
Error Code : 1146
Message    : Table 'reservationdb.flyway_schema_history' doesn't exist

        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.doAddAppliedMigration(JdbcTableSchemaHistory.java:171)
        at org.flywaydb.core.internal.schemahistory.SchemaHistory.addAppliedMigration(SchemaHistory.java:163)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:384)
        at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54)
        at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:282)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:279)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
        at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:162)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:159)
        at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
        at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:161)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:159)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:137)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:206)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:158)
        at org.flywaydb.core.Flyway.execute(Flyway.java:527)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:158)
        at org.flywaydb.gradle.task.FlywayMigrateTask.run(FlywayMigrateTask.java:28)
        at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:551)
        ... 88 more
Caused by: java.sql.SQLSyntaxErrorException: Table 'reservationdb.flyway_schema_history' doesn't exist
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
        at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97)
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:975)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1114)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1062)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1383)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:1047)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.update(JdbcTemplate.java:331)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.doAddAppliedMigration(JdbcTableSchemaHistory.java:165)
```

**Comment by MikielAgutu** [comment]
Can you check which tables are present on your DB? Perhaps it's possible you do have a Flyway schema history table with a different name.

**Comment by JoeSeff** [comment]
> Can you check which tables are present on your DB? Perhaps it's possible you do have a Flyway schema history table with a different name.

I specifically installed MySQL 8 for that project. There was only one database (**reservationdb**) and it was empty.

**Comment by juliahayward** [comment]
I'm trying to reproduce without success. Could you share your full `build.gradle` (redact any credentials) and the migration that it's trying to run please? Rather than publish here, you can email to julia.hayward@red-gate.com .

**Comment by juliahayward** [comment]
Problem found - the V1 migration contains DROP DATABASE x; - this shouldn't be done in a migration, Flyway always assumes you're starting from a clean database (unless you baseline it), and if there's a need to clean it first then just use `flyway clean`.
