### ISSUE TITLE
Set define off sqlplus

### ISSUE THREAD

**Issue by mrmarathe** [flyway/flyway#2886]
###### Which version and edition of Flyway are you using?

Enterprise edition 6.5.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java

###### Which database are you using (type & version)?

Oracle 12.1

###### Which operating system are you using?

Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

command: flyway -enterprise migrate
script being migrated is an Oracle Apex application that is exported as an sql file.
Unable to import as the set define off statement not processed

###### What did you expect to see?

set define off verify off feedback off whenever sqlerror exit sql.sqlcode rollback

should be parsed

###### What did you see instead?
Missing or invalid option 

Similar to #2257

**Comment by Lyeeedar** [comment]
Did you set oracle.sqlplus to true? If you have done, could you please post a code snippet (or email flyway support with it if you do not want to share it publically) so we can reproduce it?

**Comment by mrmarathe** [comment]
Thank you for your reply

Can you please check issue #2257.

**Comment by Lyeeedar** [comment]
`oracle.sqlplus` can either be set as a command line argument (See https://flywaydb.org/documentation/commandline/migrate#oracle.sqlplus) or in the configuration `flyway.oracle.sqlplus=true`

**Comment by mrmarathe** [comment]
I tried adding the flyway.oracle.sqlplus=true flag in the conf file. This conf file was dedicated to my script.
Referred this : https://flywaydb.org/documentation/scriptconfigfiles#structure

However I am getting an exception when the conf file is read :

org.flywaydb.core.api.FlywayException: Unknown configuration property: flyway.oracle.sqlplus
	at org.flywaydb.core.internal.configuration.ConfigUtils.checkConfigurationForUnrecognisedProperties(ConfigUtils.java:939)
	at org.flywaydb.core.internal.sqlscript.SqlScriptMetadata.<init>(SqlScriptMetadata.java:431)
	at org.flywaydb.core.internal.sqlscript.SqlScriptMetadata.fromResource(SqlScriptMetadata.java:443)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.<init>(ParserSqlScript.java:457)
	at org.flywaydb.core.internal.database.DatabaseFactory$2.createSqlScript(DatabaseFactory.java:652)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.addMigrations(SqlMigrationResolver.java:556)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:475)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:431)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:514)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:496)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:482)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:433)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:517)
	at org.flywaydb.core.internal.command.DbRepair$1.call(DbRepair.java:491)
	at org.flywaydb.core.internal.command.DbRepair$1.call(DbRepair.java:488)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:453)
	at org.flywaydb.core.internal.command.DbRepair.repair(DbRepair.java:488)
	at org.flywaydb.core.Flyway$7.execute(Flyway.java:778)
	at org.flywaydb.core.Flyway$7.execute(Flyway.java:771)
	at org.flywaydb.core.Flyway.execute(Flyway.java:914)
	at org.flywaydb.core.Flyway.repair(Flyway.java:771)

Also tried with just oracle.sqlplus=true but that didn't work as well

**Comment by Lyeeedar** [comment]
As shown on that page https://flywaydb.org/documentation/scriptconfigfiles#reference script config files only support 2 options, `encoding` and `executeInTransaction`.

To set `flyway.oracle.sqlplus=true` you have to set it in the main configuration file, or if using the api (as I see you are), via calling `.oracleSqlplus(true)` when configuring flyway.

**Comment by mrmarathe** [comment]
Ok. Thank you for the information. I thought those references are just
examples. However I have already tried setting the oraclesqlplus true in
the configuration but that would be applicable for all the scripts. I need
this as a specific feature.

As per issue #2257 it seems that 'set define off verify off feedback off'
was pushed in the 6.0.0 version.  Should we take it as it is still not
working.

What are the other alternatives.

**Comment by Lyeeedar** [comment]
`set define off verify off feedback off` is only understood by Flyway with the `oracleSqlPlus` flag turned on. If you do not wish to do this for all scripts, there is no way to make Flyway understand these commands.
