### ISSUE TITLE
gradle expects flyway.conf file even though it's provided in gradle.properties file

### ISSUE THREAD

**Issue by pietkun-j** [flyway/flyway#2930]
###### Which version and edition of Flyway are you using?

Flyway 6.0.7

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

```
gradle.properties
...
flyway.configFiles=flyway.conf // when variable disabled flyway doesn't fail, so most probably the format is different
```
Execute:
```
/c/api/gradle-5.1.1/bin/gradle flywayInfo --stacktrace

> Task :flywayInfo FAILED
:flywayInfo took 613ms
Task timings (table of pain):
    613ms  :flywayInfo

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayInfo'.
> Error occurred while executing flywayInfo
  null

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':flywayInfo'.
...
Caused by: java.lang.NullPointerException
        at org.flywaydb.gradle.task.AbstractFlywayTask.**determineConfigFiles**(AbstractFlywayTask.java:748)
        at org.flywaydb.gradle.task.AbstractFlywayTask.loadConfigurationFromConfigFiles(AbstractFlywayTask.java:683)
        at org.flywaydb.gradle.task.AbstractFlywayTask.createFlywayConfig(AbstractFlywayTask.java:665)
        at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:513)
```

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

gradle 5.1.1

###### Which database are you using (type & version)?

Oracle 12c 12.2.0.2

###### Which operating system are you using?

Windows 10
Git Bash console

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

/c/api/gradle-5.1.1/bin/gradle flywayInfo --stacktrace

###### What did you expect to see?

a table of installed (migrated) scripts

###### What did you see instead?
```
* What went wrong:
Execution failed for task ':flywayInfo'.
> Error occurred while executing flywayInfo
  null

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':flywayInfo'.

Caused by: java.lang.NullPointerException
        at org.flywaydb.gradle.task.AbstractFlywayTask.**determineConfigFiles**(AbstractFlywayTask.java:748)
        at org.flywaydb.gradle.task.AbstractFlywayTask.loadConfigurationFromConfigFiles(AbstractFlywayTask.java:683)
        at org.flywaydb.gradle.task.AbstractFlywayTask.createFlywayConfig(AbstractFlywayTask.java:665)
        at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:513)
```

**Comment by DoodleBobBuffPants** [comment]
Hi. You are meant to specify the config file in a system property not a gradle property. You can [see the docs here](https://flywaydb.org/documentation/gradle/#config-files). Can you try this and tell us if it works?

**Comment by DoodleBobBuffPants** [comment]
Closing due to inactivity
