### ISSUE TITLE
Azure SQL Data Warehouse/Synapse support V7 Beta; baseline command failed

### ISSUE THREAD

**Issue by we814** [flyway/flyway#2947]
This feature is now available in the V7 beta which you can read more about [here](https://flywaydb.org/blog/flyway-7.0.0-beta).

_Originally posted by @DoodleBobBuffPants in https://github.com/flyway/flyway/issues/2021#issuecomment-686374128_

I am unable to baseline flyway with my Azure Synapse database.  Same error as pre V7 Beta.

Flyway Community Edition 7.0.0-beta1 by Redgate

applicationName=Microsoft JDBC Driver for SQL Server;applicationIntent=readwrite; (Microsoft SQL Server 12.0)
ERROR: Unable to release SQL Server application lock
com.microsoft.sqlserver.jdbc.SQLServerException: Stored procedure sp_releaseapplock does not exist or is not supported.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:256)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1621)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:592)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:522)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7194)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:2930)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:248)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:223)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:503)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:222)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerApplicationLockTemplate.execute(SQLServerApplicationLockTemplate.java:76)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerConnection.lock(SQLServerConnection.java:96)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.create(JdbcTableSchemaHistory.java:98)
        at org.flywaydb.core.internal.command.DbBaseline.baseline(DbBaseline.java:77)
        at org.flywaydb.core.Flyway.doBaseline(Flyway.java:214)
        at org.flywaydb.core.Flyway.access$200(Flyway.java:74)
        at org.flywaydb.core.Flyway$5.execute(Flyway.java:355)
        at org.flywaydb.core.Flyway$5.execute(Flyway.java:342)
        at org.flywaydb.core.Flyway.execute(Flyway.java:501)
        at org.flywaydb.core.Flyway.baseline(Flyway.java:342)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:220)
        at org.flywaydb.commandline.Main.main(Main.java:151)
ERROR:
Unable to acquire SQL Server application lock
---------------------------------------------
SQL State  : S0001
Error Code : 104386
Message    : Stored procedure sp_getapplock does not exist or is not supported.

Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Stored procedure sp_getapplock does not exist or is not supported.

**Comment by DoodleBobBuffPants** [comment]
Hi. Azure Synapse is only supported in Flyway Enterprise.

**Comment by we814** [comment]
> Hi. Azure Synapse is only supported in Flyway Enterprise.

Are there plans to include Azure Synapse support in Flyway Community version?

**Comment by DoodleBobBuffPants** [comment]
If you head over to our [documentation](https://flywaydb.org/documentation/) then on each database's specific page you can see which versions are enterprise only. Note that Azure Synapse will appear in that list once the full V7 is released.
