### ISSUE TITLE
HSQLDB 'drop procedure foobar if exits' doesn't work

### ISSUE THREAD

**Issue by calvarius7** [flyway/flyway#3034]
###### Which version and edition of Flyway are you using?
Flyway Community Edition version 7.32 (but problem exists since version 6)

###### If this is not the latest version, can you reproduce the issue with the latest one as well?
(Many bugs are fixed in newer releases and upgrading will often resolve the issue)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
JAVA API

###### Which database are you using (type & version)?
HSQLDB 2.5.

###### Which operating system are you using?
Windows & Linux

###### What did you do?
(Please include the content causing the issue, any relevant configuration settings, the SQL statement that failed (if relevant) and the command you ran.)

We updated flyway from 3.2.1.
We handled the migration from 3 to 4 and 5 to 6. 
But starting with version 6 we get the following error during db-migration 

`Caused by: org.flywaydb.core.api.FlywayException: Incomplete statement at line 51 col 1: DROP PROCEDURE MERGE_COMPONENT_PROPERTY IF EXISTS;`

The problem seems to be `DROP PROCEDURE foobar IF EXISTS`

###### What did you expect to see?

Successful migration with all scripts that worked fine with 3.2.1.

###### What did you see instead?

Example full stacktrace from a test run: 

```org.flywaydb.core.api.FlywayException: Unable to parse statement in *****\src\main\resources\migration\sql\V43__*****.sql at line 51 col 1. See https://flywaydb.org/documentation/knownparserlimitations for more information: Incomplete statement at line 51 col 1: DROP PROCEDURE MERGE_COMPONENT_PROPERTY IF EXISTS;

call INCREASE_ALL_COMPONENT_REVISIONS();

at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:303)
at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:707)
at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:672)
at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:82)
at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:127)
at org.flywaydb.core.internal.sqlscript.ParserSqlScript.executeInTransaction(ParserSqlScript.java:196)
at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.canExecuteInTransaction(SqlMigrationExecutor.java:83)
at org.flywaydb.core.internal.command.DbMigrate.isExecuteGroupInTransaction(DbMigrate.java:358)
at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:321)
at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:290)
at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:194)
at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:191)
at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:38)
at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33)
at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:129)
at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:191)
at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152)
at org.flywaydb.core.Flyway$1.execute(Flyway.java:216)
at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
at org.flywaydb.core.Flyway.execute(Flyway.java:570)
at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
at de.coqon.persistence.dao.AbstractDaoTest.migrate(AbstractDaoTest.java:122)
at de.coqon.persistence.dao.AbstractDaoTest.deleteDatabaseDirAndMigrate(AbstractDaoTest.java:103)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
at com.tngtech.java.junit.dataprovider.DataProviderRunner.invokeBeforeClass(DataProviderRunner.java:239)
at com.tngtech.java.junit.dataprovider.DataProviderRunner.computeTestMethods(DataProviderRunner.java:190)
at com.tngtech.java.junit.dataprovider.DataProviderRunner.validateInstanceMethods(DataProviderRunner.java:109)
at org.junit.runners.BlockJUnit4ClassRunner.collectInitializationErrors(BlockJUnit4ClassRunner.java:104)
at com.tngtech.java.junit.dataprovider.DataProviderRunner.collectInitializationErrors(DataProviderRunner.java:93)
at org.junit.runners.ParentRunner.validate(ParentRunner.java:355)
at org.junit.runners.ParentRunner.<init>(ParentRunner.java:76)
at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:57)
at com.tngtech.java.junit.dataprovider.DataProviderRunner.<init>(DataProviderRunner.java:82)
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
at java.lang.reflect.Constructor.newInstance(Unknown Source)
at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:90)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:76)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:49)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:526)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: org.flywaydb.core.api.FlywayException: Incomplete statement at line 51 col 1: DROP PROCEDURE MERGE_COMPONENT_PROPERTY IF EXISTS;
call INCREASE_ALL_COMPONENT_REVISIONS();

at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:238)
... 59 more```

**Comment by DoodleBobBuffPants** [comment]
Could you share a minimal reproduction script?

**Comment by calvarius7** [comment]
Is a minimal SQL-script sufficient? That would be `DROP PROCEDURE foobar IF EXISTS;` for HSQLDB

**Comment by DoodleBobBuffPants** [comment]
Thanks for bringing this up, expect a fix soon :)
