### ISSUE TITLE
HSQLDB case-sensitive 'end' in procedures

### ISSUE THREAD

**Issue by calvarius7** [flyway/flyway#3044]
###### Which version and edition of Flyway are you using?
Flyway Community Edition version 7.4.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
JAVA API

###### Which database are you using? (Type & version)
HSQLDB 2.5.

###### Which operating system are you using?
Windows & Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

* Upgraded from Flyway 5.2.4 to Flyway 7.4.0. 
* Run our migration-scripts that worked under Flyway 5.2.4
* Example script that failed: 
```
create procedure DEMONSTRATE_BUG()
modifies sql data
  begin atomic
    declare V_TEMP BIGINT;
    declare V_TEMP_TWO BIGINT;
  SET V_TEMP = 1;
end;
```
results in an exception with message `unexpected end of statement: required: ; : line: 4`

We guess that the `end` in the last line is handled somehow case-sensitive, since we got a different bug when we use upper case `END`.
See [issue 3043](https://github.com/flyway/flyway/issues/3043)

###### What did you expect to see?

Successful migration with all scripts that worked fine with 5.2.4.

###### What did you see instead?
```
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException:
Migration V1_2__flywaybug.sql failed
------------------------------------
SQL State : 42590
Error Code : -5590
Message : unexpected end of statement: required: ; : line: 4
Location : ...
Line : 2
Statement : create procedure DEMONSTRATE_BUG()
modifies sql data
begin atomic
declare V_TEMP BIGINT

 at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:424)
at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:56)
at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:328)
at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:325)
at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:290)
at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:194)
at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:191)
at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:38)
at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33)
at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:129)
at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:191)
at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152)
at org.flywaydb.core.Flyway$1.execute(Flyway.java:216)
at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
at org.flywaydb.core.Flyway.execute(Flyway.java:570)
at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
```

**Comment by DoodleBobBuffPants** [comment]
This is largely related to https://github.com/flyway/flyway/issues/3043, so closing this and will work on that issue instead
