### ISSUE TITLE
Flyway cannot connect to Azure Edge SQL Server (edition: 9)

### ISSUE THREAD

**Issue by chakrit** [flyway/flyway#3070]
###### Which version and edition of Flyway are you using?

7.5.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

If by latest you mean a github checkout, nope havn't tried.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

Azure Edge SQL Server using this container: (https://hub.docker.com/_/microsoft-azure-sql-edge)

###### Which operating system are you using?

Mac OS X on aarch64 (Apple silicon)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Run the aforementioned container using docker preview. And then build datasource as follows:

```java
        var dataSource = new SQLServerConnectionPoolDataSource();
        dataSource.setServerName(this.dbHost);
        dataSource.setPortNumber(this.dbPort);
        dataSource.setUser(this.dbUser);
        dataSource.setPassword(this.dbPassword);
        dataSource.setDatabaseName(this.dbName);
        logger.info("using database: {} with user: {}", this.dbName, this.dbUser);
        return dataSource;
```

Using the `com.microsoft.sqlserver:mssql-jdbc:9.2.0.jre15` package for the data source.

###### What did you expect to see?

App connects to database as normal, and perform migration as usual.

###### What did you see instead?

Flyway fails to establish connection, throwing the following error:

```
java.lang.IllegalStateException: Failed to execute ApplicationRunner
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:798) ~[spring-boot-2.4.2.jar:2.4.2]
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785) ~[spring-boot-2.4.2.jar:2.4.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:333) ~[spring-boot-2.4.2.jar:2.4.2]
        at (my spring application class)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
        at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.4.2.jar:2.4.2]
Caused by: java.lang.IllegalArgumentException: Unknown SQL Server engine edition: 9
        at org.flywaydb.core.internal.database.sqlserver.SQLServerEngineEdition.fromCode(SQLServerEngineEdition.java:45) ~[flyway-core-7.5.2.jar:na]
        at org.flywaydb.core.internal.database.sqlserver.synapse.SynapseDatabaseType.handlesDatabaseProductNameAndVersion(SynapseDatabaseType.java:46) ~[flyway-core-7.5.2.jar:na]
        at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:175) ~[flyway-core-7.5.2.jar:na]
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:71) ~[flyway-core-7.5.2.jar:na]
        at org.flywaydb.core.Flyway.execute(Flyway.java:507) ~[flyway-core-7.5.2.jar:na]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:165) ~[flyway-core-7.5.2.jar:na]
        at (my spring application class)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795) ~[spring-boot-2.4.2.jar:2.4.2]
        ... 8 common frames omitted
```

**Comment by chakrit** [comment]
Thank you for the quick turnaround @DoodleBobBuffPants !!! 🙏
