### ISSUE TITLE
Connection Terminated / Unable to release PostgreSQL advisory lock

### ISSUE THREAD

**Issue by odehsemreen** [flyway/flyway#3080]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 6.4.2 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes, test also with Flyway Community Edition 7.5.3 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using? (Type & version)
Postgres 11.7

###### Which operating system are you using?
Flyway Docker

```
FLYWAY_URL='jdbc:postgresql://postgres/postgres?socketTimeout=0&tcpKeepAlive=true&options=-c%20statement_timeout=1h' 
```

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I am running a query to create an index concurrently on a table. When the query runs, flyway opens a connection, locks `flyway_schema_history`, and places an advisory lock. Then workers start a new connection and execute the script. While the script is running, flyway throw an error. The index is actually there, just the schema is not updated and becomes out of sync.

SQL: `CREATE INDEX CONCURRENTLY idx_name ON table_name USING btree (c1, c2);`

```
ERROR: Unable to release PostgreSQL advisory lock
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:865)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1771)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:418)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:344)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForBoolean(JdbcTemplate.java:170)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.unlock(PostgreSQLAdvisoryLockTemplate.java:99)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:80)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:191)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:216)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
	at org.flywaydb.core.Flyway.execute(Flyway.java:570)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:223)
	at org.flywaydb.commandline.Main.main(Main.java:144)
DEBUG: Memory usage: 15 of 126M
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to restore connection to its original state
--------------------------------------------------
SQL State  : 08003
Error Code : 0
Message    : This connection has been closed.

	at org.flywaydb.core.internal.database.base.Connection.restoreOriginalState(Connection.java:133)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.exists(JdbcTableSchemaHistory.java:93)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.allAppliedMigrations(JdbcTableSchemaHistory.java:184)
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.calculateInstalledRank(SchemaHistory.java:191)
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.addAppliedMigration(SchemaHistory.java:173)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:345)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:290)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:194)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:191)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:69)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:191)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:216)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
	at org.flywaydb.core.Flyway.execute(Flyway.java:570)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:223)
	at org.flywaydb.commandline.Main.main(Main.java:144)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:865)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1771)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:418)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:344)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:221)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.doRestoreOriginalState(PostgreSQLConnection.java:47)
	at org.flywaydb.core.internal.database.base.Connection.restoreOriginalState(Connection.java:131)
	... 20 more
```

Looking on the connection lifecycle in PG server, the connection that actually placed the advisory lock is still active and there, also the advisory lock is still there. The queries below run after the error is thrown by flyway

```
SELECT pid, application_name, wait_event_type, wait_event, state FROM pg_stat_activity;
  pid  |    application_name    | wait_event_type | wait_event | state
-------+------------------------+-----------------+------------+--------
 10822 | PostgreSQL JDBC Driver |                 |            | active
```

```
SELECT locktype, pid, mode, granted, fastpath FROM pg_locks WHERE locktype='advisory';
 locktype |  pid  |     mode      | granted | fastpath
----------+-------+---------------+---------+----------
 advisory | 10822 | ExclusiveLock | t       | f
```

I could reproduce this with using `pg_sleep` instead of actually creating an index

```
SELECT
  now();

SELECT
  pg_sleep(600);

SELECT
  now();
```

It seems flyway is timeout even that the client settings disables socket timeout and enable keep alives.

###### What did you expect to see?

Migration script runs successfully with no errors and the schema is updated

###### What did you see instead?

Error thrown by flyway 

```
ERROR: Unable to release PostgreSQL advisory lock
org.postgresql.util.PSQLException: This connection has been closed.
```

The schema also becomes out of sync

**Comment by DoodleBobBuffPants** [comment]
Could you provide the full error output after running this in the latest Flyway version? We did some work in V7 that improves error output in cases like this to help with debugging

**Comment by achanda** [comment]
Hi @DoodleBobBuffPants I work with @odehsemreen. Here is the full debug output
```
DEBUG: Loading config file: /flyway/conf/flyway.conf
DEBUG: Unable to load config file: /flyway/flyway.conf
DEBUG: Unable to load config file: /flyway/flyway.conf
DEBUG: Adding location to classpath: /flyway/drivers/google-cloud-storage-1.113.2.jar
DEBUG: Adding location to classpath: /flyway/drivers/hsqldb-2.5.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/aws-secretsmanager-jdbc-1.0.5.jar
DEBUG: Adding location to classpath: /flyway/drivers/mariadb-java-client-2.6.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/ojdbc8-19.6.0.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/snowflake-jdbc-3.12.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/derbyshared-10.15.2.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/derbyclient-10.15.2.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/mssql-jdbc-8.4.1.jre8.jar
DEBUG: Adding location to classpath: /flyway/drivers/derby-10.15.2.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/h2-1.4.200.jar
DEBUG: Adding location to classpath: /flyway/drivers/jaybird-jdk18-3.0.8.jar
DEBUG: Adding location to classpath: /flyway/drivers/postgresql-42.2.14.jar
DEBUG: Adding location to classpath: /flyway/drivers/jtds-1.3.1.jar
DEBUG: Adding location to classpath: /flyway/drivers/jna-4.5.2.jar
DEBUG: Adding location to classpath: /flyway/drivers/google-cloud-spanner-jdbc-1.16.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/sqlite-jdbc-3.30.1.jar
DEBUG: Adding location to classpath: /flyway/drivers/derbytools-10.15.2.0.jar
DEBUG: Adding location to classpath: /flyway/drivers/jna-platform-4.5.2.jar
DEBUG: Adding location to classpath: /flyway/drivers/mysql-connector-java-8.0.20.jar
DEBUG: Using configuration:
DEBUG: flyway.baselineOnMigrate -> true
DEBUG: flyway.initSql -> SET ROLE provisioner
DEBUG: flyway.jarDirs -> /flyway/jars
DEBUG: flyway.locations -> filesystem:sql
DEBUG: flyway.password -> ********************************
DEBUG: flyway.schemas -> sessions_schema
DEBUG: flyway.url -> jdbc:postgresql://host.docker.internal/sessions
DEBUG: flyway.user -> sessions_PROVISIONER
DEBUG: Multiple databases found that handle url 'jdbc:postgresql://host.docker.internal/sessions': CockroachDB, PostgreSQL
DEBUG: Scanning for classpath resources at 'classpath:db/callback' ...
DEBUG: Determining location urls for classpath:db/callback using ClassLoader java.net.URLClassLoader@1e6d1014 ...
DEBUG: Unable to resolve location classpath:db/callback.
Flyway Community Edition 7.5.3 by Redgate
DEBUG: AWS SDK available: false
DEBUG: Google Cloud Storage available: false
DEBUG: Scanning for filesystem resources at 'sql'
DEBUG: Scanning for resources in path: sql (sql)
DEBUG: Found filesystem resource: sql/Readme.md
DEBUG: Found filesystem resource: sql/V20200721125448__create_refresh_tokens_table.sql
DEBUG: Found filesystem resource: sql/V20200817101914__create_tmp_refresh_tokens_update_table.sql
DEBUG: Found filesystem resource: sql/V20200907133853__create_entity_limit_triggers.sql
DEBUG: Found filesystem resource: sql/V20200916110343__add_expiration_colums_to_tmp_refresh_token_update_table.sql
DEBUG: Found filesystem resource: sql/V20200922143207__create_track_remove_queries_table.sql
DEBUG: Found filesystem resource: sql/V20201217122200__alter_tmp_refresh_tokens_update_table.sql
DEBUG: Found script configuration: V20210128121531__create_index_grant_id_refresh_tokens.sql.conf
DEBUG: Found filesystem resource: sql/V20210128121531__create_index_grant_id_refresh_tokens.sql
DEBUG: Found filesystem resource: sql/V20210128121531__create_index_grant_id_refresh_tokens.sql.conf
Database: jdbc:postgresql://host.docker.internal/sessions (PostgreSQL 11.7)
DEBUG: Driver  : PostgreSQL JDBC Driver 42.2.14
DEBUG: Parsing  ...
DEBUG: Unable to determine database version: null
DEBUG: Unable to determine database version: null
DEBUG: Unable to determine database version: null
DEBUG: Found statement at line 1: SET ROLE provisioner
DEBUG: Executing SQL: SET ROLE provisioner
DEBUG: Update Count: 0
DEBUG: DDL Transactions Supported: true
DEBUG: Schemas: sessions_schema
DEBUG: Default schema: null
DEBUG: Scanning for SQL callbacks ...
DEBUG: Filtering out resource: sql/Readme.md (filename: Readme.md)
DEBUG: Filtering out resource: sql/V20210128121531__create_index_grant_id_refresh_tokens.sql.conf (filename: V20210128121531__create_index_grant_id_refresh_tokens.sql.conf)
DEBUG: Validating migrations ...
DEBUG: Filtering out resource: sql/Readme.md (filename: Readme.md)
DEBUG: Filtering out resource: sql/V20210128121531__create_index_grant_id_refresh_tokens.sql.conf (filename: V20210128121531__create_index_grant_id_refresh_tokens.sql.conf)
DEBUG: Found script configuration: V20210128121531__create_index_grant_id_refresh_tokens.sql.conf
DEBUG: Filtering out resource: sql/Readme.md (filename: Readme.md)
DEBUG: Filtering out resource: sql/V20200721125448__create_refresh_tokens_table.sql (filename: V20200721125448__create_refresh_tokens_table.sql)
DEBUG: Filtering out resource: sql/V20200817101914__create_tmp_refresh_tokens_update_table.sql (filename: V20200817101914__create_tmp_refresh_tokens_update_table.sql)
DEBUG: Filtering out resource: sql/V20200907133853__create_entity_limit_triggers.sql (filename: V20200907133853__create_entity_limit_triggers.sql)
DEBUG: Filtering out resource: sql/V20200916110343__add_expiration_colums_to_tmp_refresh_token_update_table.sql (filename: V20200916110343__add_expiration_colums_to_tmp_refresh_token_update_table.sql)
DEBUG: Filtering out resource: sql/V20200922143207__create_track_remove_queries_table.sql (filename: V20200922143207__create_track_remove_queries_table.sql)
DEBUG: Filtering out resource: sql/V20201217122200__alter_tmp_refresh_tokens_update_table.sql (filename: V20201217122200__alter_tmp_refresh_tokens_update_table.sql)
DEBUG: Filtering out resource: sql/V20210128121531__create_index_grant_id_refresh_tokens.sql (filename: V20210128121531__create_index_grant_id_refresh_tokens.sql)
DEBUG: Filtering out resource: sql/V20210128121531__create_index_grant_id_refresh_tokens.sql.conf (filename: V20210128121531__create_index_grant_id_refresh_tokens.sql.conf)
Successfully validated 7 migrations (execution time 00:01.046s)
Current version of schema "sessions_schema": 20201217122200
DEBUG: Using executeInTransaction=false from script configuration
DEBUG: Using executeInTransaction=false from script configuration
DEBUG: Starting migration of schema "sessions_schema" to version "20210128121531 - create index grant id refresh tokens" [non-transactional] ...
Migrating schema "sessions_schema" to version "20210128121531 - create index grant id refresh tokens" [non-transactional]
DEBUG: Parsing V20210128121531__create_index_grant_id_refresh_tokens.sql ...
DEBUG: Found statement at line 1: -- Create index on tenant_name, grant_id on refresh tokens for remove by grant
CREATE INDEX CONCURRENTLY refresh_tokens_tenant_name_grant_id_idx ON refresh_tokens USING btree (tenant_name, grant_id) [non-transactional]
DEBUG: Executing SQL: -- Create index on tenant_name, grant_id on refresh tokens for remove by grant
CREATE INDEX CONCURRENTLY refresh_tokens_tenant_name_grant_id_idx ON refresh_tokens USING btree (tenant_name, grant_id)
DEBUG: Using executeInTransaction=false from script configuration
ERROR: Migration of schema "sessions_schema" to version "20210128121531 - create index grant id refresh tokens" [non-transactional] failed! Please restore backups and roll back database and code!
ERROR: Unable to release PostgreSQL advisory lock
org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:865)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1771)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:418)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:344)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForBoolean(JdbcTemplate.java:170)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.unlock(PostgreSQLAdvisoryLockTemplate.java:99)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:80)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:191)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:216)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
	at org.flywaydb.core.Flyway.execute(Flyway.java:570)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:223)
	at org.flywaydb.commandline.Main.main(Main.java:144)
DEBUG: Memory usage: 16 of 94M
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to restore connection to its original state
--------------------------------------------------
SQL State  : 08003
Error Code : 0
Message    : This connection has been closed.

	at org.flywaydb.core.internal.database.base.Connection.restoreOriginalState(Connection.java:133)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.exists(JdbcTableSchemaHistory.java:93)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.allAppliedMigrations(JdbcTableSchemaHistory.java:184)
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.calculateInstalledRank(SchemaHistory.java:191)
	at org.flywaydb.core.internal.schemahistory.SchemaHistory.addAppliedMigration(SchemaHistory.java:173)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:345)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:290)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:194)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:191)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:69)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:191)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:216)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
	at org.flywaydb.core.Flyway.execute(Flyway.java:570)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:223)
	at org.flywaydb.commandline.Main.main(Main.java:144)
Caused by: org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:865)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:1771)
	at org.postgresql.jdbc.PgConnection.prepareStatement(PgConnection.java:418)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.prepareStatement(JdbcTemplate.java:344)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:221)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.doRestoreOriginalState(PostgreSQLConnection.java:47)
	at org.flywaydb.core.internal.database.base.Connection.restoreOriginalState(Connection.java:131)
	... 20 more
```

**Comment by DoodleBobBuffPants** [comment]
I have been unable to reproduce this. It seems that the driver is reporting that the connection is closed, even if the server is showing it as active. Could you try executing the SQL in a similar manner, but using the PostgreSQL JDBC driver directly? This will let you know if the issue lies within the driver or not. Could you also provide a minimal reproduction project? That is, scripts + configuration + execution steps that can reproduce this behavior

**Comment by DoodleBobBuffPants** [comment]
I have found a reproduction. It occurs in certain environments where idle sockets are being cleared (see [this](https://www.postgresql.org/message-id/001701c53a90$cf879cc0$6600a8c0@kermit) for more information). There doesn't seem to be any recommended way of dealing with this yourself, other than catching the specific exception and reopening the connection, so we will look into this

**Comment by odehsemreen** [comment]
Thanks for looking into this @DoodleBobBuffPants, I was just working on creating a reproduction project for you. It's kind of confusing that even with the keep alive the socket is treated as idle. Is there a recommended way to reopen the main connection that flyway uses to handle schema updates? I haven't seen anything like that in the documentations before.

**Comment by DoodleBobBuffPants** [comment]
There isn't any way to achieve this at the moment, we will be looking into a solution now that we have a reproduction

**Comment by DoodleBobBuffPants** [comment]
After investigating this we don't think there is any viable solution in Flyway, and the current approach that halts as-is is the best option since fundamentally this seems to be an issue in the PostgreSQL JDBC driver not utilizing `tcpKeepAlive`

Flyway has no way of knowing whether the connection is closed due to a user's actions or if it was automatically closed by the environment such as in this case. This makes it hard to decide whether or not we *can* do any automatic connection restarting, let alone whether or not we *should*. If we did, all we would do is mark the migration as failed in the schema history table, since retrying would cause the same problem as its due to the migration taking a long time. Doing this however is still uncertain - the connection may have been closed by a user for a reason, so it might be reasonable to expect no more changes, including changes to the schema history table

We will await a response from the maintainers of the driver and we have opened an issue here: https://github.com/pgjdbc/pgjdbc/issues/2061

To unblock yourselves in the mean time, you could try a different PostgreSQL driver such as [pgjdbc-ng](https://github.com/impossibl/pgjdbc-ng) which requires setting Flyway's [driver](https://flywaydb.org/documentation/configuration/parameters/driver) parameter to point to this driver's driver class. Note that this driver is unofficial and is unsupported, but it may unblock you

**Comment by odehsemreen** [comment]
Thanks for the updated. Unfortunately it seems that there is nothing we can do about it. We are using the official driver as all of our projects do so. I have tried to force a more aggressive TCP keep alive settings on PG server, but that also didn't help.

```
postgres=> SHOW tcp_keepalives_count;
 tcp_keepalives_count
----------------------
 5
(1 row)
postgres=> SHOW tcp_keepalives_interval;
 tcp_keepalives_interval
-------------------------
 1
(1 row)
postgres=> SHOW tcp_keepalives_idle;
 tcp_keepalives_idle
---------------------
 1
(1 row)
```

I will build a tweaked docker image with flyway to change the OS settings as suggested in https://github.com/pgjdbc/pgjdbc/issues/2061

**Comment by DoodleBobBuffPants** [comment]
Having tested the recommended solution in https://github.com/pgjdbc/pgjdbc/issues/2061 I was able to solve the issue

It shouldn't require modifying the dockefile - executing the following did the trick:
```
docker run --sysctl net.ipv4.tcp_keepalive_time=240 --sysctl net.ipv4.tcp_keepalive_intvl=60 --rm -v C:\flyway:/flyway/conf/ -v C:\flyway\sql:/flyway/sql/ flyway/flyway migrate
```

This should allow you to easily control the values of `tcp_keepalive` when running the container

**Comment by rohityadav225** [comment]
I am facing the same issue on macos big sur.

**Comment by rohityadav225** [comment]
@DoodleBobBuffPants Can you please let me know what else i could try ?
