### ISSUE TITLE
"BEGIN NOT ATOMIC IF ... THEN" from MariaDB not recognized

### ISSUE THREAD

**Issue by JD-CSTx** [flyway/flyway#3115]
###### Which version and edition of Flyway are you using?
7.7.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin.
Path:
```
<dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-core</artifactId>
    <version>7.7.0</version>
</dependency>
```

###### Which database are you using? (Type & version)
 10.4.14-MariaDB-1:10.4.14+maria~focal

###### Which operating system are you using?
macOS, Linux and Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Migrating, using ```Flyway.migrate```.
Everything worked fine before Flyway 6.4.1 came out, 6.4.0 is the last working version.

It's not understanding some proper MariaDB syntax anymore. Exactly:
```BEGIN NOT ATOMIC IF ... THEN```

Example with ```SELECT VERSION()```:
```
BEGIN NOT ATOMIC IF NOT FALSE THEN
    SELECT VERSION();
END IF;
END; 
```

It seems like a regression where MariaDB SQL is treated like MySQL SQL.

###### What did you expect to see?
+---------------------------------------+
| VERSION()                             |
+---------------------------------------+
| 10.4.14-MariaDB-1:10.4.14+maria~focal |
| +---------------------------------------+

###### What did you see instead?
```
Hibernate error stackTrace...
Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException:
Migration V1.1.1.sql failed
-----------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=18) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 2
Location   : V1.1.1.sql (...)
Line       : 8
Statement  : BEGIN NOT ATOMIC IF NOT FALSE THEN
    SELECT VERSION()
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:424)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:328)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:325)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:290)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:194)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:191)
	at org.flywaydb.core.internal.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:60)
	at org.flywaydb.core.internal.database.mysql.MySQLConnection.lock(MySQLConnection.java:161)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:191)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:152)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:216)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
	at org.flywaydb.core.Flyway.execute(Flyway.java:570)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
	at ....database.hibernate.FlywayMigrator.migrate(FlywayMigrator.java:276)
	at ....database.hibernate.FlywayMigrator.integrate(FlywayMigrator.java:327)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:280)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:468)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1249)
	... 46 more
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException:
Migration V1.1.1.sql failed
-----------------------------------
SQL State  : 42000
Error Code : 1064
Message    : (conn=18) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 2
Location   : V1.1.1.sql (...)
Line       : 8
Statement  : BEGIN NOT ATOMIC IF NOT FALSE THEN
    SELECT VERSION()
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:273)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:218)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:78)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:67)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:66)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:421)
	... 68 more
Caused by: java.sql.SQLSyntaxErrorException: (conn=18) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 2
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:153)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:274)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:363)
	at org.mariadb.jdbc.MariaDbStatement.execute(MariaDbStatement.java:501)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
	... 74 more
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 2
	at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:192)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:260)
	at org.mariadb.jdbc.MariaDbStatement.executeInternal(MariaDbStatement.java:357)
	... 78 more
Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 2
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1681)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1543)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1506)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:254)
	... 79 more
```

**Comment by Rixium** [comment]
Hey @JD-CSTx ,

Thanks for reporting the issue. I have managed to reproduce this and will be looking in to it.

**Comment by Rixium** [comment]
Hey @JD-CSTx ,
We've implemented a fix for this and it should be in the next release.

Thanks! 😀
