### ISSUE TITLE
Missing dependencies for bundle aws-secretsmanager-jdbc driver 

### ISSUE THREAD

**Issue by bobdoah** [flyway/flyway#3118]
###### Which version and edition of Flyway are you using?
I'm using version 7.7.0 with a Teams trial license

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Docker/command-line

###### Which database are you using? (Type & version)
AWS Aurora RDS with Secretsmanager

###### Which operating system are you using?
 EKS-optimized Amazon Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

The command line client bundle and docker image both include an old version of the AWS Secretsmanager JDBC driver (1.0.5, latest release is 1.0.6). They do not include any of the dependencies, or their dependencies required to run this, those are:
- aws-java-sdk-secretsmanager
- aws-secretsmanager-caching-java
- jackson-databind

When I attempted to run migrations using the docker image, the command failed with:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/amazonaws/secretsmanager/caching/SecretCache
        at com.amazonaws.secretsmanager.sql.AWSSecretsManagerDriver.<init>(AWSSecretsManagerDriver.java:120)
        at com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver.<init>(AWSSecretsManagerPostgreSQLDriver.java:55)
        at com.amazonaws.secretsmanager.sql.AWSSecretsManagerPostgreSQLDriver.<clinit>(AWSSecretsManagerPostgreSQLDriver.java:47)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:446)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:553)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:511)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:2602)
        at org.flywaydb.core.api.configuration.FluentConfiguration.configuration(FluentConfiguration.java:1587)
        at org.flywaydb.commandline.Main.main(Main.java:526)
Caused by: java.lang.ClassNotFoundException: com.amazonaws.secretsmanager.caching.SecretCache
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 11 more
```
because of these missing requirements. It would be ideal if this driver could be updated and missing dependencies bundled, so that it works out of the box [as the documentation suggests](https://flywaydb.org/documentation/configuration/secretsManagement). For EKS serviceaccount support the SDK needs to be pinned to a recent version, and the `aws-java-sdk-sts` explicitly added to the dependencies to ensure it's on the classpath (see: https://github.com/aws/aws-secretsmanager-jdbc/issues/50#issuecomment-755460783).

**Comment by DoodleBobBuffPants** [comment]
We've updated our version of AWS secrets manager

We will be looking into whether or not to ship the dependencies, as we need to consider its impact on people who aren't using this feature, but cannot commit to shipping the dependencies definitely, so in the mean time you will have to add them manually

**Comment by bobdoah** [comment]
This doesn't really help me. I am trying to use the [docker image](https://github.com/flyway/flyway-docker) in EKS. There isn't a succinct way of adding the dependencies, without being forced into building and maintaining my own image. The Docker image bundles all of the optional JDBC drivers, but without those dependencies this driver is pretty useless. Looking at the docker image, it simply unpacks the flyway-commandline tar.gz.

**Comment by DoodleBobBuffPants** [comment]
You would have to map those additional dependencies to the `jars` folder in the container, it shouldn't require rebuilding the image

You need to map them to the `jars` folder as this will add them to the classpath (see [this](https://flywaydb.org/documentation/addingToTheClasspath) for more details)

You can see an example mapping a folder to the `jars` directory [here](https://github.com/flyway/flyway-docker#example-3)

**Comment by bobdoah** [comment]
I'm aware of volume mounts. That works for docker-compose, but not Kubernetes. I'd have to have some way of downloading them beforehand, a batch job or initContainer or something. By far the easiest way than something that hacky is to just build another image on top of the flyway base.
