### ISSUE TITLE
Enabling flyway to an existing db fails

### ISSUE THREAD

**Issue by BVMarius** [flyway/flyway#3136]
Initially used "org.flywaydb:flyway-core:7.5.3" and run against a non empty database and was disabled after it failed with the same error as bellow, and then reenable after upgraded to "org.flywaydb:flyway-core:7.7.2".

The issue is reproducible with the old version as well.

We are using the Gradle plugin inside a Spring Boot application

Postgres database version 9.6.20

Linux and windows

The flyway_schema_history remains empty and the migration fails due to the 
```

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V1__baseline_migration.sql failed

`SQL State  : 42P07
Error Code : 0
Message    : ERROR: relation "xxxxx" already exists
Location   : db/migration/V1__baseline_migration.sql
Line       : 25
Statement  : CREATE TABLE public.xxxx(
    id uuid NOT NULL,
    title character varying(255),
    url character varying(255),
    company_id uuid,
    inserted_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL,
    external_id character varying(255)
)

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1159)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:913)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:588)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
	at eu.toyotaconnected.kinto.driver.api.DriverApiApplication.main(DriverApiApplication.java:20)
Caused by: org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V1__baseline_migration.sql failed`
```

I mention that  V1__baseline_migration.sql  was changed from old failed to new, however the same issue paper in the first time we tried to add flyway to our database.

The Spring boot configuration we used : 
spring.flyway.baseline-on-migrate=true

What can we do to avoid this kind of errors and to deploy the database?

Thank you in advance for your support,

**Comment by DoodleBobBuffPants** [comment]
It seems you are trying to apply a script that recreates your database

Our documentation for getting started is [here](https://flywaydb.org/documentation/learnmore/existing). but there are two ways to get started. First is by running [`baseline`](https://flywaydb.org/documentation/command/baseline) which introduces Flyway to an existing database. This doesn't require a migration that recreates your database to exist

The second approach is the one you have taken, but applying this migration fails as the contents of that migration already exist. In this case you will need to use [`skipExecutingMigrations`](https://flywaydb.org/documentation/configuration/parameters/skipExecutingMigrations) in order to mark the migration as already being applied

Either approach will get you set up with the new database
