### ISSUE TITLE
MSSQL: Flyway Clean - fails on persisted computed column using encrypted scalar function

### ISSUE THREAD

**Issue by zikato** [flyway/flyway#3144]
###### Which version and edition of Flyway are you using?
Flyway Community Edition 7.7.3 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Flyway docker - command line

###### Which database are you using? (Type & version)
Microsoft SQL Server 2019 (RTM-CU9) (KB5000642) - 15.0.4102.2 (X64) 
	Jan 25 2021 20:16:12 
	Copyright (C) 2019 Microsoft Corporation
	Developer Edition (64-bit) on Linux (Ubuntu 18.04.5 LTS) <X64>

###### Which operating system are you using?
Docker (Linux Ubuntu 18.04)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
This one is tricky because I cannot replicate the issue in isolation (even with all relevant dependencies) but it fails when part of the 100+ step migration.

> CREATE OR ALTER FUNCTION dbo.GetIP (@sIp varchar(15))
> RETURNS bigint
> WITH SCHEMABINDING, ENCRYPTION
> AS
> BEGIN
> 	RETURN 0
> END 
> GO
> 
> CREATE TABLE dbo.PersistedComputedScalarColumn
> (
> 	Pk	  int		  NOT NULL IDENTITY(1, 1),
> 	IpAdd varchar(15) NOT NULL,
> 	IpNum AS (dbo.GetIP(IpAdd)) PERSISTED,
> )
> GO
> 
> ALTER TABLE dbo.PersistedComputedScalarColumn
> ADD
> 	CONSTRAINT PK_PersistedComputedScalarColumn
> 	PRIMARY KEY CLUSTERED (Pk)
> GO
> 
> CREATE UNIQUE NONCLUSTERED INDEX IX_PersistedComputedScalarColumn#IpNum
> ON dbo.PersistedComputedScalarColumn (IpNum)
> 

Run `flyway clean -X`

DEBUG: Ignoring dependency-related error: Cannot DROP FUNCTION 'dbo.GetIP' because it is being referenced by object 'PersistedComputedScalarColumn'.

###### What did you expect to see?
Clean schema

###### What did you see instead?

ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException:                             '.
Unable to clean schema [dbo]
----------------------------
SQL State  : S0001                                                                   va:205)
Error Code : 5074                                                                    nsactionalExecutionTemplate.java:66)
Message    : The index 'IX_PersistedComputedScalarColumn#IpNum' is dependent on column 'IpNum'.

        at org.flywaydb.core.internal.database.base.Schema.clean(Schema.java:124)
        at org.flywaydb.core.internal.command.DbClean.lambda$cleanSchema$4(DbClean.java:205)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
        at org.flywaydb.core.internal.command.DbClean.cleanSchema(DbClean.java:204)
        at org.flywaydb.core.internal.command.DbClean.clean(DbClean.java:103)
        at org.flywaydb.core.Flyway.doClean(Flyway.java:346)
        at org.flywaydb.core.Flyway.access$400(Flyway.java:77)
        at org.flywaydb.core.Flyway$4.execute(Flyway.java:362)
        at org.flywaydb.core.Flyway$4.execute(Flyway.java:358)
        at org.flywaydb.core.Flyway.execute(Flyway.java:572)
        at org.flywaydb.core.Flyway.clean(Flyway.java:358)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:219)
        at org.flywaydb.commandline.Main.main(Main.java:144)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The index 'IX_PersistedComputedScalarColumn#IpNum' is dependent on column 'IpNum'.
        at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:262)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1632)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:602)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:524)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7418)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:3272)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:247)
        at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:222)
        at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:505)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:222)
        at org.flywaydb.core.internal.database.sqlserver.SQLServerSchema.doClean(SQLServerSchema.java:236)
        at org.flywaydb.core.internal.database.base.Schema.clean(Schema.java:122)
        ... 12 more

**Comment by DoodleBobBuffPants** [comment]
Based on the information provided we haven't been able to reproduce this

Are you able to provide a reproduction?

**Comment by zikato** [comment]
I couldn't reproduce it just with the one migration. I'll try to take my production scenario and delete the unrelated migrations and then anonymize the rest. Give me two days.

**Comment by zikato** [comment]
Sorry for the late reply. I couldn't reproduce with a minimal set without exposing my production code. I guess we'll have to close.
