### ISSUE TITLE
Allow application to start even if connection fails

### ISSUE THREAD

**Issue by tioback** [flyway/flyway#3146]
###### Which version and edition of Flyway are you using?

7.4.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes I can.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Quarkus

###### Which database are you using? (Type & version)

Postgres 10

###### Which operating system are you using?

Linux, MacOS and Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I'm writing a healthcheck to my app and I want it to go up even if Flyway fails to connect upon application start.
In other words, I'm using the "5 minutes tutorial" to run an create an application, then I turned I pointed the DB to an invalid address and tried to start the application.

###### What did you expect to see?

I expected to have an option to tell flyway to give a warning or something that would tell me it wasn't able to connect, instead of plain `System.exit(1)`.

Something like:

```java
// org.flywaydb.core.Flyway#execute (line ~542 at master)
// ... 
    this.failedState = false;
    // extracted it to a method to make it prettier
    result = doDatabaseExecution(all_the_necessary_parameters);
}

private <T> T createDatabase(all_the_necessary_parameters<T>) {
    Database database = null;
    try {
        // copy lines 544 through 580
    } catch (DataBaseConnectionException e) { // specific exception for said problem
        if (configuration.isFailOnDatabaseConnection) { // default = true
            throw e;
        }
        LOG.error("Unable to connect to database in order to run migrations. Moving to failed state.", e);
        this.failedState = true;
    } finally {
            IOUtils.close(database);
            showMemoryUsage();
    }
// ...

```

###### What did you see instead?

What I got was the default behaviour, which tries to connect and kills the application in case of errors.

I'll post a pull request later on.

**Comment by MikielAgutu** [comment]
Only the Flyway command line calls `System.exit`. If you're integrating Flyway into a Java application, then you should be using `flyway.core` - which is designed to be consumed as a Java library. `flyway.core` will produce an exception that you can catch if the connection fails.

Can you explain more about how you're using Flyway?

**Comment by tioback** [comment]
> Can you explain more about how you're using Flyway?

Hi, Mikiel.

I'm using Flyway through [Quarkus' automatic migration](https://quarkus.io/guides/flyway) default set up.

Basically, I add the maven dependencies to my `pom.xml`, put my scripts at the `/src/main/resources/db/migration` folder, add datasource config to my `application.properties` and enable the `migrate-at-start` option.

Thus, when I start the application, if flyway's connection attempts to the datasource fail, the application finishes.

This is the output:

```log
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-04-15 08:58:47,723 INFO  [io.qua.fly.FlywayProcessor] (build-18) Adding application migrations in path '/dev/workspace/quarkus-flyway-sample/target/classes/db/migration/' using protocol 'file'
2021-04-15 08:58:50,317 INFO  [org.fly.cor.int.lic.VersionPrinter] (Quarkus Main Thread) Flyway Community Edition 7.4.0 by Redgate
2021-04-15 08:59:00,373 WARN  [io.agr.pool] (agroal-11) Datasource 'migration': The connection attempt failed.
2021-04-15 08:59:00,374 WARN  [org.fly.cor.int.jdb.JdbcUtils] (Quarkus Main Thread) Connection error: The connection attempt failed. (Caused by connect timed out) Retrying in 1 sec...
2021-04-15 08:59:11,382 WARN  [io.agr.pool] (agroal-11) Datasource 'migration': The connection attempt failed.
2021-04-15 08:59:11,383 WARN  [org.fly.cor.int.jdb.JdbcUtils] (Quarkus Main Thread) Connection error: The connection attempt failed. (Caused by connect timed out) Retrying in 2 sec...
2021-04-15 08:59:23,390 WARN  [io.agr.pool] (agroal-11) Datasource 'migration': The connection attempt failed.
2021-04-15 08:59:23,441 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
2021-04-15 08:59:23,438 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile externos): java.net.SocketTimeoutException: connect timed out
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:609)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:231)
	at org.postgresql.core.PGStream.<init>(PGStream.java:95)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:225)
	at org.postgresql.Driver.makeConnection(Driver.java:465)
	at org.postgresql.Driver.connect(Driver.java:264)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:200)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:452)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:434)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:65)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1126)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

Quarkus application exited with code 1
Press Enter to restart or Ctrl + C to quit
```

**Comment by tioback** [comment]
As the Rubber Duck Theory comes into practice while I explain this issue to you, it just made me realize that it might not be a Flyway issue, after all. It seems like Quarkus is killing the application if the connection fails.

**Comment by MikielAgutu** [comment]
Shall I close this issue then - or do you still suspect an issue with Flyway?

**Comment by tioback** [comment]
I would rather have you wait until further investigation.
After all, the Exception is thrown by Flyway, it is just a matter of finding out where is it being captured or forwarded.
I'll keep you posted.

**Comment by tioback** [comment]
Mikiel, I'll  go ahead and close this issue.

Despite Flyway being the one that threw the exception, Quarkus itself was the one responsible for terminating the application.

In the end, I had to switch Flyway to run manually inside a bean associated with Quarkus' application lifecycle Startup phase.

Here's a sample:

```java
@Startup
@ApplicationScoped
public class MigrationService {

	private static final Logger LOGGER = LoggerFactory.getLogger(MigrationService.class);

	@Inject
	Flyway flyway;

        private boolean validState = false;

	void checkMigration() {
		LOGGER.info("Checking migration.");
		try {
			// Use the flyway instance manually
			flyway.clean();
			flyway.migrate();
			LOGGER.info("[FlyWay] DB Current Version: " + flyway.info().current().getVersion().toString());
                         validState = true;
		} catch (Exception e) {
			LOGGER.error("Something went wrong.", e);
		}
	}

        public boolean hasValidState() {
            return this.validState;
        }
}
```

I also had to set `quarkus.flyway.migrate-at-start=false` at `application.properties` in order to prevent `io.quarkus.flyway.FlywayProcessor` from running the integration automatically before my managed bean.

Thanks for waiting.
