### ISSUE TITLE
foreign_key_checks' cannot determine value type from string 'OFF'

### ISSUE THREAD

**Issue by aisensiy** [flyway/flyway#3151]
###### Which version and edition of Flyway are you using?

7.8.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API. 

Integration with spring boot at start. 

###### Which database are you using? (Type & version)

[Tidb 4.0.10](https://pingcap.com/en/) which may be compatible with mysql.

###### Which operating system are you using?

kubernetes with base image openjdk:8-jdk-alpine.

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Migration failed at the start of spring boot application with such error message below:

```
SQL State  : 22018
Error Code : 0
Message    : Cannot determine value type from string 'OFF'

	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1786)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at com.openbayes.OpenbayesServerApplication.main(OpenbayesServerApplication.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException:
Unable to determine value for 'foreign_key_checks' variable
```

https://github.com/flyway/flyway/blob/80e2006a44bd6c8c3fd2655a06405b03a3bb61bc/flyway-core/src/main/java/org/flywaydb/core/internal/database/mysql/MySQLConnection.java#L62 

the code here seems can not handle string type variables. I think it maybe the database's bug.

###### What did you expect to see?

Hope to handle `ON` `OFF` to `1` and `0`.

**Comment by DoodleBobBuffPants** [comment]
This is related to us adding TiDB support and is already captured in https://github.com/flyway/flyway/pull/2918
