### ISSUE TITLE
FlywayException: Delimiter changed inside statement

### ISSUE THREAD

**Issue by austek** [flyway/flyway#3152]
###### Which version and edition of Flyway are you using?
7.8.1, but tested with several versions post 7.2.0, where same sql was last working

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java Api

###### Which database are you using? (Type & version)
Mysql 5.7* and 8.2.*

###### Which operating system are you using?
Big Sur

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Run Flyway Migrate
```
CREATE PROCEDURE activity_cds_order_index_incrementer()
  BEGIN
    DECLARE orderIndex INT DEFAULT 1;
    DECLARE CDSUUID varchar(50);
    DECLARE done_activity, done_cds BOOLEAN DEFAULT FALSE;
    DECLARE visit_act_cur1 CURSOR FOR SELECT DISTINCT(`visit_activities_cds`.`client_division_scheme_uuid`) from `visit_activities_cds` WHERE `visit_activities_cds`.`visit_activity_uuid` IS NULL;
    DECLARE CONTINUE HANDLER FOR NOT FOUND SET done_activity = TRUE;
    SELECT MAX(`visit_activities`.`order_index`) + 1 FROM `visit_activities` INTO orderIndex;
    OPEN visit_act_cur1;

    read_loop1:
    LOOP FETCH visit_act_cur1 INTO CDSUUID;
      IF done_activity THEN
        CLOSE visit_act_cur1;
        LEAVE read_loop1;
      END IF;
      BLOCK1 : BEGIN
        DECLARE activityUUID varchar(50);
        DECLARE orderIndex2 INT DEFAULT orderIndex;
        DECLARE visit_act_cur2 CURSOR FOR SELECT `visit_activities_cds`.`uuid` from `visit_activities_cds` WHERE `visit_activities_cds`.`visit_activity_uuid` IS NULL  AND `visit_activities_cds`.`client_division_scheme_uuid` = CDSUUID;
        DECLARE CONTINUE HANDLER FOR NOT FOUND SET done_cds = TRUE;

        OPEN visit_act_cur2;
        read_loop2:
        LOOP FETCH visit_act_cur2 INTO activityUUID;
          IF  done_cds THEN
            CLOSE visit_act_cur2;
            SET done_cds = FALSE;
            LEAVE read_loop2;
          END IF;
          UPDATE `visit_activities_cds` SET `visit_activities_cds`.`order_index` = orderIndex2 where `visit_activities_cds`.`uuid` = activityUUID;
          set orderIndex2 = orderIndex2 + 1;


        END LOOP read_loop2;
      END BLOCK1;
    END LOOP read_loop1;
  End;
;;
```

###### What did you expect to see?

Migrate completes successfully 

###### What did you see instead?
```
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:313)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:727)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:693)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:77)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:122)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.executeInTransaction(ParserSqlScript.java:191)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.canExecuteInTransaction(SqlMigrationExecutor.java:83)
	at org.flywaydb.core.internal.command.DbMigrate.isExecuteGroupInTransaction(DbMigrate.java:291)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:257)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:234)
Caused by: org.flywaydb.core.api.FlywayException: Delimiter changed inside statement at line 351 col 1:
```

**Comment by DoodleBobBuffPants** [comment]
The SQL you have provided is invalid and causes a syntax exception when executed

Could you provide the exact SQL which should be correct but fails to parse?

**Comment by austek** [comment]
formatting error, SQL is copy/paste of the log printed
