### ISSUE TITLE
SQLite still executing in transaction with executeInTransaction=false ?

### ISSUE THREAD

**Issue by Leyren** [flyway/flyway#3165]
###### Which version and edition of Flyway are you using?
Flyway Free 7.8.2

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
SQLite

###### Which operating system are you using?
Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Created a script `V1_1_pragmas.sql`:
```sql
PRAGMA journal_mode=WAL;
PRAGMA foreign_keys=true;
```
and a config  `V1_1_pragmas.sql.config`
```
executeInTransaction=false
```

###### What did you expect to see?
Script gets correctly executed.

###### What did you see instead?
```
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: 
Migration V1_1__pragmas.sql failed
----------------------------------
SQL State  : null
Error Code : 1
Message    : [SQLITE_ERROR] SQL error or missing database (cannot change into wal mode from within a transaction)
Location   : db/migration/V1_1__pragmas.sql (<path>)
Line       : 1
Statement  : PRAGMA journal_mode=WAL

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:218)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:78)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:67)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:66)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:354)
	... 85 more
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (cannot change into wal mode from within a transaction)
	at org.sqlite.core.DB.newSQLException(DB.java:1012)
	at org.sqlite.core.DB.newSQLException(DB.java:1024)
	at org.sqlite.core.DB.execute(DB.java:866)
	at org.sqlite.core.CoreStatement.exec(CoreStatement.java:80)
	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:46)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
	... 91 more
```

```
15:35:23.447 [main] DEBUG o.f.c.i.s.JdbcTableSchemaHistory - Created Schema History table "main"."flyway_schema_history"
15:35:23.472 [main] DEBUG o.f.c.i.database.sqlite.SQLiteTable - Unable to lock "main"."flyway_schema_history" as SQLite does not support locking. No concurrent migration supported.
15:35:23.477 [main] INFO  o.f.core.internal.command.DbMigrate - Current version of schema "main": << Empty Schema >>
15:35:23.477 [main] DEBUG o.f.c.i.sqlscript.ParserSqlScript - Using executeInTransaction=false from script configuration
15:35:23.479 [main] DEBUG o.f.c.i.sqlscript.ParserSqlScript - Using executeInTransaction=false from script configuration
15:35:23.479 [main] DEBUG o.f.core.internal.command.DbMigrate - Starting migration of schema "main" to version "1.1 - pragmas" [non-transactional] ...
15:35:23.479 [main] INFO  o.f.core.internal.command.DbMigrate - Migrating schema "main" to version "1.1 - pragmas" [non-transactional]
15:35:23.483 [main] DEBUG o.f.core.internal.parser.Parser - Parsing V1_1__pragmas.sql ...
15:35:23.489 [main] DEBUG o.f.c.i.sqlscript.ParserSqlScript - Found statement at line 1: PRAGMA journal_mode=WAL
15:35:23.489 [main] DEBUG o.f.c.i.sqlscript.ParserSqlScript - Found statement at line 2: PRAGMA foreign_keys=true [non-transactional]
15:35:23.489 [main] DEBUG o.f.c.i.s.DefaultSqlScriptExecutor - Executing SQL: PRAGMA journal_mode=WAL
15:35:23.495 [main] DEBUG o.f.c.i.sqlscript.ParserSqlScript - Using executeInTransaction=false from script configuration
15:35:23.495 [main] ERROR o.f.core.internal.command.DbMigrate - Migration of schema "main" to version "1.1 - pragmas" [non-transactional] failed! Please restore backups and roll back database and code!
15:35:23.502 [main] DEBUG o.f.c.i.s.JdbcTableSchemaHistory - Schema History table "main"."flyway_schema_history" successfully updated to reflect changes
15:35:23.502 [main] DEBUG o.f.c.i.j.TransactionalExecutionTemplate - Rolling back transaction...
15:35:23.503 [main] DEBUG o.f.c.i.j.TransactionalExecutionTemplate - Transaction rolled back
```
I also tried using mixed mode instead, but that didn't help either. Am I doing something wrong? Executing the script outside of Flyway context works fine.

**Comment by Rixium** [comment]
Hey @Leyren ,

Thanks for reporting this.
I managed to reproduce it, and will look in to finding a fix.

**Comment by Rixium** [comment]
Hey @Leyran,

While we keep looking in to this, can you try specifying
`flyway.mixed=true `
within your flyway.conf file, this works for me.

If that fails, could you provide the output?

Thanks!

**Comment by Leyren** [comment]
Hi @Rixium, sadly that does not work for me.

 `flyway.conf`:
```ini
flyway.locations=classpath:db/migration
flyway.cleanDisabled=true
flyway.driver=org.sqlite.JDBC
flyway.mixed=true
```
Output:
```log
20:46:16.087 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Scanning for classpath resources at 'classpath:db/callback' ...
20:46:16.090 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Determining location urls for classpath:db/callback using ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@2626b418 ...
20:46:16.091 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Unable to resolve location classpath:db/callback.
20:46:16.108 [main] INFO  o.f.c.i.license.VersionPrinter - Flyway Community Edition 7.8.2 by Redgate
20:46:16.127 [main] DEBUG o.f.c.internal.util.FeatureDetector - AWS SDK available: false
20:46:16.132 [main] DEBUG o.f.c.internal.util.FeatureDetector - Google Cloud Storage available: false
20:46:16.132 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Scanning for classpath resources at 'classpath:db/migration' ...
20:46:16.132 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Determining location urls for classpath:db/migration using ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@2626b418 ...
20:46:16.133 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Scanning URL: file:/<...>/target/classes/db/migration
20:46:16.135 [main] DEBUG o.f.c.internal.util.FeatureDetector - JBoss VFS v2 available: false
20:46:16.144 [main] DEBUG o.f.c.i.s.c.FileSystemClassPathLocationScanner - Scanning starting at classpath root in filesystem: <...>\target\classes\
20:46:16.144 [main] DEBUG o.f.c.i.s.c.FileSystemClassPathLocationScanner - Scanning for resources in path: <...>\target\classes\db\migration (db/migration)
20:46:16.146 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Found resource: db/migration/V1_1__pragmas.sql
20:46:16.146 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Found resource: db/migration/V1_1__pragmas.sql.conf
20:46:16.146 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Found resource: db/migration/V1_2__setup_tables.sql
20:46:16.146 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Found resource: db/migration/V1_4__data.sql
20:46:16.146 [main] DEBUG o.f.c.i.s.classpath.ClassPathScanner - Scanning for classes at classpath:db/migration
20:46:16.314 [main] INFO  o.f.c.i.d.base.BaseDatabaseType - Database: jdbc:sqlite:<...>\test-db.sqlite (SQLite 3.34)
20:46:16.314 [main] DEBUG o.f.c.i.d.base.BaseDatabaseType - Driver  : SQLite JDBC 3.34.0
20:46:16.320 [main] DEBUG org.flywaydb.core.Flyway - DDL Transactions Supported: true
20:46:16.321 [main] DEBUG org.flywaydb.core.Flyway - Schemas: 
20:46:16.321 [main] DEBUG org.flywaydb.core.Flyway - Default schema: null
20:46:16.338 [main] DEBUG o.f.c.i.c.SqlScriptCallbackFactory - Scanning for SQL callbacks ...
20:46:16.338 [main] DEBUG o.f.core.internal.scanner.Scanner - Filtering out resource: db/migration/V1_1__pragmas.sql.conf (filename: V1_1__pragmas.sql.conf)
20:46:16.376 [main] DEBUG o.f.core.internal.command.DbValidate - Validating migrations ...
20:46:16.392 [main] DEBUG o.f.core.internal.scanner.Scanner - Filtering out resource: db/migration/V1_1__pragmas.sql.conf (filename: V1_1__pragmas.sql.conf)
20:46:16.403 [main] DEBUG o.f.c.i.sqlscript.SqlScriptMetadata - Found script configuration: V1_1__pragmas.sql.conf
20:46:16.427 [main] DEBUG o.f.core.internal.scanner.Scanner - Filtering out resource: db/migration/V1_1__pragmas.sql (filename: V1_1__pragmas.sql)
20:46:16.427 [main] DEBUG o.f.core.internal.scanner.Scanner - Filtering out resource: db/migration/V1_1__pragmas.sql.conf (filename: V1_1__pragmas.sql.conf)
20:46:16.427 [main] DEBUG o.f.core.internal.scanner.Scanner - Filtering out resource: db/migration/V1_2__setup_tables.sql (filename: V1_2__setup_tables.sql)
20:46:16.427 [main] DEBUG o.f.core.internal.scanner.Scanner - Filtering out resource: db/migration/V1_4__data.sql (filename: V1_4__data.sql)
20:46:16.442 [main] INFO  o.f.core.internal.command.DbValidate - Successfully validated 3 migrations (execution time 00:00.063s)
20:46:16.454 [main] DEBUG o.f.core.internal.command.DbSchemas - Skipping creation of existing schema: "main"
20:46:16.462 [main] INFO  o.f.c.i.s.JdbcTableSchemaHistory - Creating Schema History table "main"."flyway_schema_history" ...
20:46:16.475 [main] DEBUG o.f.core.internal.parser.Parser - Parsing  ...
20:46:16.490 [main] DEBUG o.f.c.i.sqlscript.ParserSqlScript - Found statement at line 1: CREATE TABLE "main"."flyway_schema_history" (
    "installed_rank" INT NOT NULL PRIMARY KEY,
    "version" VARCHAR(50),
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INT,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')),
    "execution_time" INT NOT NULL,
    "success" BOOLEAN NOT NULL
)
20:46:16.490 [main] DEBUG o.f.c.i.sqlscript.ParserSqlScript - Found statement at line 13: CREATE INDEX "main"."flyway_schema_history_s_idx" ON "flyway_schema_history" ("success")
20:46:16.492 [main] DEBUG o.f.c.i.s.DefaultSqlScriptExecutor - Executing SQL: CREATE TABLE "main"."flyway_schema_history" (
    "installed_rank" INT NOT NULL PRIMARY KEY,
    "version" VARCHAR(50),
    "description" VARCHAR(200) NOT NULL,
    "type" VARCHAR(20) NOT NULL,
    "script" VARCHAR(1000) NOT NULL,
    "checksum" INT,
    "installed_by" VARCHAR(100) NOT NULL,
    "installed_on" TEXT NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%f','now')),
    "execution_time" INT NOT NULL,
    "success" BOOLEAN NOT NULL
)
20:46:16.500 [main] DEBUG o.f.c.i.s.DefaultSqlScriptExecutor - 0 rows affected
20:46:16.500 [main] DEBUG o.f.c.i.s.DefaultSqlScriptExecutor - Executing SQL: CREATE INDEX "main"."flyway_schema_history_s_idx" ON "flyway_schema_history" ("success")
20:46:16.501 [main] DEBUG o.f.c.i.s.DefaultSqlScriptExecutor - 0 rows affected
20:46:16.502 [main] DEBUG o.f.c.i.s.JdbcTableSchemaHistory - Created Schema History table "main"."flyway_schema_history"
20:46:16.520 [main] DEBUG o.f.c.i.database.sqlite.SQLiteTable - Unable to lock "main"."flyway_schema_history" as SQLite does not support locking. No concurrent migration supported.
20:46:16.524 [main] INFO  o.f.core.internal.command.DbMigrate - Current version of schema "main": << Empty Schema >>
20:46:16.524 [main] DEBUG o.f.core.internal.parser.Parser - Parsing V1_1__pragmas.sql ...
20:46:16.528 [main] DEBUG o.f.c.i.sqlscript.ParserSqlScript - Found statement at line 1: PRAGMA journal_mode=WAL
20:46:16.532 [main] DEBUG o.f.c.i.sqlscript.ParserSqlScript - Found statement at line 2: PRAGMA foreign_keys=true [non-transactional]
20:46:16.535 [main] DEBUG o.f.core.internal.command.DbMigrate - Starting migration of schema "main" to version "1.1 - pragmas" [non-transactional] ...
20:46:16.535 [main] INFO  o.f.core.internal.command.DbMigrate - Migrating schema "main" to version "1.1 - pragmas" [non-transactional]
20:46:16.539 [main] DEBUG o.f.c.i.s.DefaultSqlScriptExecutor - Executing SQL: PRAGMA journal_mode=WAL
20:46:16.545 [main] ERROR o.f.core.internal.command.DbMigrate - Migration of schema "main" to version "1.1 - pragmas" [non-transactional] failed! Please restore backups and roll back database and code!
20:46:16.554 [main] DEBUG o.f.c.i.s.JdbcTableSchemaHistory - Schema History table "main"."flyway_schema_history" successfully updated to reflect changes
20:46:16.555 [main] DEBUG o.f.c.i.j.TransactionalExecutionTemplate - Rolling back transaction...
20:46:16.564 [main] DEBUG o.f.c.i.j.TransactionalExecutionTemplate - Transaction rolled back
20:46:16.567 [main] DEBUG org.flywaydb.core.Flyway - Memory usage: 76 of 512M
May 06, 2021 8:46:16 PM <...>SQLiteDB start
SEVERE: Error when executing database migration.
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: 
Migration V1_1__pragmas.sql failed
----------------------------------
SQL State  : null
Error Code : 1
Message    : [SQLITE_ERROR] SQL error or missing database (cannot change into wal mode from within a transaction)
Location   : db/migration/V1_1__pragmas.sql (<...>\target\classes\db\migration\V1_1__pragmas.sql)
Line       : 1
Statement  : PRAGMA journal_mode=WAL

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:357)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:266)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:234)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:140)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:38)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:33)
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:103)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:141)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:140)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:100)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:214)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:165)
	at org.flywaydb.core.Flyway.execute(Flyway.java:569)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:165)
```
