### ISSUE TITLE
Java Errors (e.g. OutOfMemoryError) thrown during migration do not trigger transaction rollback

### ISSUE THREAD

**Issue by dackroyd** [flyway/flyway#3193]
###### Which version and edition of Flyway are you using?

5.4.2 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Yes, reproducible on 7.9.1 (latest at the current time), but required a smaller max heap to be imposed.

The issue is also _much_ more difficult to trigger with the newer versions, as typically memory is exhausted while parsing the statements for the script _before_ anything is executed. I believe this is a change to the implementation, whereas previously the script was parsed as it was executed, so memory consumption would increase as the script was executed instead of mostly being _before_ the script was executed.

With this in mind, I included statements in the migration script which also _returned_ a lot of data (`SELECT * FROM <table>`) to force the OOM situation to be triggered _during_ execution. It doesn't always fail in the same way, but there are definitely cases where the transaction is committed despite the OOM.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

Postgres 11.5

###### Which operating system are you using?

Alpine Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Running a large set of migration scripts with `flyway migrate`, under a constrained max JVM heap (~300MB) triggering an OutOfMemoryError part way through migration.

Flyway 5.4.2

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuilder.append(StringBuilder.java:136)
        at org.flywaydb.core.internal.sqlscript.AbstractSqlStatement.getSql(AbstractSqlStatement.java:70)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:94)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:77)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:367)
        at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:54)
        at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:284)
        at org.flywaydb.core.internal.jdbc.TransactionTemplate.execute(TransactionTemplate.java:74)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:281)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
        at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:54)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:164)
        at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:161)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:71)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:104)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:155)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:161)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:139)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1395)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:1356)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1711)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:1356)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:161)
        at org.flywaydb.commandline.Main.main(Main.java:108)
```

Flyway 7.9.1

Does not print a stacktrace, so can't see where it is triggered

```
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
ERROR: 1
```

From the postgres logs (with statement logging enabled) I can see that a `COMMIT` is performed by Flyway, despite the OOM

```
2021-06-03 03:24:38.082 UTC [151] LOG:  execute <unnamed>: /*NO LOAD BALANCE*/
       SELECT "installed_rank","version","description","type","script","checksum","installed_on","installed_by","execution_time","success" FROM "public"."flyway_schema_history" WHERE "installed_rank" > $1 ORDER BY "installed_rank"
2021-06-03 03:24:38.082 UTC [151] DETAIL:  parameters: $1 = '155'
2021-06-03 03:24:38.117 UTC [151] LOG:  execute S_2: BEGIN
2021-06-03 03:24:38.117 UTC [151] LOG:  execute S_3: SET ROLE '<my role>'
2021-06-03 03:24:38.118 UTC [151] LOG:  execute <unnamed>: SELECT COUNT(*) FROM pg_namespace WHERE nspname=$1
2021-06-03 03:24:38.118 UTC [151] DETAIL:  parameters: $1 = 'public'
2021-06-03 03:24:38.119 UTC [151] LOG:  execute <unnamed>: SELECT set_config('search_path', $1, false)
2021-06-03 03:24:38.119 UTC [151] DETAIL:  parameters: $1 = '"public","$user", public'
2021-06-03 03:24:38.121 UTC [151] LOG:  execute <unnamed>: SELECT version()
2021-06-03 03:24:38.121 UTC [151] LOG:  execute <unnamed>: SELECT version()
2021-06-03 03:24:38.126 UTC [151] LOG:  execute <unnamed>: DELETE FROM public.<some table> WHERE id = 2
2021-06-03 03:24:38.129 UTC [151] LOG:  execute <unnamed>: SELECT * FROM public.<other table>
2021-06-03 03:24:41.065 UTC [151] LOG:  execute S_1: COMMIT
2021-06-03 03:24:41.072 UTC [151] LOG:  execute <unnamed>: SELECT pg_advisory_unlock(77433833903597)
2021-06-03 03:24:41.073 UTC [151] LOG:  execute S_3: SET ROLE '<my role>'
2021-06-03 03:24:41.076 UTC [151] LOG:  execute S_2: BEGIN
2021-06-03 03:24:41.076 UTC [151] LOG:  execute <unnamed>: SELECT set_config('search_path', $1, false)
2021-06-03 03:24:41.076 UTC [151] DETAIL:  parameters: $1 = '"$user", public'
2021-06-03 03:24:41.077 UTC [151] LOG:  execute S_1: COMMIT
```

###### What did you expect to see?

Migration script being processed at the time has its transaction rolled back either explicitly in response to the failure, or automatically when the connection is closed with the transaction still open.

###### What did you see instead?

Partially executed migration is explicitly committed by flyway before aborting, leaving the DB in a bad state.

**Comment by DoodleBobBuffPants** [comment]
`SELECT` statements lead to an OoM error after they execute, which is why they are committed

Are you encountering an OoM error on other statements in the latest version of Flyway?

While we _could_ catch errors, clean up isn't guaranteed or safe. We'll consider solutions in the mean time and will come back to this should others encounter the same issue, but closing for now

**Comment by dackroyd** [comment]
> Are you encountering an OoM error on other statements in the latest version of Flyway?

I've yet to reproduce a case outside of `SELECT`, but by its very nature, it is difficult to _reliably_ reproduce. It could happen for other statements, _if_ they trigger the OoM condition through handling of the DB response. As I understand it this isn't only results (e.g. from a `SELECT`), but also warnings from the database (and maybe some other things?)

> While we could catch errors, clean up isn't guaranteed or safe.

I appreciate that any `Error` condition makes clean up difficult. OoM especially so, since you need to allocate memory to invoke any additional actions, which itself is problematic given the error is because of a lack of memory.

In practice here, the `COMMIT` is done through the `finally`, where it attempts to reset the 'auto commit' mode for the connection back to 'on'. In doing so, any open tx is committed. In the `catch` case, an `Exception` would trigger a rollback (except where 'rollback on exception' is disabled). In the case of an `Error` however, no rollback is attempted (as the `catch` is not triggered), and the `finally` goes on to commit the tx anyway. If it succeeds in doing that before the application dies, then the incomplete tx is committed to the DB, leaving it in a bad state.

```
    public <T> T execute(Callable<T> callback) {
        boolean oldAutocommit = true;
        try {
            oldAutocommit = connection.getAutoCommit();
            connection.setAutoCommit(false);
            T result = callback.call();
            connection.commit();
            return result;
        } catch (Exception e) {
            RuntimeException rethrow;
            if (e instanceof SQLException) {
                rethrow = new FlywaySqlException("Unable to commit transaction", (SQLException) e);
            } else if (e instanceof RuntimeException) {
                rethrow = (RuntimeException) e;
            } else {
                rethrow = new FlywayException(e);
            }

            if (rollbackOnException) {
                try {
                    LOG.debug("Rolling back transaction...");
                    connection.rollback();
                    LOG.debug("Transaction rolled back");
                } catch (SQLException se) {
                    LOG.error("Unable to rollback transaction", se);
                }
            } else {
                try {
                    connection.commit();
                } catch (SQLException se) {
                    LOG.error("Unable to commit transaction", se);
                }
            }
            throw rethrow;
        } finally {
            try {
                connection.setAutoCommit(oldAutocommit);
            } catch (SQLException e) {
                LOG.error("Unable to restore autocommit to original value for connection", e);
            }
        }
```

I imagine it is _also_ possible in the rollback case for that to fail (while still leaving the tx open), but the `finally` to actually commit the tx. That however would likely be even more difficult to reproduce.

**Comment by dackroyd** [comment]
Managed to reproduce the issue when generating many warnings via `RAISE` as part of a migration. This was from intentionally trying to trigger the issue by outputting them (not from a genuine need to produce this output), but perhaps invoking a chatty function is normal for some users?
