### ISSUE TITLE
make "Migrations have failed validation" error info more detail in class org.flywaydb.core.internal.command.DbValidate

### ISSUE THREAD

**Issue by cuivip** [flyway/flyway#3234]
###### Which version and edition of Flyway are you using?
7.1.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I had read the source code , and the problem still there.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
java api

###### Which database are you using? (Type & version)
mysql 5.7

###### Which operating system are you using?
windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
for example,a sql script V4.0.11.15__make_user_name_bigger.sql  has been migrated and in table  "flyway_schema_history"  there is  a record of script V4.0.11.15__make_user_name_bigger.sql . 

For whatever reason   I change the content in V4.0.11.15__make_user_name_bigger.sql , when start my spring application, an error print in console  as below. ** I want to know witch script failed !!!**
```
Caused by: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:172)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:164)
	at org.flywaydb.core.Flyway.execute(Flyway.java:538)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:164)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	... 181 common frames omitted
```

###### What did you expect to see?
I want to see an useful exception info , which store  in  instant of  **ValidateOutput**   

```
Migration checksum mismatch for migration version 4.0.11.15
-> Applied to database : -103012101
-> Resolved locally    : -984332536. Either revert the changes to the migration, or run repair to update the schema history.
```

###### What did you see instead?
Can someone change the code in  org.flywaydb.core.internal.command.DbValidate  at line 186 
make the ErrorDetails contain  a detail info from ValidateOutput ,this is very important for truble shoot.
```
validationError = new ErrorDetails(ErrorCode.VALIDATE_ERROR, "Migrations have failed validation");
callbackExecutor.onEvent(Event.AFTER_VALIDATE_ERROR);
```

**Comment by tjs145** [comment]
This has already been fixed, so you'll need to update to the latest version.
