### ISSUE TITLE
Unsupported Database: PostgreSQL 11.12

### ISSUE THREAD

**Issue by codemonstur** [flyway/flyway#3235]
###### Which version and edition of Flyway are you using?

Flyway: 7.11.3 (latest)
Java: 16
PostgresJDBC: 42.2.23 (latest)

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java app.

###### Which database are you using? (Type & version)

PostgreSQL 11.

###### Which operating system are you using?

Windows / linux (debian) in WSL

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Initially I was getting this error:

    Exception in thread "main" org.flywaydb.core.api.FlywayException: No database found to handle jdbc:postgresql://localhost:5432/db

I was using this code: `Flyway.configure().initSql("").locations("/db/migration").dataSource(url, user, pass).load().migrate();`
I then realized that HikariCp had no trouble accessing the DB so I rewrote the code to this: `Flyway.configure().initSql("").locations("/db/migration").dataSource(ds).load().migrate();`. Which gave me this error:

    Exception in thread "main" org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 11.12
        at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:141)
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:69)
        at org.flywaydb.core.Flyway.execute(Flyway.java:510)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:170)

I then found [this](https://github.com/flyway/flyway/issues/3168) issue. And rewrote the code to this: ` Flyway.configure(MyContainingClass.class.getClassLoader()).initSql(init).locations(location).dataSource(ds).load().migrate();`. But the problem remains.
Also tried downgrading to 7.10.0. Didn't work.

###### What did you expect to see?

No error, migrated DB.

###### What did you see instead?

Exception and no migrated DB.

**Comment by codemonstur** [comment]
Downgraded to 7.7.3. Now it works.

**Comment by DoodleBobBuffPants** [comment]
Could you try passing in a classloader that comes from an instance of `MyContainingClass` i.e. `new MyContainingClass().getClass().getClassLoader()`

**Comment by codemonstur** [comment]
Looks like I messed things up myself. I was getting complaints from the maven-shader that there were module-info classes. I had configured the shader to delete those using `<exclude>module-info.class</exclude>`. But for some reason it continued to display the error. So I added an exclude for everything in `/META-INF`. That turns out to have been too rigorous :). 

Some more testing and it turns out that adding `<exclude>**/module-info.class</exclude>` in addition to the exclude above makes the shader warning go away and now Flyway no longer fails.

**Comment by DoodleBobBuffPants** [comment]
Thanks for sharing :)

**Comment by brenoma** [comment]
I'm having this problem

`Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: MySQL 8.0
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:106) ~[flyway-core-8.4.1.jar:na]
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75) ~[flyway-core-8.4.1.jar:na]
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:143) ~[flyway-core-8.4.1.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[flyway-core-8.4.1.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.6.2.jar:2.6.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.14.jar:5.3.14]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.14.jar:5.3.14]
	... 23 common frames omitted`

The easisest way is Downgrading Flyway?
