### ISSUE TITLE
Cannot connect to Oracle database using LDAPS

### ISSUE THREAD

**Issue by kausrga** [flyway/flyway#3325]
Wish to open issue #2526 again
We finally got down to upgrading flyway to V7 and oracle to V19

Test3:
gradle version - 6.5.1
Java version - 11.0.7
flyway (and flyway gradle plugin) version - 7.14.0

Still getting the same error as Test3 below.

Text from original issue
--------------------------
Test 1:
gradle version - 4.10
Java version - 8.212
flyway (and flyway gradle plugin) version - 4.0.3
DB - oracle version 12.1
oracle driver used - ojdbc8:12.2.0.2.jar
url used - jdbc:oracle:thin:@ldaps://host:port/tns,CN=OracleContext,dc=name,dc=com
command used - ./gradlew -Doracle.net.ldap.ssl.supportedVersions=TLSv1.2 flywayInfo

Result: works fine and as expected

Test 2:
gradle version - 5.6.2
Java version - 11.0.4
flyway (and flyway gradle plugin) version - 5.1.4
DB - (same as test 1)
oracle driver used - (same as test 1)
url used - (same as test 1)
command used - (same as test 1)

Result: throws an error
error:
SQL State : 08006
Error Code : 17002
Message : IO Error: JNDI Package failure javax.naming.CommunicationException: : [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]

at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:60)
at org.flywaydb.core.internal.database.DatabaseFactory.createDatabase(DatabaseFactory.java:72)
at org.flywaydb.core.Flyway.execute(Flyway.java:1670)
at org.flywaydb.core.Flyway.info(Flyway.java:1521)
at org.flywaydb.gradle.task.FlywayInfoTask.run(FlywayInfoTask.java:32)
at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:489)
.....
Caused by: java.sql.SQLRecoverableException: IO Error: JNDI Package failure javax.naming.CommunicationException: <host>:<port> [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]
at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:774)
at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:433)
at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:399)
at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
.....
Caused by: oracle.net.ns.NetException: JNDI Package failure javax.naming.CommunicationException: <host>:<port> [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]
at oracle.net.jndi.JndiAttrs.initializeLDAPContext(JndiAttrs.java:183)
at oracle.net.jndi.JndiAttrs.<init>(JndiAttrs.java:162)
at oracle.net.resolver.AddrResolution.<init>(AddrResolution.java:233)
at oracle.net.ns.NSProtocol.connect(NSProtocol.java:233)
at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1474)
at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)
.....
Caused by: javax.naming.CommunicationException: <host>:<port> [Root exception is java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory]
at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:237)
at java.naming/com.sun.jndi.ldap.LdapClient.<init>(LdapClient.java:137)
at java.naming/com.sun.jndi.ldap.LdapClient.getInstance(LdapClient.java:1610)
at java.naming/com.sun.jndi.ldap.LdapCtx.connect(LdapCtx.java:2752)
at java.naming/com.sun.jndi.ldap.LdapCtx.<init>(LdapCtx.java:320)
at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURL(LdapCtxFactory.java:192)
at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getUsingURLs(LdapCtxFactory.java:210)
at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getLdapCtxInstance(LdapCtxFactory.java:153)
at java.naming/com.sun.jndi.ldap.LdapCtxFactory.getInitialContext(LdapCtxFactory.java:83)
at oracle.net.jndi.JndiAttrs.initializeLDAPContext(JndiAttrs.java:175)
....
Caused by: java.lang.ClassNotFoundException: oracle.net.jndi.LDAPSSLSocketFactory
at java.naming/com.sun.jndi.ldap.VersionHelper.loadClass(VersionHelper.java:76)
at java.naming/com.sun.jndi.ldap.Connection.createSocket(Connection.java:275)
at java.naming/com.sun.jndi.ldap.Connection.<init>(Connection.java:216)

**Comment by kausrga** [comment]
Any update on this please? We are needing to decommission our old LDAP server. So this is really crutial

**Comment by kausrga** [comment]
@DoodleBobBuffPants Sorry I didnt explicitly mention in the description. We did indeed update our driver to 19.6 as will, along with the database upgrade.

**Comment by kausrga** [comment]
@DoodleBobBuffPants Are you using LDAPS url? Please look at #2521 for a history of the issue.
I am already using latest driver

**Comment by DoodleBobBuffPants** [comment]
Could you link to or upload the driver you are using

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity or we can get a reproduction

**Comment by kausrga** [comment]
@DoodleBobBuffPants hi, sorry, this got dropped out of my radar. I ended up using the docker image to run the migration. The issue seems to be only in the Gradle plugin. It always creates an instance of a DataSource that is not taken from the driver being used, and that instance throws error when LDAPS is tried. If you decide to work on this and need any more info let me know.
