### ISSUE TITLE
flyway-sqlserver not loaded, not available

### ISSUE THREAD

**Issue by djechelon** [flyway/flyway#3364]
###### Which version and edition of Flyway are you using?
8.2.3 free

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle Plugin

###### Which database are you using? (Type & version)
SQL Server 2017 on Docker

###### Which operating system are you using?
Host: Windows 11
Docker container: Linux (official image from Microsoft SQL Server)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I added both flyway-core **and** flyway-sqlserver to Gradle

```groovy
    // Flyway DB
    implementation 'org.flywaydb:flyway-core:8.2.3'
    implementation 'org.flywaydb:flyway-sqlserver:8.2.3'
    testImplementation 'org.flywaydb.flyway-test-extensions:flyway-spring-test:7.0.0'
```

Then I tried to run my Spring Boot application, which is configured to point the data source to SQL Server.

###### What did you expect to see?

First, I expected IntelliJ IDEA to show me the JAR into the classpath, but it's not working

![Intellij](https://user-images.githubusercontent.com/3042285/147166176-d3709f4e-1341-452a-ab01-b0842abddfca.png)

Secondarily, I expected the application to start and self migrate

###### What did you see instead?

Spring Boot fails with an error

```
2021-12-23 00:21:03.809  INFO 1360 --- [  restartedMain] i.o.a.backend.AmlControlliBeApplication  : Starting AmlControlliBeApplication using Java 11.0.10 on DESKTOP-9C9RHJH with PID 1360 (C:\Users\admin\IdeaProjects\aml-controlli-be\build\classes\java\main started by admin in C:\Users\admin\IdeaProjects\aml-controlli-be)
2021-12-23 00:21:03.809 DEBUG 1360 --- [  restartedMain] i.o.a.backend.AmlControlliBeApplication  : Running with Spring Boot v2.6.1, Spring v5.3.13
2021-12-23 00:21:03.809  INFO 1360 --- [  restartedMain] i.o.a.backend.AmlControlliBeApplication  : The following profiles are active: auth_ccb_token
2021-12-23 00:21:07.762 DEBUG 1360 --- [  restartedMain] i.o.a.b.config.SecurityConfiguration     : Using an ephemeral key
2021-12-23 00:21:07.793  INFO 1360 --- [  restartedMain] .FileRepositoryServiceLocalDirectoryImpl : Initializing File Repository in directory C:\orbitLog
2021-12-23 00:21:28.981  WARN 1360 --- [l-1 housekeeper] com.zaxxer.hikari.pool.HikariPool        : HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=50s750ms418µs200ns).
2021-12-23 00:21:28.997  WARN 1360 --- [  restartedMain] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Unsupported Database: Microsoft SQL Server 14.0
2021-12-23 00:21:29.153 ERROR 1360 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Unsupported Database: Microsoft SQL Server 14.0
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[spring-boot-2.6.1.jar:2.6.1]
	at it.orbit.amlc.backend.AmlControlliBeApplication.main(AmlControlliBeApplication.java:37) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.6.1.jar:2.6.1]
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: Microsoft SQL Server 14.0
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:106) ~[flyway-core-8.2.2.jar:na]
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75) ~[flyway-core-8.2.2.jar:na]
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:143) ~[flyway-core-8.2.2.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124) ~[flyway-core-8.2.2.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-2.6.1.jar:2.6.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.13.jar:5.3.13]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.13.jar:5.3.13]
	... 23 common frames omitted

Disconnected from the target VM, address: '127.0.0.1:53756', transport: 'socket'

Process finished with exit code 0
```

Ticket is sibling to #3355, but there is a fundamental difference. The other ticket is related to running flyway on Gradle, this is related to starting the entire Spring Boot application with Flyway

**Comment by djechelon** [comment]
After further investigation, it **has** to be some problem with IntelliJ IDEA. Even after downgrading flyway to 7.1.4, the stack traces report flyway 8.2.2 as current version.

**Comment by djechelon** [comment]
Confirmed. After removing, re-instating the project in IntelliJ IDEA Spring Boot starts.
The _sibling_ issue is still active for me
