### ISSUE TITLE
PluginManager.getPlugins() not finding MySQL (testing TiDB support)

### ISSUE THREAD

**Issue by noobgramming** [flyway/flyway#3374]
###### Which version and edition of Flyway are you using?
8.4.0 Community Edition

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
5.7.25-TiDB-v5.2.3

###### Which operating system are you using?
*nix

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
initializing Flyway through Java

###### What did you expect to see?
FLyway migration successful

###### What did you see instead?
`org.flywaydb.core.api.FlywayException: No database found to handle jdbc:mysql://127.0.0.1:1234/databasename
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:55) ~[XXX.jar:?]
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109) ~[app.jar:?]
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:80) ~[app.jar:?]
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:958) ~[app.jar:?]
	at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:683) ~[app.jar:?]

I have tried to track this down. I am confused that MySQL and TiDB plugins do not seem to be detected at all?
When it does database support check I expected to see TiDBDatabaseType there, but its not present. Neither is MySQL. See attached screenshot of debugging DatabaseTypeRegister.getDatabaseTypesForUrl()
[screenshot of detected databases](https://ibb.co/HhdwBR0)

am I doing something wrong or is this a bug?

**Comment by tjs145** [comment]
Have you included both the `flyway-community-db-support` and `flyway-mysql` dependencies?

**Comment by noobgramming** [comment]
I did not! That fixed it right away, thanks!

Perhaps you could put a big warning somewhere since it wasn't required pre-8 . Sorry to waste your time
