### ISSUE TITLE
Usage/troubleshooting: Connection refused in CI

### ISSUE THREAD

**Issue by carlpett** [flyway/flyway#3377]
###### Which version and edition of Flyway are you using?
8.4.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using? (Type & version)
Postgresql 13

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I'm trying to run Flyway in Google Cloud Build, but having issues getting it to work, and understanding the problem. 
First off, things Work On My Machine(tm), even when running the same container image as I later run in Cloud Build. The image executes this CLI command:
```bash
./flyway -X \
  -community \
  -url='jdbc:postgresql:///<my-instance>?cloudSqlInstance=<project>:<region>:<instance>&socketFactory=com.google.cloud.sql.postgres.SocketFactory&enableIamAuth=true&ipTypes=PRIVATE' \
  -user=<project>@cloudbuild \
  -password=ignored-but-required \
  -locations=filesystem:${MIGRATIONS_PATH} \
  info # during testing...
```

Executed locally, this works fine.

The environment is somewhat specifically configured, and I'm unsure where the issue arises.
- Google Cloud SQL/Postgresql, with Private endpoint only
- Running Flyway on Google Cloud Build, in Private Worker Pool mode (required to connect to private endpoint Cloud SQL)
- Image contains latest version (1.4.2) of https://github.com/GoogleCloudPlatform/cloud-sql-jdbc-socket-factory/

###### What did you expect to see?
Working connection, info returned

###### What did you see instead?
```
Jan 14, 2022 10:35:09 PM com.google.cloud.sql.core.CoreSocketFactory connect
INFO: Connecting to Cloud SQL instance [<instance>] via SSL socket.
Jan 14, 2022 10:35:09 PM com.google.cloud.sql.core.CoreSocketFactory getInstance
INFO: First Cloud SQL connection, generating RSA key pair.
DEBUG: Loading config file: /flyway/conf/flyway.conf
DEBUG: Unable to load config file: /flyway/flyway.conf
DEBUG: Unable to load config file: /workspace/flyway.conf
DEBUG: Using configuration:
DEBUG: flyway.jarDirs -> /flyway/jars
DEBUG: flyway.locations -> filesystem:./migrations
DEBUG: flyway.password -> ********************
DEBUG: flyway.url -> jdbc:postgresql:///<db-name>?cloudSqlInstance=<instance>&socketFactory=com.google.cloud.sql.postgres.SocketFactory&enableIamAuth=true&ipTypes=PRIVATE
DEBUG: flyway.user -> <project-id>@cloudbuild
DEBUG: Multiple databases found that handle url 'jdbc:postgresql:///<db-name>?cloudSqlInstance=<instance>&socketFactory=com.google.cloud.sql.postgres.SocketFactory&enableIamAuth=true&ipTypes=PRIVATE': CockroachDB, YugabyteDB, PostgreSQL
ERROR: Unexpected error
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to obtain connection from database (jdbc:postgresql:///<db-name>?cloudSqlInstance=<instance>&socketFactory=com.google.cloud.sql.postgres.SocketFactory&enableIamAuth=true&ipTypes=PRIVATE) for user '<project-id>@cloudbuild': Connection to :5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
SQL State  : 08001
Error Code : 0
Message    : Connection to :5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:67)
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:74)
        at org.flywaydb.commandline.Main.main(Main.java:148)
Caused by: org.postgresql.util.PSQLException: Connection to :5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:303)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:51)
        at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
        at org.postgresql.Driver.makeConnection(Driver.java:465)
        at org.postgresql.Driver.connect(Driver.java:264)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:259)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:223)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:52)
        ... 2 more
Caused by: java.net.ConnectException: Connection timed out (Connection timed out)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
        at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
        at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
        at java.base/java.net.Socket.connect(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.connect(Unknown Source)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(Unknown Source)
        at com.google.cloud.sql.core.CoreSocketFactory.createSslSocket(CoreSocketFactory.java:303)
        at com.google.cloud.sql.core.CoreSocketFactory.connect(CoreSocketFactory.java:252)
        at com.google.cloud.sql.postgres.SocketFactory.createSocket(SocketFactory.java:76)
        at org.postgresql.core.PGStream.createSocket(PGStream.java:223)
        at org.postgresql.core.PGStream.<init>(PGStream.java:95)
        at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:98)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:213)
        ... 9 more
```

##### Discussion/question
What do I do from here? It seems _something_ fails early, but the something else keeps trying to connect anyway?

**Comment by DoodleBobBuffPants** [comment]
Does this error appear instantly or after some time (i.e. is it a genuine timeout)? You can try enabling tcpKeepAlives, and you may also have to adjust the value of these keep-alives at the OS level. There is more context and an example in an older issue [here](https://github.com/flyway/flyway/issues/3080#issuecomment-779717038)

Are you able to connect to the database from within your Cloud Build outside of Flyway i.e. through any other tool?

**Comment by DoodleBobBuffPants** [comment]
Closing until further activity

**Comment by carlpett** [comment]
Sorry for lack of response, and yes, this should probably be closed anyway. It is looking a lot like an environment problem. Initial testing where it worked without Flyway appears to have been false positives.
Apologies for the noise!

**Comment by DoodleBobBuffPants** [comment]
Thanks for letting us know!

**Comment by carlpett** [comment]
In case this turns up in search results, my missing piece for reaching private Cloud SQL instances from private worker pools in Cloud Build was a missing network route.
The fix is ensuring the Service Networking VPC peer has the "Export custom routes" setting enabled, and that the Cloud Router advertises the route. The steps are actually [documented](https://cloud.google.com/sql/docs/postgres/configure-private-ip#vpn), but I was unable to find the docs until I knew the solution...
