### ISSUE TITLE
FlywayException Incomplete statement

### ISSUE THREAD

**Issue by rvvaeke** [flyway/flyway#3379]
###### Which version and edition of Flyway are you using?

Flyway enterprise 8.4.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Currently the latest version.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API with Spring Boot (2.6.2) integration

###### Which database are you using? (Type & version)

Oracle 18.4.0

###### Which operating system are you using?

Windows 10 Enterprise

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Executing an integrationtest against the Oracle database docker image 'gvenzl/oracle-xe' using tag '18-slim'. Spring Boot triggers the Flyway migration process. During Flyway parsing of the scripts under /db/migration/* directory, parsing fails on the following SQL script: 

```

PROMPT CREATING VIEW 'V_TELLER_SALDO';
CREATE OR REPLACE VIEW V_TELLER_SALDO AS
SELECT mte.syscode as id,
       mte.atr_syscode as teller_id,
       mte.mwo_syscode as overeenkomst_id,
       mte.dtvan as datum_van,
       mte.dttot as datum_tot,
       mte.aantstart as begin,
       mte.aantstart_correctie as correctie,
       mte.aantmaximum as maximum,
       mte.aantminimum as minimum,
       mte.aantvorig_opgenomen_start as vorig_opgenomen,
       mte.aantvorig_opgenomen_correctie as vorig_opgenomen_correctie,
       mte.aantstart_origineel as origineel,
       mte.cdeenheid as eenheid
from p2004.v_api_mw_teller mte;

grant insert, update, delete on V_TELLER_SALDO to WG_LOONBEREKENING_ADMIN;
grant select on V_TELLER_SALDO to WG_LOONBEREKENING_SELECT;


```

###### What did you expect to see?

No Flyway migration errors.

###### What did you see instead?

```
java.lang.IllegalStateException: Failed to load ApplicationContext

	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:132)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
	at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:190)
	at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:132)
	at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:248)
	at org.springframework.test.context.junit.jupiter.SpringExtension.postProcessTestInstance(SpringExtension.java:138)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$8(ClassBasedTestDescriptor.java:363)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.executeAndMaskThrowable(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeTestInstancePostProcessors$9(ClassBasedTestDescriptor.java:363)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:743)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:742)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeTestInstancePostProcessors(ClassBasedTestDescriptor.java:362)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$instantiateAndPostProcessTestInstance$6(ClassBasedTestDescriptor.java:283)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.instantiateAndPostProcessTestInstance(ClassBasedTestDescriptor.java:282)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$4(ClassBasedTestDescriptor.java:272)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$testInstancesProvider$5(ClassBasedTestDescriptor.java:271)
	at org.junit.jupiter.engine.execution.TestInstancesProvider.getTestInstances(TestInstancesProvider.java:31)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$prepare$0(TestMethodTestDescriptor.java:102)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:101)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.prepare(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$prepare$2(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.prepare(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:90)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.CommandLineWrapper.main(CommandLineWrapper.java:64)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Unable to parse statement in db/migration/V1.7.0/V1.7.0.10__replace_view_teller_saldo.sql at line 3 col 1. See https://rd.gt/3ipi7Pm for more information: Incomplete statement at line 3 col 1: CREATE OR REPLACE VIEW V_TELLER_SALDO AS
SELECT mte.syscode as id,
       mte.atr_syscode as teller_id,
       mte.mwo_syscode as overeenkomst_id,
       mte.dtvan as datum_van,
       mte.dttot as datum_tot,
       mte.aantstart as begin,
       mte.aantstart_correctie as correctie,
       mte.aantmaximum as maximum,
       mte.aantminimum as minimum,
       mte.aantvorig_opgenomen_start as vorig_opgenomen,
       mte.aantvorig_opgenomen_correctie as vorig_opgenomen_correctie,
       mte.aantstart_origineel as origineel,
       mte.cdeenheid as eenheid
from p2004.v_api_mw_teller mte;

grant insert, update, delete on V_TELLER_SALDO to WG_LOONBEREKENING_ADMIN;
grant select on V_TELLER_SALDO to WG_LOONBEREKENING_SELECT;


	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:121)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:99)
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
	... 76 more
Caused by: org.flywaydb.core.api.FlywayException: Unable to parse statement in db/migration/V1.7.0/V1.7.0.10__replace_view_teller_saldo.sql at line 3 col 1. See https://rd.gt/3ipi7Pm for more information: Incomplete statement at line 3 col 1: CREATE OR REPLACE VIEW V_TELLER_SALDO AS
SELECT mte.syscode as id,
       mte.atr_syscode as teller_id,
       mte.mwo_syscode as overeenkomst_id,
       mte.dtvan as datum_van,
       mte.dttot as datum_tot,
       mte.aantstart as begin,
       mte.aantstart_correctie as correctie,
       mte.aantmaximum as maximum,
       mte.aantminimum as minimum,
       mte.aantvorig_opgenomen_start as vorig_opgenomen,
       mte.aantvorig_opgenomen_correctie as vorig_opgenomen_correctie,
       mte.aantstart_origineel as origineel,
       mte.cdeenheid as eenheid
from p2004.v_api_mw_teller mte;

grant insert, update, delete on V_TELLER_SALDO to WG_LOONBEREKENING_ADMIN;
grant select on V_TELLER_SALDO to WG_LOONBEREKENING_SELECT;


	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:693)
	at org.flywaydb.core.internal.database.oracle.OracleParser.getNextStatement(OracleParser.java:1053)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:1120)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:1086)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:462)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:507)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.getReferencedSqlScripts(ParserSqlScript.java:556)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.addMigrations(SqlMigrationResolver.java:545)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:458)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationResolver.resolveMigrations(SqlMigrationResolver.java:437)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.collectMigrations(CompositeMigrationResolver.java:494)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.doFindAvailableMigrations(CompositeMigrationResolver.java:477)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:470)
	at org.flywaydb.core.internal.resolver.CompositeMigrationResolver.resolveMigrations(CompositeMigrationResolver.java:428)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:479)
	at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:538)
	at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:525)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:442)
	at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:525)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:772)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:443)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:516)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:511)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:601)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:511)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800)
	... 93 more
Caused by: org.flywaydb.core.api.FlywayException: Incomplete statement at line 3 col 1: CREATE OR REPLACE VIEW V_TELLER_SALDO AS
SELECT mte.syscode as id,
       mte.atr_syscode as teller_id,
       mte.mwo_syscode as overeenkomst_id,
       mte.dtvan as datum_van,
       mte.dttot as datum_tot,
       mte.aantstart as begin,
       mte.aantstart_correctie as correctie,
       mte.aantmaximum as maximum,
       mte.aantminimum as minimum,
       mte.aantvorig_opgenomen_start as vorig_opgenomen,
       mte.aantvorig_opgenomen_correctie as vorig_opgenomen_correctie,
       mte.aantstart_origineel as origineel,
       mte.cdeenheid as eenheid
from p2004.v_api_mw_teller mte;

grant insert, update, delete on V_TELLER_SALDO to WG_LOONBEREKENING_ADMIN;
grant select on V_TELLER_SALDO to WG_LOONBEREKENING_SELECT;


	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:626)
	... 120 more
```

**Comment by tjs145** [comment]
It looks like you've used `begin` as an alias in your SQL script (line 8):
```
mte.aantstart as begin,
```
which the Flyway Oracle parser detects as a keyword. 

This is a known limitation, for more information about parser limitations see https://flywaydb.org/documentation/knownparserlimitations.

Try renaming the alias to something else and see if that works.

**Comment by rvvaeke** [comment]
@tjs145 This was indeed the issue. My apologies, I completely looked over the sensitive keywords.
