### ISSUE TITLE
CONNECTION_PROPERTY_THIN_NET_DISABLE_OUT_OF_BAND_BREAK error

### ISSUE THREAD

**Issue by szymonk92** [flyway/flyway#3381]
###### Which version and edition of Flyway are you using?
7.6.0, 8.4.2, 8.4.1 

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line and Java

###### Which database are you using? (Type & version)
Oracle 19c

###### Which operating system are you using?
Windows/Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I have already working Flyway for PostgreSQL, now trying to configure it for Oracle DB. When I use command-line, connection is correct. I am able to apply schemas. However, when using Java, I am getting:

```
org.flywaydb.core.api.FlywayException: Unable to obtain field value oracle.jdbc.OracleConnection.CONNECTION_PROPERTY_THIN_NET_DISABLE_OUT_OF_BAND_BREAK : oracle.jdbc.OracleConnection from [Module "deployment.App.ear.app-server.jar" from Service Module Loader]
	at org.flywaydb.core.internal.util.ClassUtils.getStaticFieldValue(ClassUtils.java:215)
	at org.flywaydb.core.internal.database.oracle.OracleDatabaseType.setDefaultConnectionProps(OracleDatabaseType.java:158)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:125)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:80)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:958)
	at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:683)
	at com.company.app.server.hibernatecustom.HibernateEventListenerIntegrator.enableFlyway(HibernateEventListenerIntegrator.java:60)
	at com.company.app.server.hibernatecustom.HibernateEventListenerIntegrator.integrate(HibernateEventListenerIntegrator.java:39)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:276)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.__build(SessionFactoryBuilderImpl.java:467)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:41009)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.__build(EntityManagerFactoryBuilderImpl.java:1250)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:40002)
	at org.jboss.as.jpa.hibernate5.TwoPhaseBootstrapImpl.__build(TwoPhaseBootstrapImpl.java:44)
	at org.jboss.as.jpa.hibernate5.TwoPhaseBootstrapImpl.build(TwoPhaseBootstrapImpl.java:46002)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:171)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:129)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:664)
	at org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:214)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:513)
Caused by: java.lang.ClassNotFoundException: oracle.jdbc.OracleConnection from [Module "deployment.App.ear.app-server.jar" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:200)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.flywaydb.core.internal.util.ClassUtils.getStaticFieldValue(ClassUtils.java:211)
	... 25 more
```

Error is in:
ClassUtils -> getStaticFieldValue (line: 125)
	oracle.jdbc.OracleConnection from [Module "deployment.App.ear.app-server.jar" from Service Module Loader]
	
	where: 
		className = oracle.jdbc.OracleConnection
		fieldName = CONNECTION_PROPERTY_THIN_NET_DISABLE_OUT_OF_BAND_BREAK
		classLoader = ModuleClassLoader for Module "deployment.App.ear.app-server.jar" from Service Module Loader

Using exactly the same url, username and password as in command-line connection.

Java code:
```
               Flyway flyway = Flyway.configure()
                        .dataSource(url, user, password) // Error here
                        .baselineOnMigrate(true)
                        .load();
                flyway.migrate();
```

**Comment by DoodleBobBuffPants** [comment]
The `ClassNotFoundException` suggests you do not have the Oracle JDBC driver as a dependency

Could you ensure it is there and available on the classpath?

**Comment by szymonk92** [comment]
That was the case, no Oracle driver in "deployment.App.ear.app-server.jar".  Thanks!

As application is being deployed on WildFly server, I keep PostgresSQL driver and Oracle driver there as a module. Do you know any way I could point to that location instead of including a driver in the jar? This approach worked fine for Postgres, thus I did not include oracle driver in the jar at first.
