### ISSUE TITLE
FlywayException: No database found to handle jdbc:mysql://localhost:3306/...

### ISSUE THREAD

**Issue by codemonstur** [flyway/flyway#3448]
###### Which version and edition of Flyway are you using?

8.5.11

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

MySQL 8.0.25

###### Which operating system are you using?

Windows / Linux WSL

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Upgraded Flyway from 7.14.0 to 8.5.11. Ran the code again, got an exception on migration:

    org.flywaydb.core.api.FlywayException: No database found to handle jdbc:mysql://localhost:3306/mydb?useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:55)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:80)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:958)
        at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:683)
        at common.db.RelationalDB.migrateRelationalDB(RelationalDB.java:131)
        at app.Main.newServer(Main.java:59)
        at app.Main.lambda$main$0(Main.java:50)
        at common.util.AppInitializer.buildApp(AppInitializer.java:21)
        at app.Main.main(Main.java:30)

The `migrateRelationalDB()` function calls Flyway this way:

    Flyway.configure().initSql(init).locations(location).dataSource(url, user, pass).load().migrate();

I managed to get the code to work by downgrading to 8.1.0
The app is a fatjar that includes `mysql:mysql-connector-java:8.0.29`.

###### What did you expect to see?

No error. Normal connection and working app.

###### What did you see instead?

Can't start up if the migration doesn't succeed. (There are no new migrations, Flyway only needs to verify that everything is still up to date)

**Comment by DoodleBobBuffPants** [comment]
See the MySQL docs [here](https://flywaydb.org/documentation/database/mysql#java-usage)

You'll need a dependency on the `flyway-mysql` module

**Comment by codemonstur** [comment]
I had the library but it was still failing. Turns out my build is rearranging the dependencies in alphabetical order which made the core library always come first. Which meant that my packaging step always included the `META-INF/services/org.flywaydb.core.extensibility.Plugin` from the core library instead of the mysql library. And that made it fail. I have some work to do.

**Comment by Joel-x-x** [comment]
Thanks almost 2 hours with this problem I didn't think in the versions.
