### ISSUE TITLE
NoSuchMethodError: org.flywaydb.core.api.configuration.FluentConfiguration

### ISSUE THREAD

**Issue by javiyt** [flyway/flyway#3484]
###### Which version and edition of Flyway are you using?
Flyway core 9.0.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using? (Type & version)
PostgreSQL 12.2

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Run migrations

###### What did you expect to see?
Can start spring boot application

###### What did you see instead?
```
Caused by:
                                    org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is java.lang.NoSuchMethodError: 'org.flywaydb.core.api.configuration.FluentConfiguration org.flywaydb.core.api.configuration.FluentConfiguration.ignoreMissingMigrations(boolean)'
                                        at app//org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
                                        at app//org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
                                        ... 168 more
                                        Caused by:
                                        java.lang.NoSuchMethodError: 'org.flywaydb.core.api.configuration.FluentConfiguration org.flywaydb.core.api.configuration.FluentConfiguration.ignoreMissingMigrations(boolean)'
                                            at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.configureIgnoredMigrations(FlywayAutoConfiguration.java:264)
                                            at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.configureProperties(FlywayAutoConfiguration.java:205)
                                            at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.flyway(FlywayAutoConfiguration.java:119)
                                            at jdk.internal.reflect.GeneratedMethodAccessor270.invoke(Unknown Source)
                                            at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                                            at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                                            at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
                                            ... 169 more
```

**Comment by xiaomaitai** [comment]
I assume this is a bug need to be fixed.We application developers didn't call these deprecated methods proactively.
I reverted the version to 8.5.13 and avoided this problem by the way.

**Comment by DoodleBobBuffPants** [comment]
It isn't a bug - Spring Boot will need to update to support the latest major version of Flyway

**Comment by billyshen26** [comment]
> It isn't a bug - Spring Boot will need to update to support the latest major version of Flyway

i tried Spring Boot 2.7.2.  Flyway 9.1.3 ，got the same issue.   any advice?

**Comment by billyshen26** [comment]
<img width="1584" alt="WX20220816-225844@2x" src="https://user-images.githubusercontent.com/5089845/184912040-adbe1bcf-952e-4cc3-b8f7-2dee097663e2.png">

**Comment by javiyt** [comment]
It would be fixed in Spring 2.7.3, see https://github.com/spring-projects/spring-boot/issues/32034 for more information

**Comment by billyshen26** [comment]
got it ,thx

**Comment by Yangyy99** [comment]
i tried Spring Boot 3.0.2  Flyway 9.20.1 , PostgreSQL 15 ，got the same issue.
