### ISSUE TITLE
Support externalbrowser authenticator for Snowflake

### ISSUE THREAD

**Issue by dlawrences** [flyway/flyway#3532]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 9.3.0 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I have looked at 9.3.1 and 9.4.0 and this hasn't been enabled

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

Snowflake Business Critical

###### Which operating system are you using?

macOS Monterrey v12.5.1

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Tried connecting to Snowflake using External Browser SSO

###### What did you expect to see?

Expected Flyway to support External Browser SSO

###### What did you see instead?

Flyway doesn't support the `authenticator` URL parameter that the Snowflake JDBC driver supports (https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use.html#setting-up-browser-based-sso).

In organisations that enforce the usage of SSO, Flyway cannot be used by developers locally. Sure enough, Flyway works just fine in CI/CD where we use user/password or user and private keys.

**Comment by DoodleBobBuffPants** [comment]
Closing till further activity

**Comment by uclatommy** [comment]
Please reopen this request. Here is my error:

```powershell
ERROR: Unable to determine the original schema for the connection
----------------------------------------------------------
SQL State  : XX000
Error Code : 200001
Message    : JDBC driver internal error: exception creating result java.lang.ExceptionInInitializerError at net.snowflake.client.jdbc.internal.apache.arrow.memory.UnsafeAllocationManager.<clinit>(UnsafeAllocationManager.java:27).

Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver internal error: exception creating result java.lang.ExceptionInInitializerError at net.snowflake.client.jdbc.internal.apache.arrow.memory.UnsafeAllocationManager.<clinit>(UnsafeAllocationManager.java:27).
```

Here is my stack trace (with redacted strings in angle brackets):
```powershell
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
QUOTED_IDENTIFIERS_IGNORE_CASE option is false
Flyway Community Edition 9.12.0 by Redgate
See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.12.0

Database: jdbc:snowflake://<redacted>.snowflakecomputing.com:443/ (Snowflake 7.2)
QUOTED_IDENTIFIERS_IGNORE_CASE option is false
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Jan 26, 2023 5:34:53 PM net.snowflake.client.jdbc.internal.apache.arrow.memory.BaseAllocator <clinit>
INFO: Debug mode disabled.
Jan 26, 2023 5:34:54 PM net.snowflake.client.jdbc.internal.apache.arrow.memory.DefaultAllocationManagerOption getDefaultAllocationManagerFactory
INFO: allocation manager type not specified, using netty as the default type
Jan 26, 2023 5:34:54 PM net.snowflake.client.jdbc.internal.apache.arrow.memory.CheckAllocator reportResult
INFO: Using DefaultAllocationManager at memory/DefaultAllocationManagerFactory.class
Jan 26, 2023 5:34:54 PM net.snowflake.client.core.SFStatement executeQueryInternal
SEVERE: Exception creating result
java.lang.ExceptionInInitializerError
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.UnsafeAllocationManager.<clinit>(UnsafeAllocationManager.java:27)
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.DefaultAllocationManagerFactory.<clinit>(DefaultAllocationManagerFactory.java:26)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.DefaultAllocationManagerOption.getFactory(DefaultAllocationManagerOption.java:111)
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.DefaultAllocationManagerOption.getDefaultAllocationManagerFactory(DefaultAllocationManagerOption.java:101)
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.BaseAllocator$Config.getAllocationManagerFactory(BaseAllocator.java:735)
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.ImmutableConfig.access$801(ImmutableConfig.java:24)
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.ImmutableConfig$InitShim.getAllocationManagerFactory(ImmutableConfig.java:83)
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.ImmutableConfig.<init>(ImmutableConfig.java:47)
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.ImmutableConfig.<init>(ImmutableConfig.java:24)
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.ImmutableConfig$Builder.build(ImmutableConfig.java:485)
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.BaseAllocator.<clinit>(BaseAllocator.java:63)
        at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:577)
        at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:489)
        at net.snowflake.client.core.SFResultSetFactory.getResultSet(SFResultSetFactory.java:29)
        at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:218)
        at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:133)
        at net.snowflake.client.core.SFStatement.execute(SFStatement.java:746)
        at net.snowflake.client.core.SFStatement.execute(SFStatement.java:656)
        at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:236)
        at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:118)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForString(JdbcTemplate.java:158)
        at org.flywaydb.core.internal.database.snowflake.SnowflakeConnection.getCurrentSchemaNameOrSearchPath(SnowflakeConnection.java:51)
        at org.flywaydb.core.internal.database.base.Connection.<init>(Connection.java:49)
        at org.flywaydb.core.internal.database.snowflake.SnowflakeConnection.<init>(SnowflakeConnection.java:35)
        at org.flywaydb.core.internal.database.snowflake.SnowflakeDatabase.doGetConnection(SnowflakeDatabase.java:63)
        at org.flywaydb.core.internal.database.snowflake.SnowflakeDatabase.doGetConnection(SnowflakeDatabase.java:32)
        at org.flywaydb.core.internal.database.base.Database.getConnection(Database.java:88)
        at org.flywaydb.core.internal.database.base.Database.getMainConnection(Database.java:280)
        at org.flywaydb.core.internal.schemahistory.SchemaHistoryFactory.prepareSchemas(SchemaHistoryFactory.java:67)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:178)
        at org.flywaydb.core.Flyway.validate(Flyway.java:238)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:363)
        at org.flywaydb.commandline.Main.main(Main.java:146)
Caused by: java.lang.RuntimeException: Failed to initialize MemoryUtil.
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:139)
        ... 35 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @a9cd3b1
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
        at net.snowflake.client.jdbc.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:87)
        ... 35 more
```

I'm using the snowflake-jdbc-3.13.22.jar driver included with the distribution.

Here's my flyway.conf file (with redacted info in angle brackets)
```
flyway.url=jdbc:snowflake://<redacted>.snowflakecomputing.com/?db=<redacted>&warehouse=<redacted>&role=<redacted>&authenticator=externalbrowser
flyway.driver=net.snowflake.client.jdbc.SnowflakeDriver
flyway.locations=filesystem:sql
flyway.user=<redacted>
flyway.password=
```

**Comment by uclatommy** [comment]
I've found a way to avoid the error and use externalbrowser as the authentication method. I added the following parameter to the connection string:
`JDBC_QUERY_RESULT_FORMAT=JSON`

So now my `flyway.conf` file looks like this:
```
flyway.url=jdbc:snowflake://<redacted>.snowflakecomputing.com/?db=<redacted>&warehouse=<redacted>&role=<redacted>&authenticator=externalbrowser&JDBC_QUERY_RESULT_FORMAT=JSON
flyway.driver=net.snowflake.client.jdbc.SnowflakeDriver
flyway.locations=filesystem:sql
flyway.user=<redacted>
flyway.password=
```
