### ISSUE TITLE
Support Batch Statements of Cloud Spanner

### ISSUE THREAD

**Issue by Glavis** [flyway/flyway#3563]
###### Which version and edition of Flyway are you using?
9.7.0 Community Edition

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin and command-line

###### Which database are you using? (Type & version)
Cloud Spanner

---

Do you support batch statements of Cloud Spanner[1]?
We would like to use those to create a batch of DDL statements, but flyway shows the following error when using `START BATCH DDL` and `RUN BATCH` statements:

```
SQL State  : null
Error Code : 3
Message    : INVALID_ARGUMENT: Invalid column type to get as string: ARRAY
Location   : (location to my file)
Line       : xxx
Statement  :RUN BATCH

        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:275)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:222)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:68)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
        at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:376)
        ... 131 more
Caused by: com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory$JdbcSqlExceptionImpl: INVALID_ARGUMENT: Invalid column type to get as string: ARRAY
        at com.google.cloud.spanner.jdbc.JdbcSqlExceptionFactory.of(JdbcSqlExceptionFactory.java:247)
        at com.google.cloud.spanner.jdbc.JdbcResultSet.createInvalidToGetAs(JdbcResultSet.java:122)
        at com.google.cloud.spanner.jdbc.JdbcResultSet.getString(JdbcResultSet.java:163)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.extractResults(JdbcTemplate.java:263)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:202)
        at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:95)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:210)
        ... 137 more
```

The SQL statement that causes the error above looks like below:

```
START BATCH DDL;

(Some CREATE TABLE and CREATE INDEX statements here)

RUN BATCH;
```

Any comments are appreciated.

[1] https://cloud.google.com/spanner/docs/jdbc-session-mgmt-commands#start_batch_ddl

**Comment by tjs145** [comment]
I've tried executing a batch statement like the one you mentioned but I wasn't able to reproduce the error, it just executed fine. Based on the error message: `INVALID_ARGUMENT`, it might be a problem with one of the statements within the batch. You might need to provide us with the full SQL script to allow us to reproduce the error.

**Comment by Glavis** [comment]
I have tested the new version, 9.8.1 which fixes this issue, but unfortunately it did not work properly.

With 9.8.1, `flywayMigration` command ends successfully, but the tables declared between `START BATCH DDL` and `RUN BATCH` are not created on Cloud Spanner database.

`flywayInfo` command says its state is `Success`, though the table are not created.
```
+-----------+------------+-------------+------+---------------------+---------+----------+
| Category  | Version    | Description | Type | Installed On        | State   | Undoable |
+-----------+------------+-------------+------+---------------------+---------+----------+
| Versioned | 00.000.001 | CreateTable | SQL  | 2022-11-16 14:16:41 | Success | No       |
+-----------+------------+-------------+------+---------------------+---------+----------+
```

**Comment by kntmr** [comment]
I have same issue ([above comment](https://github.com/flyway/flyway/issues/3563#issuecomment-1316381617)) with version 9.21.1.

**Comment by DrowsyDormouse** [comment]
I have same issue (https://github.com/flyway/flyway/issues/3563#issuecomment-1316381617) with version 10.11.1(Flyway Community Edition).
