### ISSUE TITLE
"Unrecognised migration name format" error when trying to use SQL migrations

### ISSUE THREAD

**Issue by AlxDoesStuff** [flyway/flyway#3594]
###### Which version and edition of Flyway are you using?
Flyway 9.10.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

I am using the latest version of Flyway (9.10.2).

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API with a Spigot plugin for minecraft

###### Which database are you using? (Type & version)

MariaDB 10.6.11

###### Which operating system are you using?

Windows 10 64-Bit

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I tried migrating a database using an sql migration.
Flyway configuration:

```
flyway = Flyway.configure(plugin.getClass().getClassLoader())
                .dataSource(DataSource.ds)
                .validateMigrationNaming(true)
                .locations("classpath:db/migration")
                .sqlMigrationPrefix("V")
                .sqlMigrationSeparator("__")
                .load();
```
The migration was in src/main/resources/db/migration/V1__Initial_setup.sql. As far as I can tell this is following the standard naming and location conventions for Flyway which the configurations above don't change.

###### What did you expect to see?

[INFO]: Current version of schema "db": << Empty Schema >>
[INFO]: Migrating schema "db" to version 1 - Initial setup
[INFO]: Successfully applied 1 migration to schema "db" 

###### What did you see instead?
```
org.flywaydb.core.api.FlywayException: Invalid SQL filenames found:
Unrecognised migration name format: V1__Initial_setup.sql
        at org.flywaydb.core.internal.resource.ResourceNameValidator.validateSQLMigrationNaming(ResourceNameValidator.java:59) ~[InventoryGuiThing-1.0-SNAPSHOT-all.jar:?]
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:144) ~[InventoryGuiThing-1.0-SNAPSHOT-all.jar:?]
        at org.flywaydb.core.Flyway.migrate(Flyway.java:128) ~[InventoryGuiThing-1.0-SNAPSHOT-all.jar:?]
        at com.gmail.alxdoesstuff.InventoryGuiThing.onEnable(InventoryGuiThing.java:49) ~[InventoryGuiThing-1.0-SNAPSHOT-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:371) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:544) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:578) ~[paper-1.19.3.jar:git-Paper-350]
        at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:492) ~[paper-1.19.3.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.19.3.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.19.3.jar:git-Paper-350]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:301) ~[paper-1.19.3.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.19.3.jar:git-Paper-350]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-350]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by DoodleBobBuffPants** [comment]
Internally, Flyway makes use of the `ServiceLoader` and I suspect changing the `ClassLoader` is causing the service that implements our migration name validation to not be detected

Could you try removing `plugin.getClass().getClassLoader()` and see if it works? If it does, you would need to modify or use a different `ClassLoader`

**Comment by AlxDoesStuff** [comment]
I removed ```plugin.getClass().getClassLoader()```
Instead of the exception it cant find the migrations at all anymore:
```[15:29:22 INFO]: [org.flywaydb.core.internal.command.DbValidate] Successfully validated 0 migrations (execution time 00:00.017s)
[15:29:22 WARN]: [org.flywaydb.core.internal.command.DbValidate] No migrations found. Are your locations set up correctly?
[15:29:22 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Current version of schema `db`: << Empty Schema >>
[15:29:22 INFO]: [org.flywaydb.core.internal.command.DbMigrate] Schema `db` is up to date. No migration necessary.```

**Comment by DoodleBobBuffPants** [comment]
What's likely happening here is that the migrations are only found by the `ClassLoader` you get from `plugin.getClass().getClassLoader()`

It might be worth looking at custom ClassLoaders so that you can combine the default with the one from your plugin, or using a ClassLoader that can access the classes in your project and plugin, though this depends on how your project is set up. At this point however this is a problem outside of Flyway so closing for now

**Comment by dotnomi** [comment]
Hello, I know it is stupid to answer something after 2 years. I had the same problem. After 2 days of debugging I found a solution.

When you create a plugin for Minecraft with Velocity, Spigot or whatever it seems that the `META-INF/services/` folder is empty. That is the problem because the ResourceTypeProvider could not load its configuration which is stored in this folder in the builded jar file.

The workaround:

Just put 

`
shadowJar {
    mergeServiceFiles()
}
`

in your build.gradle

or for maven users:

```
<build>
    <plugins>
        <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-shade-plugin</artifactId>
            <version>3.5.3</version> <executions>
                <execution>
                    <phase>package</phase>
                    <goals>
                        <goal>shade</goal>
                    </goals>
                    <configuration>
                        <transformers>
                            <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                    </configuration>
                </execution>
            </executions>
        </plugin>
    </plugins>
</build>
```

When you now build your plugin with shade/shadowJar it finally works :)

**Comment by KweezyCode** [comment]
I spent few hours because of this, could it be fixed? Or just mention it in documentation. This issue is 2 years old and must be reopened

**Comment by douglasqueirozalmeida** [comment]
I spent few hours because of this, could it be fixed? Or just mention it in documentation. This issue is 2 years old and must be reopened

**Comment by ilyako87** [comment]
After updating Gradle to versions that use shadow plugin > 9.0.0, the problem appears again.
Migration is recommended for shadow plugin, but now it does not help. Does anyone have any ideas?

<img width="711" height="599" alt="Image" src="https://github.com/user-attachments/assets/e3f91d22-8017-4f5b-ad04-87bd6a572413" />

**Comment by chrisjenx** [comment]
I just updated my shadowjar script to this:

```
tasks.withType<ShadowJar>().configureEach {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
    mergeServiceFiles()
    failOnDuplicateEntries = true
    transform<com.github.jengelman.gradle.plugins.shadow.transformers.PreserveFirstFoundResourceTransformer> {
        // resources.add("META-INF/foo.version.properties") // Or something else where the first occurrence should be preserved.
    }
    isZip64 = true
}
```

Is there bettery way? Maybe but that seemed to work for me

**Comment by ea-ae** [comment]
Solution:

https://youtrack.jetbrains.com/projects/KTOR/issues/KTOR-8987/A-problem-with-mergeServiceFiles-of-ShadowJar-after-upgrading-Ktor-to-3.3.0
