### ISSUE TITLE
9.12 - Unable to determine the original schema for the connection

### ISSUE THREAD

**Issue by EMCINS** [flyway/flyway#3604]
###### Which version and edition of Flyway are you using?
9.12

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin) 
Docker Image - flyway/flyway

###### Which database are you using?
Snowflake 7.2

###### Which operating system are you using?
Docker Image - flyway/flyway

###### What did you do?
flyway migrate

###### What did you expect to see?
Successful migrations

If I revert to Flyway 9.11, I can still successfully perform a migration againts Snowflake 7.2.  It is also successfully when using 9.12 with "jdbc_query_result_format=json" added to the connection string.

###### What did you see instead?
```
error	20-Jan-2023 12:32:24	SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
error	20-Jan-2023 12:32:24	SLF4J: Defaulting to no-operation (NOP) logger implementation
error	20-Jan-2023 12:32:24	SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
error	20-Jan-2023 12:32:24	Jan 20, 2023 6:32:24 PM net.snowflake.client.jdbc.internal.apache.arrow.memory.BaseAllocator <clinit>
error	20-Jan-2023 12:32:24	INFO: Debug mode disabled.
error	20-Jan-2023 12:32:24	Jan 20, 2023 6:32:24 PM net.snowflake.client.jdbc.internal.apache.arrow.memory.DefaultAllocationManagerOption getDefaultAllocationManagerFactory
error	20-Jan-2023 12:32:24	INFO: allocation manager type not specified, using netty as the default type
error	20-Jan-2023 12:32:24	Jan 20, 2023 6:32:24 PM net.snowflake.client.jdbc.internal.apache.arrow.memory.CheckAllocator reportResult
error	20-Jan-2023 12:32:24	INFO: Using DefaultAllocationManager at memory/DefaultAllocationManagerFactory.class
error	20-Jan-2023 12:32:24	Jan 20, 2023 6:32:24 PM net.snowflake.client.core.SFStatement executeQueryInternal
error	20-Jan-2023 12:32:24	SEVERE: Exception creating result
error	20-Jan-2023 12:32:24	java.lang.ExceptionInInitializerError
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.UnsafeAllocationManager.<clinit>(UnsafeAllocationManager.java:27)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.DefaultAllocationManagerFactory.<clinit>(DefaultAllocationManagerFactory.java:26)
error	20-Jan-2023 12:32:24		at java.base/java.lang.Class.forName0(Native Method)
error	20-Jan-2023 12:32:24		at java.base/java.lang.Class.forName(Unknown Source)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.DefaultAllocationManagerOption.getFactory(DefaultAllocationManagerOption.java:111)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.DefaultAllocationManagerOption.getDefaultAllocationManagerFactory(DefaultAllocationManagerOption.java:101)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.BaseAllocator$Config.getAllocationManagerFactory(BaseAllocator.java:735)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.ImmutableConfig.access$801(ImmutableConfig.java:24)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.ImmutableConfig$InitShim.getAllocationManagerFactory(ImmutableConfig.java:83)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.ImmutableConfig.<init>(ImmutableConfig.java:47)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.ImmutableConfig.<init>(ImmutableConfig.java:24)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.ImmutableConfig$Builder.build(ImmutableConfig.java:485)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.BaseAllocator.<clinit>(BaseAllocator.java:63)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:577)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.SnowflakeResultSetSerializableV1.create(SnowflakeResultSetSerializableV1.java:489)
error	20-Jan-2023 12:32:24		at net.snowflake.client.core.SFResultSetFactory.getResultSet(SFResultSetFactory.java:29)
error	20-Jan-2023 12:32:24		at net.snowflake.client.core.SFStatement.executeQueryInternal(SFStatement.java:218)
error	20-Jan-2023 12:32:24		at net.snowflake.client.core.SFStatement.executeQuery(SFStatement.java:133)
error	20-Jan-2023 12:32:24		at net.snowflake.client.core.SFStatement.execute(SFStatement.java:746)
error	20-Jan-2023 12:32:24		at net.snowflake.client.core.SFStatement.execute(SFStatement.java:656)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.SnowflakeStatementV1.executeQueryInternal(SnowflakeStatementV1.java:236)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.SnowflakePreparedStatementV1.executeQuery(SnowflakePreparedStatementV1.java:118)
error	20-Jan-2023 12:32:24		at org.flywaydb.core.internal.jdbc.JdbcTemplate.queryForString(JdbcTemplate.java:158)
error	20-Jan-2023 12:32:24		at org.flywaydb.core.internal.database.snowflake.SnowflakeConnection.getCurrentSchemaNameOrSearchPath(SnowflakeConnection.java:51)
error	20-Jan-2023 12:32:24		at org.flywaydb.core.internal.database.base.Connection.<init>(Connection.java:49)
error	20-Jan-2023 12:32:24		at org.flywaydb.core.internal.database.snowflake.SnowflakeConnection.<init>(SnowflakeConnection.java:35)
error	20-Jan-2023 12:32:24		at org.flywaydb.core.internal.database.snowflake.SnowflakeDatabase.doGetConnection(SnowflakeDatabase.java:63)
error	20-Jan-2023 12:32:24		at org.flywaydb.core.internal.database.snowflake.SnowflakeDatabase.doGetConnection(SnowflakeDatabase.java:32)
error	20-Jan-2023 12:32:24		at org.flywaydb.core.internal.database.base.Database.getConnection(Database.java:88)
error	20-Jan-2023 12:32:24		at org.flywaydb.core.internal.database.base.Database.getMainConnection(Database.java:280)
error	20-Jan-2023 12:32:24		at org.flywaydb.core.internal.schemahistory.SchemaHistoryFactory.prepareSchemas(SchemaHistoryFactory.java:62)
error	20-Jan-2023 12:32:24		at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:178)
error	20-Jan-2023 12:32:24		at org.flywaydb.core.Flyway.repair(Flyway.java:320)
error	20-Jan-2023 12:32:24		at org.flywaydb.commandline.Main.executeOperation(Main.java:392)
error	20-Jan-2023 12:32:24		at org.flywaydb.commandline.Main.main(Main.java:146)
error	20-Jan-2023 12:32:24	Caused by: java.lang.RuntimeException: Failed to initialize MemoryUtil.
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:139)
error	20-Jan-2023 12:32:24		... 35 more
error	20-Jan-2023 12:32:24	Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @22c6d958
error	20-Jan-2023 12:32:24		at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
error	20-Jan-2023 12:32:24		at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
error	20-Jan-2023 12:32:24		at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)
error	20-Jan-2023 12:32:24		at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)
error	20-Jan-2023 12:32:24		at net.snowflake.client.jdbc.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:87)
error	20-Jan-2023 12:32:24		... 35 more
error	20-Jan-2023 12:32:24	
error	20-Jan-2023 12:32:24	ERROR: Unable to determine the original schema for the connection
error	20-Jan-2023 12:32:24	----------------------------------------------------------
error	20-Jan-2023 12:32:24	SQL State  : XX000
error	20-Jan-2023 12:32:24	Error Code : 200001
error	20-Jan-2023 12:32:24	Message    : JDBC driver internal error: exception creating result java.lang.ExceptionInInitializerError at net.snowflake.client.jdbc.internal.apache.arrow.memory.UnsafeAllocationManager.<clinit>(UnsafeAllocationManager.java:27).
error	20-Jan-2023 12:32:24	
error	20-Jan-2023 12:32:24	Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver internal error: exception creating result java.lang.ExceptionInInitializerError at net.snowflake.client.jdbc.internal.apache.arrow.memory.UnsafeAllocationManager.<clinit>(UnsafeAllocationManager.java:27).
error	20-Jan-2023 12:32:25	Exit code: 1, output: STDERR: 	at org.flywaydb.commandline.Main.executeOperation(Main.java:392)STDERR: 	at org.flywaydb.commandline.Main.main(Main.java:146)STDERR: Caused by: java.lang.RuntimeException: Failed to initialize MemoryUtil.STDERR: 	at net.snowflake.client.jdbc.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:139)STDERR: 	... 35 moreSTDERR: Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field long java.nio.Buffer.address accessible: module java.base does not "opens java.nio" to unnamed module @22c6d958STDERR: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)STDERR: 	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)STDERR: 	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Unknown Source)STDERR: 	at java.base/java.lang.reflect.Field.setAccessible(Unknown Source)STDERR: 	at net.snowflake.client.jdbc.internal.apache.arrow.memory.util.MemoryUtil.<clinit>(MemoryUtil.java:87)STDERR: 	... 35 moreSTDERR: STDERR: ERROR: Unable to determine the original schema for the connectionSTDERR: ----------------------------------------------------------STDERR: SQL State  : XX000STDERR: Error Code : 200001STDERR: Message    : JDBC driver internal error: exception creating result java.lang.ExceptionInInitializerError at net.snowflake.client.jdbc.internal.apache.arrow.memory.UnsafeAllocationManager.<clinit>(UnsafeAllocationManager.java:27).STDERR: STDERR: Caused by: net.snowflake.client.jdbc.SnowflakeSQLException: JDBC driver internal error: exception creating result java.lang.ExceptionInInitializerError at net.snowflake.client.jdbc.internal.apache.arrow.memory.UnsafeAllocationManager.<clinit>(UnsafeAllocationManager.java:27).
```

**Comment by DoodleBobBuffPants** [comment]
This is a [known issue](https://github.com/snowflakedb/snowflake-jdbc/issues/589) with the Snowflake JDBC driver to do with compatibility with Java 17, and we have recently updated to support both Java 8 and 17 as we move to 17 only

We can update the driver once a fix is available but your workaround is completely valid, so closing for now
