### ISSUE TITLE
Problem with parsing Snowflake scripts Flyway 9.14.1 (same was working fine in Flyway 8.5.9) Not able to perform migration that worked earlier

### ISSUE THREAD

**Issue by niegowic** [flyway/flyway#3613]
###### Which version and edition of Flyway are you using?
9.14.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Reverted back to 8.5.9 and it executed same migrations without any issues. 

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Sowflake 7.3 

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Running this V0_initial migration:

```
--======================
-- 1. Security - Roles:
--========================
USE ROLE SECURITYADMIN;

CREATE OR REPLACE ROLE OWNER_FINANCIAL_DB;
GRANT EXECUTE TASK ON account TO ROLE OWNER_FINANCIAL_DB;
GRANT ROLE OWNER_FINANCIAL_DB TO ROLE SYSADMIN;

CREATE OR REPLACE ROLE READER_FINANCIAL_DB;
GRANT USAGE, MONITOR ON Warehouse Integrations TO ROLE READER_FINANCIAL_DB;
GRANT ROLE READER_FINANCIAL_DB TO ROLE OWNER_FINANCIAL_DB;
GRANT ROLE READER_FINANCIAL_DB TO ROLE SYSADMIN;
GRANT ROLE READER_FINANCIAL_DB TO ROLE Analytics_Role;

--==========================
-- 2. database and schemas:
--==========================
USE ROLE SYSADMIN;
USE DATABASE FINANCIAL_DB;


CREATE SCHEMA STG COMMENT = 'STAGING SCHEMA';
CREATE SCHEMA RAW COMMENT = 'RAW DATA';
CREATE SCHEMA DW COMMENT = 'DATA WAREHOUSE SCHEMA';
CREATE SCHEMA TV COMMENT = 'TECHNICAL VIEWS SCHEMA';
CREATE SCHEMA RECON COMMENT = 'RECONCILIATION VIEWS SCHEMA';


--==========================
-- 3. Security - Privileges:
--==========================
USE ROLE SECURITYADMIN;

GRANT OWNERSHIP ON DATABASE FINANCIAL_DB TO ROLE OWNER_FINANCIAL_DB;
GRANT MONITOR, USAGE ON DATABASE FINANCIAL_DB TO ROLE READER_FINANCIAL_DB;
GRANT MONITOR ON FUTURE tasks IN DATABASE FINANCIAL_DB TO ROLE READER_FINANCIAL_DB;
GRANT SELECT ON FUTURE tables IN DATABASE FINANCIAL_DB TO ROLE READER_FINANCIAL_DB;
GRANT SELECT ON FUTURE views IN DATABASE FINANCIAL_DB TO ROLE READER_FINANCIAL_DB;
GRANT USAGE, READ ON FUTURE stages IN DATABASE FINANCIAL_DB TO ROLE READER_FINANCIAL_DB;
GRANT USAGE ON FUTURE file formats IN DATABASE FINANCIAL_DB TO ROLE READER_FINANCIAL_DB;
GRANT SELECT ON FUTURE streams IN DATABASE FINANCIAL_DB TO ROLE READER_FINANCIAL_DB;
GRANT USAGE ON schema FINANCIAL_DB.PUBLIC TO ROLE READER_FINANCIAL_DB;
GRANT ALL PRIVILEGES ON schema FINANCIAL_DB.PUBLIC TO ROLE OWNER_FINANCIAL_DB;
GRANT USAGE ON FUTURE schemas IN DATABASE FINANCIAL_DB TO ROLE OWNER_FINANCIAL_DB;
GRANT USAGE ON FUTURE functions IN DATABASE FINANCIAL_DB TO ROLE OWNER_FINANCIAL_DB;

--================================
-- 4. Target tables:
--================================
USE ROLE SYSADMIN;
USE WAREHOUSE INTEGRATIONS;
USE DATABASE FINANCIAL_DB;
USE SCHEMA RAW;

ALTER SESSION SET TIMEZONE ='America/New_York';

DROP  TABLE IF EXISTS  FINANCIAL_DB.RAW.VENDOR_INVOICES;
DROP  TABLE IF EXISTS  FINANCIAL_DB.RAW.PROFIT_CENTER;
DROP  TABLE IF EXISTS  FINANCIAL_DB.RAW.MOVEMENT_DOCUMENTS;
DROP  TABLE IF EXISTS  FINANCIAL_DB.RAW.MAP_PRICE;
DROP  TABLE IF EXISTS  FINANCIAL_DB.RAW.INFO_RECORDS;
DROP  TABLE IF EXISTS  FINANCIAL_DB.RAW.COST_CENTER_DISTRIBUTIONS;
DROP  TABLE IF EXISTS  FINANCIAL_DB.RAW.COST_CENTER_DETAIL;
DROP  TABLE IF EXISTS  FINANCIAL_DB.RAW.COST_CENTER;
DROP  TABLE IF EXISTS  FINANCIAL_DB.RAW.ACCOUNT;
----------------------

USE ROLE SYSADMIN;
USE WAREHOUSE INTEGRATIONS;
USE DATABASE FINANCIAL_DB;
USE SCHEMA PUBLIC;


DROP  TABLE IF EXISTS  FINANCIAL_DB.PUBLIC.IAN_FINANCE2;
DROP  TABLE IF EXISTS  FINANCIAL_DB.PUBLIC.VENDOR_INVOICES;

---------------------

USE ROLE SYSADMIN;
USE WAREHOUSE INTEGRATIONS;
USE DATABASE FINANCIAL_DB;
USE SCHEMA RECON;


DROP  TABLE IF EXISTS  FINANCIAL_DB.RECON.AUDIT;

--===========
-- 5. stages:
--===========
-- NOTE:  Stage is an intermediate space where new files are being uploaded
-- so that the pipe will use the COPY command to load or unload the target tables


USE ROLE SYSADMIN;
USE WAREHOUSE INTEGRATIONS;
USE DATABASE FINANCIAL_DB;
USE SCHEMA STG;

DROP  STAGE IF EXISTS  FINANCIAL_ACCOUNT_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_COSTCENTER_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_COST_CENTER_DISTRIBUTIONS_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_COST_CENTER_DETAIL_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_MAP_PRICE_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_INFO_RECORDS_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_MOVEMENT_DOCUMENTS_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_PROFITCENTER_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_VENDOR_INVOICES_SRC;



--==========
-- 9. Pipes:
--==========
-- NOTE: Pipe is responsible for loading/unloading the target table automation.
--       It uses:
--               a) specific notification integration(which uses specific queue)
--               b) specific stage
--               c) COPY command with specific logic to load/unload the target table:

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE INTEGRATIONS;
USE DATABASE FINANCIAL_DB;
USE SCHEMA STG;

DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_COST_CENTER_DETAIL_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_ACCOUNT_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_MAP_PRICE_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_INFO_RECORDS_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_MOVEMENT_DOCUMENTS_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_PROFITCENTER_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_VENDOR_INVOICES_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_COSTCENTER_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_COST_CENTER_DISTRIBUTIONS_PIPE;


```

###### What did you expect to see?

Succesful migration 

###### What did you see instead?

```
USE ROLE ACCOUNTADMIN;
USE WAREHOUSE INTEGRATIONS;
USE DATABASE FINANCIAL_DB;
USE SCHEMA STG;

DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_COST_CENTER_DETAIL_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_ACCOUNT_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_MAP_PRICE_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_INFO_RECORDS_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_MOVEMENT_DOCUMENTS_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_PROFITCENTER_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_VENDOR_INVOICES_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_COSTCENTER_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_COST_CENTER_DISTRIBUTIONS_PIPE;


**Caused by: Incomplete statement at line 100 col 1:** 

DROP  STAGE IF EXISTS  FINANCIAL_ACCOUNT_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_COSTCENTER_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_COST_CENTER_DISTRIBUTIONS_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_COST_CENTER_DETAIL_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_MAP_PRICE_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_INFO_RECORDS_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_MOVEMENT_DOCUMENTS_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_PROFITCENTER_SRC;
DROP  STAGE IF EXISTS  FINANCIAL_VENDOR_INVOICES_SRC;



--==========
-- 9. Pipes:
--==========
-- NOTE: Pipe is responsible for loading/unloading the target table automation.
--       It uses:
--               a) specific notification integration(which uses specific queue)
--               b) specific stage
--               c) COPY command with specific logic to load/unload the target table:

USE ROLE ACCOUNTADMIN;
USE WAREHOUSE INTEGRATIONS;
USE DATABASE FINANCIAL_DB;
USE SCHEMA STG;

DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_COST_CENTER_DETAIL_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_ACCOUNT_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_MAP_PRICE_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_INFO_RECORDS_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_MOVEMENT_DOCUMENTS_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_PROFITCENTER_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_VENDOR_INVOICES_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_COSTCENTER_PIPE;
DROP PIPE IF EXISTS FINANCIAL_DB.STG.FINANCIAL_COST_CENTER_DISTRIBUTIONS_PIPE;
```

Line 100 is DROP  STAGE IF EXISTS  FINANCIAL_ACCOUNT_SRC; - I know there are some issues with parser but this was working fine in older version of flyway

**Comment by niegowic** [comment]
it was working in version 9.8.0 - trying to narrow down the problem

**Comment by niegowic** [comment]
Seems issue caused by recent changes  in flyway-core/src/main/java/org/flywaydb/core/internal/database/snowflake/Snolyway-core/src/main/java/org/flywaydb/core/internal/database/snowflake/SnowflakeParser.javawflakeParser.java

**Comment by shamy500** [comment]
Similar issue. I tested it with 9.15.0 & 9.15.1.... It works in 9.11

`
 DROP FILE FORMAT IF EXISTS appstak_staging_csv_format;
 
         at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:308)
         at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.<init>(Parser.java:717)
         at org.flywaydb.core.internal.parser.Parser.parse(Parser.java:130)
         at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:72)
         at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:120)
         at org.flywaydb.core.internal.sqlscript.ParserSqlScript.executeInTransaction(ParserSqlScript.java:187)
         at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.canExecuteInTransaction(SqlMigrationExecutor.java:73)
         at org.flywaydb.core.internal.command.DbMigrate.isExecuteGroupInTransaction(DbMigrate.java:304)
         at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:269)
         at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
         at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
         at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:36)
         at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
         at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:31)
         at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:102)
         at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
         at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
         at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
         at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:177)
         at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:196)
         at org.flywaydb.core.Flyway.migrate(Flyway.java:129)
         at com.chilicoders.util.SnowflakeUtils.updateCustomerDatabase(SnowflakeUtils.java:131)
         at com.chilicoders.util.SnowflakeUtils.createCustomerDatabase(SnowflakeUtils.java:73)
         at com.chilicoders.bl.AgentBusiness$1.run(AgentBusiness.java:2715)
          Caused by: org.flywaydb.core.api.FlywayException: Incomplete statement at line 1 col 1: DROP FILE FORMAT IF EXISTS apprules_staging_csv_format;
`
