### ISSUE TITLE
Unable to start, execution of sql does not return results, stuck

### ISSUE THREAD

**Issue by lvhaosir6** [flyway/flyway#3637]
###### Which version and edition of Flyway are you using?

SpringBoot 		2.2.5.RELEASE
ShardingSphere  	4.1.1
flyway-code 	7.1.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using? (Type & version)

PostgreSql

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

The correct sentences that initialize the correct sentence cannot be returned.

It will always be stuck in this execution without any return.

###### What did you expect to see?
Execute correctly

###### What did you see instead?

<img width="966" alt="error0" src="https://user-images.githubusercontent.com/30766232/226332601-d6407c2d-ccd1-4a0f-9505-e136d039cce6.png">

<img width="819" alt="error1" src="https://user-images.githubusercontent.com/30766232/226332652-cae4441e-bf25-4750-849b-feeb86ffbc77.png">

**Comment by lvhaosir6** [comment]
<img width="819" alt="error1" src="https://user-images.githubusercontent.com/30766232/226332850-dc658327-5786-4d81-9863-6ba10d8cbf89.png">

**Comment by lvhaosir6** [comment]
flyway-code 7.1.1

**Comment by lvhaosir6** [comment]
After very many attempts, the following error is thrown

**Comment by lvhaosir6** [comment]
If you run for a long time, there will be an error



2023-03-21 13:05:29.160 ERROR 30032 --- [           main] com.alibaba.druid.pool.DruidDataSource   : recyle error

org.postgresql.util.PSQLException: This connection has been closed.
	at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:885)
	at org.postgresql.jdbc.PgConnection.clearWarnings(PgConnection.java:778)
	at com.alibaba.druid.pool.DruidConnectionHolder.reset(DruidConnectionHolder.java:331)
	at com.alibaba.druid.pool.DruidDataSource.recycle(DruidDataSource.java:1917)
	at com.alibaba.druid.pool.DruidPooledConnection.recycle(DruidPooledConnection.java:325)
	at com.alibaba.druid.pool.DruidPooledConnection.close(DruidPooledConnection.java:270)
	at org.apache.shardingsphere.sql.parser.binder.metadata.table.TableMetaDataLoader.load(TableMetaDataLoader.java:47)
	at org.apache.shardingsphere.core.metadata.ShardingMetaDataLoader.load(ShardingMetaDataLoader.java:83)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.loadTableMeta(AbstractStatementExecutor.java:240)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.refreshTableMetaData(AbstractStatementExecutor.java:187)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.refreshMetaDataIfNeeded(AbstractStatementExecutor.java:170)
	at org.apache.shardingsphere.shardingjdbc.executor.AbstractStatementExecutor.executeCallback(AbstractStatementExecutor.java:130)
	at org.apache.shardingsphere.shardingjdbc.executor.StatementExecutor.execute(StatementExecutor.java:221)
	at org.apache.shardingsphere.shardingjdbc.executor.StatementExecutor.execute(StatementExecutor.java:176)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.ShardingStatement.execute(ShardingStatement.java:147)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:241)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:111)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:206)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:82)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.access$000(SqlMigrationExecutor.java:32)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:70)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$1.call(SqlMigrationExecutor.java:67)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:28)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:67)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:434)
	at org.flywaydb.core.internal.command.DbMigrate.access$200(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$3.call(DbMigrate.java:341)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:66)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:338)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:303)
	at org.flywaydb.core.internal.command.DbMigrate.access$100(DbMigrate.java:56)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:207)
	at org.flywaydb.core.internal.command.DbMigrate$2.call(DbMigrate.java:204)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:73)
	at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:99)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:204)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:165)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:215)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:164)
	at org.flywaydb.core.Flyway.execute(Flyway.java:538)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:164)
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1380)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1300)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:917)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:582)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:767)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:426)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:326)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at com.maxcares.taas.lbs.TaasLbsApplication.main(TaasLbsApplication.java:26)

**Comment by Barry-RG** [comment]
@lvhaosir6 apologies for the delay in this response. With maven you can make transitive dependencies as excluded when importing. In this case I would exclude the flyway-core from spring boot and add a dependency yourself on the latest flyway-core. 
See [maven documentation](Ensure Flyway uses ALL_CREDENTIALS when using versions of Oracle where ALL_SCHEDULER_CREDENTIALS is deprecated) on how this works. 
This should allow you to continue using spring boot but with a more recent version of Flyway.

**Comment by Barry-RG** [comment]
I hope the above solved your issue. As there has been no response in a month I am going to close this issue.
