### ISSUE TITLE
Can't get connection with Java API

### ISSUE THREAD

**Issue by Izocel** [flyway/flyway#3689]
So i'm trying to setup flyway into my java Minecraft® plugin...
I've managed to use the mvn plugin to run clean,baseline and migrate with the 2 database instance without issues
Maria (lan) -> mysql 5.5
Mysql (localhost) -> mysql 8.0

But when I try to integrate the Java API in the project I can't get any connection...
Tried multiple flyway version, both urls and both datasource (ComboPooled)

###### Which version and edition of Flyway are you using?
Community 9.19.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API, Maven plugin

###### Which database are you using? (Type & version)
Mariadb (mysql 5.5) or Mysql native 8.8

###### Which operating system are you using?
Windows pro 64b 

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Can't get pass the fluent.load() to initiate connection:

###### What did you expect to see?
 - Unsupported Database: MySQL 5.5 <-- With ComboPooledDatasource (used by a DaoManger and 'c3po')
-  Unsupported Database: MySQL 8.0 <-- With ComboPooledDatasource
-  Unable to obtain connection from database jdbc:mariadb <-- With url, user,pass
-  Unable to obtain connection from database jdbc:mysql <-- With url,user,pass

###### What did you see instead?
Unable to get a connection to DB

Pom.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.rvdprojects.whitelistje</groupId>
    <artifactId>Whitelist-Je</artifactId>
    <version>2023.3 ${maven.build.timestamp}</version>
    <packaging>jar</packaging>

    <name>Whitelist Je</name>

    <properties>
        <java.version>18</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.build.timestamp.format>yyyyMMdd</maven.build.timestamp.format>
        <flyaway.configuration>flyaway.conf</flyaway.configuration>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.11.0</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.4.1</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-maven-plugin</artifactId>
                <version>9.19.1</version>
                <configuration>
                    <configFiles>
                        <configFile>${flyaway.configuration}</configFile>
                    </configFiles>
                </configuration>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
    </build>

    <repositories>
        <repository>
            <id>spigotmc-repo</id>
            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>
        </repository>
        <repository>
            <id>dv8tion</id>
            <name>m2-dv8tion</name>
            <url>https://m2.dv8tion.net/releases</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
            <version>8.0.33</version>
        </dependency>
        <dependency>
            <groupId>c3p0</groupId>
            <artifactId>c3p0</artifactId>
            <version>0.9.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20230227</version>
        </dependency>
        <dependency>
            <groupId>org.spigotmc</groupId>
            <artifactId>spigot-api</artifactId>
            <version>1.18.2-R0.1-SNAPSHOT</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>net.dv8tion</groupId>
            <artifactId>JDA</artifactId>
            <version>4.4.1_353</version>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq</artifactId>
            <version>3.18.4</version>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-meta</artifactId>
            <version>3.18.4</version>
        </dependency>
        <dependency>
            <groupId>org.jooq</groupId>
            <artifactId>jooq-codegen</artifactId>
            <version>3.18.4</version>
        </dependency>
        <dependency>
            <groupId>io.sentry</groupId>
            <artifactId>sentry</artifactId>
            <version>6.22.0</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>9.19.1</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
            <version>9.19.1</version>
        </dependency>
        <dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>3.1.4</version>
        </dependency>        
    </dependencies>
</project>

```

Source for ComboPolledDatasource
```java
package helpers;

import com.mchange.v2.c3p0.ComboPooledDataSource;

import configs.ConfigManager;

public class DbPoolFactory {

    public static final ComboPooledDataSource getMysqlPool(ConfigManager configs) throws Exception {

        // JDBC Driver Name & Database URL
        final String JDBC_DRIVER = "com.mysql.jdbc.Driver";

        // JDBC Driver Name & Database URL
        final String JDBC_URL = configs.get("mysqlJdbcUrl") + 
            "?connectionAttributes=program_name:WhiteList-Je";

        final Integer JDBC_MAX_ACTIVE = Integer.parseInt(configs.get("mysqlMaxConnection", "15"));
        final Integer JDBC_MAX_IDLE = Integer.parseInt(configs.get("mysqlMaxConnectionIDLE", "5"));

        final String JDBC_USER = configs.get("mysqlUser");
        final String JDBC_PASS = configs.get("mysqlPass");

        Class.forName(JDBC_DRIVER);

        // Creates an Instance of GenericObjectPool That Holds Our Pool of Connections
        // Object!
        ComboPooledDataSource ds = new ComboPooledDataSource();
        ds.setDriverClass(JDBC_DRIVER);
        ds.setJdbcUrl(JDBC_URL);
        ds.setUser(JDBC_USER);
        ds.setPassword(JDBC_PASS);
        ds.setMinPoolSize(JDBC_MAX_IDLE);
        ds.setMaxPoolSize(JDBC_MAX_ACTIVE);
        ds.setTestConnectionOnCheckin(true);
        ds.setTestConnectionOnCheckout(true);
        ds.setDescription("Pool for Wje Mc®");
        ds.setDataSourceName("Wje-plugin");


        return ds;
    }
}
```

MIGRATOR CLASS: //FIXME:
```java
package db;

import java.util.logging.Logger;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.configuration.FluentConfiguration;

import configs.ConfigManager;
import dao.DaoManager;
import io.sentry.ISpan;
import io.sentry.SpanStatus;
import main.WhitelistJe;
import services.sentry.SentryService;

public class Migrator {
    private WhitelistJe plugin;
    private Flyway flyway;
    private Logger logger;

    /**
     * @param plugin
     */
    public Migrator(WhitelistJe plugin) {
        try {
            ISpan process = plugin.getSentryService().findWithuniqueName("onEnable")
                    .startChild("Migrator");

            this.plugin = plugin;
            this.logger = Logger.getLogger("WJE:" + getClass().getSimpleName());

            final ConfigManager configs = this.plugin.getConfigManager();
            
            final String JDBC_USER = configs.get("mysqlUser");
            final String JDBC_PASS = configs.get("mysqlPass");
            final String JDBC_URL = configs.get("mysqlJdbcUrl");
            final String M_JDBC_URL = configs.get("mariaJdbcUrl");
            
            FluentConfiguration flywayConfigs = Flyway.configure()
            .dataSource(DaoManager.getDatasource())
            .locations("classpath:db/migration");

            this.flyway = new Flyway(flywayConfigs);
            flyway.migrate();

            process.setStatus(SpanStatus.OK);
            process.finish();
        } catch (Exception e) {
            SentryService.captureEx(e);
        }
    }
}
```

Where the class is instanciated: *Minecraft server 'load'
```
    @Override
    public final void onEnable() {
        ITransaction transaction = Sentry.startTransaction("onEnable", "configurePlugin");
        final StringBuilder sb = new StringBuilder();

        try {
            this.configManager = new ConfigManager();
            logger.info("LOADED: ConfigManager");
            
            LOCALES = new LocalManager(this);
            logger.info("LOADED: LocalManager");
            
            sentryService = new SentryService(this);
            transaction = sentryService.createTx("onEnable", "configurePlugin");
            logger.info("LOADED: SentryService");
            
            daoManager = new DaoManager(this);
            logger.info("LOADED: DaoManager");

            migrator = new Migrator(this);
            logger.info("LOADED: Migrator");
          
        } catch (Exception e) {
                ............
        }

        transaction.setStatus(SpanStatus.OK);
        transaction.finish();
    }
```

**Comment by Izocel** [comment]
Feel free to ask for any other details i'm trying to fix this for 3days nows

**Comment by Izocel** [comment]
Since i'm here I dont see the advantage of the community version since we can only clean merge and migrate up.
I don't understand why the most needed feature 'undo' comes with a price.

**Comment by Izocel** [comment]
Already checked taht does not seem to pose problem ??

![image](https://github.com/flyway/flyway/assets/68454661/e6483ed1-4b70-4283-a5eb-e52bf21798d8)

**Comment by JasonLuo-Redgate** [comment]
Could you share a full print out log of the failed execution ?

**Comment by Izocel** [comment]
> 

They are only warning so I don't have many details:

code:
![image](https://github.com/flyway/flyway/assets/68454661/ad6a3451-502a-4a4f-b77a-5f3f63dd4a32)


## With localhost connection on mysql 8.0 and ComboPooledDatasource:
```csharp
[17:59:36 WARN]: [WJE:Migrator] Unsupported Database: MySQL 8.0
[17:59:36 WARN]: org.flywaydb.core.api.FlywayException: Unsupported Database: MySQL 8.0
[17:59:36 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105)
[17:59:36 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)
[17:59:36 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:140)
[17:59:36 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.Flyway.migrate(Flyway.java:140)
[17:59:36 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//db.Migrator.<init>(Migrator.java:43)
[17:59:36 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//main.WhitelistJe.onEnable(WhitelistJe.java:115)
[17:59:36 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[17:59:36 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[17:59:36 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[17:59:36 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[17:59:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
[17:59:36 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
[17:59:36 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[17:59:36 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[17:59:36 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[17:59:36 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[17:59:36 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[17:59:36 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

## With localhost connection on mysql 8.0  and url, user, pass:
**.dataSource(JDBC_URL, JDBC_USER, JDBC_PASS)**
                
```csharp
[18:11:12 WARN]: [WJE:Migrator] No database found to handle jdbc:mysql://127.0.0.1:3306/whitelist_je
[18:11:12 WARN]: org.flywaydb.core.api.FlywayException: No database found to handle jdbc:mysql://127.0.0.1:3306/whitelist_je
[18:11:12 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:54)
[18:11:12 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109)
[18:11:12 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:80)
[18:11:12 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1079)
[18:11:12 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:626)
[18:11:12 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//db.Migrator.<init>(Migrator.java:39)
[18:11:12 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//main.WhitelistJe.onEnable(WhitelistJe.java:115)
[18:11:12 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[18:11:12 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[18:11:12 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[18:11:12 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[18:11:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
[18:11:12 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
[18:11:12 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[18:11:12 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[18:11:12 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[18:11:12 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[18:11:12 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[18:11:12 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

## With ipv4 lan connection on mariadb 10.3.32-1040  and and ComboPooledDatasource:
using: 'org.mariadb.jdbc.Driver' as JDBC_DRIVER for ComboPooledDatasource
```csharp
[18:23:24 WARN]: [WJE:Migrator] Unsupported Database: MariaDB 10.3
[18:23:24 WARN]: org.flywaydb.core.api.FlywayException: Unsupported Database: MariaDB 10.3
[18:23:24 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105)
[18:23:24 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)
[18:23:24 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:140)
[18:23:24 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.Flyway.migrate(Flyway.java:140)
[18:23:24 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//db.Migrator.<init>(Migrator.java:44)
[18:23:24 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//main.WhitelistJe.onEnable(WhitelistJe.java:115)
[18:23:24 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[18:23:24 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[18:23:24 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[18:23:24 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[18:23:24 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
[18:23:24 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
[18:23:24 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[18:23:24 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[18:23:24 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[18:23:24 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[18:23:24 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[18:23:24 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

## With localhost connection on mysql 8.0  and url, user, pass:
**.dataSource(M_JDBC_URL, JDBC_USER, JDBC_PASS)**
```csharp
[18:26:25 WARN]: [WJE:Migrator] No database found to handle jdbc:mariadb://192.168.0.128:3306/whitelist_je
[18:26:25 WARN]: org.flywaydb.core.api.FlywayException: No database found to handle jdbc:mariadb://192.168.0.128:3306/whitelist_je
[18:26:25 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForUrl(DatabaseTypeRegister.java:54)
[18:26:25 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109)
[18:26:25 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:80)
[18:26:25 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1079)
[18:26:25 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:626)
[18:26:25 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//db.Migrator.<init>(Migrator.java:39)
[18:26:25 WARN]:        at Whitelist-Je-2023.3 20230614-shaded.jar//main.WhitelistJe.onEnable(WhitelistJe.java:115)
[18:26:25 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
[18:26:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
[18:26:25 WARN]:        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
[18:26:25 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
[18:26:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:563)
[18:26:25 WARN]:        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:474)
[18:26:25 WARN]:        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:638)
[18:26:25 WARN]:        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:437)
[18:26:25 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:308)
[18:26:25 WARN]:        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
[18:26:25 WARN]:        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
[18:26:25 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by Izocel** [comment]
A Players cache is update after all those warning with c3po and the ComboPooledDatasource 'daoManager' without any problems

**Comment by Izocel** [comment]
@JasonLuo-Redgate awaiting on your toughts

**Comment by zieglar** [comment]
Me too, 
flyway ce version 9.19.1
mysql version 8.0
still `Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: MySQL 8.0`

**Comment by Izocel** [comment]
> It's there check the repos

I'll check the 'jar' tonight and send yo ua print screen ;)

**Comment by Izocel** [comment]
@JasonLuo-Redgate 
![image](https://github.com/flyway/flyway/assets/68454661/f1afda39-1315-49c1-a338-9972e47fabcc)

**Comment by zieglar** [comment]
![image](https://github.com/flyway/flyway/assets/514693/8a4d216b-4a08-448d-8ec8-864b44b2213e)
I think I found why the error was reported

**Comment by JasonLuo-Redgate** [comment]
Hi @Izocel , just a follow up, are you still facing this same issue?

**Comment by JasonLuo-Redgate** [comment]
Hi @Izocel , I downloaded your repo, and locally created a  `Migrator ` object with a simple test case. 
No that ` No database found ` thrown.

![image](https://github.com/flyway/flyway/assets/130552403/335e452c-a1c8-46a9-98cc-bd2964665663)

![image](https://github.com/flyway/flyway/assets/130552403/aeefe20d-0b56-441e-8cc4-090ce0502b19)

**Comment by JasonLuo-Redgate** [comment]
Again, the only way I can locally to reproduce that error with your repo is to remove the `flyway-mysql dependency` from the pom file. 

Below is what happen if I remove that dependency and run the case again:


![image](https://github.com/flyway/flyway/assets/130552403/87575b18-de81-4271-a307-fce674755173)

**Comment by Izocel** [comment]
you cloned the repos literaly ?
Used the java 18 SDK ?
clean, build , insatll from maven ?
and the migrator works ?

**Comment by JasonLuo-Redgate** [comment]
Hi @Izocel , yes, I locally cloned the repo, made code changes in Migrator class as shown in above screenshots, and added a UT to run it.  It didn't throw that Exception, the UT is running fine. 
Only when I deleted that dependency from pom, reload Maven, and run that case again, I can see that Exception.

**Comment by Izocel** [comment]
@JasonLuo-Redgate Ok thank you, I did not saw your code change... Your changes make senses, i'll check on another computer and a vanilla mysql and mariadb service could be 'Amps' or 'Synology NAS' db service cofiguration issues.
Thanks for you time i'll let you know

**Comment by Izocel** [comment]
@JasonLuo-Redgate I really don't get it :(... I'm still on the same pc but freshly installed mariadb
![image](https://github.com/flyway/flyway/assets/68454661/261142ff-c614-472a-b356-55ed96c669dd)

**Comment by Izocel** [comment]
will this work ??

![image](https://github.com/flyway/flyway/assets/68454661/eed4cb93-8c3e-4214-9dc2-4799df2a4466)

**Comment by JasonLuo-Redgate** [comment]
Hi @Izocel , could you check your `WhitelistJe-2023.3-20230622-shaded.jar `that `flyway-mysql `exists in the `META-INF\maven\org.flywaydb` path?

**Comment by Izocel** [comment]
![image](https://github.com/flyway/flyway/assets/68454661/f6029b9c-3bd1-4f20-91fd-df9e8eb6fed0)

**Comment by Izocel** [comment]
With the Maven CLI the same DB and project it works. Im able to do migrations.

**Comment by JasonLuo-Redgate** [comment]
Hi @Izocel , so currently you're facing the situation that Maven plugin is working fine, but Java API failed to connect? With the same environment?

**Comment by Izocel** [comment]
yes

**Comment by Izocel** [comment]
@JasonLuo-Redgate didn't hear from you since a bit, have you got any hint ?

**Comment by Izocel** [comment]
@JasonLuo-Redgate You can see details of the run in my github workflow:
https://github.com/Izocel/Minecraft-Whitelist-Discord-Bot/actions/runs/5418541374/jobs/9850735265

The "Seed database" part is a 'baseline' and 'migrate' with mvn
And if you go to "Mc® Server Launch" line:129 you'll see the same migrator error...

```shell
[02:11:25 WARN]: [WJE:Migrator] Unsupported Database: MySQL 8.0
[02:11:25 WARN]: org.flywaydb.core.api.FlywayException: Unsupported Database: MySQL 8.0
```

**Comment by JasonLuo-Redgate** [comment]
Hi @Izocel , sorry it looks like we mixed discussions for two different errors in previous loops:

- No database found to handle xxx
- Unsupported Database: xxx

There are different causes behind these two.

**Comment by Izocel** [comment]
The same environement could give both errors it depends if i connect with user,pass,url or a MysqlResourcePooledConnectoin object

**Comment by Izocel** [comment]
@JasonLuo-Redgate still on this ?

**Comment by Izocel** [comment]
@JasonLuo-Redgate awaiting further explanation

**Comment by Izocel** [comment]
still going on with last update
