### ISSUE TITLE
flyway-core depends on jackson: fails if not present

### ISSUE THREAD

**Issue by froque** [flyway/flyway#3690]
###### Which version and edition of Flyway are you using?
Version 9.19.2

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
yes

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
flyway-core java API

###### Which database are you using? (Type & version)
postgresql

###### Which operating system are you using?
linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
upgraded flyway-core from 9.19.1 to 9.19.4 

this excerpt reproduces the problem
```java
final Flyway flyway = Flyway
                .configure()
                .configuration(Map.of("flyway.postgresql.transactional.lock", "false"))
                .load();
```

###### What did you expect to see?
Expected flyway-core to work normally, even if jackson is not present

###### What did you see instead?

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
	at org.flywaydb.core.api.configuration.ClassicConfiguration.determineKeysToRemoveAndRemoveFromProps(ClassicConfiguration.java:1910)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1479)
	at org.flywaydb.core.api.configuration.FluentConfiguration.configuration(FluentConfiguration.java:959)
	at org.example.Main.main(Main.java:11)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 4 more
```

This seems similar to https://github.com/flyway/flyway/issues/3672. jackson is marked as optional on the pom.xml. Also why is two different json libraries being used ?

**Comment by JasonLuo-Redgate** [comment]
And the two different json libraries being used thing will also be taken care of.

**Comment by DougC** [comment]
I have just updated to 11.8.1 (from 11.8.0) and am seeing this same issue.

```
java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
	at org.flywaydb.core.extensibility.ConfigurationExtension.copy(ConfigurationExtension.java:40)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at org.flywaydb.core.internal.plugin.PluginRegister.getCopy(PluginRegister.java:122)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1674)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.<init>(ClassicConfiguration.java:158)
	at org.flywaydb.core.Flyway.<init>(Flyway.java:132)
	at org.flywaydb.core.api.configuration.FluentConfiguration.load(FluentConfiguration.java:64)
```

**Comment by domdorn** [comment]
Is there no way to load configuration without Jackson? e.g. in our app, we configure flyway just with the DSL, still its pulling in Jackson which we try to get rid of.
