### ISSUE TITLE
Flyway plugin triggers Gradle deprecation warnings

### ISSUE THREAD

**Issue by marshallpierce** [flyway/flyway#3701]
###### Which version and edition of Flyway are you using?
Version 9.20.0 Community

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
N/A, 9.20.0 is currently the latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin with Gradle 8.2

###### Which database are you using? (Type & version)
PostgreSQL 11.7

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Use the Gradle plugin. FlywayMigrateTask, FlywayCleanTask, etc all trigger the deprecation warnings.

###### What did you expect to see?
No deprecation warnings

###### What did you see instead?

```
The Project.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)
        at org.flywaydb.gradle.task.AbstractFlywayTask.addClassesAndResourcesDirs(AbstractFlywayTask.java:620)
        at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:598)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:51)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:29)
        at org.gradle.api.internal.tasks.execution.TaskExecution$3.run(TaskExecution.java:248)
...
```

The offending code: https://github.com/flyway/flyway/blob/main/flyway-gradle-plugin/src/main/java/org/flywaydb/gradle/task/AbstractFlywayTask.java#L620

Presumably the path forward is to find a way to access source sets other than via the Java plugin convention, but I'm not a Gradle API expert.

**Comment by Barry-RG** [comment]
Thank you for bringing this to our attention. We will look into fixing this.
