### ISSUE TITLE
Error in Docker image 9.20.1: java.lang.NoClassDefFoundError 

### ISSUE THREAD

**Issue by armandduijn** [flyway/flyway#3705]
###### Which version and edition of Flyway are you using?
Community Edition 9.20.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
N/A

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Docker image

###### Which database are you using? (Type & version)
Redshift

###### Which operating system are you using?
Ubuntu 22.04 (Amazon CodeBuild Standard 7.0)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Run the Docker image using the `migrate` command.

```
docker run --rm
  -v $(pwd)/sql:/flyway/sql
  -v $(pwd)/drivers:/flyway/drivers
  -v $(pwd)/flyway.conf:/flyway/conf/flyway.conf
  flyway/flyway:9.20.1 migrate
```

###### What did you expect to see?
A list of migrations that were executed.

###### What did you see instead?
```
Status: Downloaded newer image for ***/***:9.20.1
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
    at java.base/java.lang.ClassLoader.defineClass1(Native Method)
    at java.base/java.lang.ClassLoader.defineClass(Unknown Source)
    at java.base/java.security.SecureClassLoader.defineClass(Unknown Source)
    at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(Unknown Source)
    at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(Unknown Source)
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(Unknown Source)
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
    at org.***db.commandline.MavenVersionChecker.checkForVersionUpdates(MavenVersionChecker.java:60)
    at org.***db.commandline.Main.main(Main.java:107)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
    at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
    ... 11 more
```

**Comment by KeithTreagueParaport** [comment]
@Barry-RG  the docs on the docker hub page specifically contain the following statement to override the drivers folder. Based on your statement, you still need to update your official docker documentation. 


You can now let Flyway make use of it my mapping that volume as well:

docker run --rm -v /absolute/path/to/my/sqldir:/flyway/sql -v /absolute/path/to/my/confdir:/flyway/conf -v /absolute/path/to/my/driverdir:/flyway/drivers flyway/flyway migrate
