### ISSUE TITLE
Flyway migrate 9.20.1 via command-line has a runtime dependency on jackson-databind which is located in the drivers/ folder only

### ISSUE THREAD

**Issue by rzanner** [flyway/flyway#3711]
###### Which version and edition of Flyway are you using?
9.20.1 Community Edition

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
9.20.0 did not have the runtime dependency on jackson-databind, yet, although the JAR is already packaged inside the drivers/ folder.
Does some of the packaged JDBC drivers have a dependency on it?

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line

###### Which database are you using? (Type & version)
Oracle 18 XE

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

We are re-packaging "flyway-commandline-9.20.1.tar.gz" and remove all driver JARs that are not required on our environment. 
This is mainly to keep the footprint of our deployment small and save network band-with and disk space during and after deployment.
We only link the commercial Oracle driver of the database installation folder to the drivers/ folder after unzipping the package, so this is the only JAR present in the drivers/ folder.

###### What did you expect to see?
I expect "flyway migrate" to pass without errors.
I consider everything in the drivers/ folder as optional for the normal runtime of flyway-core.

###### What did you see instead?
Exception in thread "main" java.lang.NoClassDefFoundError: com/fasterxml/jackson/databind/ObjectMapper
at java.lang.ClassLoader.defineClass1(Native Method)
at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
at java.security.AccessController.doPrivileged(Native Method)
at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
at org.flywaydb.commandline.MavenVersionChecker.checkForVersionUpdates(MavenVersionChecker.java:60)
at org.flywaydb.commandline.Main.main(Main.java:107)
Caused by: java.lang.ClassNotFoundException: com.fasterxml.jackson.databind.ObjectMapper
at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 14 more

**Comment by Barry-RG** [comment]
Please see #3705

**Comment by rzanner** [comment]
Hi @Barry-RG, you closed this issue - so you are not considering moving the jackson-databind.jar to the lib/ folder?

**Comment by JasonLuo-Redgate** [comment]
Hi @rzanner , no worries, we have put this request under tracking.
