### ISSUE TITLE
When SPANNER_EMULATOR_HOST is set flyway still reaches out to GCP auth endpoints.

### ISSUE THREAD

**Issue by samvanryssegem-qz** [flyway/flyway#3715]
###### Which version and edition of Flyway are you using?

9.21.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Docker

###### Which database are you using? (Type & version)
Spanner

###### Which operating system are you using?
MacOS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I set up a docker-compose file like so, with a docker image that's copying in my schema migration files. Which I ran using `docker-compose up --build` . I was expecting to see flyway connect to spanner and start migrating my files.

```version: '3'
services:   
   ### Spanner Specific stuff
  spanner:
   image: gcr.io/cloud-spanner-emulator/emulator:1.2.0
   ports:
       - 9010:9010
       - 9020:9020

  # Init (Create Instance)
  gcloud-spanner-init:
    image: gcr.io/google.com/cloudsdktool/cloud-sdk:332.0.0-slim
    command: >
     bash -c 'gcloud config configurations create emulator &&
             gcloud config set auth/disable_credentials true &&
             gcloud config set project $${PROJECT_ID} &&
             gcloud config set api_endpoint_overrides/spanner $${SPANNER_EMULATOR_URL} &&
             gcloud config set auth/disable_credentials true &&
             gcloud spanner instances create $${INSTANCE_NAME} --config=emulator-config --description=Emulator --nodes=1'
    environment:
      PROJECT_ID: "test-project"
      SPANNER_EMULATOR_URL: "http://spanner:9020/"
      INSTANCE_NAME: "test-instance"
      DATABASE_NAME: "test-database"

  flyway:
    build: ./spanner
    environment:
      SPANNER_EMULATOR_HOST: "spanner:9020"
      GOOGLE_APPLICATION_CREDENTIALS: /flyway/nonsense.json
      SPANNER_EMULATOR_URL: "http://spanner:9020/"
      FLYWAY_URL: jdbc:cloudspanner:/projects/test-project/instances/test-instance/databases/test-database?credentials=/flyway/nonsense.json
    command: -locations=filesystem:/flyway/sql -schemas=flyway -baselineOnMigrate=false migrate
    restart: on-failure
```

###### What did you expect to see?

 I was expecting to see flyway connect to spanner and start using my schema files to initiate a migration.

###### What did you see instead?

```
Flyway Community Edition 9.21.0 by Redgate
flyway_1               | See release notes here: https://rd.gt/416ObMi
flyway_1               |
flyway_1               | Database: jdbc:cloudspanner:/projects/test-project/instances/test-instance/databases/test-database (Google Cloud Spanner 1.0)
flyway_1               | Join the GCP Spanner beta via https://rd.gt/3yqM3jJ
flyway_1               |
flyway_1               | Experiencing performance issues while using GCP Spanner?
flyway_1               | Find out how Flyway Teams improves performance with batching at https://rd.gt/2ZvELhV
flyway_1               |
gcloud-spanner-init_1  | Creating instance...
gcloud-spanner-init_1  | .....done.
local-dev-demo_gcloud-spanner-init_1 exited with code 0
flyway_1               | ERROR: com.google.cloud.spanner.SpannerException: UNAVAILABLE: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | Caused by: com.google.cloud.spanner.SpannerException: UNAVAILABLE: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | Caused by: com.google.cloud.spanner.SpannerException: UNAVAILABLE: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | Caused by: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | Caused by: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | Caused by: com.google.auth.oauth2.GoogleAuthException: Error getting access token for service account: 400 Bad Request
flyway_1               | POST https://oauth2.googleapis.com/token
flyway_1               | {"error":"invalid_grant","error_description":"Invalid JWT Signature."}, iss: example@example.iam.gserviceaccount.com
flyway_1               | Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
flyway_1               | POST https://oauth2.googleapis.com/token
flyway_1               | {"error":"invalid_grant","error_description":"Invalid JWT Signature."}

```

I'd expect that by passing in stuff like the emulator host env var spanner would skip the google cloud auth process.

**Comment by samvanryssegem-qz** [comment]
more detailed stack trace:

```

flyway_1               | Database: jdbc:cloudspanner:/projects/test-project/instances/test-instance/databases/test-database (Google Cloud Spanner 1.0)
flyway_1               | DEBUG: Driver  : com.google.cloud.spanner.jdbc.JdbcDriver 2.0
flyway_1               | Join the GCP Spanner beta via https://rd.gt/3yqM3jJ
flyway_1               |
flyway_1               | Experiencing performance issues while using GCP Spanner?
flyway_1               | Find out how Flyway Teams improves performance with batching at https://rd.gt/2ZvELhV
flyway_1               |
flyway_1               | DEBUG: DDL Transactions Supported: false
flyway_1               | DEBUG: Schemas: flyway
flyway_1               | DEBUG: Default schema: null
flyway_1               | DEBUG: Performing operation in non-transactional context.
flyway_1               | DEBUG: Memory usage: 27 of 69M
flyway_1               | ERROR: Unexpected error
flyway_1               | com.google.cloud.spanner.SpannerException: UNAVAILABLE: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:291)
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:297)
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:170)
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:110)
flyway_1               | 	at com.google.cloud.spanner.SessionPool$WaiterFuture.pollUninterruptiblyWithTimeout(SessionPool.java:1633)
flyway_1               | 	at com.google.cloud.spanner.SessionPool$WaiterFuture.get(SessionPool.java:1604)
flyway_1               | 	at com.google.cloud.spanner.SessionPool$WaiterFuture.get(SessionPool.java:1581)
flyway_1               | 	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:67)
flyway_1               | 	at com.google.cloud.spanner.SessionPool$PooledSessionFuture.get(SessionPool.java:1354)
flyway_1               | 	at com.google.cloud.spanner.SessionPool.getDialect(SessionPool.java:1992)
flyway_1               | 	at com.google.cloud.spanner.DatabaseClientImpl.getDialect(DatabaseClientImpl.java:59)
flyway_1               | 	at com.google.cloud.spanner.connection.ConnectionImpl.getDialect(ConnectionImpl.java:363)
flyway_1               | 	at com.google.cloud.spanner.jdbc.AbstractJdbcConnection.getDialect(AbstractJdbcConnection.java:83)
flyway_1               | 	at com.google.cloud.spanner.jdbc.JdbcDatabaseMetaData.getTables(JdbcDatabaseMetaData.java:755)
flyway_1               | 	at org.flywaydb.database.spanner.SpannerDatabase.getNumberOfFields(SpannerDatabase.java:69)
flyway_1               | 	at org.flywaydb.database.spanner.SpannerDatabase.ensureSupported(SpannerDatabase.java:52)
flyway_1               | 	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:181)
flyway_1               | 	at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
flyway_1               | 	at org.flywaydb.commandline.Main.executeOperation(Main.java:215)
flyway_1               | 	at org.flywaydb.commandline.Main.executeFlyway(Main.java:154)
flyway_1               | 	at org.flywaydb.commandline.Main.main(Main.java:115)
flyway_1               | Caused by: com.google.cloud.spanner.SpannerException: UNAVAILABLE: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:291)
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:297)
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:170)
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:110)
flyway_1               | 	at com.google.cloud.spanner.SessionPool$SessionConsumerImpl.onSessionCreateFailure(SessionPool.java:2486)
flyway_1               | 	at com.google.cloud.spanner.SessionClient$BatchCreateSessionsRunnable.run(SessionClient.java:140)
flyway_1               | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
flyway_1               | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
flyway_1               | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
flyway_1               | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
flyway_1               | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
flyway_1               | 	at java.base/java.lang.Thread.run(Unknown Source)
flyway_1               | Caused by: com.google.cloud.spanner.SpannerException: UNAVAILABLE: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:291)
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerExceptionPreformatted(SpannerExceptionFactory.java:297)
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:61)
flyway_1               | 	at com.google.cloud.spanner.SpannerExceptionFactory.newSpannerException(SpannerExceptionFactory.java:181)
flyway_1               | 	at com.google.cloud.spanner.spi.v1.GapicSpannerRpc.get(GapicSpannerRpc.java:1862)
flyway_1               | 	at com.google.cloud.spanner.spi.v1.GapicSpannerRpc.batchCreateSessions(GapicSpannerRpc.java:1547)
flyway_1               | 	at com.google.cloud.spanner.SessionClient.internalBatchCreateSessions(SessionClient.java:303)
flyway_1               | 	at com.google.cloud.spanner.SessionClient.access$000(SessionClient.java:38)
flyway_1               | 	at com.google.cloud.spanner.SessionClient$BatchCreateSessionsRunnable.run(SessionClient.java:137)
flyway_1               | 	... 6 more
flyway_1               | Caused by: java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592)
flyway_1               | 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:571)
flyway_1               | 	at com.google.cloud.spanner.spi.v1.GapicSpannerRpc.get(GapicSpannerRpc.java:1856)
flyway_1               | 	... 10 more
flyway_1               | Caused by: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | 	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:112)
flyway_1               | 	at com.google.api.gax.rpc.ApiExceptionFactory.createException(ApiExceptionFactory.java:41)
flyway_1               | 	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:86)
flyway_1               | 	at com.google.api.gax.grpc.GrpcApiExceptionFactory.create(GrpcApiExceptionFactory.java:66)
flyway_1               | 	at com.google.api.gax.grpc.GrpcExceptionCallable$ExceptionTransformingFuture.onFailure(GrpcExceptionCallable.java:97)
flyway_1               | 	at com.google.api.core.ApiFutures$1.onFailure(ApiFutures.java:84)
flyway_1               | 	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1127)
flyway_1               | 	at com.google.common.util.concurrent.DirectExecutor.execute(DirectExecutor.java:31)
flyway_1               | 	at com.google.common.util.concurrent.AbstractFuture.executeListener(AbstractFuture.java:1286)
flyway_1               | 	at com.google.common.util.concurrent.AbstractFuture.complete(AbstractFuture.java:1055)
flyway_1               | 	at com.google.common.util.concurrent.AbstractFuture.setException(AbstractFuture.java:807)
flyway_1               | 	at io.grpc.stub.ClientCalls$GrpcFuture.setException(ClientCalls.java:574)
flyway_1               | 	at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544)
flyway_1               | 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
flyway_1               | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
flyway_1               | 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
flyway_1               | 	at com.google.api.gax.grpc.ChannelPool$ReleasingClientCall$1.onClose(ChannelPool.java:541)
flyway_1               | 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
flyway_1               | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
flyway_1               | 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
flyway_1               | 	at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
flyway_1               | 	at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
flyway_1               | 	at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
flyway_1               | 	at com.google.cloud.spanner.spi.v1.SpannerErrorInterceptor$1$1.onClose(SpannerErrorInterceptor.java:100)
flyway_1               | 	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
flyway_1               | 	at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
flyway_1               | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
flyway_1               | 	at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
flyway_1               | 	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
flyway_1               | 	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
flyway_1               | 	... 3 more
flyway_1               | Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: Credentials failed to obtain metadata
flyway_1               | 	at io.grpc.Status.asRuntimeException(Status.java:539)
flyway_1               | 	... 21 more
flyway_1               | Caused by: com.google.auth.oauth2.GoogleAuthException: Error getting access token for service account: 400 Bad Request
flyway_1               | POST https://oauth2.googleapis.com/token
flyway_1               | {"error":"invalid_grant","error_description":"Invalid JWT Signature."}, iss: external-ingress-backend-dev@compact-sylph-785.iam.gserviceaccount.com
flyway_1               | 	at com.google.auth.oauth2.GoogleAuthException.createWithTokenEndpointResponseException(GoogleAuthException.java:129)
flyway_1               | 	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:541)
flyway_1               | 	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:269)
flyway_1               | 	at com.google.auth.oauth2.OAuth2Credentials$1.call(OAuth2Credentials.java:266)
flyway_1               | 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
flyway_1               | 	at com.google.auth.oauth2.OAuth2Credentials$RefreshTask.run(OAuth2Credentials.java:633)
flyway_1               | 	... 3 more
flyway_1               | Caused by: com.google.api.client.http.HttpResponseException: 400 Bad Request
flyway_1               | POST https://oauth2.googleapis.com/token
flyway_1               | {"error":"invalid_grant","error_description":"Invalid JWT Signature."}
flyway_1               | 	at com.google.api.client.http.HttpResponseException$Builder.build(HttpResponseException.java:293)
flyway_1               | 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1118)
flyway_1               | 	at com.google.auth.oauth2.ServiceAccountCredentials.refreshAccessToken(ServiceAccountCredentials.java:538)
flyway_1               | 	... 7 more
```

**Comment by Barry-RG** [comment]
Thank you for your issue. Flyway's integration with GCP Cloud Spanner is still in beta and features like Spanner emulation are still missing. I will put this on the feature log and assess what we can do to fix your issue.

**Comment by samvanryssegem-qz** [comment]
> Thank you for your issue. Flyway's integration with GCP Cloud Spanner is still in beta and features like Spanner emulation are still missing. I will put this on the feature log and assess what we can do to fix your issue.

Thanks Barry, much appreciated

**Comment by lhriley** [comment]
I just ran into this and found a workaround from one of our developers that looks like this:

```
FLYWAY_URL: jdbc:cloudspanner://spanner:9020/projects/test-project/instances/test-instance/databases/test-database?credentials=/flyway/nonsense.json
```

Note the change from `jdbc:cloudspanner:/` to `jdbc:cloudspanner://spanner:9020/`

**Comment by tjs145** [comment]
Is this still an issue, given the workaround above?

We use a very similar setup for testing Spanner internally and don't run into this issue.

**Comment by alistair-RG** [comment]
Closing as a stale issue
