### ISSUE TITLE
Azure SQL MSI Authentication - ClassNotFoundException: com.azure.identity.ManagedIdentityCredentialBuilder

### ISSUE THREAD

**Issue by mikec-greene** [flyway/flyway#3724]
###### Which version and edition of Flyway are you using?
9.21.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line using docker image

###### Which database are you using? (Type & version)
Azure SQL

###### Which operating system are you using?
ubuntu

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
We're trying to authenticate with our Azure SQL server using Azure Active Directory MSI by setting authentication=ActiveDirectoryMSI in our url as documented here: https://documentation.red-gate.com/fd/sql-server-184127608.html

###### What did you expect to see?
A successful info output

###### What did you see instead?
Exception in thread "main" java.lang.NoClassDefFoundError: com/azure/identity/ManagedIdentityCredentialBuilder
	at com.microsoft.sqlserver.jdbc.SQLServerSecurityUtility.getManagedIdentityCredAuthToken(SQLServerSecurityUtility.java:342)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:5665)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5618)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5463)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:311)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:131)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:42)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6490)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:5068)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:93)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:5002)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7685)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4048)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3487)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:258)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:223)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1082)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1664)
	at org.flywaydb.core.api.configuration.FluentConfiguration.configuration(FluentConfiguration.java:919)
	at org.flywaydb.commandline.configuration.LegacyConfigurationManager.getConfiguration(LegacyConfigurationManager.java:91)
	at org.flywaydb.commandline.configuration.ConfigurationManagerImpl.getConfiguration(ConfigurationManagerImpl.java:41)
	at org.flywaydb.commandline.Main.main(Main.java:100)
Caused by: java.lang.ClassNotFoundException: com.azure.identity.ManagedIdentityCredentialBuilder
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	... 26 more

**Comment by mikec-greene** [comment]
Just to add it looks like this was introduced in 9.20.0, only thing I can see in the release notes is the SQL 2022 compatibility work so could be related to that

**Comment by jylipaa** [comment]
Later versions of mssql-jdbc require a lot of external libraries in order to work.

So you probably need to add com.azure:azure-identity jar (and it's dependencies) to your flyway image's [/flyway/drivers ](https://hub.docker.com/r/flyway/flyway)-volume.

**Comment by Skyere** [comment]
The same error👀

**Comment by Skyere** [comment]
Fixed by using gradle to download all dependencies 
`plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'com.azure:azure-identity:1.10.1'
    implementation group: 'com.fasterxml.jackson.datatype', name: 'jackson-datatype-jsr310', version: '2.15.2'
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.15.2'
}

task downloadDependencies {
    doLast {
        copy {
            from configurations.runtimeClasspath
            into '/flyway/drivers/'
        }
    }
}
`
gradle downloadDependencies
