### ISSUE TITLE
Unable to Insert Row For Version in Schema History Table Error

### ISSUE THREAD

**Issue by joesan** [flyway/flyway#3734]
###### Which version and edition of Flyway are you using?
I'm using the community edition Flyway version 9.9.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
I tried the 9.21.2 version and I get the same errors!

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
I'm using custom sbt command that runs my Scala code to perform the migrations

###### Which database are you using? (Type & version)
H2 version 2.1.214

###### Which operating system are you using?
Ubuntu 20.04

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I have an application.conf that has the following:

```
my-platform.jdbc {
  driver = "org.h2.Driver"
  dbName = "my-platform-h2-test.db;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL"
  url = "jdbc:h2:~/my-platform/database/"${my-platform.jdbc.dbName}
  user = "sa"
  migrations-table = "MyPlatformDBSchema"
  migrations-locations = [
    "classpath:h2/"
  ]
}
```

I'm reading that config using the Typesafe config and I traverse over the config and I run my sbt project which then results in the following error below:

```
INFO: Current version of schema "PUBLIC": << Empty Schema >>
Aug 28, 2023 9:33:23 PM org.flywaydb.core.internal.command.DbMigrate doMigrateGroup
INFO: Migrating schema "PUBLIC" to version "001 - baseline create initial tables"
org.flywaydb.core.internal.exception.FlywaySqlException: Unable to insert row for version '001' in Schema History table "PUBLIC"."MyPlatformDBSchema"
---------------------------------------------------------------------------------------------
SQL State  : 42S02
Error Code : 42102
Message    : Table "MyPlatformDBSchema" not found; SQL statement:
INSERT INTO "PUBLIC"."MyPlatformDBSchema" ("installed_rank", "version", "description", "type", "script", "checksum", "installed_by", "execution_time", "success") VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) [42102-214]

    at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.doAddAppliedMigration(JdbcTableSchemaHistory.java:177)
    at org.flywaydb.core.internal.schemahistory.SchemaHistory.addAppliedMigration(SchemaHistory.java:192)
    at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:402)
    at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:274)
```

I have in my src/main/resources folder a folder called h2, inside which I have my sql file called V001__baseline_create_initial_tables.sql which contains the schema that I want to use for my database like this:

```
--
-- Drop everything if exists
--

DROP ALL OBJECTS DELETE FILES;

--
-- Schema for my-platform
--
CREATE SCHEMA my_platform_schema AUTHORIZATION SA;
SET SCHEMA my_platform_schema;
....
.... 
-- The remaining create tables
....
....
```

What is it I'm doing wrong here?

**Comment by joesan** [comment]
https://github.com/flyway/flyway/issues/2877 helped me solve it!
