### ISSUE TITLE
FlywayValidateException after upgrading from Quarkus 2.13.x to Quarkus 3.2.x and Flyway 9.17.0)

### ISSUE THREAD

**Issue by miqui** [flyway/flyway#3747]
###### Which version and edition of Flyway are you using?

Flyway Community Edition 9.17.0 by Redgate

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Maven, Quarkus extension (quarkus:add-extension)

###### Which database are you using? (Type & version)
RDS/postgres

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Upgraded from Quarkus 2.13.1 to 3.2.0-final

================ start =======================
Upgraded from 2.13.x to 3.2.0-final and now our quarkus instance won't start due to the failed flyway validation. We, do have java/jdbc script in the classpath (but, not under convention /db/migration like our other sql scripts). Any hints? Thanks.

`src/main/resources/application-dev.properties`
added this entry after upgrade:

quarkus.flyway.locations=classpath:/db/migration,classpath:/com/delta/ccoe/dataMigrations

__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-09-19 18:48:29,833 WARN  [org.hib.id.UUIDHexGenerator] (main) HHH000409: Using org.hibernate.id.UUIDHexGenerator which does not generate IETF RFC 4122 compliant UUID values; consider using org.hibernate.id.UUIDGenerator instead
2023-09-19 18:48:35,133 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 9.17.0 by Redgate
2023-09-19 18:48:35,133 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) See release notes here: https://rd.gt/416ObMi
2023-09-19 18:48:35,134 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) 
2023-09-19 18:48:36,546 INFO  [org.fly.cor.int.dat.bas.BaseDatabaseType] (main) Database: jdbc:postgresql: *****
2023-09-19 18:48:37,037 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected applied migration not resolved locally: 1.0.19.
If you removed this migration intentionally, run repair to mark the migration as deleted.
Need more flexibility with validation rules? Learn more: https://rd.gt/3AbJUZE
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:146)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:196)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:93)
	at io.quarkus.deployment.steps.FlywayProcessor$startActions2035800939.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.FlywayProcessor$startActions2035800939.deploy(Unknown Source)
======================= end =========================

###### What did you expect to see?

no exceptions

###### What did you see instead?

Caused by: org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation
Detected applied migration not resolved locally: 1.0.19.

**Comment by tjs145** [comment]
This means that the migration script with version 1.0.19 was applied to the database at some point in the past, but Flyway can no longer find that script. 

This could be caused by changing the ['locations'](https://documentation.red-gate.com/fd/locations-184127514.html) parameter, or if the script got moved into a different directory which is not configured as a 'location'.
