### ISSUE TITLE
📢 Modular Flyway V10 (No database found to handle or Unsupported Database)

### ISSUE THREAD

**Issue by Barry-RG** [flyway/flyway#3780]
It has come to our attention that the move to a more modular Flyway in version V10.0.0 may not have been made clear enough in our [release notes](https://documentation.red-gate.com/flyway/release-notes-and-older-versions/release-notes-for-flyway-engine). 

As we attempt to move towards a much wider range of supported databases and database types we have found ourselves needing to extract database support out from `flyway-core` and into their own modules in order to improve maintainability and distribution size. 

As a result, databases, with the exception of in-memory or file databases such as H2 or SQLite, have been moved into their own packages which need to be added to your project when upgrading to Flyway V10.0.0. This includes whether you are using Flyway as a dependency in your project or using the Gradle or Maven plugins. 

The list of additional dependencies can be seen below:
* org.flywaydb:flyway-database-db2
* org.flywaydb:flyway-database-derby
* org.flywaydb:flyway-database-hsqldb
* org.flywaydb:flyway-database-informix
* org.flywaydb:flyway-database-postgresql
* org.flywaydb:flyway-database-oracle
* org.flywaydb:flyway-database-redshift
* org.flywaydb:flyway-database-saphana
* org.flywaydb:flyway-database-snowflake
* org.flywaydb:flyway-database-sybasease
* org.flywaydb:flyway-firebird
* org.flywaydb:flyway-gcp-bigquery
* org.flywaydb:flyway-gcp-spanner
* org.flywaydb:flyway-mysql
* org.flywaydb:flyway-singlestore
* org.flywaydb:flyway-sqlserver

If you are using any of the databases affected, please include the corresponding dependency in your project.

We are expecting that by structuring Flyway in to purposeful dependencies that we can both give developers more control of what aspects of Flyway they include in their project but also allow us to more fluently accept contributions and desired functionality from our community.

For more information on our on going goal to improve Flyway's open source version please see the following [blog](https://documentation.red-gate.com/flyway/flyway-blog/the-flyway-engine-oss-open-source-software-and-redgate).

**Comment by lachezar** [comment]
Thank you for preemptively opening this issue. I was about to open issue myself when I saw it 🙈

**Comment by davinkevin** [comment]
It could be cool to update the documentation for common used database (`postgresql`, `mysql`…) and with common build tools (`gradle`, `maven`), because the current documentation is still on 9.19 😅. 

In my specific case, I've tried for `gradle` build tool, but without success in my [module](https://gitlab.com/davinkevin/Podcast-Server/-/blob/dfdb905578ec869924ea4acf40d6dbf954ff6ada/backend-lib-database/build.gradle.kts). 

I tried to add `implementation("org.flywaydb:flyway-database-postgresql:10.0.0")` in the dependencies block, but with the same error/result when I run `:flywayMigrate` task

Additionally, I would like to have this dependency **ONLY** during task execution. Except if I'm wrong, the `flyway` plugin doesn't have a custom dep definition (like the `jooq` plugin in my example), it means to me I'll have to carry this dependency in my application… even if I don't use it !? 🤔.

**Comment by Barry-RG** [comment]
> It could be cool to update the documentation for common used database (postgresql, mysql…) and with common build tools (gradle, maven), because the current documentation is still on 9.19 😅.

Can you please point me to the URL that is still on 9.19?

**Comment by davinkevin** [comment]
> > It could be cool to update the documentation for common used database (postgresql, mysql…) and with common build tools (gradle, maven), because the current documentation is still on 9.19 😅.
> 
> @davinkevin Can you please point me to the URL that is still on 9.19?

https://documentation.red-gate.com/fd/quickstart-gradle-184127577.html 😇

**Comment by thetaurean** [comment]
> It could be cool to update the documentation for common used database (`postgresql`, `mysql`…) and with common build tools (`gradle`, `maven`), because the current documentation is still on 9.19 😅.
> 
> In my specific case, I've tried for `gradle` build tool, but without success in my [module](https://gitlab.com/davinkevin/Podcast-Server/-/blob/dfdb905578ec869924ea4acf40d6dbf954ff6ada/backend-lib-database/build.gradle.kts).
> 
> I tried to add `implementation("org.flywaydb:flyway-database-postgresql:10.0.0")` in the dependencies block, but with the same error/result when I run `:flywayMigrate` task
> 
> Additionally, I would like to have this dependency **ONLY** during task execution. Except if I'm wrong, the `flyway` plugin doesn't have a custom dep definition (like the `jooq` plugin in my example), it means to me I'll have to carry this dependency in my application… even if I don't use it !? 🤔.

This is also broken for [us](https://github.com/CDCgov/prime-reportstream/pull/12223)...

```
No database found to handle jdbc:postgresql://localhost:5432/prime_data_hub
```

The appropriate dependency has been added:
```
    implementation("org.flywaydb:flyway-database-postgresql:10.0.1")
    implementation("org.flywaydb:flyway-core:10.0.1")
```

I noticed this in the release notes:
```
Notes
Flyway Gradle Plugin is currently unable to be released.
```
So I assume we are waiting for the gradle plugin to be release?

**Comment by sansnom** [comment]
For gradle, you need to follow the [documentation](https://documentation.red-gate.com/fd/gradle-task-184127407.html). 😄 

The dependency MUST be added inside the buildscript. Example for postgresql:

```properties
buildscript {
    dependencies {
        classpath "org.flywaydb:flyway-database-postgresql:10.0.0"
    }
}
```

**Comment by thetaurean** [comment]
> For gradle, you need to follow the [documentation](https://documentation.red-gate.com/fd/gradle-task-184127407.html). 😄
> 
> The dependency MUST be added inside the buildscript. Example for postgresql:
> 
> ```ini
> buildscript {
>     dependencies {
>         classpath "org.flywaydb:flyway-database-postgresql:10.0.0"
>     }
> }
> ```

Thanks for calling this out! Not sure how I missed it 🤦 

@davinkevin this may solve your issue as well. In my case I had to add parens to classpath **_(_**"org.flyway..."**_)_**

**Comment by thetaurean** [comment]
@sansnom Could you help me with another seemingly elementary but related issue?

We had this line in our `gradle.properties` to disable transactional locks:
```
flyway.postgresql.transactional.lock=false
```

And we are now getting: 
```
Unknown configuration property: flyway.plugins.postgresql.transactional.lock
```

I've tried moving the config value to `build.gradle.kts` to no avail:
```
flyway {
    url = dbUrl
    user = dbUser
    password = dbPassword
    pluginConfiguration = mapOf("postgresqlTransactionalLock" to "false")
}
```

**Comment by davinkevin** [comment]
I confirm it worked for me, but it's not a very good pattern for `gradle` build tool. By doing that, all flyway dependencies leak to the build classpath, for all plugins. 

The best solution would be to declare a dedicated configuration used by the plugin and which can be declared by a dedicated element in the `dependencies` block, like [done by the `jooq` plugin](https://github.com/etiennestuder/gradle-jooq-plugin/blob/c90a25f170180ad2c418afe1d561ad5d8b7bbc12/src/main/groovy/nu/studer/gradle/jooq/JooqPlugin.java#L78-L87). 

It could be like this for `flyway`, which is better for configuration and good to avoid conflicts between plugin dependencies.  

```kotlin
dependencies {
    flyway("org.flywaydb:flyway-database-postgresql:10.0.0")
}
```

**Comment by Barry-RG** [comment]
@davinkevin thank you for your suggestion, that is something we may look into

**Comment by Jukurrpa** [comment]
Hello, adding the dependencies to `flyway-mysql` and `flyway-database-postgresql` did not solve the issue in our case.

We're running Flyway in an AWS Lambda using a JAR created with the maven shade plugin. All the dependencies are in the pom.xml as below (we're using version 10.11.1). The database type are present when the lambda is running (we can log their class name). Despite all of this, we keep getting `No database found to handle jdbc:postgresql:` and the MySQL equivalent.

Is there something specific to do for Lambdas?

```xml
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>${flyway.version}</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
            <version>${flyway.version}</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
            <version>${flyway.version}</version>
        </dependency>
```

**Comment by Lob2018** [comment]
[Flyway 10.12.0 (for HSQLDB 2.7.2 by API) doesn't work with maven-shade-plugin 3.5.2](https://github.com/flyway/flyway/issues/3780)
v9.22.3 OK - 1 dependency : flyway-core
v10.12.0 NOK - 2 dependencies : flyway-core+flyway-database-hsqldb

It works in development.
The error with the fat jar is the same as in development without flyway-database-hsql dependency :

<pre><code>
FlywayException catch for flyway.migrate() : No database found to handle jdbc:hsqldb:file:C:/Users/toMyDb
org.flywaydb.core.api.FlywayException: No database found to handle jdbc:hsqldb:file:C:/Users/toMyDb
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:158)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:96)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1093)
	at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:626)
	at fr.bla.utils.DatabaseMigration.configure(DatabaseMigration.java:23)
	at fr.bla.MyMain.initializationAsynchronousTask(MyMain.java:82)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
2024-04-29 13:38:00,898 ERROR f.s.s.MyMain [ForkJoinPool.commonPool-worker-1] Error in splash screen initialization virtual thread : org.flywaydb.core.api.FlywayException: No database found to handle jdbc:hsqldb:file:C:/Users/toMyDb
java.util.concurrent.CompletionException: org.flywaydb.core.api.FlywayException: No database found to handle jdbc:hsqldb:file:C:/Users/toMyDb
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:507)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1491)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:2073)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:2035)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:187)
Caused by: org.flywaydb.core.api.FlywayException: No database found to handle jdbc:hsqldb:file:C:/Users/toMyDb
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:158)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:96)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1093)
	at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:626)
	at fr.bla.utils.DatabaseMigration.configure(DatabaseMigration.java:23)
	at fr.bla.MyMain.initializationAsynchronousTask(MyMain.java:82)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
</code></pre>

Flyway code using API :
<pre><code> Flyway flyway = Flyway.configure()
    .dataSource(
        databasePath,    // as jdbc:hsqldb:file:...
        JVMApplicationProperties.getDbUser(),
        JVMApplicationProperties.getDbPassord()
     )
     .locations("classpath:" + ApplicationPaths.getDATABASE_MIGRATION_PATH())
    .baselineOnMigrate(true)
     .load();
 flyway.migrate();
</code></pre>

**Comment by SleeveShirtholes** [comment]
I am still getting this error even after adding in the org.flywaydb:flyway-database-postgresql dependency. Please help:

build.gradle
```
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.0'
    id 'io.spring.dependency-management' version '1.1.5'
    id "org.flywaydb.flyway" version "10.13.0"
}

group = 'com.discoverfinancial'
version = '0.0.1-SNAPSHOT'

java {
    sourceCompatibility = '17'
}

repositories {
    maven { url nexusPublicRepoURL }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.flywaydb:flyway-core'
    runtimeOnly 'org.flywaydb:flyway-database-postgresql'
    implementation 'org.postgresql:postgresql'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}

```

**Comment by tobias-lippert** [comment]
I get a FlywayApiException: Unsupported Database: PostgreSQL 15.4, when trying to migrate a Postgres 15.4 database using the built-in Spring Boot Support. I haven't tried using an oracle db yet.
Spring Boot Version 3.3.0 (and hence, Flyway 10.10)
I use maven  and have the following dependencies declared
```
<dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
            <version>42.7.0</version>
        </dependency>
        <dependency>
            <groupId>com.oracle.database.jdbc</groupId>
            <artifactId>ojdbc8</artifactId>
            <scope>runtime</scope>
            <version>19.21.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-oracle</artifactId>
            <scope>runtime</scope>
        </dependency>
```

The flyway versions come from the Spring Boot dependency management.

**Comment by peterkemppe** [comment]
I have been struggling all weekend to get Flyway to run/work. 
I have setup an initial Spring Boot (3.3.3) java (17) application. Initially I was using postgres. But despite using both org.flywaydb:flyway-core and flyway-database-postgresql  (10.17.2) my migration did not run. 
When running "gradlew flywayInfo" I get this message.
> Error occurred while executing flywayInfo
  No database found to handle jdbc:mysql://my_host:my_port/my_database
  
  Then today, I gave up and changed to mysql instead. But I got the same problem. Frustrating.

**Comment by goldman7911** [comment]
Created a small spring app from [spring](https://start.spring.io/) 

Can't make it work. Also, tried @Lob2018 SO suggestion but I receive some main error

What I am missing?

https://docs.spring.io/spring-boot/how-to/data-initialization.html#howto.data-initialization.migration-tool.flyway

https://documentation.red-gate.com/flyway/getting-started-with-flyway/system-requirements/supported-databases-and-versions 

Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 16.0

properties
```
spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/omnidb
spring.datasource.username=omni
spring.datasource.password=omni
spring.datasource.driverClassName=org.postgresql.Driver
```

POM
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.3</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>
	<description>Demo project for Spring Boot</description>
	<url/>
	<licenses>
		<license/>
	</licenses>
	<developers>
		<developer/>
	</developers>
	<scm>
		<connection/>
		<developerConnection/>
		<tag/>
		<url/>
	</scm>
	<properties>
		<java.version>21</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-core</artifactId>
		</dependency>
		<dependency>
			<groupId>org.flywaydb</groupId>
			<artifactId>flyway-database-postgresql</artifactId>
		</dependency>

		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.18.30</version>
            <scope>provided</scope>
        </dependency>
    </dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>

<!--			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-shade-plugin</artifactId>
				<version>3.6.0</version>
				<configuration>
					<transformers>
						<transformer
								implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
							<mainClass>fr.bla.Launcher</mainClass>
						</transformer>
						<transformer
								implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
					</transformers>
					<filters>
						<filter>
							<artifact>*:*</artifact>
							<excludes>
								<exclude>META-INF/maven/**</exclude>
								<exclude>META-INF/*.SF</exclude>
								<exclude>META-INF/*.DSA</exclude>
								<exclude>META-INF/*.RSA</exclude>
							</excludes>
						</filter>
					</filters>
				</configuration>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>shade</goal>
						</goals>
					</execution>
				</executions>
			</plugin>-->

		</plugins>
	</build>

</project>

```

**Comment by Lob2018** [comment]
Hello, 

Is that your own mainClass : <mainClass>fr.bla.Launcher</mainClass> ?

Whenever you can get it work without this transformers by using classpath on Flyway.configure().locations("classpath:"+DATABASE_MIGRATION_PATH)

**Comment by Lob2018** [comment]
> Created a small spring app from [spring](https://start.spring.io/)
> 
> Can't make it work. Also, tried @Lob2018 SO suggestion but I receive some main error
> 
> What I am missing?
> 
> https://docs.spring.io/spring-boot/how-to/data-initialization.html#howto.data-initialization.migration-tool.flyway
> 
> https://documentation.red-gate.com/flyway/getting-started-with-flyway/system-requirements/supported-databases-and-versions
> 
> Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 16.0
> 
> properties
> 
> ```
> spring.application.name=demo
> spring.datasource.url=jdbc:postgresql://localhost:5432/omnidb
> spring.datasource.username=omni
> spring.datasource.password=omni
> spring.datasource.driverClassName=org.postgresql.Driver
> ```
> 
> POM
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
> 	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
> 	<modelVersion>4.0.0</modelVersion>
> 	<parent>
> 		<groupId>org.springframework.boot</groupId>
> 		<artifactId>spring-boot-starter-parent</artifactId>
> 		<version>3.3.3</version>
> 		<relativePath/> 
> 	</parent>
> 	<groupId>com.example</groupId>
> 	<artifactId>demo</artifactId>
> 	<version>0.0.1-SNAPSHOT</version>
> 	<name>demo</name>
> 	<description>Demo project for Spring Boot</description>
> 	<url/>
> 	<licenses>
> 		<license/>
> 	</licenses>
> 	<developers>
> 		<developer/>
> 	</developers>
> 	<scm>
> 		<connection/>
> 		<developerConnection/>
> 		<tag/>
> 		<url/>
> 	</scm>
> 	<properties>
> 		<java.version>21</java.version>
> 	</properties>
> 	<dependencies>
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-data-jpa</artifactId>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.flywaydb</groupId>
> 			<artifactId>flyway-core</artifactId>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.flywaydb</groupId>
> 			<artifactId>flyway-database-postgresql</artifactId>
> 		</dependency>
> 
> 		<dependency>
> 			<groupId>com.h2database</groupId>
> 			<artifactId>h2</artifactId>
> 			<scope>runtime</scope>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.postgresql</groupId>
> 			<artifactId>postgresql</artifactId>
> 			<scope>runtime</scope>
> 		</dependency>
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-test</artifactId>
> 			<scope>test</scope>
> 		</dependency>
>         <dependency>
>             <groupId>org.projectlombok</groupId>
>             <artifactId>lombok</artifactId>
>             <version>1.18.30</version>
>             <scope>provided</scope>
>         </dependency>
>     </dependencies>
> 
> 	<build>
> 		<plugins>
> 			<plugin>
> 				<groupId>org.springframework.boot</groupId>
> 				<artifactId>spring-boot-maven-plugin</artifactId>
> 			</plugin>
> 
> 
> 
> 		</plugins>
> 	</build>
> 
> </project>
> ```
> 
> EDIT:
> 
> By defining explicity jar version, it worked (was not working even with postgres 15.8)
> 
> ```
>         <dependency>
>             <groupId>org.flywaydb</groupId>
>             <artifactId>flyway-core</artifactId>
>             <version>10.17.3</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.flywaydb</groupId>
>             <artifactId>flyway-database-postgresql</artifactId>
>             <version>10.17.3</version>
>         </dependency>
> ```

Hello,

Is that your own mainClass : fr.bla.Launcher ?
Whenever you can get it work without this transformers if you specify your mainClass in your pom.xml.
You've got H2 and postgresql in runtime ?

**Comment by jobsecta-ask** [comment]
Not using Maven Shade. Using Postgres 16.1. This does not work for me (in Spring Boot 3.3.3) - just bleating in the logs about not supporting Postgres 16.1.
```
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>10.17.3</version>
        </dependency>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
            <version>10.17.3</version>
        </dependency>
```
Simple solution for me - back to 9.22.3.

**Comment by Lob2018** [comment]
> Not using Maven Shade. Using Postgres 16.1. This does not work for me (in Spring Boot 3.3.3) - just bleating in the logs about not supporting Postgres 16.1.
> ```
>         <dependency>
>             <groupId>org.flywaydb</groupId>
>             <artifactId>flyway-core</artifactId>
>             <version>10.17.3</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.flywaydb</groupId>
>             <artifactId>flyway-database-postgresql</artifactId>
>             <version>10.17.3</version>
>         </dependency>
> ```
> Simple solution for me - back to 9.22.3.

Hello,
For Flyway with Spring Boot this like may help you :
https://www.baeldung.com/database-migrations-with-flyway

**Comment by goldman7911** [comment]
@jobsecta-ask 

I'm using **image: postgres:16** (that is 16.4) and spring boot 3.3.2.
It is working for me. 

 ```
   <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.2</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>10.17.3</version>
        </dependency>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
            <version>10.17.3</version>
        </dependency>

        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>

```

**Comment by lackovic** [comment]
Changing this in my `build.gradle` has fixed the `Unsupported Database` error for me:

```diff
- org.flywaydb:flyway-core
+ org.flywaydb:flyway-database-postgresql:10.20.1
```

**Comment by Likqez** [comment]
> Changing this in my `build.gradle` has fixed the `Unsupported Database` error for me:
> 
> ```diff
> - org.flywaydb:flyway-core
> + org.flywaydb:flyway-database-postgresql:10.20.1
> ```

I tried this, and also checked the content of my packaged spring jar. It contains the `flyway-database-postgresql` Jar but still give me Unsupported Database...
