### ISSUE TITLE
Stored Procedure Parse Exception with Spring Boot 3.1.5 and HSQLDB 2.7.2

### ISSUE THREAD

**Issue by pacphi** [flyway/flyway#3782]
###### Which version and edition of Flyway are you using?
The curated version with Spring Boot 3.1.5 which is 9.16.3

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Yes, using Flyway 9.22.3 also fails the same way

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java

###### Which database are you using? (Type & version)
HSQLDB 2.7.2

###### Which operating system are you using?
Mac OS

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Created a [unit test](https://github.com/pacphi/grivet/blob/main/core/deployables/query/src/test/java/com/fns/grivet/service/NamedQueryServiceSprocTest.java)

This is the Flyway [asset](https://github.com/pacphi/grivet/blob/main/core/test-resources/src/main/resources/db/hsqldb/V1_1__add_test_sproc.sql)

Ran `mvn install`

JDK 17
Maven 3.9.4

###### What did you expect to see?
Passing test, successful parsing 

###### What did you see instead?

This is the error

```
Caused by: org.flywaydb.core.api.FlywayException: Unable to parse statement in db/hsqldb/V1_1__add_test_sproc.sql at line 3 col 1. See https://rd.gt/3ipi7Pm for more information: Incomplete statement at line 3 col 1: -- Tested w/ HSQLDB only

CREATE PROCEDURE GET_ATTRIBUTES_CREATED_BEFORE (IN CREATED_TIME TIMESTAMP)
  READS SQL DATA
  DYNAMIC RESULT SETS 1
  BEGIN ATOMIC
          DECLARE results SCROLL CURSOR WITH HOLD WITH RETURN FOR
          SELECT NAME, CREATED_TIME FROM ATTRIBUTE WHERE UNIX_MILLIS(CREATED_TIME) < UNIX_MILLIS(createdTime);
          OPEN results;
  END;
        at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:306)
        at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.<init>(Parser.java:715)
        at org.flywaydb.core.internal.parser.Parser.parse(Parser.java:130)
        at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:72)
        at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:120)
        at org.flywaydb.core.internal.sqlscript.ParserSqlScript.executeInTransaction(ParserSqlScript.java:187)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.canExecuteInTransaction(SqlMigrationExecutor.java:73)
        at org.flywaydb.core.internal.command.DbMigrate.isExecuteGroupInTransaction(DbMigrate.java:305)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:270)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:247)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:142)
        at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:36)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
        at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:31)
        at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:102)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:142)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:99)
        at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:188)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:190)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:140)
        at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1817)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
        ... 96 more
Caused by: org.flywaydb.core.api.FlywayException: Incomplete statement at line 3 col 1: -- Tested w/ HSQLDB only

CREATE PROCEDURE GET_ATTRIBUTES_CREATED_BEFORE (IN CREATED_TIME TIMESTAMP)
  READS SQL DATA
  DYNAMIC RESULT SETS 1
  BEGIN ATOMIC
          DECLARE results SCROLL CURSOR WITH HOLD WITH RETURN FOR
          SELECT NAME, CREATED_TIME FROM ATTRIBUTE WHERE UNIX_MILLIS(CREATED_TIME) < UNIX_MILLIS(createdTime);
          OPEN results;
  END;
        at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:241)
        ... 119 more
```

**Comment by JasonLuo-Redgate** [comment]
Hi @pacphi , according to the doc here https://documentation.red-gate.com/fd/hsqldb-184127598.html, the latest supported version for HSQLDB is `2.4` with `Standard SQL syntax with statement delimiter`.

**Comment by pacphi** [comment]
Two things: 

1. Forcing dependency on hsqldb to 2.4.1, you will see

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Flyway Teams Edition or HSQLDB upgrade required: HSQLDB 2.4 is no longer supported by Flyway Community Edition, but still supported by Flyway Teams Edition.
```

2. The community edition additional dependency mentioned in the doc link (i.e., `flyway-database-hsqldb`) seems to be available only in 10.0.0, see https://repo1.maven.org/maven2/org/flywaydb/flyway-database-hsqldb/.  

So when I tried that, I got...

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception with message: 'org.flywaydb.core.api.configuration.FluentConfiguration org.flywaydb.core.api.configuration.FluentConfiguration.licenseKey(java.lang.String)'
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:654) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:642) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1332) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1162) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:560) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1166) ~[spring-context-6.0.13.jar:6.0.13]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:940) ~[spring-context-6.0.13.jar:6.0.13]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616) ~[spring-context-6.0.13.jar:6.0.13]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.test.context.SpringBootContextLoader.lambda$loadContext$3(SpringBootContextLoader.java:137) ~[spring-boot-test-3.1.5.jar:3.1.5]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:58) ~[spring-core-6.0.13.jar:6.0.13]
        at org.springframework.util.function.ThrowingSupplier.get(ThrowingSupplier.java:46) ~[spring-core-6.0.13.jar:6.0.13]
        at org.springframework.boot.SpringApplication.withHook(SpringApplication.java:1406) ~[spring-boot-3.1.5.jar:3.1.5]
        at org.springframework.boot.test.context.SpringBootContextLoader$ContextLoaderHook.run(SpringBootContextLoader.java:545) ~[spring-boot-test-3.1.5.jar:3.1.5]
        at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:137) ~[spring-boot-test-3.1.5.jar:3.1.5]
        at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:108) ~[spring-boot-test-3.1.5.jar:3.1.5]
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:187) ~[spring-test-6.0.13.jar:6.0.13]
        at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:119) ~[spring-test-6.0.13.jar:6.0.13]
        ... 73 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception with message: 'org.flywaydb.core.api.configuration.FluentConfiguration org.flywaydb.core.api.configuration.FluentConfiguration.licenseKey(java.lang.String)'
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:171) ~[spring-beans-6.0.13.jar:6.0.13]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:650) ~[spring-beans-6.0.13.jar:6.0.13]
        ... 99 common frames omitted
Caused by: java.lang.NoSuchMethodError: 'org.flywaydb.core.api.configuration.FluentConfiguration org.flywaydb.core.api.configuration.FluentConfiguration.licenseKey(java.lang.String)'
        at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.configureProperties(FlywayAutoConfiguration.java:254) ~[spring-boot-autoconfigure-3.1.5.jar:3.1.5]
        at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.flyway(FlywayAutoConfiguration.java:150) ~[spring-boot-autoconfigure-3.1.5.jar:3.1.5]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139) ~[spring-beans-6.0.13.jar:6.0.13]
        ... 100 common frames omitted
```

I suppose I need to wait for Spring Boot 3.2.0 release for compatibility reasons. 

Others will be similarly stuck with a use case like this.

**Comment by pacphi** [comment]
Looks like ultimately this issue will get resolved when this issue is addressed: https://github.com/spring-projects/spring-boot/issues/38164.

**Comment by JasonLuo-Redgate** [comment]
Yes, @pacphi , the combability error now depending on the spring-boot ticket you posted.

**Comment by JasonLuo-Redgate** [comment]
The Sprint boot ticket is now fixed https://github.com/spring-projects/spring-boot/issues/38164
