### ISSUE TITLE
baselineVersion(MigrationVersion.NEXT) not work

### ISSUE THREAD

**Issue by JajaComp** [flyway/flyway#3802]
###### Which version and edition of Flyway are you using?
10.1.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Postgresql

###### Which operating system are you using?
MacOs

I try integrate migration to exist project and got issue:
```
Exception in thread "main" org.flywaydb.core.api.FlywayException: Version may only contain 0..9 and . (dot). Invalid version: << Next Version >>
	at org.flywaydb.core.api.MigrationVersion.toBigInteger(MigrationVersion.java:297)
	at org.flywaydb.core.api.MigrationVersion.tokenize(MigrationVersion.java:280)
	at org.flywaydb.core.api.MigrationVersion.<init>(MigrationVersion.java:94)
	at org.flywaydb.core.api.MigrationVersion.fromVersion(MigrationVersion.java:83)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.getBaselineVersion(ClassicConfiguration.java:441)
	at org.flywaydb.core.Flyway.doBaseline(Flyway.java:424)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:187)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:215)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
```
Sample code:
```
Flyway
            .configure()
            .dataSource("correct db url")
            .baselineVersion(MigrationVersion.NEXT)
            .baselineOnMigrate(true)
            .load()
            .migrate()
```

**Comment by JasonLuo-Redgate** [comment]
Hi @JajaComp , `MigrationVersion.NEXT` is only a marker, it won't get he actual version number of your "next version".

**Comment by JajaComp** [comment]
For what it? Can i use auto max version number of migration for integration to production server? Sample: ORM (Exposed) install fresh schema with migration changes. After it Flyway trying set migrations and i want to set baselineVersion as maximum migration version for ignore old files.

**Comment by JasonLuo-Redgate** [comment]
For that purpose, just `baselineOnMigrate(true)` will do, no need to call `baselineVersion`. Could you try that?

**Comment by JajaComp** [comment]
My scenario is the following. I'm using orm exposed. During a clean installation on a new server(SchemaUtils.create(*tables)), an up-to-date database is created. At the same moment, FlyWay is initialized where I must ignore all migrations and set the data version equal to the maximum migration version. How can i do this? So far I've just come up with this "bad solution":
```
    override fun updateDb() {
        val flyway = Flyway
            .configure()
            .dataSource(ConnectString, dbUser, dbPassword)
            .createSchemas(false)
            .load()
        val info = flyway.info()
        val current = info.current()
        if (current == null) {
            val maxVersion = info.infoResult
                .migrations
                .filter { it.filepath?.isNotBlank() == true }
                .maxOfOrNull { it.version.replace("_", ".").toBigDecimal() }
            Flyway
                .configure()
                .dataSource(ConnectString, dbUser, dbPassword)
                .createSchemas(false)
                .baselineVersion(maxVersion?.toString() ?: "1")
                .baselineOnMigrate(true)
                .load()
                .baseline()
            return
        }
        flyway.migrate()
    }
```

**Comment by JasonLuo-Redgate** [comment]
Set `baselineOnMigrate(true)` will do, based on my understanding.

**Comment by JasonLuo-Redgate** [comment]
Hi @JajaComp ,
When `baselineOnMigrate(true)` is applied, Flyway will take current schema as baseline automictically without needing to set a  `baselineVersion`.

**Comment by JajaComp** [comment]
My sample:
Migrations:
V1__Test1.sql:
```
CREATE TABLE IF NOT EXISTS test1 (test_id uuid NOT NULL);
```
V1__Test1.sql:
```
CREATE TABLE IF NOT EXISTS test2 (test_id uuid NOT NULL, field_id uuid NOT NULL);
ALTER TABLE test2 DROP COLUMN field_id;
```
Code:
```
internal class Test {
    object Test1Table : IntIdTable("test1") {
        val name = text("name")
    }

    object Test2Table : IntIdTable("test2") {
        val name = text("name").nullable()
    }

    @Test
    fun generateRolesGroupsScopeViewTest() {
        val url = "jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH"
        Database.connect(url)
        transaction {
            SchemaUtils.create(Test1Table, Test2Table)
        }
        val flyWay = Flyway
            .configure()
            .dataSource(url, null, null)
            .baselineOnMigrate(true)
            .load()
        flyWay.migrate()
    }
}
```
Error:
```
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V2__Test2.sql failed
------------------------------
SQL State  : 42S22
Error Code : 42122
```
I expect what flyWay set data version to 2 without try apply migrations

**Comment by JasonLuo-Redgate** [comment]
Hi @JajaComp , I'm confused with your scenario that if you must ignore all migrations , why run `flyWay.migrate()` at all?

In you scenario, it looks like you must know your max version number (for example, you have V1 .. V6 pending to run), you need to call `baselineVersion("6")`.

**Comment by JajaComp** [comment]
In my scenario, the exposed kotlin orm framework always contains the actual data structure. Migration is needed to update already configured servers, and disabling migration is required for new installations in which exposed will install the latest version of the database automatically.

**Comment by JasonLuo-Redgate** [comment]
Hi @JajaComp,
You have two types of servers:

1. Configured servers. Migration is needed for this type. 
2. Newly installed servers. Migration should be ignored for this type. 

If my above understanding is correct, you code which sets baseline number to the maximum migration number only works for scenario 2, how does your code deal with scenario 1?

**Comment by JajaComp** [comment]
Correct. Now i use next code 
```
    override fun updateDb() {
        val flyway = Flyway
            .configure()
            .dataSource(ConnectString, dbUser, dbPassword)
            .createSchemas(false)
            .load()
        val info = flyway.info()
        val current = info.current()
        if (current == null) {
            val maxVersion = info.infoResult
                .migrations
                .filter { it.filepath?.isNotBlank() == true }
                .maxOfOrNull { it.version.replace("_", ".").toBigDecimal() }
            Flyway
                .configure()
                .dataSource(ConnectString, dbUser, dbPassword)
                .createSchemas(false)
                .baselineVersion(maxVersion?.toString() ?: "1")
                .baselineOnMigrate(true)
                .load()
                .baseline()
            return
        }
        flyway.migrate()
    }
```
When app is run i check database. If tables was not created - i run setup scenario else call method updateDb

**Comment by JasonLuo-Redgate** [comment]
@JajaComp , the `maxVersion` looks unnecessary if I understood your code correctly. 
Since you put `return` statement after `baseline`, the following `migrate()` won't be called at all for newly installed servers. Therefore, there is no need to set maxVersion as baselineVersion to guard it？

`val flyway = Flyway
            .configure()
            .dataSource(ConnectString, dbUser, dbPassword)
            .createSchemas(false)
            .load()
        val info = flyway.info()
        val current = info.current()
        if (current == null) {
            flyway.baseline()
            return
        }
        flyway.migrate()`

**Comment by JajaComp** [comment]
But if I don't use baseVersion it will be set to default (1). And when the next restart of server will make migrate from the first version to the latest version found, and will i get error.
