### ISSUE TITLE
SQLite Migration fails.

### ISSUE THREAD

**Issue by DxsSucuk** [flyway/flyway#3803]
###### Which version and edition of Flyway are you using?

10.1.0-Community

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API

###### Which database are you using? (Type & version)

SQLite - 3.44.1.0

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
The code that is being used to run the migrations:

```java
        try {
            Flyway flyway = Flyway
                    .configure(ClasspathHelper.staticClassLoader())
                    .dataSource(getDataSource())
                    .locations("sql/migrations")
                    .installedBy("Ree6-SQL").load();

            MigrationInfo[] migrationInfo = flyway.info().pending();

            if (migrationInfo.length != 0) {
                log.info("Found " + migrationInfo.length + " pending migrations.");
                log.info("The pending migrations are: " + String.join(", ",
                        Arrays.stream(migrationInfo).map(MigrationInfo::getDescription).toArray(String[]::new)));

                log.info("Running Flyway Migrations.");
            } else {
                log.info("No pending migrations found.");
            }

            MigrateResult result = flyway.migrate();

            if (result.success) {
                log.info("Flyway Migrations were successful.");
            } else {
                log.error("Flyway Migrations were unsuccessful.");
            }
        } catch (Exception exception) {
            log.error("Migration failed!", exception);
        }
```

The actual error: 
```
org.flywaydb.core.internal.command.DbMigrate$FlywayMigrateException: Migration V1__Initial.sql failed
--------------------------------
SQL State  : null
Error Code : 1
Message    : [SQLITE_ERROR] SQL error or missing database (near "CONSTRAINT": syntax error)
Location   : sql/migrations/V1__Initial.sql (C:\!Entwicklung\Project\Ree6\file:\C:\!Entwicklung\M2\de\ree6\Ree6-SQL\2.1.6-TEST14\Ree6-SQL-2.1.6-TEST14.jar!\sql\migrations\V1__Initial.sql)
Line       : 405
Statement  : ALTER TABLE Money_Transaction
    ADD CONSTRAINT FK_MONEY_TRANSACTION_ON_RECEIVER FOREIGN KEY (receiver) REFERENCES Money_Holder (Id)

	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:382)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$applyMigrations$1(DbMigrate.java:272)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:271)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:244)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:139)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate$1.call(TableLockingExecutionTemplate.java:36)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.jdbc.TableLockingExecutionTemplate.execute(TableLockingExecutionTemplate.java:31)
	at org.flywaydb.core.internal.database.base.Connection.lock(Connection.java:102)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:215)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
	at de.presti.ree6.sql.SQLConnector.runMigrations(SQLConnector.java:119)
	at de.presti.ree6.sql.SQLConnector.<init>(SQLConnector.java:62)
	at de.presti.ree6.sql.SQLSession.<init>(SQLSession.java:179)
	at de.presti.ree6.main.Main.main(Main.java:214)
Caused by: org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Migration V1__Initial.sql failed
--------------------------------
SQL State  : null
Error Code : 1
Message    : [SQLITE_ERROR] SQL error or missing database (near "CONSTRAINT": syntax error)
Location   : sql/migrations/V1__Initial.sql (C:\!Entwicklung\Project\Ree6\file:\C:\!Entwicklung\M2\de\ree6\Ree6-SQL\2.1.6-TEST14\Ree6-SQL-2.1.6-TEST14.jar!\sql\migrations\V1__Initial.sql)
Line       : 405
Statement  : ALTER TABLE Money_Transaction
    ADD CONSTRAINT FK_MONEY_TRANSACTION_ON_RECEIVER FOREIGN KEY (receiver) REFERENCES Money_Holder (Id)

	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:270)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:225)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:128)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:68)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
	at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
	at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:374)
	... 19 common frames omitted
Caused by: org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (near "CONSTRAINT": syntax error)
	at org.sqlite.core.DB.newSQLException(DB.java:1179)
	at org.sqlite.core.DB.newSQLException(DB.java:1190)
	at org.sqlite.core.DB.throwex(DB.java:1150)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:132)
	at org.sqlite.core.DB.prepare(DB.java:264)
	at org.sqlite.jdbc3.JDBC3Statement.lambda$execute$0(JDBC3Statement.java:53)
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:459)
	at org.sqlite.jdbc3.JDBC3Statement.execute(JDBC3Statement.java:42)
	at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94)
	at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:210)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:97)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:213)
	... 25 common frames omitted
```
###### What did you expect to see?

A "flawless" migration.

###### What did you see instead?

A not so functional migration.

**Comment by JasonLuo-Redgate** [comment]
Hi @DxsSucuk , are you able to share the full V1__Initial.sql ? Because from the error message, it looks like a sql error to me.

**Comment by DxsSucuk** [comment]
Sorry for the latest response!
Here is a link to the migration -> https://raw.githubusercontent.com/Ree6-Applications/Ree6-SQL/master/src/main/resources/sql/migrations/V1__Initial.sql

**Comment by JasonLuo-Redgate** [comment]
Hi @DxsSucuk , could you have a look into https://www.sqlite.org/foreignkeys.html#fk_enable, and check whether this is related? Because the error message seemed to be a sql syntax error.
