### ISSUE TITLE
org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 16.1

### ISSUE THREAD

**Issue by Abdullah-Akbar** [flyway/flyway#3807]
###### Which version and edition of Flyway are you using?
implementation group: 'org.flywaydb', name: 'flyway-core', version: '10.2.0'

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using? (Type & version)
PostgreSQL 16.1

###### Which operating system are you using?

Windows 11

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Spring Boot 3.2.0 application startup with PostgreSQL 16.1

###### What did you expect to see?

Successful startup

###### What did you see instead?

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Unsupported Database: PostgreSQL 16.1
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1775) ~[spring-beans-6.1.1.jar:6.1.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:601) ~[spring-beans-6.1.1.jar:6.1.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:523) ~[spring-beans-6.1.1.jar:6.1.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.1.jar:6.1.1]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.1.jar:6.1.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.1.jar:6.1.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.1.jar:6.1.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312) ~[spring-beans-6.1.1.jar:6.1.1]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.1.jar:6.1.1]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1173) ~[spring-context-6.1.1.jar:6.1.1]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:936) ~[spring-context-6.1.1.jar:6.1.1]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:616) ~[spring-context-6.1.1.jar:6.1.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:753) ~[spring-boot-3.2.0.jar:3.2.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:455) ~[spring-boot-3.2.0.jar:3.2.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:323) ~[spring-boot-3.2.0.jar:3.2.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1342) ~[spring-boot-3.2.0.jar:3.2.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1331) ~[spring-boot-3.2.0.jar:3.2.0]
	at com.apisec.inference.main.Application.main(Application.java:16) ~[main/:na]
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 16.1
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105) ~[flyway-core-10.2.0.jar:na]
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75) ~[flyway-core-10.2.0.jar:na]
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:144) ~[flyway-core-10.2.0.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:147) ~[flyway-core-10.2.0.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-3.2.0.jar:3.2.0]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1822) ~[spring-beans-6.1.1.jar:6.1.1]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1771) ~[spring-beans-6.1.1.jar:6.1.1]
	... 17 common frames omitted

**Comment by Abdullah-Akbar** [comment]
- Flyway 10.1.0 (2023-11-22) already [supports](https://documentation.red-gate.com/fd/release-notes-for-flyway-engine-179732572.html#:~:text=issue%20in%20%60ConfigUtils%60-,Database%20compatibility,preview%20in%20Redgate%20edition%20CLI.) PostgreSQL 16.  
-  This bug is for version 10.2.0.

**Comment by Barry-RG** [comment]
Hi @Abdullah-Akbar,
It seems from the exception that you are using Spring Boot to start Flyway, not the Flyway Gradle Plugin. 

I suspect from the exception that you might be missing the `flyway-database-postgresql` module from your build. 
Please see the[ pinned issue](https://github.com/flyway/flyway/issues/3780) for more details. 
For what you need to add for PostgreSQL specifically, please see the database [support page for PostgreSQL](https://documentation.red-gate.com/flyway/flyway-cli-and-api/supported-databases/postgresql).

**Comment by Abdullah-Akbar** [comment]
Thanks @Barry-RG you are a gem. It's working fine now.
