### ISSUE TITLE
Syntax error with '-- Use ...' comment on the first line of script

### ISSUE THREAD

**Issue by isacssouza** [flyway/flyway#3820]
###### Which version and edition of Flyway are you using?

10.4.1

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Tested with latest and also 9.20.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Command-line

###### Which database are you using? (Type & version)

Mysql 5.5

###### Which operating system are you using?

Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

This SQL script:

```
-- Use mysql database
USE mysql;
```

fails with:

```
java.sql.SQLSyntaxErrorException: (conn=493) Unknown database 'Use mysql database
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
        at org.mariadb.jdbc.internal.util.exceptions.ExceptionFactory.create(ExceptionFactory.java:158)
        at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:262)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:229)
        at org.mariadb.jdbc.ClientSidePreparedStatement.execute(ClientSidePreparedStatement.java:149)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:190)
        at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:71)
        at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:150)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:144)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:139)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:97)
        at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:202)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:215)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:226)
        at org.flywaydb.commandline.Main.executeFlyway(Main.java:155)
        at org.flywaydb.commandline.Main.main(Main.java:111)
Caused by: org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException: Unknown database 'Use mysql database
        at org.mariadb.jdbc.internal.util.exceptions.MariaDbSqlException.of(MariaDbSqlException.java:34)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:195)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.exceptionWithQuery(AbstractQueryProtocol.java:178)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:322)
        at org.mariadb.jdbc.ClientSidePreparedStatement.executeInternal(ClientSidePreparedStatement.java:220)
        ... 13 more
Caused by: java.sql.SQLException: Unknown database 'Use mysql database
USE `mysql`'
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1693)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1555)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:1518)
        at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:319)
        ... 14 more
ERROR: Unable to restore connection to its original state
--------------------------------------------------
SQL State  : 42000
Error Code : 1049
Message    : (conn=493) Unknown database 'Use mysql database
```

I tried to reproduce this with other comment strings and other statements but I could only reproduce with this pattern:
```
-- Use ...
USE ...
```

###### What did you expect to see?

A successful migration with no errors.

###### What did you see instead?

An unexpected syntax error.

**Comment by isacssouza** [comment]
Additional context: I'm using [ProxySQL](https://proxysql.com/) in front of MySQL. 
If I run the migration connecting directly to MySQL then I do not get an error.

This is probably a bug with ProxySQL, not Flyway.
