### ISSUE TITLE
Numeric Overflow on FlywaySqlException: Error while retrieving the list of applied migrations from Schema History table

### ISSUE THREAD

**Issue by lokaish39** [flyway/flyway#3830]
###### Which version and edition of Flyway are you using?
8.5.13

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Not attempted

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Spring

###### Which database are you using? (Type & version)
Oracle 19c

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
Applying migrations

###### What did you expect to see?
Successful migration

###### What did you see instead?
Wrapped by: org.flywaydb.core.internal.exception.FlywaySqlException: Error while retrieving the list of applied migrations from Schema History table "Schema"."flyway_schema_history"
-------------------------------------------------------------------------------------------------------------------
SQL State  : 99999
Error Code : 17026
Message    : Numeric Overflow

	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.refreshCache(JdbcTableSchemaHistory.java:223)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.allAppliedMigrations(JdbcTableSchemaHistory.java:187)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:93)
	at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:151)
	at org.flywaydb.core.internal.command.DbValidate$2.call(DbValidate.java:138)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
	at org.flywaydb.core.internal.command.DbValidate.validate(DbValidate.java:138)
	at org.flywaydb.core.Flyway.doValidate(Flyway.java:372)
	at org.flywaydb.core.Flyway.access$100(Flyway.java:56)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:128)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:124)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:205)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:124)

**Comment by CleanCoder007** [comment]
Hi @lokaish39,
Check by any chance if the flyway history table contains any migration that has checksum beyond the range of int. You will get more hints by migrating in debug enabled logs.
Thanks!

**Comment by thecoolestcoderrushil** [comment]
A Flyway migration that fails with Numeric Overflow while retrieving the list of applied migrations is a painful history bug, since the schema history table cannot be read and the migration cannot proceed. Rehearsing the migration on a production-shaped twin first would surface the overflow problem before deploy day. antifailure.dev (https://antifailure.dev) spins up disposable database twins for migration rehearsal, and it is open source and free to try. Happy to set up a demo if that would help.
