### ISSUE TITLE
Flyway 10.7.1 does not seem to be compatible with mssql-jdbc:12.6.0.jre11 - 'sp_getapplock' expects parameter '@LockMode'

### ISSUE THREAD

**Issue by olerabanal** [flyway/flyway#3833]
###### Which version and edition of Flyway are you using?
 10.7.1

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle

###### Which database are you using? (Type & version)

MSSQL 
com.microsoft.sqlserver:mssql-jdbc:12.6.0.jre11 

###### Which operating system are you using?
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Trying to run flyway-core migrate 

###### What did you expect to see?
A migration based on a migration-file.
Expect to see the migration work, as it works with the former version of mssql-jdbc: 12.4.2.jre11. 

###### What did you see instead?
Added #### on paths that are not relevant

org.flywaydb.core.internal.exception.FlywaySqlException: Unable to acquire SQL Server application lock
---------------------------------------------
SQL State  : S0004
Error Code : 201
Message    : Procedure or function 'sp_getapplock' expects parameter '@LockMode', which was not supplied.

	at org.flywaydb.database.sqlserver.SQLServerApplicationLockTemplate.execute(SQLServerApplicationLockTemplate.java:63)
	at org.flywaydb.database.sqlserver.SQLServerConnection.lock(SQLServerConnection.java:93)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.create(JdbcTableSchemaHistory.java:104)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:199)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:200)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:147)
	at ####.ifx.utils.Database.migrate(Database.kt:122)
	at####.ifx.database.DatabaseTestBaseSimulatorTestDb.initTest(DatabaseTestBaseSimulatorTestDb.kt:12)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Procedure or function 'sp_getapplock' expects parameter '@LockMode', which was not supplied.
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:261)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1752)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:657)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:576)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7739)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4384)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:293)
	at com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:263)
	at com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:553)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:190)
	at org.flywaydb.database.sqlserver.SQLServerApplicationLockTemplate.execute(SQLServerApplicationLockTemplate.java:59)
	... 10 more

Procedure or function 'sp_getapplock' expects parameter '@LockMode', which was not supplied.
com.microsoft.sqlserver.jdbc.SQLServerException: Procedure or function 'sp_getapplock' expects parameter '@LockMode', which was not supplied.
	at app//com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:261)
	at app//com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1752)
	at app//com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.doExecutePreparedStatement(SQLServerPreparedStatement.java:657)
	at app//com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd.doExecute(SQLServerPreparedStatement.java:576)
	at app//com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7739)
	at app//com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4384)
	at app//com.microsoft.sqlserver.jdbc.SQLServerStatement.executeCommand(SQLServerStatement.java:293)
	at app//com.microsoft.sqlserver.jdbc.SQLServerStatement.executeStatement(SQLServerStatement.java:263)
	at app//com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement.execute(SQLServerPreparedStatement.java:553)
	at app//com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at app//com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at app//org.flywaydb.core.internal.jdbc.JdbcTemplate.execute(JdbcTemplate.java:190)
	at app//org.flywaydb.database.sqlserver.SQLServerApplicationLockTemplate.execute(SQLServerApplicationLockTemplate.java:59)
	at app//org.flywaydb.database.sqlserver.SQLServerConnection.lock(SQLServerConnection.java:93)
	at app//org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.create(JdbcTableSchemaHistory.java:104)
	at app//org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:199)
	at app//org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:200)
	at app//org.flywaydb.core.Flyway.migrate(Flyway.java:147)
	at ####ifx.utils.Database.migrate(Database.kt:122)
	at ####DatabaseTestBaseSimulatorTestDb.initTest(DatabaseTestBaseSimulatorTestDb.kt:12)
	at java.base@17.0.10/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base@17.0.10/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base@17.0.10/java.util.ArrayList.forEach(ArrayList.java:1511)

**Comment by jpgoelz** [comment]
We are experiencing the same issue.

**Comment by driverpt** [comment]
Apparently it's a bug in MSSQL Server Driver

https://github.com/microsoft/mssql-jdbc/issues/2323#issuecomment-1933173020

**Comment by davidkarlsen** [comment]
Yes, it is released: https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/12.6.1.jre11/

**Comment by jpgoelz** [comment]
I can confirm that the issue was fixed for us with the release of 12.6.1.jre11. 🥳
