### ISSUE TITLE
flyway desktop can't use AD-auth

### ISSUE THREAD

**Issue by davidkarlsen** [flyway/flyway#3844]
Database connection failed: KrbException: Cannot locate default realm
java.lang.IllegalArgumentException: KrbException: Cannot locate default realm
	at java.security.jgss/javax.security.auth.kerberos.KerberosPrincipal.<init>(Unknown Source)
	at java.security.jgss/javax.security.auth.kerberos.KerberosPrincipal.<init>(Unknown Source)
	at com.microsoft.sqlserver.jdbc.SQLServerMSAL4JUtils.getSqlFedAuthTokenIntegrated(SQLServerMSAL4JUtils.java:127)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:5769)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5618)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5463)
	at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:311)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:131)
	at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:42)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6490)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:5068)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.access$100(SQLServerConnection.java:93)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:5002)
	at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7685)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4048)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3487)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3077)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:2919)
	at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1787)
	at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1229)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:258)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.getConnection(DriverDataSource.java:223)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:72)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:133)
	at org.flywaydb.core.Flyway.info(Flyway.java:226)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:264)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:170)
	at org.flywaydb.commandline.Main.main(Main.java:113)

**Comment by Barry-RG** [comment]
@davidkarlsen Can you provide us with minimum reproduction instructions to investigate this issue?
