### ISSUE TITLE
Upgrading from flways 9.x to 10.8.1 breaks system

### ISSUE THREAD

**Issue by bsutton** [flyway/flyway#3851]
###### Which version and edition of Flyway are you using?
10.8.1

```
      <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>10.8.1</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
        </dependency>
```

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

java api.

###### Which database are you using? (Type & version)

mariadb 10.11

###### Which operating system are you using?
ubuntu 23.04

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

upgrade maven from 9.22.1 to 10.8.1

This was my old pom:
```
   <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>9.22.1</version> <!--$NO-MVN-MAN-VER$ -->
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
        </dependency>
```

###### What did you expect to see?

After changing the version in the pom from 9.x to 10.x I expected the system to work as normal.

###### What did you see instead?

Am exception is thrown on startup:

```
java.util.ServiceConfigurationError: org.flywaydb.core.extensibility.Plugin: org.flywaydb.database.mysql.MySQLDatabaseType Unable to get public no-arg constructor
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:679)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1240)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at org.flywaydb.core.internal.plugin.PluginRegister.registerPlugins(PluginRegister.java:82)
	at org.flywaydb.core.internal.plugin.PluginRegister.getPlugins(PluginRegister.java:72)
	at org.flywaydb.core.internal.plugin.PluginRegister.getPlugins(PluginRegister.java:45)
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.<clinit>(DatabaseTypeRegister.java:35)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:109)
	at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:89)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.setDataSource(ClassicConfiguration.java:1073)
	at org.flywaydb.core.api.configuration.FluentConfiguration.dataSource(FluentConfiguration.java:601)
	at dev.onepub.servlets.DbUpgrade.installDB2(DbUpgrade.java:113)
	at dev.onepub.servlets.DbUpgrade.installDB(DbUpgrade.java:38)
	at dev.onepub.servlets.ContextListener.contextInitialized(ContextListener.java:108)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4422)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:4860)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:846)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1332)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1322)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:145)
	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:866)
	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:241)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:433)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:918)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:171)
	at org.apache.catalina.startup.Tomcat.start(Tomcat.java:485)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:123)
	at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:104)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:489)
	at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:211)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:183)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:161)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:602)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:737)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1309)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1298)
	at dev.onepub.AppShell.startApp(AppShell.java:106)
	at dev.onepub.AppShell.main(AppShell.java:93)
Caused by: java.lang.NoClassDefFoundError: org/flywaydb/core/internal/license/FlywayTeamsUpgradeRequiredException
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3373)
	at java.base/java.lang.Class.getConstructor0(Class.java:3578)
	at java.base/java.lang.Class.getConstructor(Class.java:2271)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:666)
	at java.base/java.util.ServiceLoader$1.run(ServiceLoader.java:663)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at java.base/java.util.ServiceLoader.getConstructor(ServiceLoader.java:674)
	... 54 more
Caused by: java.lang.ClassNotFoundException: org.flywaydb.core.internal.license.FlywayTeamsUpgradeRequiredException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 62 more
An Exception was thrown from ContextListener: org.flywaydb.core.extensibility.Plugin: org.flywaydb.database.mysql.MySQLDatabaseType Unable to get public no-arg constructor
Exception Cause: org/flywaydb/core/internal/license/FlywayTeamsUpgradeRequiredException
```

**Comment by bsutton** [comment]
Using 10.8.0 yields the same error.

**Comment by Barry-RG** [comment]
Looking at your maven extract, can you confirm what version of `flyway-mysql` it thinks it is using? You are not specifying a version so I am concerned it is just grabbing whatever version is available locally.
If you specify a version for `flyway-mysql` we can at least be sure that they are in sync

```xml
      <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>10.8.1</version>
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
            <version>10.8.1</version>
        </dependency>
```

**Comment by fernandochafim** [comment]
Specifying the same version in flyway-mysql, solved my problem. Thanks

**Comment by Barry-RG** [comment]
I am going to close this issue as there has not been a response from the original raiser. However, if this issue persists, please reopen and we can continue to look at what could be the problem.

**Comment by bsutton** [comment]
Sorry about the late response. I can confirm that making the version explict in the flyway-mysql entry solved the problem.

```
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>10.8.1</version> <!--$NO-MVN-MAN-VER$ -->
        </dependency>
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-mysql</artifactId>
            <version>10.8.1</version> <!--$NO-MVN-MAN-VER$ -->
        </dependency>
```
As I also use spring boot I need to add the no-mvn-man-ver tag to suppress a warning.
