### ISSUE TITLE
Problem with Spring Boot 3.2.3 and Flyway 10.10.0 for MongoDB 7.0.6

### ISSUE THREAD

**Issue by lkwheel** [flyway/flyway#3856]
###### Which version and edition of Flyway are you using?

flyway-core 10.10.0
mongo-jdbc-driver 1.19.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

This is the latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Java API (Maven, Spring Boot)

###### Which database are you using? (Type & version)

MongoDB 7.0 version 7.0.6

###### Which operating system are you using?

Windows

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.me.webapi</groupId>
    <artifactId>applications</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>

  <groupId>io.me.webapi.applications</groupId>
  <artifactId>data-migration-tool</artifactId>
  <name>data-migration-tool</name>

  <description>Tool to migrate Web API data model versions</description>

  <properties>
    <spring.boot.version>3.2.3</spring.boot.version>
    <flyway.database.mongodb.version>10.10.0</flyway.database.mongodb.version>
    <mongo.jdbc.driver.version>1.19</mongo.jdbc.driver.version>
  </properties>

  <dependencies>
    <!-- Spring starters -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
      <version>${spring.boot.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
      <version>${spring.boot.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jdbc</artifactId>
      <version>${spring.boot.version}</version>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <version>${spring.boot.version}</version>
      <scope>test</scope>
    </dependency>

    <!-- Mongo Flyway Migration dependencies -->
    <dependency>
      <groupId>org.mongodb</groupId>
      <artifactId>mongodb-driver-sync</artifactId>
    </dependency>
    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-core</artifactId>
      <version>${flyway.database.mongodb.version}</version>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
    </dependency>
    <dependency>
      <groupId>com.github.kornilova203</groupId>
      <artifactId>mongo-jdbc-driver</artifactId>
      <version>${mongo.jdbc.driver.version}</version>
      <scope>system</scope>
      <systemPath>${project.basedir}/lib/mongo-jdbc-standalone-1.19.jar</systemPath>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
      </plugin>

      <!-- Copy dependencies so they can be copied to container image. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.6.1</version>
        <configuration>
          <includeScope>runtime</includeScope>
          <overWriteReleases>true</overWriteReleases>
          <overWriteSnapshots>true</overWriteSnapshots>
          <prependGroupId>true</prependGroupId>
        </configuration>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <goals>
              <goal>copy-dependencies</goal>
            </goals>
            <phase>prepare-package</phase>
          </execution>
        </executions>
      </plugin>

      <!-- Generates code coverage report in viable via
      target/site/jacoco/index.html -->
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
      </plugin>

      <!-- Uses the checkstyle ruleset defined in checkstyle.xml. -->
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <configuration>
          <configLocation>../../etc/checkstyle.xml</configLocation>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <mainClass>${main.application.class}</mainClass>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>repackage</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>

</project>
```

Application Yaml
```yaml
spring:
  application:
    name: data-migration-tool

  datasource:
    url: jdbc:mongodb://localhost:27017/mydb
    user: "fakeadmin"
    password: "password"
    driver-class-name: com.dbschema.MongoJdbcDriver

  flyway:
    url: jdbc:mongodb://localhost:27017/mydb
    user: "fakeadmin"
    password: "password"
    driver-class-name: com.dbschema.MongoJdbcDriver
    environment: "mongodb"
    fail-on-missing-locations: true
    locations: classpath:db/migration/js
    sqlMigrationSuffixes:
      - ".js"

logging:
  level:
    org.flywaydb: DEBUG
```

V1__create_collection.js
```javascript
db.test-users.insert({name: "Ada Lovelace", age: 205});
```

V2__create_collection.js
```javascript
db.test-users.createIndex({ name: 1 });
db.test-users.createIndex({ age: -1 });
```

###### What did you expect to see?

Successful migration

###### What did you see instead?

```bash
"C:\Program Files\Eclipse Adoptium\jdk-21.0.1+12\bin\java.exe" -agentlib:jdwp=transport=dt_socket,address=127.0.0.1:50868,suspend=y,server=n -XX:TieredStopAtLevel=1 -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true "-Dmanagement.endpoints.jmx.exposure.include=*" -javaagent:C:\Users\...\AppData\Local\JetBrains\IntelliJIdea2023.3\captureAgent\debugger-agent.jar -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath "...";io.me.webapi.applications.datamigrationtool.DataMigrationToolApplication
Connected to the target VM, address: '127.0.0.1:50868', transport: 'socket'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.2)

2024-03-18T13:01:28.982-04:00  INFO 24680 --- [data-migration-tool] [           main] n.n.n.w.a.d.DataMigrationToolApplication : Starting DataMigrationToolApplication using Java 21.0.1 with PID 24680 (C:\Users\...\web-api\applications\data-migration-tool\target\classes started by Wheeler in C:\Users\...\web-api)
2024-03-18T13:01:28.985-04:00  INFO 24680 --- [data-migration-tool] [           main] n.n.n.w.a.d.DataMigrationToolApplication : No active profile set, falling back to 1 default profile: "default"
2024-03-18T13:01:29.856-04:00  INFO 24680 --- [data-migration-tool] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 8080 (http)
2024-03-18T13:01:29.866-04:00  INFO 24680 --- [data-migration-tool] [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-03-18T13:01:29.866-04:00  INFO 24680 --- [data-migration-tool] [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.18]
2024-03-18T13:01:29.916-04:00  INFO 24680 --- [data-migration-tool] [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-03-18T13:01:29.917-04:00  INFO 24680 --- [data-migration-tool] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 893 ms
[To redirect Truffle log output to a file use one of the following options:
* '--log.file=<path>' if the option is passed using a guest language launcher.
* '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
* Configure logging using the polyglot embedding API.]
[engine] WARNING: The polyglot context is using an implementation that does not support runtime compilation.
The guest application code will therefore be executed in interpreted mode only.
Execution only in interpreted mode will strongly impact the guest application performance.
For more information on using GraalVM see https://www.graalvm.org/java/quickstart/.
To disable this warning the '--engine.WarnInterpreterOnly=false' option or use the '-Dpolyglot.engine.WarnInterpreterOnly=false' system property.
2024-03-18T13:01:30.551-04:00 DEBUG 24680 --- [data-migration-tool] [           main] o.f.c.i.s.classpath.ClassPathScanner     : Scanning for classpath resources at 'classpath:db/callback' ...
2024-03-18T13:01:30.551-04:00 DEBUG 24680 --- [data-migration-tool] [           main] o.f.c.i.s.classpath.ClassPathScanner     : Determining location urls for classpath:db/callback using ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@76ed5528 ...
2024-03-18T13:01:30.551-04:00 DEBUG 24680 --- [data-migration-tool] [           main] o.f.c.i.s.classpath.ClassPathScanner     : Unable to resolve location classpath:db/callback.
2024-03-18T13:01:30.551-04:00 DEBUG 24680 --- [data-migration-tool] [           main] o.f.c.i.s.classpath.ClassPathScanner     : Scanning for classpath resources at 'classpath:db/migration/js' ...
2024-03-18T13:01:30.551-04:00 DEBUG 24680 --- [data-migration-tool] [           main] o.f.c.i.s.classpath.ClassPathScanner     : Determining location urls for classpath:db/migration/js using ClassLoader jdk.internal.loader.ClassLoaders$AppClassLoader@76ed5528 ...
2024-03-18T13:01:30.551-04:00 DEBUG 24680 --- [data-migration-tool] [           main] o.f.c.i.s.classpath.ClassPathScanner     : Scanning URL: file:./applications/data-migration-tool/target/classes/db/migration/js
2024-03-18T13:01:30.551-04:00 DEBUG 24680 --- [data-migration-tool] [           main] i.s.c.FileSystemClassPathLocationScanner : Scanning starting at classpath root in filesystem: C:\Users\...\web-api\applications\data-migration-tool\target\classes\
2024-03-18T13:01:30.551-04:00 DEBUG 24680 --- [data-migration-tool] [           main] i.s.c.FileSystemClassPathLocationScanner : Scanning for resources in path: C:\Users\...\web-api\applications\data-migration-tool\target\classes\db\migration\js (db/migration/js)
2024-03-18T13:01:30.553-04:00 DEBUG 24680 --- [data-migration-tool] [           main] o.f.c.i.s.classpath.ClassPathScanner     : Found resource: db/migration/js/V1__create_test_users.js
2024-03-18T13:01:30.553-04:00 DEBUG 24680 --- [data-migration-tool] [           main] o.f.c.i.s.classpath.ClassPathScanner     : Found resource: db/migration/js/V2__create_name_age_index.js
2024-03-18T13:01:30.553-04:00 DEBUG 24680 --- [data-migration-tool] [           main] o.f.c.i.s.classpath.ClassPathScanner     : Scanning for classes at classpath:db/migration/js
2024-03-18T13:01:30.557-04:00 DEBUG 24680 --- [data-migration-tool] [           main] o.f.c.i.resource.ResourceNameValidator   : Validating V2__create_name_age_index.js
2024-03-18T13:01:30.703-04:00  INFO 24680 --- [data-migration-tool] [           main] org.mongodb.driver.client                : MongoClient with metadata {"driver": {"name": "mongo-java-driver|sync", "version": "4.11.1"}, "os": {"type": "Windows", "name": "Windows 10", "architecture": "amd64", "version": "10.0"}, "platform": "Java/Eclipse Adoptium/21.0.1+12-LTS"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=MongoCredential{mechanism=null, userName='fakeadmin', source='mydb', password=<hidden>, mechanismProperties=<hidden>}, transportSettings=null, streamFactoryFactory=null, commandListeners=[], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, CollectionCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.client.model.mql.ExpressionCodecProvider@1d4cc7, com.mongodb.Jep395RecordCodecProvider@7d28cdcd, com.mongodb.KotlinCodecProvider@255ed8e4]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[localhost:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='10000 ms', localThreshold='15 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, connectionPoolSettings=ConnectionPoolSettings{maxSize=3, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=STANDARD, serverApi=null, autoEncryptionSettings=null, dnsClient=null, inetAddressResolver=null, contextProvider=null}
2024-03-18T13:01:30.724-04:00  INFO 24680 --- [data-migration-tool] [localhost:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=21, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=30664400}
2024-03-18T13:09:45.007-04:00 DEBUG 24680 --- [data-migration-tool] [           main] o.f.c.i.resource.ResourceNameValidator   : Validating V1__create_test_users.js
2024-03-18T13:09:45.012-04:00  INFO 24680 --- [data-migration-tool] [           main] org.mongodb.driver.client                : MongoClient with metadata {"driver": {"name": "mongo-java-driver|sync", "version": "4.11.1"}, "os": {"type": "Windows", "name": "Windows 10", "architecture": "amd64", "version": "10.0"}, "platform": "Java/Eclipse Adoptium/21.0.1+12-LTS"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=MongoCredential{mechanism=null, userName='tstark', source='naiads', password=<hidden>, mechanismProperties=<hidden>}, transportSettings=null, streamFactoryFactory=null, commandListeners=[], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, CollectionCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.client.model.mql.ExpressionCodecProvider@1d4cc7, com.mongodb.Jep395RecordCodecProvider@7d28cdcd, com.mongodb.KotlinCodecProvider@255ed8e4]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[localhost:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='10000 ms', localThreshold='15 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, connectionPoolSettings=ConnectionPoolSettings{maxSize=3, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=STANDARD, serverApi=null, autoEncryptionSettings=null, dnsClient=null, inetAddressResolver=null, contextProvider=null}
2024-03-18T13:09:45.012-04:00  INFO 24680 --- [data-migration-tool] [           main] org.mongodb.driver.cluster               : No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 10000 ms before timing out
2024-03-18T13:09:45.016-04:00  INFO 24680 --- [data-migration-tool] [localhost:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=21, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=2783400}
2024-03-18T13:09:45.076-04:00  INFO 24680 --- [data-migration-tool] [           main] org.mongodb.driver.client                : MongoClient with metadata {"driver": {"name": "mongo-java-driver|sync", "version": "4.11.1"}, "os": {"type": "Windows", "name": "Windows 10", "architecture": "amd64", "version": "10.0"}, "platform": "Java/Eclipse Adoptium/21.0.1+12-LTS"} created with settings MongoClientSettings{readPreference=primary, writeConcern=WriteConcern{w=null, wTimeout=null ms, journal=null}, retryWrites=true, retryReads=true, readConcern=ReadConcern{level=null}, credential=MongoCredential{mechanism=null, userName='tstark', source='naiads', password=<hidden>, mechanismProperties=<hidden>}, transportSettings=null, streamFactoryFactory=null, commandListeners=[], codecRegistry=ProvidersCodecRegistry{codecProviders=[ValueCodecProvider{}, BsonValueCodecProvider{}, DBRefCodecProvider{}, DBObjectCodecProvider{}, DocumentCodecProvider{}, CollectionCodecProvider{}, IterableCodecProvider{}, MapCodecProvider{}, GeoJsonCodecProvider{}, GridFSFileCodecProvider{}, Jsr310CodecProvider{}, JsonObjectCodecProvider{}, BsonCodecProvider{}, EnumCodecProvider{}, com.mongodb.client.model.mql.ExpressionCodecProvider@1d4cc7, com.mongodb.Jep395RecordCodecProvider@7d28cdcd, com.mongodb.KotlinCodecProvider@255ed8e4]}, loggerSettings=LoggerSettings{maxDocumentLength=1000}, clusterSettings={hosts=[localhost:27017], srvServiceName=mongodb, mode=SINGLE, requiredClusterType=UNKNOWN, requiredReplicaSetName='null', serverSelector='null', clusterListeners='[]', serverSelectionTimeout='10000 ms', localThreshold='15 ms'}, socketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=0, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, heartbeatSocketSettings=SocketSettings{connectTimeoutMS=10000, readTimeoutMS=10000, receiveBufferSize=0, proxySettings=ProxySettings{host=null, port=null, username=null, password=null}}, connectionPoolSettings=ConnectionPoolSettings{maxSize=3, minSize=0, maxWaitTimeMS=120000, maxConnectionLifeTimeMS=0, maxConnectionIdleTimeMS=0, maintenanceInitialDelayMS=0, maintenanceFrequencyMS=60000, connectionPoolListeners=[], maxConnecting=2}, serverSettings=ServerSettings{heartbeatFrequencyMS=10000, minHeartbeatFrequencyMS=500, serverListeners='[]', serverMonitorListeners='[]'}, sslSettings=SslSettings{enabled=false, invalidHostNameAllowed=false, context=null}, applicationName='null', compressorList=[], uuidRepresentation=STANDARD, serverApi=null, autoEncryptionSettings=null, dnsClient=null, inetAddressResolver=null, contextProvider=null}
2024-03-18T13:09:45.077-04:00  INFO 24680 --- [data-migration-tool] [           main] org.mongodb.driver.cluster               : No server chosen by ReadPreferenceServerSelector{readPreference=primary} from cluster description ClusterDescription{type=UNKNOWN, connectionMode=SINGLE, serverDescriptions=[ServerDescription{address=localhost:27017, type=UNKNOWN, state=CONNECTING}]}. Waiting for 10000 ms before timing out
2024-03-18T13:09:45.079-04:00  INFO 24680 --- [data-migration-tool] [localhost:27017] org.mongodb.driver.cluster               : Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, minWireVersion=0, maxWireVersion=21, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=2592500}
2024-03-18T13:09:45.137-04:00  WARN 24680 --- [data-migration-tool] [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Unsupported Database: Mongo DB 7.0
2024-03-18T13:09:45.139-04:00  INFO 24680 --- [data-migration-tool] [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2024-03-18T13:09:45.149-04:00  WARN 24680 --- [data-migration-tool] [           main] o.a.c.loader.WebappClassLoaderBase       : The web application [ROOT] appears to have started a thread named [MongoShell ExecutorService] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 com.oracle.truffle.polyglot.PolyglotValueDispatch$PrimitiveValue.<init>(PolyglotValueDispatch.java:1666)
 com.oracle.truffle.polyglot.PolyglotValueDispatch.addDefaultValue(PolyglotValueDispatch.java:1652)
 com.oracle.truffle.polyglot.PolyglotValueDispatch.createDefaultValues(PolyglotValueDispatch.java:1639)
 com.oracle.truffle.polyglot.PolyglotLanguageInstance.<init>(PolyglotLanguageInstance.java:105)
 com.oracle.truffle.polyglot.PolyglotLanguage.createInstance(PolyglotLanguage.java:171)
 com.oracle.truffle.polyglot.PolyglotSharingLayer.allocateHostLanguage(PolyglotSharingLayer.java:334)
 com.oracle.truffle.polyglot.PolyglotLanguageContext.ensureCreated(PolyglotLanguageContext.java:574)
 com.oracle.truffle.polyglot.PolyglotContextImpl.createContextArray(PolyglotContextImpl.java:679)
 com.oracle.truffle.polyglot.PolyglotContextImpl.<init>(PolyglotContextImpl.java:516)
 com.oracle.truffle.polyglot.PolyglotEngineImpl.createContext(PolyglotEngineImpl.java:1750)
 com.oracle.truffle.polyglot.PolyglotEngineDispatch.createContext(PolyglotEngineDispatch.java:162)
 org.graalvm.polyglot.Context$Builder.build(Context.java:1861)
 com.mongodb.mongosh.MongoShellContext.<init>(MongoShellContext.kt:14)
 com.mongodb.mongosh.MongoShell.<init>(MongoShell.kt:10)
 com.dbschema.mongo.mongosh.PrecalculatingShellHolder.lambda$submitNewShell$0(PrecalculatingShellHolder.java:31)
 java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317)
 java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
 java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
 java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
 java.base/java.lang.Thread.run(Thread.java:1583)
2024-03-18T13:09:45.160-04:00  INFO 24680 --- [data-migration-tool] [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2024-03-18T13:09:45.180-04:00 ERROR 24680 --- [data-migration-tool] [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Unsupported Database: Mongo DB 7.0
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1773) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:599) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:521) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:325) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:323) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:312) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:975) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:959) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:624) ~[spring-context-6.1.3.jar:6.1.3]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.2.jar:3.2.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.2.jar:3.2.2]
	at io.me.applications.datamigrationtool.DataMigrationToolApplication.main(DataMigrationToolApplication.java:10) ~[classes/:na]
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: Mongo DB 7.0
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:105) ~[flyway-core-10.10.0.jar:na]
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:73) ~[flyway-core-10.10.0.jar:na]
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:134) ~[flyway-core-10.10.0.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:147) ~[flyway-core-10.10.0.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-3.2.2.jar:3.2.2]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1820) ~[spring-beans-6.1.3.jar:6.1.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1769) ~[spring-beans-6.1.3.jar:6.1.3]
	... 18 common frames omitted
```

**Comment by Barry-RG** [comment]
You appear to be missing the `flyway-database-mongodb` module. It is mentioned in the pre-requisits of how to use [Flyway with MongoDB](https://documentation.red-gate.com/flyway/flyway-cli-and-api/supported-databases/mongodb), however, I can see that it is not as clear as it is on other pages and will be updated. 
Please let us know if this solves your issue.

**Comment by hendisantika** [comment]
Do You have full sample code or github link @lkwheel ?
I have same issue. I already followed the instruction above. But still got the error.

Thank in advance
