### ISSUE TITLE
Support for Postgres 14

### ISSUE THREAD

**Issue by Fraser-Chapman** [flyway/flyway#3902]
###### Which version and edition of Flyway are you using?

10.10.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

Stilll happening in 10.13.0

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

Gradle

###### Which database are you using? (Type & version)

PostgreSQL 14.10

###### Which operating system are you using?

Mac OS Sonoma 14.5

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

I upgraded a Springboot API I maintain that was using Flyway 9.22.3 coming from Springboot 3.2.5 to Flyway 10.10.0 (and Springboot 3.3.0).

Running my unit/integration tests (which use a local dockerised PostgreSQL db for testing) I get the following error:

```
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 14.10
	at app//org.flywaydb.core.internal.database.DatabaseTypeRegister.lambda$getDatabaseTypeForConnection$7(DatabaseTypeRegister.java:122)
	at java.base@21.0.2/java.util.Optional.orElseThrow(Optional.java:403)
	at app//org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:122)
	at app//org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:77)
	at app//org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:138)
	at app//org.flywaydb.core.Flyway.migrate(Flyway.java:156)
	at app//org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1835)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
	... 122 more
```

###### What did you expect to see?

After checking the [flyway documentation](https://documentation.red-gate.com/fd/database-version-support-143754067.html), I expected my app to be able to start successfully as Postgres 14 is listed as compatible with Flyway 10.

###### What did you see instead?

My app was unable to start and the following error was printed:

```
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 14.10
	at app//org.flywaydb.core.internal.database.DatabaseTypeRegister.lambda$getDatabaseTypeForConnection$7(DatabaseTypeRegister.java:122)
	at java.base@21.0.2/java.util.Optional.orElseThrow(Optional.java:403)
	at app//org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:122)
	at app//org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:77)
	at app//org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:138)
	at app//org.flywaydb.core.Flyway.migrate(Flyway.java:156)
	at app//org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1835)
	at app//org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1784)
	... 122 more
```

**Comment by temanskyM** [comment]
Just replace your old flyway dependency to 
```
<dependency>
    <groupId>org.flywaydb</groupId>
    <artifactId>flyway-database-postgresql</artifactId>
</dependency>
```

If you want to find more about it check https://github.com/flyway/flyway/issues/3780

**Comment by Fraser-Chapman** [comment]
> Just replace your old flyway dependency to
> 
> ```
> <dependency>
>     <groupId>org.flywaydb</groupId>
>     <artifactId>flyway-database-postgresql</artifactId>
> </dependency>
> ```
> 
> If you want to find more about it check #3780

Ahh thanks for that. I did a lookup for a related issue but didn't spot that one. That's fixed my issues. Thanks @temanskyM!
