### ISSUE TITLE
Application hangs indefinitely during migration when no database connection is available

### ISSUE THREAD

**Issue by Quairix** [flyway/flyway#3915]
###### Which version and edition of Flyway are you using?
10.13

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
10.15 has the same problem. 
10.1 works fine

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Java API

###### Which database are you using? (Type & version)
Postgresql 15

###### Which operating system are you using?
Windows\Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
After upgrading to Flyway 10.13, when there is no database connection during migration, the application hangs for an extended period. In my project, there are around 500 migrations. Through debugging, I discovered that the issue lies in the ignoring of exceptions in org.flywaydb.core.api.configuration.ClassicConfiguration#getDatabaseType. As a result, org.flywaydb.core.internal.resource.ResourceNameValidator#validateSQLMigrationNaming iterates over all files and catches an exception for each one, indicating that there is no database connection, instead of terminating the application.

###### What did you expect to see?
Application shutdown after first connect exception.

###### What did you see instead?
I have to wait 500*30 sec (migrations count * db connect timeout). Also i have lock on gracefully shutdown.

Thread dump:
"main" prio=0 tid=0x0 nid=0x0 waiting on condition
     java.lang.Thread.State: TIMED_WAITING
	at java.base@21.0.3/java.lang.Thread.sleep0(Native Method)
	at java.base@21.0.3/java.lang.Thread.sleep(Thread.java:509)
	at app//com.zaxxer.hikari.util.UtilityElf.quietlySleep(UtilityElf.java:53)
	at app//com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:567)
	at app//com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:98)
	at app//com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:111)
	at java.base@21.0.3/java.lang.invoke.LambdaForm$DMH/0x0000028f810f8400.invokeInterface(LambdaForm$DMH)
	at java.base@21.0.3/java.lang.invoke.LambdaForm$MH/0x0000028f81c0e800.invoke(LambdaForm$MH)
	at java.base@21.0.3/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at java.base@21.0.3/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:153)
	at java.base@21.0.3/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base@21.0.3/java.lang.reflect.Method.invoke(Method.java:580)
	at app//net.bull.javamelody.JdbcWrapper$3.invoke(JdbcWrapper.java:812)
	at app//net.bull.javamelody.JdbcWrapper$DelegatingInvocationHandler.invoke(JdbcWrapper.java:306)
	at app/jdk.proxy2/jdk.proxy2.$Proxy148.getConnection(Unknown Source)
	at app//org.flywaydb.core.api.configuration.ClassicConfiguration.getDatabaseType(ClassicConfiguration.java:1130)
	at app//org.flywaydb.core.internal.resource.ResourceNameValidator.isSpecialResourceFile(ResourceNameValidator.java:79)
	at app//org.flywaydb.core.internal.resource.ResourceNameValidator.validateSQLMigrationNaming(ResourceNameValidator.java:53)
	at app//org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:136)
	at app//org.flywaydb.core.Flyway.migrate(Flyway.java:164)

**Comment by JasonLuo-Redgate** [comment]
Hi @Quairix ,
I looked into this code. It seems this case only happens when no `url` is configured and no `DataSource` is configured either. Could you work around this by configure either of those?

**Comment by Quairix** [comment]
My dataSource from FluentConfiguration:
![image](https://github.com/flyway/flyway/assets/40596678/47b60ab4-8f4d-4864-9cac-a17c04782bd7)

**Comment by Quairix** [comment]
I think this block should not ignore exceptions like "Connection refused":
![image](https://github.com/flyway/flyway/assets/40596678/e237d47a-b832-4512-a42c-ba34d86f1df7)

![image](https://github.com/flyway/flyway/assets/40596678/feb2d558-60f4-4c08-8c61-fd206e32decf)

**Comment by JasonLuo-Redgate** [comment]
Hi @Quairix ,
I understand the problem now, I will bring this issue to the team.

**Comment by RaviKalasapur** [comment]
Was this fixed ?
