### ISSUE TITLE
flyway failes to insert installed_on timestamp when running a migration

### ISSUE THREAD

**Issue by linde9821** [flyway/flyway#3927]
###### Which version and edition of Flyway are you using?
10.16.0

###### Which client are you using? 
Java API

###### Which database are you using? (Type & version)
mysql  Ver 8.0.37 (MySQL Community Server - GPL)

###### Which operating system are you using?
Linux x86_64 

###### What did you do? 

I have a program which applies migration running within a CI. No special configuration settings or otherwise are used.  

```kotlin
val config = Configuration.loadConfiguration()
val flyway = Flyway.configure()
    .dataSource(config.jdbcUrl, config.username, config.password)
    .schemas("myproject")
    .locations(config.migrationsPath)
    .load()
flyway.migrate()
```
###### What did you expect to see?
I expect that flyway terminates successfully while setting the correct `installed_on` timestamp in the `flyway_schema_history` table. 

###### What did you see instead?
The migrations are applied correctly however the insertion of the `installed_on` field in the `flyway_schema_history` fails. The rest of the fields in the table are set correctly. This exception occurs:

```
Error: Exception in thread "main" java.lang.IllegalArgumentException: null string

	at java.sql/java.sql.Timestamp.valueOf(Timestamp.java:190)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lambda$refreshCache$1(JdbcTableSchemaHistory.java:2[31](https://github.com/My-Project/DataImport-Migrations/actions/runs/10029633569/job/27718076662#step:4:32))
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.query(JdbcTemplate.java:359)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.refreshCache(JdbcTableSchemaHistory.java:207)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.allAppliedMigrations(JdbcTableSchemaHistory.java:198)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:87)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:176)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:146)
	at org.flywaydb.database.mysql.MySQLNamedLockTemplate.execute(MySQLNamedLockTemplate.java:62)
	at org.flywaydb.database.mysql.MySQLConnection.lock(MySQLConnection.java:154)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:149)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:146)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:104)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:222)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:210)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:164)
	at my.project.dataImporter.migrations.DataImportMigrations.runMigrations(DataImportMigrations.kt:27)
	at my.project.dataImporter.migrations.DataImportMigrationsKt.main(DataImportMigrations.kt:[34]
> Task :app:run FAILED
``` 

Furthermore this issue did not occur in the beginning. It just randomly started.

**Comment by JasonLuo-Redgate** [comment]
Hi @linde9821 ,

To better understand this issue, have you just upgraded from a older version of Flyway? 

I'm asking this because this might be related to a similar issue https://github.com/flyway/flyway/issues/3876

**Comment by JasonLuo-Redgate** [comment]
Just to follow up — does this ticket still need attention?

**Comment by jtuemmer** [comment]
I am experiencing the same issue using Flyway Desktop.

Client
- Windows 10
- Flyway Desktop 7.6.1
- Flyway CLI 10.19.0

Database server
- Ubuntu 18.04.6 LTS
- PostgreSQL 14.4 (Ubuntu 14.4-1.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0, 64-bit

After running a (repeatable) migration, Flyway Desktop shows the following error message:

`Unexpected error running flyway migrate`

Looking at the detailed error in Flyway Desktop shows the following info:

```
null string
java.lang.IllegalArgumentException: null string
	at java.sql/java.sql.Timestamp.valueOf(Unknown Source)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lambda$refreshCache$1(JdbcTableSchemaHistory.java:999)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.query(JdbcTemplate.java:1127)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.refreshCache(JdbcTableSchemaHistory.java:975)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.allAppliedMigrations(JdbcTableSchemaHistory.java:966)
	at org.flywaydb.core.internal.info.MigrationInfoServiceImpl.refresh(MigrationInfoServiceImpl.java:855)
	at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:954)
	at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:924)
	at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:845)
	at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.lambda$execute$0(PostgreSQLAdvisoryLockTemplate.java:828)
	at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:827)
	at org.flywaydb.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:828)
	at org.flywaydb.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:873)
	at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:917)
	at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:924)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:875)
	at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:990)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:980)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:932)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:1055)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:970)
	at org.flywaydb.commandline.Main.main(Main.java:893)
```

However, as @linde9821 already stated, the migration was executed successfully but the value of `installed_on` in the `flyway_history_schema table` is not set. Setting the value manually resolves the issue in FlywayDesktop.

In my case, Flyway Desktop worked fine yesterday. The issue came up when running the first migration today.

**Comment by akigmm** [comment]
Is there any update on this issue, we are facing the same error on our systems 

Springboot : 3.3.5
Flyway : 7.15.0 

I don't think the issue is related to the flyway version upgrade - we haven't updated the version for a long time and we started seeing this error recently only 

`Unable to insert row for version '202209121634' in Schema History table db_name.`flyway_schema_history`
----------------------------------------------------------------------------------------------------------------------
SQL State  : HY000
Error Code : 1364
Message    : Field 'installed_on' doesn't have a default value

        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644)
        ... 32 common frames omitted
Caused by: org.flywaydb.core.internal.exception.FlywaySqlException: Unable to insert row for version '202209121634' in Schema History table `db_name`.`flyway_schema_history`
`

**Comment by linde9821** [comment]
> Hi @linde9821 ,
> 
> 
> 
> To better understand this issue, have you just upgraded from a older version of Flyway? 
> 
> 
> 
> I'm asking this because this might be related to a similar issue https://github.com/flyway/flyway/issues/3876 
> 
> 

Hi sorry for the late response. Yes we upgraded but this did not solve our issue. 

Since we are still in active development we recently deleted the old MySQL instance and created a new one (same version) which actually solved the issue in our case.

**Comment by vinfang** [comment]
We're using flyway 9.19.4 and we're planning to upgrade, but we're seeing errors with 11.1.1 and we tried 10.22.0, 10.9.1, and 10.4.1 and we're getting an

`ERROR: java.lang.IllegalArgumentException: null string`

looking at the installed_on column in our flyway history schema, it looks like for whatever reason it stopped populating that column with version 9.14.4 but is there any explanation why it's null in the first place?

**Comment by sebaap** [comment]
I'm facing the same issue on a PostgreSQL db. Since it's a production system I can't recreate the db, so I fixed it by setting a default value on the `installed_on` column:
```
ALTER TABLE flyway_schema_history ALTER COLUMN installed_on SET DEFAULT now();
``` 
In case it's useful for someone else

**Comment by JasonLuo-Redgate** [comment]
This `IllegalArgumentException` issue has been fixed in the latest Flyway release. If you encounter any further problems, please feel free to let us know. Many thanks for bringing this to our attention.
