### ISSUE TITLE
Flyway 10.17.1 - SQL Server - Use JsonReader.setLenient(true) to accept malformed JSON

### ISSUE THREAD

**Issue by luke9216** [flyway/flyway#3945]
###### Which version and edition of Flyway are you using?
Flyway 10.17.1 - CLI

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Using latest

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using? (Type & version)
SQL Server

###### Which operating system are you using?
Linux - Ubuntu 24.04 LTS (GNU/Linux 6.8.0-1013-aws x86_64)

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)

Running concurrent Flyway Tasks in Octopus Deploy. Works fine deploying one database at a time. However, appears when running on updating multiple databases at the same time (current deployment process)

flyway check -dryrun -changes -drift -code -X info -stream="true" -locations="filesystem:$migrationsPath" -baselineOnMigrate="true" -licenseKey="$flyway_license_key" -configFiles="$configPath" "-check.failOnDrift=$FailOnDrift" "-check.buildUrl=$buildUrl" "-check.buildUser=$user" "-check.buildPassword=$password" -url="$env_JDBC" -reportFilename="$reportPath" -user="$user" -password="$password"

###### What did you see instead?

ERROR: Unexpected error
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 983789 path $
	at com.google.gson.JsonParser.parseReader(JsonParser.java:76)
	at com.google.gson.JsonParser.parseString(JsonParser.java:51)
	at org.flywaydb.core.internal.util.JsonUtils.parseJsonArray(JsonUtils.java:867)
	at org.flywaydb.check.rgcompare.RGCompareCheckTasksPlugin.getChangesResult(RGCompareCheckTasksPlugin.java:1089)
	at org.flywaydb.check.rgcompare.RGCompareCheckTasksPlugin.generateChangeReportFromBuildEnvironmentAndUrl(RGCompareCheckTasksPlugin.java:991)
	at org.flywaydb.check.rgcompare.RGCompareCheckTasksPlugin.generateChangeReport(RGCompareCheckTasksPlugin.java:839)
	at org.flywaydb.check.changes.ChangesCommandExtension.handle(ChangesCommandExtension.java:844)
	at org.flywaydb.check.CheckCommandExtension.handle(CheckCommandExtension.java:936)
	at org.flywaydb.core.internal.util.CommandExtensionUtils.lambda$runCommandExtension$1(CommandExtensionUtils.java:804)
	at java.base/java.util.Optional.map(Unknown Source)
	at org.flywaydb.core.internal.util.CommandExtensionUtils.runCommandExtension(CommandExtensionUtils.java:804)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:1106)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:967)
	at org.flywaydb.commandline.Main.main(Main.java:890)
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 983789 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1659)
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1465)
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:551)
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:433)
	at com.google.gson.JsonParser.parseReader(JsonParser.java:71)
	... 13 more

**Comment by WilliamL-RG** [comment]
In the latest release, we have moved away from GSON to use Jackson in all internal code. I will close this issue, but if you encounter further issues please raise a new ticket and we will have a look.

**Comment by luke9216** [comment]
Hi William,

After updating to 10.17.3 (This is the version I assume you are referring to)

This erro has occurred.

```
ERROR: Unexpected error
java.lang.ClassCastException: class com.fasterxml.jackson.databind.node.MissingNode cannot be cast to class com.fasterxml.jackson.databind.node.ArrayNode (com.fasterxml.jackson.databind.node.MissingNode and com.fasterxml.jackson.databind.node.ArrayNode are in unnamed module of loader 'app')
	at org.flywaydb.core.internal.util.JsonUtils.parseJsonArray(JsonUtils.java:867)
	at org.flywaydb.check.legacy.rgcompare.RGCompareCheckTasksPlugin.getChangesResult(RGCompareCheckTasksPlugin.java:1088)
	at org.flywaydb.check.legacy.rgcompare.RGCompareCheckTasksPlugin.generateDriftReportFromBuildEnvironmentAndUrl(RGCompareCheckTasksPlugin.java:957)
	at org.flywaydb.check.legacy.rgcompare.RGCompareCheckTasksPlugin.generateDriftReport(RGCompareCheckTasksPlugin.java:871)
	at org.flywaydb.check.drift.DriftCommandExtension.handle(DriftCommandExtension.java:845)
	at org.flywaydb.check.CheckCommandExtension.handle(CheckCommandExtension.java:899)
	at org.flywaydb.core.internal.util.CommandExtensionUtils.lambda$runCommandExtension$1(CommandExtensionUtils.java:804)
	at java.base/java.util.Optional.map(Unknown Source)
	at org.flywaydb.core.internal.util.CommandExtensionUtils.runCommandExtension(CommandExtensionUtils.java:804)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:1113)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:974)
	at org.flywaydb.commandline.Main.main(Main.java:892)
```
