### ISSUE TITLE
Flyway 10.19.0 CLI java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by luke9216** [flyway/flyway#3962]
###### Which version and edition of Flyway are you using?
Flyway 10.19.0 CLI - Enterprise

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
CLI

###### Which database are you using? (Type & version)
SQL Server 2019

###### Which operating system are you using?
Linux Ubuntu

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
- Using Octopus Deploy
- Command: flyway check -dryrun -changes -drift -code -X info -stream="true" -locations="filesystem:$migrationsPath" -baselineOnMigrate="true" -licenseKey="$flyway_license_key" -configFiles="$configPath" "-check.failOnDrift=$FailOnDrift" "-check.buildUrl=$buildUrl" "-check.buildUser=$user" "-check.buildPassword=$password" -url="$env_JDBC" -reportFilename="$reportPath" -user="$user" -password="$password"

###### What did you see instead?

DEBUG: Scanning for classpath resources at 'classpath:db/callback' ...
DEBUG: Determining location urls for classpath:db/callback using ClassLoader java.net.URLClassLoader@23ee75c5 ...
DEBUG: Unable to resolve location classpath:db/callback.
Drift report summary:
Added: 386        Deleted: 3        Modified: 31
ERROR: Error converting model to map
DEBUG: Executing sqlfluff version
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.flywaydb.telemetry.otel.OTelTelemetryPlugin.convertModelToMap(OTelTelemetryPlugin.java:1000)
	at org.flywaydb.telemetry.otel.OTelTelemetryPlugin.addEvent(OTelTelemetryPlugin.java:905)
	at org.flywaydb.telemetry.otel.OTelTelemetryPlugin.logEventDetails(OTelTelemetryPlugin.java:881)
	at org.flywaydb.core.FlywayTelemetryManager.logEvent(FlywayTelemetryManager.java:846)
	at org.flywaydb.core.extensibility.EventTelemetryModel.close(EventTelemetryModel.java:816)
	at org.flywaydb.check.CheckCommandExtension.handle(CheckCommandExtension.java:935)
	at org.flywaydb.core.internal.util.CommandExtensionUtils.lambda$runCommandExtension$1(CommandExtensionUtils.java:804)
	at java.base/java.util.Optional.map(Unknown Source)
	at org.flywaydb.core.internal.util.CommandExtensionUtils.runCommandExtension(CommandExtensionUtils.java:804)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:1117)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:978)
	at org.flywaydb.commandline.Main.main(Main.java:892)
Caused by: java.lang.NullPointerException: Cannot invoke "org.flywaydb.check.drift.DriftTelemetryModel$DeployedSnapshotSource.getValue()" because "this.deployedSnapshotSource" is null
	at org.flywaydb.check.drift.DriftTelemetryModel.getDeployedSnapshotSource(DriftTelemetryModel.java:806)
	... 16 more
DEBUG: Cannot run program "sqlfluff": error=2, No such file or directory
Flyway SqlFluff code analysis requires Python 3, pip and SqlFluff version 1.2.1 or greater, preferably version 3.0.7
Run 'pip install sqlfluff==3.0.7' to install SqlFluff if you would like to access this function
DEBUG: Scanning for classpath resources at 'classpath:db/callback' ...

**Comment by JasonLuo-Redgate** [comment]
Hi @luke9216 ,
Many thanks for reporting this issue and we're looking into it.

**Comment by JasonLuo-Redgate** [comment]
Hi @luke9216 ,
The reported issue has been fixed in the latest release  10.20.0. 
https://documentation.red-gate.com/flyway/release-notes-and-older-versions/release-notes-for-flyway-engine

**Comment by luke9216** [comment]
@JasonLuo-Redgate Thanks for your hard work, much appreciated.
