### ISSUE TITLE
Unsupported Database: PostgreSQL 16.4 when upgrade to 10.20.1

### ISSUE THREAD

**Issue by NguyenDuyKhanh03** [flyway/flyway#3969]
###### Which version and edition of Flyway are you using?10.20.1
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception with message: Unsupported Database: PostgreSQL 16.4
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:178) ~[spring-beans-6.1.12.jar:6.1.12]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:644) ~[spring-beans-6.1.12.jar:6.1.12]
	... 20 common frames omitted
Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 16.4
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.lambda$getDatabaseTypeForConnection$7(DatabaseTypeRegister.java:124) ~[flyway-core-10.20.1.jar:na]
	at java.base/java.util.Optional.orElseThrow(Optional.java:403) ~[na:na]
	at org.flywaydb.core.internal.database.DatabaseTypeRegister.getDatabaseTypeForConnection(DatabaseTypeRegister.java:124) ~[flyway-core-10.20.1.jar:na]
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:77) ~[flyway-core-10.20.1.jar:na]
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:137) ~[flyway-core-10.20.1.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:176) ~[flyway-core-10.20.1.jar:na]
	at com.example.clothes_api.config.FlywayConfig.flyway(FlywayConfig.java:34) ~[classes/:na]
	at com.example.clothes_api.config.FlywayConfig$$SpringCGLIB$$0.CGLIB$flyway$1(<generated>) ~[classes/:na]
	at com.example.clothes_api.config.FlywayConfig$$SpringCGLIB$$FastClass$$1.invoke(<generated>) ~[classes/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:258) ~[spring-core-6.1.12.jar:6.1.12]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:348) ~[spring-context-6.1.12.jar:6.1.12]
	at com.example.clothes_api.config.FlywayConfig$$SpringCGLIB$$0.flyway(<generated>) ~[classes/:na]
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:146) ~[spring-beans-6.1.12.jar:6.1.12]
	... 21 common frames omitted

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Maven plugin

###### Which operating system are you using?Windows

![Untitled](https://github.com/user-attachments/assets/95a66bb4-c536-47fd-94d0-683829d4b0f3)

**Comment by JasonLuo-Redgate** [comment]
Hi @NguyenDuyKhanh03 ,

Could you confirm whether the below dependency is also included?

```
       <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
            <scope>runtime</scope>
        </dependency>
```

**Comment by NguyenDuyKhanh03** [comment]
> Xin chào ,
> 
> Bạn có thể xác nhận liệu sự phụ thuộc dưới đây cũng được bao gồm?
> 
> ```
>        <dependency>
>             <groupId>org.postgresql</groupId>
>             <artifactId>postgresql</artifactId>
>         </dependency>
> ```

I have this dependency

**Comment by csiitian** [comment]
I am also facing the same issue.
Error: `Caused by: org.flywaydb.core.api.FlywayException: Unsupported Database: PostgreSQL 16.3`

```xml
<!--pom.xml-->
<dependency>
	<groupId>org.flywaydb</groupId>
	<artifactId>flyway-core</artifactId>
	<version>10.20.1</version>
</dependency>
<dependency>
        <groupId>org.postgresql</groupId>
        <artifactId>postgresql</artifactId>
        <version>42.7.4</version>
</dependency>
```

**Comment by JasonLuo-Redgate** [comment]
Hello, 
I tried Flyway Maven plugin `10.20.1` with below configurations. However, I can't not replicate the issue and the connection is running fine. 

```
      <plugin>
        <groupId>org.flywaydb</groupId>
        <artifactId>flyway-maven-plugin</artifactId>
        <version>10.20.1</version>
      </plugin>

     <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <version>42.7.2</version>
    </dependency>
    <dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-database-postgresql</artifactId>
      <version>10.20.1</version>
    </dependency>
```

**Comment by dahioth** [comment]
I had the same issue.
**Solved by adding:**

// in Gradle
implementation("org.flywaydb:flyway-database-postgresql")
// in Maven
<dependency>
      <groupId>org.flywaydb</groupId>
      <artifactId>flyway-database-postgresql</artifactId>
      <version>10.20.1</version>
</dependency>

Should be good if you have the 3 dependencies: 

- org.flywaydb:flyway-database-postgresql
- org.flywaydb:flyway-core
- org.postgresql:postgresql
