### ISSUE TITLE
Receiver class org.flywaydb.database.postgresql.PostgreSQLConfigurationExtension does not define or inherit an implementation of the resolved method 'abstract void extractParametersFromConfiguration(java.util.Map)' of interface org.flywaydb.core.extensibility.ConfigurationExtension

### ISSUE THREAD

**Issue by felix9ia** [flyway/flyway#3975]
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flyway' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is java.lang.AbstractMethodError: Receiver class org.flywaydb.database.postgresql.PostgreSQLConfigurationExtension does not define or inherit an implementation of the resolved method 'abstract void extractParametersFromConfiguration(java.util.Map)' of interface org.flywaydb.core.extensibility.ConfigurationExtension.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1519)
	... 73 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.flywaydb.core.Flyway]: Factory method 'flyway' threw exception; nested exception is java.lang.AbstractMethodError: Receiver class org.flywaydb.database.postgresql.PostgreSQLConfigurationExtension does not define or inherit an implementation of the resolved method 'abstract void extractParametersFromConfiguration(java.util.Map)' of interface org.flywaydb.core.extensibility.ConfigurationExtension.
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:648)
	... 88 common frames omitted
Caused by: java.lang.AbstractMethodError: Receiver class org.flywaydb.database.postgresql.PostgreSQLConfigurationExtension does not define or inherit an implementation of the resolved method 'abstract void extractParametersFromConfiguration(java.util.Map)' of interface org.flywaydb.core.extensibility.ConfigurationExtension.
	at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1373)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.configureFromConfigurationProviders(ClassicConfiguration.java:1669)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:1345)
	at org.flywaydb.core.api.configuration.ClassicConfiguration.<init>(ClassicConfiguration.java:412)
	at org.flywaydb.core.Flyway.<init>(Flyway.java:100)
	at org.flywaydb.core.api.configuration.FluentConfiguration.load(FluentConfiguration.java:59)
	at org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration$FlywayConfiguration.flyway(FlywayAutoConfiguration.java:126)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 89 common frames omitted
```

###### Which version and edition of Flyway are you using?
```
   <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
            <version>10.20.1</version>
        </dependency>

        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-database-postgresql</artifactId>
            <version>10.20.1</version>
            <scope>runtime</scope>
        </dependency>

```

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)

latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)

```
   <spring-boot.version>2.7.18</spring-boot.version>

```
###### Which database are you using? (Type & version)

PostgreSQL 16.4

###### Which operating system are you using?

Windows 11

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
```
spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      maximum-pool-size: 5
      minimum-idle: 2
      pool-name: HikariPool-Postgres
    url: jdbc:postgresql://localhost:5432/xxx_db?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: xxx
    password: xxx
  jpa:
    show-sql: false
  flyway:
    enabled: true
```

###### What did you expect to see?

I hope it works properly

**Comment by JasonLuo-Redgate** [comment]
Hi @felix9ia ,
Thanks for reporting this issue. 

I looked into the latest code and found the involved method `extractParametersFromConfiguration` has been marked as `default` in the interface which means there shouldn't be implementation requirement for this method. 

One possible cause of this error I can think of is that somehow a old version of `flyway-core` was used accidently in which the method wasn't marked as `default` at that time.

**Comment by felix9ia** [comment]
![image](https://github.com/user-attachments/assets/7edd21e0-75e4-4132-bfcd-9db7169ba503)
@JasonLuo-Redgate There is indeed a weird 8.5.13 version of core. Even if I delete .m2, it doesn't work...

**Comment by JasonLuo-Redgate** [comment]
Hi @felix9ia ,

Thanks for the confirmation, so it looks like a jar decency issue. Hope you don't mind I close this ticket for now.

**Comment by felix9ia** [comment]
I used Maven helper to check and found the following conflicts, but I don't understand why this happened

<img width="726" alt="c21a85fb20515ff47de94c0e04a9d45" src="https://github.com/user-attachments/assets/a63fdabc-6047-40d0-98d6-5313045946d4">
