### ISSUE TITLE
org.flywaydb.core.api.FlywayException: Unable to parse statement

### ISSUE THREAD

**Issue by anuragp09** [flyway/flyway#3983]
###### Which version and edition of Flyway are you using?
10.21.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Not applicable.

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command-line and Gradle plugin

###### Which database are you using? (Type & version)
Oracle autonomous database version 23ai

###### Which operating system are you using?
oracle linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I am trying to create a new user via the init sql property. the SQL is below:
export FLYWAY_INIT_SQL="CREATE USER IF NOT EXISTS APPHUB12 IDENTIFIED BY \"PASSWD123\" DEFAULT TABLESPACE DATA QUOTA UNLIMITED ON DATA;"

###### What did you expect to see?
the user should have been successfully created.

###### What did you see instead?
flyway threw an error. error is shown below.
the user got created.
the user was in LOCKED(TIMED) state when checked in DB.

DEBUG: Parsing  ...
DEBUG: Memory usage: 202 of 336M
ERROR: Unexpected error
org.flywaydb.core.api.FlywayException: Unable to parse statement in  at line 1 col 1. See https://rd.gt/3ipi7Pm for more information. For Oracle-specific information about syntax and limitations, see https://rd.gt/3SISqKJ. Incomplete statement at line 1 col 1: CREATE USER IF NOT EXISTS APPHUB12 IDENTIFIED BY "PASSWD123" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:1067)
	at org.flywaydb.database.oracle.OracleParser.getNextStatement(OracleParser.java:1463)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:1495)
	at org.flywaydb.core.internal.parser.Parser$ParserSqlStatementIterator.next(Parser.java:1460)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.parse(ParserSqlScript.java:843)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.validate(ParserSqlScript.java:884)
	at org.flywaydb.core.internal.sqlscript.ParserSqlScript.getSqlStatements(ParserSqlScript.java:890)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:873)
	at org.flywaydb.database.oracle.OracleSqlScriptExecutor.execute(OracleSqlScriptExecutor.java:861)
	at org.flywaydb.core.FlywayExecutor.lambda$execute$1(FlywayExecutor.java:927)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.openConnection(JdbcConnectionFactory.java:874)
	at org.flywaydb.core.internal.database.base.Database.<init>(Database.java:857)
	at org.flywaydb.database.oracle.OracleDatabase.<init>(OracleDatabase.java:827)
	at org.flywaydb.database.oracle.OracleDatabaseType.createDatabase(OracleDatabaseType.java:881)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:932)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:945)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:1066)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:972)
	at org.flywaydb.commandline.Main.main(Main.java:895)
Caused by: org.flywaydb.core.api.FlywayException: Incomplete statement at line 1 col 1: CREATE USER IF NOT EXISTS APPHUB12 IDENTIFIED BY "PASSWD123" DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
	at org.flywaydb.core.internal.parser.Parser.getNextStatement(Parser.java:1007)
	... 18 more

**Comment by madbrain** [comment]
The SQL parser for Oracle seems to be broken : it doesn't support classical `CREATE xxx IF NOT EXISTS` as `IF` keyword is considered a control flow keyword and increase the block level which is never decreased (with and END) then the end delimiter `;` can't terminate the statement because of not zero block level (https://github.com/flyway/flyway/blame/main/flyway-database/flyway-database-oracle/src/main/java/org/flywaydb/database/oracle/OracleParser.java#L526C20-L526C142).

I can't any workaround other than removing `IF NOT EXISTS` keywords.

**Comment by JasonLuo-Redgate** [comment]
Solved via #4231
