### ISSUE TITLE
Init SQL executing multiple times

### ISSUE THREAD

**Issue by anuragp09** [flyway/flyway#3984]
###### Which version and edition of Flyway are you using?
Flyway OSS Edition 10.21.0 by Redgate

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
Not applicable

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Command line

###### Which database are you using? (Type & version)
Oracle Database version 19C

###### Which operating system are you using?
Linux

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I am trying to run flyway migrations from a shell script.
I tried to create a new user using the FLYWAY_INIT_SQL property as show below:
`export FLYWAY_INIT_SQL="CREATE USER APPHUB13 IDENTIFIED BY PASSWD123 QUOTA UNLIMITED ON USERS;"`

###### What did you expect to see?
I expected that the init SQL will run just once, immediately after DB connection is made.

###### What did you see instead? ######
I see that init SQL is executed multiple times, which leads to an error as shown below:

DEBUG: Validating V9__Feature_Switch_Audit_Update_tables.sql
DEBUG: Parsing  ...
DEBUG: Found statement at line 1: CREATE USER APPHUB13 IDENTIFIED BY PASSWD123 QUOTA UNLIMITED ON USERS
DEBUG: Executing SQL: CREATE USER APPHUB13 IDENTIFIED BY PASSWD123 QUOTA UNLIMITED ON USERS
DEBUG: 0 rows affected
Database: jdbc:oracle:thin:@//localhost:1522/ORCLPDB1 (Oracle 19.0)
DEBUG: Database Type: Oracle
DEBUG: Driver: Oracle JDBC driver 19.6.0.0.0
<some other logs excluded>
DEBUG: Executing SQL: CREATE TABLE "APPHUB13"."flyway_schema_history" (
    "installed_rank" INT NOT NULL,
    "version" VARCHAR2(50),
    "description" VARCHAR2(200) NOT NULL,
    "type" VARCHAR2(20) NOT NULL,
    "script" VARCHAR2(1000) NOT NULL,
    "checksum" INT,
    "installed_by" VARCHAR2(100) NOT NULL,
    "installed_on" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "execution_time" INT NOT NULL,
    "success" NUMBER(1) NOT NULL,
    CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank")
) TABLESPACE "USERS"
DEBUG: 0 rows affected
Table created.
DEBUG: Executing SQL: CREATE INDEX "APPHUB13"."flyway_schema_history_s_idx" ON "APPHUB13"."flyway_schema_history" ("success")
DEBUG: 0 rows affected
DEBUG: Created Schema History table "APPHUB13"."flyway_schema_history"
DEBUG: Parsing  ...
DEBUG: Found statement at line 1: CREATE USER APPHUB13 IDENTIFIED BY PASSWD123 QUOTA UNLIMITED ON USERS
DEBUG: Executing SQL: CREATE USER APPHUB13 IDENTIFIED BY PASSWD123 QUOTA UNLIMITED ON USERS
DEBUG: Memory usage: 449 of 960M
ERROR: Unexpected error
org.flywaydb.core.internal.sqlscript.FlywaySqlScriptException: Script  failed
SQL State  : 42000
Error Code : 1920
Message    : ORA-01920: user name 'APPHUB13' conflicts with another user or role name
Location   :  ()
Line       : 1
Statement  : CREATE USER APPHUB13 IDENTIFIED BY PASSWD123 QUOTA UNLIMITED ON USERS
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.handleException(DefaultSqlScriptExecutor.java:1024)
	at org.flywaydb.database.oracle.OracleSqlScriptExecutor.handleException(OracleSqlScriptExecutor.java:933)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:985)
	at org.flywaydb.database.oracle.OracleSqlScriptExecutor.executeStatement(OracleSqlScriptExecutor.java:877)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:905)
	at org.flywaydb.database.oracle.OracleSqlScriptExecutor.execute(OracleSqlScriptExecutor.java:861)
	at org.flywaydb.core.FlywayExecutor.lambda$execute$1(FlywayExecutor.java:927)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.openConnection(JdbcConnectionFactory.java:874)
	at org.flywaydb.core.internal.database.base.Database.getMigrationConnection(Database.java:1076)
	at org.flywaydb.core.internal.command.DbMigrate.<init>(DbMigrate.java:845)
	at org.flywaydb.core.Flyway.lambda$migrate$1(Flyway.java:999)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:981)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:945)
	at org.flywaydb.commandline.Main.executeOperation(Main.java:1066)
	at org.flywaydb.commandline.Main.executeFlyway(Main.java:972)
	at org.flywaydb.commandline.Main.main(Main.java:895)
Caused by: java.sql.SQLSyntaxErrorException: ORA-01920: user name 'APPHUB13' conflicts with another user or role name
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:509)
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:461)
	at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1104)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:553)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:269)
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:655)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:229)
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:41)
	at oracle.jdbc.driver.T4CStatement.executeForRows(T4CStatement.java:928)
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1205)
	at oracle.jdbc.driver.OracleStatement.executeInternal(OracleStatement.java:1823)
	at oracle.jdbc.driver.OracleStatement.execute(OracleStatement.java:1778)
	at oracle.jdbc.driver.OracleStatementWrapper.execute(OracleStatementWrapper.java:303)
	at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:978)
	at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:856)
	at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:980)
	... 13 more
Caused by: Error : 1920, Position : 12, Sql = CREATE USER APPHUB13 IDENTIFIED BY PASSWD123 QUOTA UNLIMITED ON USERS, OriginalSql = CREATE USER APPHUB13 IDENTIFIED BY PASSWD123 QUOTA UNLIMITED ON USERS, Error Msg = ORA-01920: user name 'APPHUB13' conflicts with another user or role name
	at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:513)
	... 28 more

**Comment by anuragp09** [comment]
ok thank you.
I request to add this point to the docs.
