### ISSUE TITLE
No database found to handle ... [db connection url] (even after specialized dependency inclusion)

### ISSUE THREAD

**Issue by BrainDias** [flyway/flyway#3998]
###### Which version and edition of Flyway are you using?
flyway-database-postgresql:11.1.0

###### If this is not the latest version, can you reproduce the issue with the latest one as well? (Many bugs are fixed in newer releases and upgrading will often resolve the issue)
The latest version

###### Which client are you using? (Command-line, Java API, Maven plugin, Gradle plugin)
Gradle plugin

###### Which database are you using? (Type & version)
PostgreSQL 16.4

###### Which operating system are you using?
Windows 10

###### What did you do? (Please include the content causing the issue, any relevant configuration settings, the SQL statement(s) that failed (if any), and the command you ran)
I have 2 flyway dependencies in my Gradle Groovy build script:
1. 'id 'org.flywaydb.flyway' version '11.1.0''
2. 'runtimeOnly 'org.flywaydb:flyway-database-postgresql:11.1.0''
And also postgresql driver dependency of ver. 42.7.3 (although I've tried 42.2.22)

Flyway configuration is as follows (default):
'flyway {
	url = 'jdbc:postgresql://localhost:5432/postgres'
	driver = 'org.postgresql.Driver'
	user = 'postgres'
	password = 'password'
	locations = ['classpath:db/migration']
}'
DB itself is 100% working and accessible

###### What did you expect to see?
Successful execution of the command

###### What did you see instead?
'Caused by: org.flywaydb.core.api.FlywayException: No database found to handle jdbc:postgresql://localhost:5432/postgres
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:158)
        at org.flywaydb.core.internal.jdbc.DriverDataSource.<init>(DriverDataSource.java:96)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.getDataSource(ClassicConfiguration.java:250)
        at org.flywaydb.core.api.configuration.ClassicConfiguration.configure(ClassicConfiguration.java:2048)
        at org.flywaydb.core.api.configuration.FluentConfiguration.configuration(FluentConfiguration.java:907)
        at org.flywaydb.gradle.task.AbstractFlywayTask.runTask(AbstractFlywayTask.java:605)
        ... 150 more'

**Comment by JasonLuo-Redgate** [comment]
Hi @BrainDias ,

Can you run it with `-X` flag to get a full debug log?

**Comment by BrainDias** [comment]
@JasonLuo-Redgate 
As I don't have Flyway CLI on my machine, only Gradle plugin, I used console command `./gradlew flywayInfo` with `flyway.debug=true` in created "flyway.conf" file. I've read this should be equal to using -X in Flyway CLI.

The result is nothing more than it was:
`* What went wrong:
Execution failed for task ':flywayInfo'.
> Error occurred while executing flywayInfo
  No database found to handle jdbc:postgresql://localhost:5432/postgres`
  
  Actually yesterday I've installed and connected to PostgreSQL 17.2 but problem persisted.
  I should've mentioned that it executes migrations correctly into this same DB it doesn't "see" while executing console commands

**Comment by EliasDerHai** [comment]
had the same issue and solved it by adding 
```
buildscript {
    dependencies {
        classpath("org.flywaydb:flyway-database-postgresql:11.1.0")
    }
}
```
to my build.gradle.kts 
as per this [post](https://github.com/flyway/flyway/issues/3774#issuecomment-1829245496)

took me ages and am considering stepping away from flyway now.
unbelievable that managing a simple sql file takes a gradle plugin, plus various dependencies, drivers, configs and then still fails with some completely useless arbitrary errorcode because some magic classpath is missing

**Comment by jameskyle** [comment]
Just chiming in, I see the same error with flyway 11.2. Gradle 8.x. Even after adding the buildscript class path dependency and the flyway-database-postgresql implementation for 11.2

I rolled back to 9.x to get it working.

**Comment by Mr-EmPee** [comment]
I've encountered this problem as well, the solution seems more like a workaround than a proper fix.
It would be helpful if this was at least mentioned in the documentation until an official fix is available.

For now, I'm using version 9.22.0 of the Gradle plugin, which doesn't require this workaround.

**Comment by TbirdDuncan** [comment]
Heya, I'm also experiencing this issue. Tried fixing it via Elias post, but I'm hit with: 
```:flywayMigrate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flywayMigrate'.
> 'void org.flywaydb.core.internal.configuration.ConfigUtils.dumpConfigurationMap(java.util.Map)'

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.10.2/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 1s
1 actionable task: 1 executed```
This is a really barebones demo project I'm trying to get working...
