### ISSUE TITLE
SQL Server Unable to drop schema when functions exist

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#472]
_Original author: timan...@gmail.com (April 02, 2013 20:15:12)_

Using Flyway 2.2.1 from Maven, when I run 'mvn flyway:clean' it will not drop my schema that has a function that is uses as the default value for a column.

[ERROR] Failed to execute goal com.googlecode.flyway:flyway-maven-plugin:2.1.1:clean (default-cli) on project sql-fod-flyway: Flyway Error: com.googlecode.flyway.core.api.FlywayException: Unable to clean schema [dbo]: Cannot DROP FUNCTION 'dbo.myFunction' because it is being referenced by object 'DEFAULT_THAT_USES_MYFUNCTION'. -&gt; [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.googlecode.flyway:flyway-maven-plugin:2.1.1:clean (default-cli) on project sql-fod-flyway: Flyway Error: com.googlecode.flyway.core.api.FlywayException: Unable to clean schema [dbo]
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: Flyway Error: com.googlecode.flyway.core.api.FlywayException: Unable to clean schema [dbo]
        at com.googlecode.flyway.maven.AbstractFlywayMojo.execute(AbstractFlywayMojo.java:260)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: com.googlecode.flyway.core.api.FlywayException: Unable to clean schema [dbo]
        at com.googlecode.flyway.core.dbsupport.Schema.clean(Schema.java:146)
        at com.googlecode.flyway.core.command.DbClean$2.doInTransaction(DbClean.java:119)
        at com.googlecode.flyway.core.command.DbClean$2.doInTransaction(DbClean.java:117)
        at com.googlecode.flyway.core.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:54)
        at com.googlecode.flyway.core.command.DbClean.cleanSchema(DbClean.java:117)
        at com.googlecode.flyway.core.command.DbClean.clean(DbClean.java:81)
        at com.googlecode.flyway.core.Flyway$3.execute(Flyway.java:919)
        at com.googlecode.flyway.core.Flyway$3.execute(Flyway.java:915)
        at com.googlecode.flyway.core.Flyway.execute(Flyway.java:1177)
        at com.googlecode.flyway.core.Flyway.clean(Flyway.java:915)
        at com.googlecode.flyway.maven.CleanMojo.doExecute(CleanMojo.java:32)
        at com.googlecode.flyway.maven.AbstractFlywayMojo.execute(AbstractFlywayMojo.java:251)
        ... 21 more
Caused by: java.sql.SQLException: Cannot DROP FUNCTION 'dbo.myFunction' because it is being referenced by object 'DEFAULT_THAT_USES_MYFUNCTION'.
        at net.sourceforge.jtds.jdbc.SQLDiagnostic.addDiagnostic(SQLDiagnostic.java:368)
        at net.sourceforge.jtds.jdbc.TdsCore.tdsErrorToken(TdsCore.java:2820)
        at net.sourceforge.jtds.jdbc.TdsCore.nextToken(TdsCore.java:2258)
        at net.sourceforge.jtds.jdbc.TdsCore.getMoreResults(TdsCore.java:632)
        at net.sourceforge.jtds.jdbc.JtdsStatement.processResults(JtdsStatement.java:584)
        at net.sourceforge.jtds.jdbc.JtdsStatement.executeSQL(JtdsStatement.java:546)
        at net.sourceforge.jtds.jdbc.JtdsPreparedStatement.execute(JtdsPreparedStatement.java:558)
        at com.googlecode.flyway.core.dbsupport.JdbcTemplate.execute(JdbcTemplate.java:214)
        at com.googlecode.flyway.core.dbsupport.sqlserver.SQLServerSchema.doClean(SQLServerSchema.java:81)
        at com.googlecode.flyway.core.dbsupport.Schema.clean(Schema.java:144)
        ... 32 more
[ERROR]
[ERROR]

_Original issue: http://code.google.com/p/flyway/issues/detail?id=472_

**Comment by mdaquel** [comment]
Hi, 

Just wonder if there a fix to this issue on the latest release?

Cheers

**Comment by axelfontaine** [comment]
If you feel this is still a bug, please open a new issue with a small sample script and EXACT steps on how to reproduce.

**Comment by mdaquel** [comment]
Hi Axel, 

Thank you for your quick reply, will do the above as you recommended. 

Cheers
