### ISSUE TITLE
No "current" schema in flyway.url causes a Flyway exception

### ISSUE THREAD

**Issue by tomsquest** [flyway/flyway#598]
Using the Maven plugin, with a Mysql JDBC url containing no schema, Flyway migrates the database, but fails just after complaining with "Error setting current schema to ``: No database selected".

Failing Jdbc url : jdbc:mysql://localhost:3306
Valid Jdbc url : jdbc:mysql://localhost:3306/myDatabase

This occurs even with some schemas specified (in the pom.xml), 

Not reproduced with Flyway 2.1.1 (maven 3.0.5)
Failing with Flyway plugin : 2.2.1 (maven 3.1)
Driver : org.gjt.mm.mysql.Driver

It seems that this line in Flyway.java (https://github.com/flyway/flyway/blob/master/flyway-core/src/main/java/com/googlecode/flyway/core/Flyway.java#L875) assumes that `dbSupport.getCurrentSchema()` will return something meaningful but it returns an empty string the failing jdbc url.

**Comment by g0t4** [comment]
Without a schema in the connection string (ie: flyway.url=jdbc:mysql://localhost), the following exception comes back from the command line interface to flyway:

ERROR: Unexpected error
java.lang.NullPointerException
        at org.flywaydb.core.internal.dbsupport.mysql.MySQLDbSupport.doSetCurren
tSchema(MySQLDbSupport.java:60)
        at org.flywaydb.core.internal.dbsupport.DbSupport.setCurrentSchema(DbSup
port.java:101)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:975)
        at org.flywaydb.core.Flyway$1.execute(Flyway.java:919)
        at org.flywaydb.core.Flyway.execute(Flyway.java:1320)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:919)
        at org.flywaydb.commandline.Main.executeOperation(Main.java:118)
        at org.flywaydb.commandline.Main.main(Main.java:87)

**Comment by g0t4** [comment]
Just an update, if I use the platform independent mysql driver (mysql-connector-java-5.1.34-bin.jar), I don't get an error when not specifying a schema in the connection string, and instead specifying the schema with flyway.schemas. Flyway successfully creates the database.

However, if I do specify the schema and the database doesn't exist, I do still get an exception (and perhaps this is intended and I should leave the schema out of the connection string if I want flyway to create my database for me):

	org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:mysql://localhost/newdb) for user 'dev': Unknown database 'newdb'
		at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:298)
		at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:257)
		at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
		at org.flywaydb.core.Flyway.execute(Flyway.java:1287)
		at org.flywaydb.core.Flyway.migrate(Flyway.java:919)
		at org.flywaydb.commandline.Main.executeOperation(Main.java:118)
		at org.flywaydb.commandline.Main.main(Main.java:87)
	Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'newdb'
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
		at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
		at com.mysql.jdbc.Util.getInstance(Util.java:360)
		at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:978)
		at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887)
		at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
		at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870)
		at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659)
		at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206)
		at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2234)
		at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265)
		at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2064)
		at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
		at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
		at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
		at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
		at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
		at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
		at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:295)
		... 6 more

**Comment by g0t4** [comment]
After finding your comments in this SOF question (https://stackoverflow.com/questions/22963186/flywayunable-to-create-schema-incorrect-database-name/22973660#22973660), I now understand that flyway expects the database to be created in advance. Creating it in advance was how I've been doing it all along but because mysql has a loophole (SCHEMA=DB) that allows flyway to create a database if the database name isn't in the connection string, I was led down a path of wondering what the intended behavior was in flyway :)... thanks! Is there somewhere this exists in the documentation already or that we could add this if not?

**Comment by axelfontaine** [comment]
I wasn't able to reproduce this. We actually already had a test that covers this case and it was green. My suspicion is that some versions of the JDBC driver, including the one I use for testing returned "" for a connection with no schema, whereas other like the one that was used here return null.

I've added an extra null check to be on the safe side.

Cheers
Axel

**Comment by g0t4** [comment]
Sounds good, thanks!

**Comment by CyborTronik** [comment]
Hi I have the next issue: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:mysql:...

Using flyway maven plugin 3.2.1 and MySQL driver 5.1.36. 
The mysql server is used via docker container 5.6.26

For configuration : 
  <configuration>
                    <driver>com.mysql.jdbc.Driver</driver>
                    <url>jdbc:mysql://127.0.0.1:3307/?createDatabaseIfNotExist=true</url>
                    <user>root</user>
                    <password>xxx</password>
                    <schemas>
                        <schema>xxx</schema>
                    </schemas>
                </configuration>

Using same details I'm connecting with success via Workbench.

Any workarounds for that?

**Comment by g0t4** [comment]
Create your mysql database with the mysql command line tool, then you'll be
able to connect. Flyway isn't mean to create non-existent databases, as
there are a plethora of nuances to every database platform (when creating a
database) and for the most part there are good command line tools to create
new databases.

Here's what I use in a shell script along with flyway when I want to create
databases (by the way this drops and recreates, say a testing db):

mysql -u dev -e "DROP DATABASE IF EXISTS database_name; CREATE
DATABASE database_name;"

**Comment by diogogmt** [comment]
Having similar issues:

```
org.flywaydb.core.api.FlywayException: Unable to check whether schema `sphereds` is empty
	at org.flywaydb.core.internal.dbsupport.Schema.empty(Schema.java:95)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1021)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
	at com.clouddynamics.exosphere.platform.flyway.FlywayService.migrate(FlywayService.java:81)
	at com.clouddynamics.exosphere.platform.common.init.ServiceContainerStartupManager.initializeResources(ServiceContainerStartupManager.java:34)
	at com.clouddynamics.exosphere.platform.common.init.ExosphereServiceContainerListener.contextInitialized(ExosphereServiceContainerListener.java:35)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4728)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5166)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:940)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1738)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: Cannot proceed because system tables used by Event Scheduler were found damaged at server start
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1094)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4226)
	at com.mysql.jdbc.MysqlIO.nextRowFast(MysqlIO.java:2188)
	at com.mysql.jdbc.MysqlIO.nextRow(MysqlIO.java:2044)
	at com.mysql.jdbc.MysqlIO.readSingleRowSet(MysqlIO.java:3538)
	at com.mysql.jdbc.MysqlIO.getResultSet(MysqlIO.java:489)
	at com.mysql.jdbc.MysqlIO.readResultsForQueryOrUpdate(MysqlIO.java:3240)
	at com.mysql.jdbc.MysqlIO.readAllResults(MysqlIO.java:2411)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2834)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2840)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2082)
	at com.mysql.jdbc.PreparedStatement.executeQuery(PreparedStatement.java:2212)
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.queryForInt(JdbcTemplate.java:156)
	at org.flywaydb.core.internal.dbsupport.mysql.MySQLSchema.doEmpty(MySQLSchema.java:49)
	at org.flywaydb.core.internal.dbsupport.Schema.empty(Schema.java:93)
```

Running mysql  Ver 14.14 Distrib 5.6.26, for Linux (x86_64) on CentOS 7

**Comment by g0t4** [comment]
Cannot proceed because system tables used by Event Scheduler were
found damaged at server start - seems like a different issue?

**Comment by treaz** [comment]
@g0t4 @diogogmt I don't think this is a flyway issue.
login to mysql on the server with the user that flyway uses and then do:
select count(*) form information_schema.events;

I bet that you'll be getting a
    ERROR 1577 (HY000): Cannot proceed because system tables used by Event Scheduler were found damaged at server start

Then you need to fix your mysql server (I haven't found out how to do that yet). But there's a couple of links out there

**Comment by xiaofengli** [comment]
I got the following exception, any idea? Is it database driver issue? thanks!

ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:4.0.3:migrate (default-cli) on project app: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:mysql://localhost:3306/) for user 'root': Could not create connection to database server. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.flywaydb:flyway-maven-plugin:4.0.3:migrate (default-cli) on project app: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:mysql://localhost:3306/) for user 'root': Could not create connection to database server.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)


Here is what I have in my pom.xml,

<plugin>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-maven-plugin</artifactId>
                <version>4.0.3</version>
                <configuration>
                        <url>jdbc:mysql://localhost:3306/</url>
                        <user>root</user>
                        <password>123456</password>
                        <basedir>db/migrations/words</basedir>
                        <schemas>
                           <schema>flyway_schema</schema>
                        </schemas>
                </configuration>
      </plugin>

I tried the following it works fine,

$ flyway migrate -url=jdbc:mysql://localhost -user=root -password=123456
Flyway 4.0.3 by Boxfuse

Database: jdbc:mysql://localhost:3306/ (MySQL 5.6)
Successfully validated 0 migrations (execution time 00:00.005s)
Creating schema `flyway_schema` ...
Creating Metadata table: `flyway_schema`.`schema_version`
Current version of schema `flyway_schema`: 0
Schema `flyway_schema` is up to date. No migration necessary.

**Comment by charneykaye** [comment]
@treaz thanks that's a good observation.

**Comment by mauromol** [comment]
I'm still having the "no database selected" problem with Flyway 4.2.0 and running Flyway through Gradle.
The `flyway.url` is set without the schema name, while `flyway.schemas` is set to the correct schema name.
This did not happen with Flyway 3.2.1.

Any suggestion?

**Comment by mauromol** [comment]
I opened #1921 to track that the problem still exists for me.

**Comment by HenriquePereiraRosa** [comment]
I'm having this problem. it's seems that the Flyway can't crate the schema in a new database. I don't create by my own because i don't remeber the default schema name of my project that Flyway creates.

  -- POM:
        
        <dependency>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-core</artifactId>
        </dependency>

-- Exception:


2018-05-05 16:03:07.660 ERROR 5172 --- [  restartedMain] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'flywayInitializer' defined in class path resource [org/springframework/boot/autoconfigure/flyway/FlywayAutoConfiguration$FlywayConfiguration.class]: Invocation of init method failed; nested exception is org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:296) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1078) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at com.example.BasicApplication.main(BasicApplication.java:10) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) [spring-boot-devtools-1.5.7.RELEASE.jar:1.5.7.RELEASE]
Caused by: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56) ~[flyway-core-3.2.1.jar:na]
	at org.flywaydb.core.Flyway.execute(Flyway.java:1385) ~[flyway-core-3.2.1.jar:na]
	at org.flywaydb.core.Flyway.migrate(Flyway.java:1006) ~[flyway-core-3.2.1.jar:na]
	at org.springframework.boot.autoconfigure.flyway.FlywayMigrationInitializer.afterPropertiesSet(FlywayMigrationInitializer.java:66) ~[spring-boot-autoconfigure-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1687) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1624) ~[spring-beans-4.3.11.RELEASE.jar:4.3.11.RELEASE]
	... 23 common frames omitted
Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

This is the first time that this problem has occurred (Windows 7). I've used in other two Windows 10 PCs and have worked fine.
