### ISSUE TITLE
NuoDB support

### ISSUE THREAD

**Issue by andyjefferson** [flyway/flyway#671]
NuoDB is a "NewSQL" datastore (using the http://www.nuodb.com) and if I try to use it with Flyway currently I get

com.googlecode.flyway.core.api.FlywayException: Unable to autodetect Jdbc driver for url: jdbc:com.nuodb://127.0.0.1/test
        at com.googlecode.flyway.core.util.jdbc.DriverDataSource.<init>(DriverDataSource.java:104)
        at com.googlecode.flyway.core.Flyway.setDataSource(Flyway.java:689)

Would be a great addition to your excellent tool; sadly I don't have resource to offer to help you provide this, just wanted to register it. Thanks

**Comment by rbuck** [comment]
Hi Axel,

I could have swore you merged this work in, and since a year ago I've cleaned up and deleted all my repos that I was done with. Did you not merge these?

Bob

**Comment by kakawait** [comment]
Any updates about *Nuodb* integration?

**Comment by selliera** [comment]
Hello,

I tried to revive nuodb integration, by merging the proposed changes with the latest in tree version.
It is here: https://github.com/selliera/flyway, but I didn't propose a PR yet, since I only tested locally.

I tried to follow the instruction from https://flywaydb.org/documentation/contribute/code/database but did not succeed to run tests. NuoDB is easy to install (at least in a single node setup), so it should no be a big deal for someone used to running flyway tests I hope.

I had an issue with the NuoDBConnection.doGetCurrentschemaName(): at start I get an empty schema name, which is not supported. I chose to return the default schema name "USER" in this case, but it may not be the best solution.
