### ISSUE TITLE
Flyway multiple schemas support and search_path conflicts

### ISSUE THREAD

**Issue by ghost** [flyway/flyway#807]
Hello,

there's an issue when using multiple flyway instances to manage multiple schemas distinct as described here (second strategy):

http://flywaydb.org/documentation/faq.html#multiple-schemas

_Example:_ I got 2 schemas: 'foo' and 'bar' and the search path is set to 'foo, bar'

I create a flyway instance to manage schema 'foo'

`locations = /sql/foo`
`schemas = foo`
`table = schema_version`

and a script containing the code

`drop table if exists toDrop;`

The table `toDrop` lives in schema 'bar' and not 'foo'. So the flyway instance will drop the table from schema 'bar'! But this instance was created to manage schema 'foo' and only this schema. So this behaviour is very dangerous.

I know why this is happening. It's because of this fix:

https://code.google.com/p/flyway/issues/detail?id=358

Flyway sets the `search_path` to something like that `foo, foo, bar`. So the scripts might also touch schema 'bar'.

I think it would be nice to have 
- a property to set the search_path on my own or
- a pre-executing sql-script which is always executed before migrating begins (to set priviliges, search_paths, ...)
- an additional boolean option for the `setSchemas()` to also set the search_path simultaneously

Thanks in advance!

**Comment by maroonyw** [comment]
There is a problem using method `beforeMigrate` for setting the `search_path` to a specific schema. My database setup is the following:

I use a PostgreSQL 9.1 database with 2 schemas `foo` and `bar` and the search path is set to `foo, bar`. Both schemas were migrated using flyway. Now I remove schema `bar` for example with

    drop schema bar cascade;

and create a **new flyway sql script** for schema `foo`. This migration fails at `flyway.migrate()`:

    Caused by: org.flywaydb.core.api.FlywayException: Error setting current schema to "foo"
            at org.flywaydb.core.internal.dbsupport.DbSupport.setCurrentSchema(DbSupport.java:103)
            at org.flywaydb.core.Flyway$1.execute(Flyway.java:1052)
            at org.flywaydb.core.Flyway$1.execute(Flyway.java:1006)
            at org.flywaydb.core.Flyway.execute(Flyway.java:1418)
            at org.flywaydb.core.Flyway.migrate(Flyway.java:1006)
            ... 18 more
    Caused by: org.postgresql.util.PSQLException: ERROR: invalid value for parameter "search_path": "foo, bar"
      Detail: schema "bar" does not exist
            at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2198)
            at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1927)
            at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
            at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:561)
            at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:419)
            at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:412)
            at org.flywaydb.core.internal.dbsupport.JdbcTemplate.execute(JdbcTemplate.java:219)
            at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.doSetCurrentSchema(PostgreSQLDbSupport.java:67)
            at org.flywaydb.core.internal.dbsupport.DbSupport.setCurrentSchema(DbSupport.java:101)
            ... 23 more

I don't understand this behavior. I want to migrate schema `foo` so the "missing schema `bar`" is something irrelevant at this moment. That's exactly the reason I'm using method `beforeMigrate`. But this method seems to be called later? 

Using Flyway 3.2.1
