### ISSUE TITLE
PostgreSQL: 'SET client_encoding = ...' causes IOException

### ISSUE THREAD

**Issue by marksievers** [flyway/flyway#840]
flyway-core v3.0
By migrating pg_dump output into an initial schema migration file I seem to have discovered an issue with this statement:

`SET client_encoding = 'UTF8;`

When I create a migration file with this line alone, I get this exception:

```
org.flywaydb.core.api.FlywayException: Error setting current schema to "public"
    at org.flywaydb.core.internal.dbsupport.DbSupport.setCurrentSchema(DbSupport.java:102) 
    at org.flywaydb.core.Flyway$1.execute(Flyway.java:867) 
    at org.flywaydb.core.Flyway$1.execute(Flyway.java:811) 
    at org.flywaydb.core.Flyway.execute(Flyway.java:1171) 
    at org.flywaydb.core.Flyway.migrate(Flyway.java:811) 
    ...
Caused by: org.postgresql.util.PSQLException: An I/O error occured while sending to the backend.
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:218) 
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:451) 
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:350) 
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:254) 
    at org.flywaydb.core.internal.dbsupport.JdbcTemplate.queryForString(JdbcTemplate.java:185) 
    at org.flywaydb.core.internal.dbsupport.postgresql.PostgreSQLDbSupport.doSetCurrentSchema(PostgreSQLDbSupport.java:61) 
    at org.flywaydb.core.internal.dbsupport.DbSupport.setCurrentSchema(DbSupport.java:100) 
    ... 8 common frames omitted
Caused by: java.io.IOException: Stream closed
    at sun.nio.cs.StreamEncoder.ensureOpen(StreamEncoder.java:45) ~[na:1.7.0_67]
    at sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:140) ~[na:1.7.0_67]
    at java.io.OutputStreamWriter.flush(OutputStreamWriter.java:229) ~[na:1.7.0_67]
    at org.postgresql.core.PGStream.flush(PGStream.java:507) 
    at org.postgresql.core.v3.QueryExecutorImpl.sendSync(QueryExecutorImpl.java:676) 
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:191) 
    ... 14 common frames omitted
```

When I run through an alternative datasource implementation (Bonecp) I see:

```
org.postgresql.util.PSQLException: The server's client_encoding parameter was changed to UTF8. The JDBC driver requires client_encoding to be UNICODE for correct operation.
    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1366)
    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:192)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:451)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:350)
    at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:343)
```

Which seems to be explained in this PG forum thread:
http://www.postgresql.org/message-id/1203689294.4960.56.camel@localhost

So seems like the only real improvement to Flyway here is to bring the Postgres output into the Exception (which I have noticed elsewhere Flyway is very good at doing).

**Comment by tylerhjones** [comment]
This is still an occurring issue in 5.0.7, the root cause from postgres is not provided in the exceptions from flyway.

**Comment by axelfontaine** [comment]
@tylerhjones Please open a new issue with steps how to reproduce.
