### ISSUE TITLE
JTA & XA DataSource support

### ISSUE THREAD

**Issue by flyway** [flyway/flyway#86]
_Original author: axel.fontaine.business@gmail.com (January 01, 2012 03:21:02)_

Previously JTA &amp; XA DataSources were supported by specifying a JTA transaction manager using the setTransactionManager method.

As part of the removal of the Spring dependency, this method will be going away in the next release.

An alternative could be JTA &amp; XA DataSource autodetection, fetching the UserTransaction object from JNDI and starting a new transaction that way.

If you do require this, please star this issue and add a comment with the specific runtime environment (AppServer + Version) you use.

_Original issue: http://code.google.com/p/flyway/issues/detail?id=203_

**Comment by 71m024** [comment]
I need this feature. Since i switched to jta-managed datasource, i can't migrate my project:
`can't call setAutoCommit when the connection is JtaManaged`

If there is a workaround which solves my problem, please tell me about it ;)

My environment: tomee:7.0.1-webprofile

**Comment by axelfontaine** [comment]
Workaround by @71m024 is good enough for me. Closing.

**Comment by SamSoldatenko** [comment]
It's still broken.
* Wildfly-13.0.0.Final
* Postgres 9.5
* xa-datasource using postgresql-42.2.2.jar

Fail with
```
00:57:46,848 INFO  [org.flywaydb.core.internal.util.VersionPrinter] (ServerService Thread Pool -- 102) Flyway Community Edition 5.1.3 by Boxfuse
00:57:46,868 INFO  [org.flywaydb.core.internal.database.DatabaseFactory] (ServerService Thread Pool -- 102) Database: jdbc:postgresql://XXX/XXXX (PostgreSQL 9.5)
00:57:46,908 INFO  [org.flywaydb.core.internal.command.DbValidate] (ServerService Thread Pool -- 102) Successfully validated 1 migration (execution time 00:00.010s)
00:57:46,922 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 102) MSC000001: Failed to start service ...
	at ...
Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
	at ...
	... 8 more
Caused by: javax.ejb.EJBException: org.flywaydb.core.api.FlywayException: Found non-empty schema(s) "public" without schema history table! Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
	at ...
	... 13 more
Caused by: org.flywaydb.core.api.FlywayException: Found non-empty schema(s) "public" without schema history table! Use baseline() or set baselineOnMigrate to true to initialize the schema history table.
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:938)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:910)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1238)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:910)
```
