### ISSUE TITLE
Optional timeout on migrate process

### ISSUE THREAD

**Issue by PeeZu** [flyway/flyway#887]
As improvement, migrate process should support a time-out property in order to prevent too long execution for each migration file. 
For instance:
On continuous delivery process, each changes are deployed on next environment if build success. the goal is to break the deployment process if the time-out occur => identify mistake due to the data volumetry not present in development environment (Thin database) comparing to the next deployment environment (Pre-Production, Staging etc...).

**Comment by oriptipalti** [comment]
Would appreciate this as well.

For now, we have a workaround where we wrap the entire flyway run with a timeout script - we essentially kill the process if it's been running more than X seconds.
It's not the same behavior as in the suggestion and it's not very safe, but for us, it's better than nothing.

**Comment by juliahayward** [comment]
Do you understand why your scripts are taking a long time? Eg. deadlocks, high database usage, ...? Would they be safe to interrupt mid-execution?

**Comment by oriptipalti** [comment]
> Do you understand why your scripts are taking a long time? Eg. deadlocks, high database usage, ...? Would they be safe to interrupt mid-execution?

For us, it's been a lethal combination of heavy workload tasks like index creation and table locks we did not anticipate.

**Comment by tbeauvais-imagine** [comment]
With millions of records, simple operations can take a very long time and even timeout. They are completed by the database eventually, yet Flyway times out not waiting for the result marking the migration as failed which requires manual intervention to fix.

Are you saying that the only way to increase the timeout for Flyway is to increase the timeout for all types of transitions?

**Comment by manojsoft** [comment]
I'm also encountering this issue where my view creation is taking longer than 30 mins, it does eventually completes on database, but the flyway migration timeouts and tries to rollback the migration. 
I've been looking for a configurable parameter / default value for transaction timeout in flyway configs, but couldn't find it.

Here's the error log, from my flyway migration:
```
ERROR: Unable to rollback transaction
org.postgresql.util.PSQLException: This connection has been closed.
    at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:907)
    at org.postgresql.jdbc.PgConnection.rollback(PgConnection.java:914)
    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:71)
    at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:56)
    at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:96)
    at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
    at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
    at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
    at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:176)
    at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
    at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
    at org.flywaydb.commandline.Main.executeOperation(Main.java:358)
    at org.flywaydb.commandline.Main.main(Main.java:148)
ERROR: Unable to restore autocommit to original value for connection
org.postgresql.util.PSQLException: This connection has been closed.
    at org.postgresql.jdbc.PgConnection.checkClosed(PgConnection.java:907)
    at org.postgresql.jdbc.PgConnection.setAutoCommit(PgConnection.java:836)
    at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:86)
    at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:56)
    at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:96)
    at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
    at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
    at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
    at org.flywaydb.core.Flyway.lambda$migrate$0(Flyway.java:176)
    at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:204)
    at org.flywaydb.core.Flyway.migrate(Flyway.java:128)
    at org.flywaydb.commandline.Main.executeOperation(Main.java:358)
    at org.flywaydb.commandline.Main.main(Main.java:148)
ERROR: Unable to restore connection to its original state
--------------------------------------------------
SQL State  : 08006
Error Code : 0
Message    : An I/O error occurred while sending to the backend.

Caused by: org.postgresql.util.PSQLException: FATAL: terminating connection due to idle-in-transaction timeout
```

**Comment by rethab** [comment]
The native connector for mongodb has a hard-coded timeout of five minutes, which means you can't use this to create an index on a larger collection..?

https://github.com/flyway/flyway/blob/abf6d45ebd6edd082cca651093ba80cf8a56efed/flyway-database/flyway-database-nc-mongodb/src/main/java/org/flywaydb/database/nc/mongodb/MongoDBDatabase.java#L434

**Comment by alersrt** [comment]
Agreed with @rethab. Recently faced with that issue. Need any option to control this timeout.
