### ISSUE TITLE
JDBC escape syntax support

### ISSUE THREAD

**Issue by maroonyw** [flyway/flyway#894]
I recently upgraded from flyway 3.0 to version 3.1. In my sql scripts I use something like that:

```
insert into testDate values ({ts '2015-01-01 00:00:00'});
```

This doens't work with Flyway 3.1 anymore (postgresql 9.2-1002.jdbc4):

```
Caused by: org.flywaydb.core.internal.dbsupport.FlywaySqlScriptException: 
Migration V1.0.0__foo.sql failed
----------------------------------------------------------------------------------------
SQL State  : 42601
Error Code : 0
Message    : ERROR: syntax error at or near "{"

	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:117)
	at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:71)
	at org.flywaydb.core.internal.command.DbMigrate$5.doInTransaction(DbMigrate.java:287)
	at org.flywaydb.core.internal.command.DbMigrate$5.doInTransaction(DbMigrate.java:285)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.applyMigration(DbMigrate.java:285)
	at org.flywaydb.core.internal.command.DbMigrate.access$800(DbMigrate.java:46)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:207)
	at org.flywaydb.core.internal.command.DbMigrate$2.doInTransaction(DbMigrate.java:156)
	at org.flywaydb.core.internal.util.jdbc.TransactionTemplate.execute(TransactionTemplate.java:72)
	at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:156)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:972)
	at org.flywaydb.core.Flyway$1.execute(Flyway.java:919)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1320)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:919)
	at de.debeka.aktuariatlv.augur.databaseservice.migration.DatabaseMigration.migrateSchema(DatabaseMigration.java:102)
	... 26 more
Caused by: org.postgresql.util.PSQLException: ERROR: syntax error at or near "{"
  Position: 120
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2157)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1886)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:555)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:403)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:395)
	at org.flywaydb.core.internal.dbsupport.JdbcTemplate.executeStatement(JdbcTemplate.java:238)
	at org.flywaydb.core.internal.dbsupport.SqlScript.execute(SqlScript.java:114)
	... 
```

**Comment by axelfontaine** [comment]
Closing as upon further consideration I do not wish to expose this jdbc-specific syntax.

**Comment by maroonyw** [comment]
Does this mean, that the jdbc syntax is gone forever? I already created over 100 database scripts for our current productive database. Your decision would force me to stick with flyway 3.0 forever...

**Comment by maroonyw** [comment]
Ok. I finally fixed my flyway scripts...
