### ISSUE TITLE
Error in connection Pool 

### ISSUE THREAD

**Issue by subodhchhabra** [flyway/flyway#976]
always get following error, if I try to execute multiple migrations in parallel ( to different target Oracle  DB's)
--------
Failed to execute goal org.flywaydb:flyway-maven-plugin:3.1:migrate (default-cli) on project AutomatedDBDeploy: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource.  to recreate run 2 Different projects at same time

**Comment by axelfontaine** [comment]
The error is either with your connection pool configuration or you DB (max allowed connection?). Flyway doesn't do anything special here.

**Comment by subodhchhabra** [comment]
I have verified DB, it looks good. issue is reproduce-able if you run 2 projects on same machine at same time and target DB's are different. I am invoking maven through a shell script.

**Comment by axelfontaine** [comment]
Please post a small github repository to reproduce the issue.

**Comment by subodhchhabra** [comment]
Here is sample error for you to look , 
again to reiterate - we are running 2 instances of flyway ( both for different target DB's) at same time through mvn like - 
---
window1<DIR1>
mvn clean compile flyway:migrate
---
window 2 <DIR2>
mvn clean compile flyway:migrate
---
[ERROR] Failed to execute goal org.flywaydb:flyway-maven-plugin:3.1:migrate (default-cli) on project AutomatedDBDeploy: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:oracle:thin:<SCHEMA>/cps@//<HOST>:1521/<DB>) for user '<SCHEMA>': IO Error: Connection reset -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.flywaydb:flyway-maven-plugin:3.1:migrate (default-cli) on project AutomatedDBDeploy: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:oracle:thin:<SCHEMA>/cps@//<HOST>:1521/<DB>) for user '<SCHEMA>': IO Error: Connection reset
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Caused by: org.apache.maven.plugin.MojoExecutionException: org.flywaydb.core.api.FlywayException: Unable to obtain Jdbc connection from DataSource (jdbc:oracle:thin:<SCHEMA>/cps@//<HOST>:1521/<DB>) for user '<SCHEMA>': IO Error: Connection reset
	at org.flywaydb.maven.AbstractFlywayMojo.execute(AbstractFlywayMojo.java:509)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 19 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:153)
	at oracle.net.ns.DataPacket.send(DataPacket.java:210)
	at oracle.net.ns.NetOutputStream.flush(NetOutputStream.java:230)
	at oracle.net.ns.NetInputStream.getNextPacket(NetInputStream.java:312)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:260)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:185)
	at oracle.net.ns.NetInputStream.read(NetInputStream.java:102)
	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.readNextPacket(T4CSocketInputStreamWrapper.java:124)
	at oracle.jdbc.driver.T4CSocketInputStreamWrapper.read(T4CSocketInputStreamWrapper.java:80)
	at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1137)
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:290)
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:192)
	at oracle.jdbc.driver.T4CTTIoauthenticate.doOSESSKEY(T4CTTIoauthenticate.java:404)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:385)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:546)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:236)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:521)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnectionFromDriver(DriverDataSource.java:295)
	at org.flywaydb.core.internal.util.jdbc.DriverDataSource.getConnection(DriverDataSource.java:257)
	at org.flywaydb.core.internal.util.jdbc.JdbcUtils.openConnection(JdbcUtils.java:50)
	at org.flywaydb.core.Flyway.execute(Flyway.java:1287)
	at org.flywaydb.core.Flyway.info(Flyway.java:1050)
	at org.flywaydb.maven.MigrateMojo.doExecute(MigrateMojo.java:29)
	at org.flywaydb.maven.AbstractFlywayMojo.execute(AbstractFlywayMojo.java:507)
	... 21 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
